### ISSUE TITLE
Error when 

### ISSUE THREAD

**Issue by GeorgianaPetria** [Miserlou/Zappa#1029]
I'm managed to successfully deploy my dev stage using zappa. However, when I'm calling 
`curl -d '{"payload": "something"}' https://my_url/dev`

I'm getting the following error:

`"{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 434, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/tmp/pip-build-wcg6nH/Werkzeug/werkzeug/wrappers.py\", line 903, in from_app\\n', '  File \"/tmp/pip-build-wcg6nH/Werkzeug/werkzeug/test.py\", line 884, in run_wsgi_app\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"`

Also, when calling `zappa invoke dev 'predictions.app'` I'm getting:
```
Calling invoke for stage dev..
[START] RequestId: 4cb49327-779e-11e7-b905-e3f3f4ddec0e Version: $LATEST
[DEBUG] 2017-08-02T16:19:03.396Z 4cb49327-779e-11e7-b905-e3f3f4ddec0e Zappa Event: {u'command': u'predictions.app'}
No module named predictions: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 491, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 243, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 341, in handler
    app_function = self.import_module_and_get_function(whole_function)
  File "/var/task/handler.py", line 234, in import_module_and_get_function
    app_module = importlib.import_module(module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named predictions
```

Here's my zappa_settings.json:
`{
    "dev": {
        "app_function": "predictions.app",
        "slim_handler": true,
	"profile_name": "zappa", 
        "s3_bucket": "my-bucket"
    }
}`

My lambda is only printing "Hello world".
zappa --version: **0.43.1**

Do you know what might be the issue here?

**Comment by zaraken** [comment]
Could you provide your source code? It just seems like a "normal" python error. You may be trying to access something that is not initialized properly.

**Comment by madalinoprea** [comment]
Usually I get these errors when a python module tries to load an C extensions that's not available in AWS Lambda runtime or an C extension from Zappa package is not compatible with AWS (compiled on Mac, wrong ELF). 

Check carefully your CloudWatch logs and you should see an error. They are hard to spot because I believe they happen only when Lamda is reloaded, not when a requested is handled.

Solution for me was to deploy from a AWS Lamba compatible environment:

Installed packages were my _special_ requirements:
```
# ./build/Dockerfile
FROM lambci/lambda:build-python2.7

RUN yum -y update && rpm --rebuilddb \
    && yum install -y yum-plugin-ovl openldap-devel libxml2-devel

# Using rpms from https://github.com/onelogin/python-saml/issues/30
RUN yum -y update && rpm --rebuilddb \
    && curl --silent -O http://vault.centos.org/6.5/cr/x86_64/Packages/xmlsec1-1.2.20-4.el6.x86_64.rpm \
    && curl --silent -O http://vault.centos.org/6.5/cr/x86_64/Packages/xmlsec1-devel-1.2.20-4.el6.x86_64.rpm \
    && curl --silent -O http://vault.centos.org/6.5/cr/x86_64/Packages/xmlsec1-openssl-1.2.20-4.el6.x86_64.rpm \
    && curl --silent -O http://vault.centos.org/6.5/cr/x86_64/Packages/xmlsec1-openssl-devel-1.2.20-4.el6.x86_64.rpm \
    && ls -al \
    && yum install -y xmlsec1-1.2.20-4.el6.x86_64.rpm xmlsec1-devel-1.2.20-4.el6.x86_64.rpm \
        xmlsec1-openssl-1.2.20-4.el6.x86_64.rpm xmlsec1-openssl-devel-1.2.20-4.el6.x86_64.rpm \
    && yum install -y libtool-ltdl-devel

RUN sed -i 's/LIBLTDL=1 -I/LIBLTDL=1 -DXMLSEC_NO_SIZE_T -I/' /usr/bin/xmlsec1-config
```
- And during build, I install requirements, copy libs not available on AWS, etc:
```bash
        stage('AWS Build') {
            agent {
                dockerfile {
                    reuseNode true
                    dir 'build'
                }
            }
            steps {
                 sh '''
                 virtualenv --clear .venv
                 source .venv/bin/activate
                 pip install -r requirements.txt

                 cd src
                 mkdir -p lib
                 # Add to lambda package our custom libraries not available on AWS Lambda env
                 cp /usr/lib64/libxmlsec1-openssl.so.1 lib/
                 cp /usr/lib64/libxmlsec1-openssl.so lib/
                 cp /usr/lib64/libxmlsec1.so.1 lib/

                 zappa package qa -o "../${APP_NAME}-${BRANCH_NAME}-${BUILD_ID}.zip"

                 # Destroy virtualenv
                 cd ..
                 deactivate; rm -rf .venv
                 '''
            }
        }
```

**Comment by codalprashant** [comment]
Remove all packages versions from requirements.txt, Create new virtualenv and then update server. Same thing happen with me and it was solved by performing such action.

**Comment by chasetb** [comment]
FWIW, I ran into the same error today while using `slim_handler: true`. If I set it to `false` then my issue of libxmlsec1.so.1 not being found went away. I plan to research the issue more later.

**Comment by codalprashant** [comment]
I find the solution for me. I removed all the pyc files before updating the environment and the error was gone
