### ISSUE TITLE
CloudFormation stack missing, an error occurred! :(

### ISSUE THREAD

**Issue by nautilus28** [Miserlou/Zappa#1067]
It looks like a bug happened when CloudFormation was not enabled.

Calling update for stage dev..
Downloading and installing dependencies...
Packaging project as zip.
Uploading magsoc-javascri-dev-1503661683.zip (5.7MiB)..
Updating Lambda function code..
Updating Lambda function configuration..
Uploading magsoc-javascri-dev-template-1503661725.json (1.6KiB)..
CloudFormation stack missing, re-deploy to enable updates
Oh no! An error occurred! :(
```
==============

Traceback (most recent call last):
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/zappa/cli.py", line 2495, in handle
    sys.exit(cli.handle())
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/zappa/cli.py", line 477, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/zappa/cli.py", line 521, in dispatch_command
    self.update()
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/zappa/cli.py", line 909, in update
    self.zappa.add_binary_support(api_id=api_id, cors=self.cors)
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/zappa/core.py", line 1325, in add_binary_support
    restApiId=api_id
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/botocore/client.py", line 531, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/botocore/client.py", line 586, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter restApiId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

**Comment by mcrowson** [comment]
did you find a way around this?

**Comment by nautilus28** [comment]
if I recall correctly, the problem disappeared after I deleted the project and deploy it again.

**Comment by dashk** [comment]
I ran into this yesterday, and it was a permission issue with my deployment credentials, and fixed by making sure all required permissions are granted to the Zappa deployer role: https://github.com/Miserlou/Zappa/issues/244#issuecomment-611993787

**Comment by nyck33** [comment]
@nautilus28 is correct.  Deleting the function on AWS Console and redeploying worked.
