### ISSUE TITLE
Won't install 

### ISSUE THREAD

**Issue by simonrb2000** [Miserlou/Zappa#1075]
Fails to install from PIP Install

 
I am
## Expected Behavior

Should install
## Actual Behavior

Fails at 99% (Killed
## Steps to Reproduce

1. pip install zappa under venv

`(venv) pi@raspberrypi:~/kodi-alexa$ pip install zappa
Collecting zappa
  Using cached zappa-0.43.2-py2-none-any.whl
Requirement already satisfied: six==1.10.0 in ./venv/lib/python2.7/site-packages (from zappa)
Requirement already satisfied: wheel==0.29.0 in ./venv/lib/python2.7/site-packages (from zappa)
Collecting durationpy==0.5 (from zappa)
  Using cached durationpy-0.5.tar.gz
Collecting kappa==0.6.0 (from zappa)
  Using cached kappa-0.6.0-py2-none-any.whl
Collecting botocore==1.5.40 (from zappa)
  Using cached botocore-1.5.40-py2.py3-none-any.whl
Collecting tqdm==4.15.0 (from zappa)
  Using cached tqdm-4.15.0-py2.py3-none-any.whl
Collecting wsgi-request-logger==0.4.6 (from zappa)
  Using cached wsgi-request-logger-0.4.6.tar.gz
Collecting base58==0.2.4 (from zappa)
  Using cached base58-0.2.4.tar.gz
Collecting hjson==3.0.0 (from zappa)
  Using cached hjson-3.0.0.tar.gz
Requirement already satisfied: python-dateutil==2.6.1 in ./venv/lib/python2.7/site-packages (from zappa)
Requirement already satisfied: requests>=2.10.0 in ./venv/lib/python2.7/site-packages (from zappa)
Collecting argcomplete==1.8.2 (from zappa)
  Using cached argcomplete-1.8.2-py2.py3-none-any.whl
Collecting docutils>=0.12 (from zappa)
  Using cached docutils-0.14-py2-none-any.whl
Collecting lambda-packages==0.16.1 (from zappa)
  Downloading lambda_packages-0.16.1.tar.gz (59.2MB)
    99% |████████████████████████████████| 59.1MB 7.9MB/s eta 0:00:01Killed
You have new mail in /var/mail/pi
(venv) pi@raspberrypi:~/kodi-alexa$ pip uninstall zappa
Cannot uninstall requirement zappa, not installed
(venv) pi@raspberrypi:~/kodi-alexa$ `

**Comment by Miserlou** [comment]
try another large package? i dont think this is zappa, but rather pip

From my phone..

**Comment by simonrb2000** [comment]
Tried this on another raspberry pi and got this

`Requirement already satisfied: docutils>=0.12 in /usr/local/lib/python2.7/dist-packages (from zappa)
Collecting lambda-packages==0.16.1 (from zappa)
  Downloading lambda_packages-0.16.1.tar.gz (59.2MB)
    99% |████████████████████████████████| 59.1MB 167kB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/cachecontrol/serialize.py", line 55, in dumps
    "body": _b64_encode_bytes(body),
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/cachecontrol/serialize.py", line 12, in _b64_encode_bytes
    return base64.b64encode(b).decode("ascii")
MemoryError
(venv) pi@raspberrypi:~/kodi-alexa $ 
`

**Comment by simonrb2000** [comment]
found this:-
https://github.com/Miserlou/lambda-packages/issues/27

**Comment by bxm156** [comment]
I think we can close this issue :)
