### ISSUE TITLE
zappa invoke passes a dictionary as an first positional argument

### ISSUE THREAD

**Issue by centralniak** [Miserlou/Zappa#1079]
## Context

I have the following function inside `dummy.tasks`:

```
def hello(name=None):
    if not name:
        name = 'Stranger'
    return 'Hello {}'.format(name.ucfirst())
```

If I run `zappa invoke dummy.tasks.hello` the function fails with:

```
Traceback (most recent call last):
  File "/var/task/handler.py", line 505, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 242, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 341, in handler
    result = self.run_function(app_function, event, context)
  File "/var/task/handler.py", line 274, in run_function
    result = app_function(event, context) if varargs else app_function(event)
  File "/tmp/useless/dummy/tasks.py", line 13, in hello
    return 'Hello {}'.format(name.ucfirst())
AttributeError: 'dict' object has no attribute 'ucfirst'
```
This is happening because `{u'command': u'dummy.tasks.hello'}` is passed as the `name` argument to the function.

## Expected Behavior

The `name` argument should not be passed to the function.

## Actual Behavior

A dict is passed as the `name` argument.

## Steps to Reproduce

Create a function with a single default parameter and invoke.

**Comment by centralniak** [comment]
Somewhat related to https://github.com/Miserlou/Zappa/pull/983
