### ISSUE TITLE
deploy on OSX Sierra fails with OSError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by gdudek** [Miserlou/Zappa#1098]
On Mac OS X 10.12.6 zappa deploy fails with an OSError when it tried to do a os.chflags
from copystat which is called by copytree. This requires root privileges.

## Context
It appears that sudo (root privileges) are needed for the flag choices used by the zappa
deployment step on OS X Sierra.  This is undesirable, and also if sudo is used then zappa will not correctly find the original user's .aws settings file so a lot of insecure and messy work-arounds are needed.

## Expected Behavior
os.chflags should presumably just work, but without it the deployment also works OK

## Actual Behavior
A traceback is generated as below:

Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/zappa/cli.py", line 2495, in handle
    sys.exit(cli.handle())
  File "/Library/Python/2.7/site-packages/zappa/cli.py", line 477, in handle
    self.dispatch_command(self.command, stage)
  File "/Library/Python/2.7/site-packages/zappa/cli.py", line 511, in dispatch_command
    self.deploy()
  File "/Library/Python/2.7/site-packages/zappa/cli.py", line 680, in deploy
    self.create_package()
  File "/Library/Python/2.7/site-packages/zappa/cli.py", line 2076, in create_package
    disable_progress=self.disable_progress
  File "/Library/Python/2.7/site-packages/zappa/core.py", line 461, in create_lambda_zip
    copytree(cwd, temp_project_path, symlinks=False, ignore=shutil.ignore_patterns(*excludes))
  File "/Library/Python/2.7/site-packages/zappa/utilities.py", line 57, in copytree
    copytree(s, d, symlinks, ignore)
  File "/Library/Python/2.7/site-packages/zappa/utilities.py", line 57, in copytree
    copytree(s, d, symlinks, ignore)
  File "/Library/Python/2.7/site-packages/zappa/utilities.py", line 33, in copytree
    shutil.copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/qd/d537m93x3794m7dl8lth818c0000gn/T/1505021727/include/python2.7'

## Possible Fix
Unacceptable fix (for many users) is to patch 
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py
line 101 and catch the EPERM error and ignore it.

Another ugly work-around is to copy (cp -a) the .aws file from the normal user to the root
home directory and run everything, including the virtual environment, as root.  For me this is
less acceptable than the shutil patch above due to the security implications.

## Steps to Reproduce
As far as I can tell, just run zappa deploy on OS X 10.12.6

## Your Environment
* Zappa version used: 0.43.2
* Operating System and Python version:
OS X 10.12.6
Apple's standard install of Python 2.7.10 (default, Feb  7 2017, 00:08:15)

**Comment by Miserlou** [comment]
There was another issue with a different workaround for this but I couldn't find it.

**Comment by mcrowson** [comment]
This either had to do with having two virtual environments in the same folder, or something else. Also a reboot might fix it if I remember correctly?

**Comment by rgov** [comment]
I reported this also at #1295 with a pull request at #1297. It has to do with System Integrity Protection on macOS and `shutil.copystat()` behavior.

**Comment by scoates** [comment]
Looks like this was fixed in #1297. Please reopen if I'm incorrect.
