### ISSUE TITLE
zappa tail showing exception in base64 encoded

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#115]
When I `zappa tail test` in my project, and see the Exception message did not decoded right. It would be nice if zappa decode that base64:

```
Traceback (most recent call last):
  File "/var/task/handler.py", line 195, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 55, in lambda_handler
    return cls().handler(event, context)
  File "/var/task/handler.py", line 176, in handler
    raise e
LambdaException: PCFET0NUWVBFIGh0bWw+NDA0PCFET0NUWVBFIEhUTUwgUFVCTElDICItLy9XM0MvL0RURCBIVE1MIDMuMiBGaW5hbC8vRU4iPgo8dGl0bGU+NDA0IE5vdCBGb3VuZDwvdGl0bGU+CjxoMT5Ob3QgRm91bmQ8L2gxPgo8cD5UaGUgcmVxdWVzdGVkIFVSTCB3YXMgbm90IGZvdW5kIG9uIHRoZSBzZXJ2ZXIuICBJZiB5b3UgZW50ZXJlZCB0aGUgVVJMIG1hbnVhbGx5IHBsZWFzZSBjaGVjayB5b3VyIHNwZWxsaW5nIGFuZCB0cnkgYWdhaW4uPC9wPgo=
```

**Comment by Miserlou** [comment]
Oh yeah, this is a great call. There is a reason for returning it in B64 format, but there's no reason why it can't be logged in plaintext.

**Comment by Miserlou** [comment]
I think this is fixed, reopen if not.
