### ISSUE TITLE
deploy failed with ResourceNotFoundException (Function not found)

### ISSUE THREAD

**Issue by tk3369** [Miserlou/Zappa#1162]
## Context
Trying to deploy a simple hello.py python flask app on AWS

 

## Expected Behavior

should deploy

## Actual Behavior

Failed as follows:

$ zappa deploy dev
Calling deploy for stage dev..
Creating hello-flask-dev-ZappaLambdaExecutionRole IAM Role..
Creating zappa-permissions policy on hello-flask-dev-ZappaLambdaExecutionRole IAM Role.
Downloading and installing dependencies..
Packaging project as zip.
Uploading hello-flask-dev-1507515263.zip (2.3MiB)..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 2.43M/2.43M [00:00<00:00, 18.3MB/s]
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/zappa/cli.py", line 718, in deploy
    function_name=self.lambda_name)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/zappa/core.py", line 1106, in get_lambda_function
    FunctionName=function_name)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetFunction operation: Function not found: arn:aws:lambda:us-west-2:141043145990:function:hello-flask-dev

## Possible Fix

no idea

## Steps to Reproduce

1. just run deploy

## Your Environment

* Zappa version used: 0.44.3
* Operating System and Python version: AWS Linux 4.9.20-11.31.amzn1.x86_64
* The output of `pip freeze`:
$ pip freeze
click==6.7
Flask==0.12.2
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
Werkzeug==0.12.2

* Link to your project (optional):
* Your `zappa_settings.py`: 
$ cat zappa_settings.json
{
    "dev": {
        "app_function": "hello.app",
        "aws_region": "us-west-2",
        "profile_name": "default",
        "project_name": "hello-flask",
        "runtime": "python3.6",
        "s3_bucket": "zappa-zgy5747y4"
    }
}

**Comment by tk3369** [comment]
FYI.  Running deploy again worked fine.  

However, a simple hello_world flask app happily returns Internal Server Error.

```
$ cat hello.py
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'

if __name__ == '__main__':
    app.run()
```

**Comment by tk3369** [comment]
Found the problem and fixed it!  Just Fyi:

Internal Server Error was caused by missing handler.py.  It's my fault - zappa was installed in the root python environment rather than the virtual environment of the app.  Installing zappa in the virtual environment fixed the problem.
