### ISSUE TITLE
Zappa _ Lambda-packages 0.16.1 fail to install on rpi Jessie Stretch

### ISSUE THREAD

**Issue by kebogaer** [Miserlou/Zappa#1173]
Trying to load zappa on my raspberry pi, and it fails.
When I try to install zappa, it reaches for lambda-pacakges-0.16.1, giving me the following error:

Collecting kappa==0.6.0 (from zappa)
  Downloading kappa-0.6.0-py2-none-any.whl
Collecting lambda-packages==0.16.1 (from zappa)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://www.piwheels.hostedpi.com/simple/lambda-packages/

(venv) pi@raspberrypi:~/kodi-alexa $

What may be causing this?

**Comment by kebogaer** [comment]
IT seems lambda-packages 17 can be fetched, but it seems zappa needs 0.16.1?

**Comment by kebogaer** [comment]
Any comment/help on this please?

**Comment by bennuttall** [comment]
Ok we discovered that there's a known bug in pip which breaks when additional indexes 404. The bug is still open in [pypa/pip](https://github.com/pypa/pip/issues/4605), and we can't expect a fix to find its way into Debian any time soon.

However, we (piwheels) have mitigated this by creating empty directories for packages we haven't successfully built, which means pip gets an empty list of files rather than a 404 (which is an enhandled exception causing the fatal error).

Hopefully that means that this is no longer an issue here.

**Comment by Miserlou** [comment]
Nasty bug! Thanks for diagnosing and reporting back here. I'm gonna close as this isn't a Zappa issue.

Related: https://github.com/pypa/pip/issues/4580

**Comment by bennuttall** [comment]
Also have you seen what lambda_packages is? It's a package that contains sdist tarballs of a bunch of other packages (for AWS Lambda). Pointless on a Pi - no idea why it's a dependency...
