### ISSUE TITLE
Deploy on Py27 Causing Issue with xray

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#1182]
## Context

 
Went to deploy a new project and got this error

```bash
Traceback (most recent call last):
  File "/myproject/env/lib/python2.7/site-packages/zappa/cli.py", line 2525, in handle
    sys.exit(cli.handle())
  File "/myproject/env/lib/python2.7/site-packages/zappa/cli.py", line 484, in handle
    self.dispatch_command(self.command, stage)
  File "/myproject/env/lib/python2.7/site-packages/zappa/cli.py", line 518, in dispatch_command
    self.deploy()
  File "/myproject/env/lib/python2.7/site-packages/zappa/cli.py", line 734, in deploy
    aws_kms_key_arn=self.aws_kms_key_arn
  File "/myproject/env/lib/python2.7/site-packages/zappa/core.py", line 972, in create_lambda_function
    'Mode': 'Active' if self.xray_tracing else 'PassThrough'
  File "/myproject/env/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/myproject/env/lib/python2.7/site-packages/botocore/client.py", line 518, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/myproject/env/lib/python2.7/site-packages/botocore/client.py", line 573, in _convert_to_request_dict
    api_params, operation_model)
  File "/myproject/env/lib/python2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Unknown parameter in input: "TracingConfig", must be one of: FunctionName, Runtime, Role, Handler, Code, Description, Timeout, MemorySize, Publish, VpcConfig, DeadLetterConfig, Environment, KMSKeyArn

```

## Expected Behavior

You know, it deploys

## Actual Behavior

I get a fun traceback

## Possible Fix

No clue here

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: 0.44.3
* Operating System and Python version: OSX Python 2.7.13

* The output of `pip freeze`:
appdirs==1.4.3
argcomplete==1.9.2
base58==0.2.4
boto3==1.4.4
botocore==1.5.38
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
coverage==4.3.4
docutils==0.13.1
durationpy==0.5
funcsigs==1.0.2
future==0.16.0
futures==3.0.5
hjson==3.0.0
idna==2.6
Jinja2==2.9.6
jmespath==0.9.2
kappa==0.6.0
lambda-packages==0.16.1
MarkupSafe==1.0
nodb==0.3.2
nose==1.3.7
packaging==16.8
pbr==2.0.0
piplapis-python==5.1.4
placebo==0.8.1
pyparsing==2.2.0
python-dateutil==2.6.0
python-http-client==3.0.0
python-slugify==1.2.4
pytz==2017.2
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.10
sendgrid==5.2.0
six==1.10.0
toml==0.9.2
tqdm==4.15.0
troposphere==2.0.0
Unidecode==0.4.21
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.44.3

* Your `zappa_settings.py`: 
```json
{
    "prod": {
        "touch": false,
        "keep_warm": false,
        "apigateway_enabled": false,
        "aws_region": "us-east-1",
        "profile_name": "default",
        "project_name": "scheduled-funks",
        "runtime": "python2.7",
        "s3_bucket": "zappa-builds-prod",
        "timeout_seconds": 300,
        "events": [
            {
                "function": "scheduled_funks.funky.func",
                "expression": "rate(30 minutes)"
            }
        ],
        "log_level": "DEBUG",
        "memory_size": 128
    }
}
```

**Comment by mcrowson** [comment]
Any ideas @mathom ?

**Comment by mcrowson** [comment]
Closing. Issue was due to outdated boto/botocore required by another package.
