### ISSUE TITLE
An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation

### ISSUE THREAD

**Issue by robomotic** [Miserlou/Zappa#1193]
## Context
I have added a function handle to process new S3 objects into my existing flask app process.
The flask app process is working fine.

## Expected Behavior
I will expect no errors when deploying the new function.

## Actual Behavior
I received this error:

Calling tail for stage fileprocess..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/zappa/cli.py", line 2525, in handle
    sys.exit(cli.handle())
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/zappa/cli.py", line 484, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/zappa/cli.py", line 572, in dispatch_command
    force_colorize=self.vargs['force_color'] or None,
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/zappa/cli.py", line 984, in tail
    filter_pattern=filter_pattern,
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/zappa/core.py", line 2506, in fetch_logs
    orderBy='LastEventTime'
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/robomotic/.pyenv/versions/AwsFlask/lib/python3.6/site-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!

## Steps to Reproduce
I am following the example provided in the documentation page and the examples to fit my use case.
The code for the event case:

import boto3

s3_client = boto3.client('s3')

def process_upload_function(event, context):
    """
    Process a file upload.
    """
    print("File processing in S3")
    # Get the uploaded file's information
    bucket = event['Records'][0]['s3']['bucket']['name'] # Will be `my-bucket`
    key = event['Records'][0]['s3']['object']['key'] # Will be the file path of whatever file was uploaded.
    print(bucket)
    print(key)
    # Get the bytes from S3
    s3_client.download_file(bucket, key, '/tmp/' + key) # Download this file to writable tmp space.
    print("File downloaded")
    file_bytes = open('/tmp/' + key).read()
    print("File read")

## Your Environment

* Zappa version used: 0.44.3
* Operating System and Python version: OSX, Python 3.6.0
* The output of `pip freeze`:
argcomplete==1.9.2
base58==0.2.4
boto==2.48.0
boto3==1.4.7
botocore==1.7.14
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
docutils==0.14
dominate==2.3.1
durationpy==0.5
Flask==0.12.2
Flask-Bootstrap==3.3.7.1
Flask-SQLAlchemy==2.3.2
future==0.16.0
futures==3.1.1
hjson==3.0.0
idna==2.6
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
MarkupSafe==1.0
placebo==0.8.1
psycopg2==2.7.3.1
python-dateutil==2.6.1
python-magic==0.4.13
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.11
six==1.11.0
SQLAlchemy==1.1.14
toml==0.9.2
tqdm==4.15.0
troposphere==2.0.1
Unidecode==0.4.21
urllib3==1.22
visitor==0.1.3
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.44.3

* Link to your project (optional):
* Your `zappa_settings.py`: 
{
    "fileprocess": {
     "project_name": "logstotal_file_dissector",
     "keep_warm": false,
     "debug": true,
     "log_level": "DEBUG",
     "events": [{
          "function": "dissector.process_upload_function",
          "event_source": {
                "arn":  "arn:aws:s3:::landing.logstotal.com",
                "events": [
                  "s3:ObjectCreated:*
                ]
             }
          }],
      "aws_region": "eu-west-2",
     "s3_bucket": "logstotal-flask-app-dev-eu-west-2",
     "lambda_handler": "app.lambda_handler",
     "use_apigateway": false,
     "http_methods": ["GET"],
     "parameter_depth": 1,
     "timeout_seconds": 300,
     "memory_size": 128,
     "use_precompiled_packages": true
    },
    "main": {
       "project_name": "logstotal_flask_app",
       "keep_warm": false,
       "debug": true,
       "log_level": "DEBUG",
       "aws_region": "eu-west-2",
       "s3_bucket": "logstotal-flask-app-dev-eu-west-2",
       "app_function": "app.app",
       "http_methods": ["GET","POST"],
       "parameter_depth": 1,
       "timeout_seconds": 300,
       "memory_size": 128,
       "use_precompiled_packages": true
    }
}

**Comment by robomotic** [comment]
It seems this issue is related to #1194 which I have solved.

**Comment by robomotic** [comment]
I am sorry but have to reopen this, I have made a fork and with the relevant change to reproduce [here](https://github.com/robomotic/Zappa/blob/master/example/zappa_settings.json).

Which still produces the: 
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.

**Comment by robomotic** [comment]
It seems like that the issue is having underscores in the function name, using a function name without underscore is working, obviously somebody hasn't tested it since in the example there is a function with the underscore but not in the zappa configuration.

**Comment by robomotic** [comment]
I have found another issue which cannot be easily bypassed is when you receive SNS events:

>      "events": [{
>           "function": "imagehasher.process",
>           "event_source": {
>                 "arn":  "arn:aws:sns:aaaaa:aaaaaaaaa:landing_logstotal_com",
>                 "events": [
>                   "sns:Publish"
>                 ]
>              }
>           }],

Those ARN are usually very long so I am unable to shorten that.
