### ISSUE TITLE
No space left on device: IOError

### ISSUE THREAD

**Issue by brandonhilkert** [Miserlou/Zappa#1203]
Getting the following error when attempting to run function: `No space left on device: IOError`. I've increased the RAM to 1GB, assuming it would need enough memory to untar the whole thing.

I'm using `slim_handler: true` in config.

```
Packaging project as gzipped tarball.
Downloading and installing dependencies..
Packaging project as zip.
Uploading bark-api-dev-1509120567.tar.gz (144.5MiB)..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 152M/152M [00:32<00:00, 2.61MB/s]
Uploading handler_bark-api-dev-1509120733.zip (7.0MiB)..
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.31M/7.31M [00:01<00:00, 4.37MB/s]
Updating Lambda function code..
Updating Lambda function configuration..
Uploading bark-api-dev-template-1509120781.json (1.6KiB)..
```

`Uploading bark-api-dev-1509120567.tar.gz (144.5MiB)..`
Extracted size: `583.1 MB on disk`

## Context
I saw the issues surrounding .zip files and extracting the contents and them both being on the drive at the same time. Seems like there's been a release since then, which relies on tar.gz files, which I see being created in the output during a deploy.

## Expected Behavior
Function should run.

## Actual Behavior
```
[1509120799538] [Errno 28] No space left on device: IOError
Traceback (most recent call last):
  File "/var/task/handler.py", line 511, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 239, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 104, in __init__
  self.load_remote_project_archive(project_archive_path)
  File "/var/task/handler.py", line 168, in load_remote_project_archive
  t.extractall(project_folder)
  File "/usr/lib64/python2.7/tarfile.py", line 2079, in extractall
  self.extract(tarinfo, path)
  File "/usr/lib64/python2.7/tarfile.py", line 2116, in extract
  self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib64/python2.7/tarfile.py", line 2192, in _extract_member
  self.makefile(tarinfo, targetpath)
  File "/usr/lib64/python2.7/tarfile.py", line 2233, in makefile
  copyfileobj(source, target)
  File "/usr/lib64/python2.7/tarfile.py", line 266, in copyfileobj
  shutil.copyfileobj(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 52, in copyfileobj
  fdst.write(buf)
IOError: [Errno 28] No space left on device
```

## Your Environment

* Zappa version used: `0.44.3`
* Operating System and Python version: OSX El Capitan / `2.7.44`
* The output of `pip freeze`:
```
alphabet-detector==0.0.5
aniso8601==1.1.0
appdirs==1.4.3
argcomplete==1.9.2
asn1crypto==0.23.0
backports.csv==1.0.4
-e git+git@github.com:Bark-us/bark-nlp.git@7327b230db47fba6ef7d7c41663ff8e28f4c2128#egg=bark_nlp
base58==0.2.4
beautifulsoup4==4.5.3
boto==2.42.0
boto3==1.4.7
botocore==1.7.14
bs4==0.0.1
bz2file==0.98
cachetools==2.0.0
cffi==1.10.0
-e git+git@github.com:Bark-us/classify-text.git@dcde234fd3102a3612189052052e76ffa9c0e26d#egg=classify_text
cld2-cffi==0.1.4
click==6.6
cloudpickle==0.2.1
ConceptNet==5.4.2
cryptography==2.1.2
cymem==1.31.2
cytoolz==0.8.2
decorator==4.0.11
dill==0.2.6
docutils==0.14
durationpy==0.5
emoji==0.3.9
enum34==1.1.6
Flask==0.11.1
Flask-Cors==3.0.2
Flask-HTTPAuth==3.2.1
Flask-Limiter==0.9.3
Flask-RESTful==0.3.5
ftfy==4.4.2
funcsigs==1.0.2
future==0.16.0
futures==3.1.1
fuzzywuzzy==0.15.0
gensim==0.12.1
-e git+git@github.com:Bark-us/gglsbl.git@72a02c4c01cf87fd5a9b1fa31c8fd70310b58110#egg=gglsbl
google-api-python-client==1.6.2
grako==3.14.0
hjson==3.0.0
html5lib==0.999999999
httplib2==0.10.3
idna==2.6
ijson==2.3
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.8
jmespath==0.9.3
joblib==0.10.0
kappa==0.6.0
lambda-packages==0.16.1
langcodes-py2==1.1.2
limits==1.1.1
marisa-trie==0.7.2
MarkupSafe==0.23
mock==2.0.0
msgpack-python==0.4.8
murmurhash==0.26.4
ndg-httpsclient==0.4.2
-e git+git@github.com:Bark-us/neo4j-rest-client.git@bc1151f84c7612643902b6a5756f7db0ebfafae6#egg=neo4jrestclient
networkx==1.11
newrelic==2.70.0.51
nltk==3.2
nose==1.3.7
numpy==1.11.1
oauth2client==3.0.0
oauthlib==2.0.0
packaging==16.8
pandas==0.18.1
pathlib==1.0.1
Pattern==2.6
pbr==1.10.0
plac==0.9.6
placebo==0.8.1
preshed==1.0.0
psycopg2==2.6.2
pyasn1==0.2.3
pyasn1-modules==0.0.8
pycparser==2.17
pyemd==0.4.3
pyenchant==1.6.6
Pygments==2.1.3
pyOpenSSL==17.0.0
pyparsing==2.2.0
Pyphen==0.9.4
python-dateutil==2.6.1
python-Levenshtein==0.12.0
python-slugify==1.2.4
pytz==2016.6.1
PyYAML==3.12
requests==2.13.0
requests-oauthlib==0.6.2
rsa==3.4.2
s3transfer==0.1.11
scikit-learn==0.17.1
scipy==0.18.1
semver==2.6.0
simplejson==3.8.2
six==1.11.0
sklearn==0.0
smart-open==1.3.4
spacy==1.7.3
sputnik==0.9.3
termcolor==1.1.0
textacy==0.3.3
textblob==0.11.1
-e git+https://github.com/sloria/textblob-aptagger.git@fb98bbd16a83650cab4819c4b89f0973e60fb3fe#egg=textblob_aptagger
-e git+git@github.com:Bark-us/textstat.git@f94746d5596c10ab7e46ef78b62b89224d044937#egg=textstat
thinc==6.5.2
toml==0.9.2
toolz==0.8.2
tqdm==4.15.0
troposphere==2.0.2
twython==3.4.0
ujson==1.35
Unidecode==0.4.20
uritemplate==3.0.0
urllib3==1.20
wcwidth==0.1.7
webencodings==0.5
Werkzeug==0.12
wrapt==1.10.10
wsgi-request-logger==0.4.6
xgboost==0.6a2
xmltodict==0.10.2
zappa==0.44.3
```

* Link to your project (optional):
* Your `zappa_settings.py`: 

```
{
    "dev": {
        "app_function": "sever.app",
        "aws_region": "us-east-1",
        "profile_name": "default",
        "project_name": "bark-api",
        "runtime": "python2.7",
        "slim_handler": true,
        "manage_roles": false,
        "role_name": "bark-api-dev-ZappaLambdaExecutionRole",
        "s3_bucket": "zappa-[bucketid]",
        "timeout_seconds": 300,
        "memory_size": 1024,
        "vpc_config": {
          "SubnetIds": ["subnet-fd3564a5", "subnet-6abf8957", "subnet-61070317", "subnet-4c015566"],
          "SecurityGroupIds": ["sg-3e433645"]
        }
    }
}
```

**Comment by brandonhilkert** [comment]
I realized the extracted size is larger than the limit, so nothing can be done here.

**Comment by Miserlou** [comment]
What do you have that's so giant? Check the contents of your package, it's possible there's something big in there that you can `exclude`

**Comment by brandonhilkert** [comment]
Yeah, it's a bunch of ML packages, which we need to audit to attempt this. Thanks!

**Comment by bjinwright** [comment]
@brandonhilkert Are there any file types that you could shove in S3 that your zip? Also, are there files that are already in S3 that can be filtered out in the zappa_settings.json using the **exclude** setting.

**Comment by brandonhilkert** [comment]
@bjinwright It's actually just really big packages (e.g. `pandas`, `scikit-learn`, etc.). We have to try to pull some out. I don't think all are in use.
