### ISSUE TITLE
Failure to deploy while following tutorial instructions.

### ISSUE THREAD

**Issue by goodtune** [Miserlou/Zappa#1220]
## Expected Behavior
Successful deployment.

## Actual Behavior
Failed deployment with following traceback.

```
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "~/.virtualenvs/zappademo/lib/python2.7/site-packages/zappa/cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "~/.virtualenvs/zappademo/lib/python2.7/site-packages/zappa/cli.py", line 505, in handle
    self.dispatch_command(self.command, stage)
  File "~/.virtualenvs/zappademo/lib/python2.7/site-packages/zappa/cli.py", line 539, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "~/.virtualenvs/zappademo/lib/python2.7/site-packages/zappa/cli.py", line 769, in deploy
    self.lambda_arn = self.zappa.create_lambda_function(**kwargs)
  File "~/.virtualenvs/zappademo/lib/python2.7/site-packages/zappa/core.py", line 1048, in create_lambda_function
    response = self.lambda_client.create_function(**kwargs)
  File "~/.virtualenvs/zappademo/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "~/.virtualenvs/zappademo/lib/python2.7/site-packages/botocore/client.py", line 605, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (SubscriptionRequiredException) when calling the CreateFunction operation: The AWS Access Key Id needs a subscription for the service

==============
```

## Steps to Reproduce
1. django-admin startproject zappademo
2. cd zappademo
3. mkvirtualenv zappademo
4. pip install django zappa
5. zappa init # accept all defaults
6. zappa deploy dev

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: macOS 10.12.6
* The output of `pip freeze`: 
```
argcomplete==1.9.2
base58==0.2.4
boto3==1.4.7
botocore==1.7.39
certifi==2017.11.5
chardet==3.0.4
click==6.7
Django==1.11.7
docutils==0.14
durationpy==0.5
future==0.16.0
futures==3.1.1
hjson==3.0.1
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
placebo==0.8.1
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2017.3
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.11
six==1.11.0
toml==0.9.3
tqdm==4.19.1
troposphere==2.0.2
Unidecode==0.4.21
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1
```
* Link to your project (optional):
* Your `zappa_settings.json`: 
```json
{
    "dev": {
        "aws_region": "ap-southeast-2",
        "django_settings": "zappademo.settings",
        "profile_name": "default",
        "project_name": "zappademo",
        "runtime": "python2.7",
        "s3_bucket": "zappa-wcdm8o6hz"
    }
}
```

**Comment by goodtune** [comment]
Seems to have been related to my billing details; updating my credit card resolved the issue and I was able to upload the bundle.

**Comment by el-aro** [comment]
it is normal that i have the same message, but i can update in a machine with a key an api, but using the same credentials in another machine gave me that message "The AWS Access Key Id needs a subscription for the service" ?
