### ISSUE TITLE
Zappa Certify: BadRequest -Unable to associate certificate with CloudFront

### ISSUE THREAD

**Issue by JimiPedros** [Miserlou/Zappa#1225]
Zappa Certify BadRequest Errors:  Unable to associate certificate with CloudFront
## Context
Recently transferred a domain from GoDaddy to AWS. I have generated a certificate and put this in the zappa settings json file.
Python 2.7

## Expected Behavior
Should certify the domain

## Actual Behavior
```
Certifying domain minnidesign.com..
Updating domain name!
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/JamesPeters/FlowersDiana/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 2489, in handle
    sys.exit(cli.handle())
  File "/home/JamesPeters/FlowersDiana/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 473, in handle
    self.dispatch_command(self.command, stage)
  File "/home/JamesPeters/FlowersDiana/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 577, in dispatch_command
    manual=self.vargs['manual']
  File "/home/JamesPeters/FlowersDiana/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 1741, in certify
    route53=self.stage_config.get('route53_enabled', True)
  File "/home/JamesPeters/FlowersDiana/venv/local/lib/python2.7/site-packages/zappa/core.py", line 1801, in update_domain_name
    "value" : certificate_arn}
  File "/home/JamesPeters/FlowersDiana/venv/local/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/JamesPeters/FlowersDiana/venv/local/lib/python2.7/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
BadRequestException: An error occurred (BadRequestException) when calling the UpdateDomainName operation: Unable to associate certificate arn:aws:acm:us-east-1:_________:certificate/57cd____-__________________ with CloudFront. This error may prevent the domain name minnidesign.com from being used in API Gateway for up to 40 minutes. Please ensure the certificate domain name matches the requested domain name, and that this user has permission to call cloudfront:UpdateDistribution on '*' resources.

```
## Steps to Reproduce
1. zappa certify

## Your Environment
`argcomplete==1.8.2
asn1crypto==0.22.0
awscli==1.11.123
base58==0.2.4
boto3==1.4.4
botocore==1.5.40
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.4
click==6.7
colorama==0.3.7
cryptography==2.0
docutils==0.13.1
durationpy==0.4
enum34==1.1.6
Flask==0.12.2
future==0.16.0
futures==3.1.1
hjson==2.0.7
idna==2.5
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
MarkupSafe==1.0
passlib==1.7.1
placebo==0.8.1
pyasn1==0.2.3
pycparser==2.18
pynamodb==3.1.0
pyOpenSSL==17.2.0
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.1
rsa==3.4.2
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.14.0
troposphere==1.9.4
Unidecode==0.4.21
urllib3==1.21.1
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.43.1`

`{
    "staging": {
        "app_function": "__init__.app",
        "aws_region": "ap-southeast-2",
        "profile_name": "default",
        "s3_bucket": "zappa-g8dee1e1c"
        "domain": "minnidesign.com",
        "certificate_arn": "arn:aws:acm:us-east-1:_________:certificate/57cd____-__________________"
    }
}`

**Comment by scoates** [comment]
Is it possible that `arn:aws:acm:us-east-1:_________:certificate/57cd____-__________________` isn't actually a certificate for `minnidesign.com`?

**Comment by pavel64-sutyrin** [comment]
I am experiencing similar problem. @JimiPedros what's the status of your certificate, isn't it in "pending validation" perha[s?

**Comment by danielfranca** [comment]
@pavel64-sutyrin Did you find out what was the issue? I'm experiencing the same thing, I hope I don't need to move everything to us-east-1

**Comment by jneves** [comment]
The requirement that the certificate is in us-east-1 is a cloudfront one, but other than that you can have everything else somewhere else.

**Comment by aralmpa** [comment]
Just to complement above previous discussions @danielfranca since I already faced this issue:

As jneves said AWS CloudFront requires ACM certificates to be in N.Virginia (us-east-1) in order to be used by it. Now you only are required to use CloudFront for you API endpoint only if using API Gateway in 'EDGE-optimized' mode. 'REGIONAL' type APIs do not make use of CloudFront and therefore can make use of a certificate created in the same region.

**Comment by aralmpa** [comment]
So I just tried using the REGIONAL configuration / type of my zappa deployed API and then tried making the certification process outlined in the Zappa documentation (where it is stated that the certificate should be in us-east-1) and as expected failed. 

However you are able to use a regional (same region that is) certificate with a REGIONAL API and this capability is offered by the similar to Zappa Serverless Framework (a plugin of the framework to be precise). I suppose this is a matter of implementation? A feature not yet implemented for Zappa?

**Comment by danielfranca** [comment]
@aralmpa so, as it is not implemented by Zappa, am I required to have everything on us-east-1?
I tried the same approach, setting the endpoint to regional, creating the certificate in the same region... and it failed

**Comment by aralmpa** [comment]
@danielfranca If I understood jneves's answer correctly, for EDGE-optimized types of API, you only need the certificates to be in N. Virginia - everything else can be wherever you want.

**Comment by danielfranca** [comment]
I thinking I got in a certificate hell, if there's such thing

I have attempted to create certification using zappa, but kept getting the message

`botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the CreateDomainName operation: Unable to associate certificate arn:aws:acm:us-east-1:111111:certificate/xxxxxxxxxxxx with CloudFront. This error may prevent the domain name xxxx.com from being used in API Gateway for up to 40 minutes. Please ensure the certificate domain name matches the requested domain name, and that this user has permission to call cloudfront:UpdateDistribution on '*' resources.`
I cheked to see if the zappa role was missing the cloudfront:UpdateDistribution permission, and it was... so I thought "maybe that is it"
So, I added the cloudfront:UpdateDistribution to the zappa permissions... simulated the command through the simulator... working fine
but still getting the same message

so, I tried manually attach the certifiate with the API Gateway, set the route53... blabla... started getting a forbidden message on the endpoint through the domain name
tried to create manually a cloudfront distribution, with the certificate on it... still not working
I said, f***** this shit, let me move everyting to us-east-1 and start over

Then I deleted the domain from the CF distribution, undeployed everything, changed the S3 bucket and region to us-east-1 and re-deployed it to us-east-1, which works fine and the project is accessible now from the API GW url

Now back to the certificate 
Tried to delete the certificate, and it doesn't let me to do it, stating that it is associated to a CF distribution... that was deleted already.
I thought that I probably just had to wait a bit... and here I am 3 hours later, getting the same error every time I try to delete the certificate

I also tried to certifiy via zappa with this same old certificate, and got the same error, again
`when calling the CreateDomainName operation: Unable to associate certificate arn:aws:acm:us-east-1:11111:certificate/xxxxxx with CloudFront. This error may prevent the domain name blablabla.com`

I also have tried adding extra_permissions on Zappa settings file:
        "extra_permissions": [{ 
            "Effect": "Allow",
            "Action": ["cloudfront:UpdateDistribution"], 
            "Resource": "*"
        }],
No success

I decided to go for another subdomain, so I created the certificate for it, updated the ARN and domain on the zappa settings

And again getting the same error, so I guess my error is somewhere else, not related to the region/domain

Not idea where else to look

I'll try it again Tomorrow

**Comment by aralmpa** [comment]
Sorry to hear that you are having so much hard time @danielfranca  - I just tried deploying an example with domain certification support through Zappa and it worked smoothlessly.

So I followed these steps:
1) zappa deploy dev (with regular zappa_settings.json - nothing needed for now)
2) Go to AWS ACM (N. Virginia) create the certificate and make sure it is issued normally
3) add in zappa_settings.json the following
[a) **certficate_arn**: arn from step 2 b) **domain**: example.com c) **route53_enabled**: true (assuming you have AWS as your domain's DNS)]
4) zappa certify dev

A regular message appears after this like:
`
Certifying domain example.com..
Created a new domain name with supplied certificate. Please note that it can take up to 40 minutes for this domain to be created and propagated through AWS, but it requires no further work on your part.
Certificate updated!
`

Then everything seems to be working right - I am able to access my app through the domain. 
Note that my deployment stack is in Ireland whilst my certificate in N. Virginia. 
Note No2: I used admin rights for all this so it might be an indication that permissions might be at fault in your case - I ll try again with required permissions only.

Maybe there is something else in your stack? Did you try a different flow from the above-described?

A third Note: the Route53 A record was not deleted when I undeployed the stack - not sure if this should be also be part of the clean up process

**Comment by danielfranca** [comment]
damn, I have changed my credentials to an Admin one, and it worked!
So, it was permission related, but not the UpdateDistribtution one, I guess

**Comment by jneves** [comment]
Extra permissions is for the execution role, not the one deploying. I think that may have confused you.On 11 Mar 2020 10:10, Daniel França <notifications@github.com> wrote:damn, I have changed my credentials to an Admin one, and it worked!
So, it was permission related, but not the UpdateDistribtution one, I guess

**Comment by aralmpa** [comment]
Yes it make sense that this confusion happened. The user (or in some other cases  the role) that is doing the **certify** needs to have the **UpdateDistribution** permission (at least I assume others as well) and the permissions of this user do no relate at all with the extra permissions of the execution role that refer to the rights of the executing function created by Zappa.

It seems that the error that danielfranca faced is identical with the original reported in the issue so I would say if @danielfranca can confirm that the previous user he was using did not had the appropriate rights (especially the UpdateDistribution) we can pretty much safely say that we have found the cause of this issue. Zappa certify seems to be working fine.
