### ISSUE TITLE
Initial deploy error on "No such file or directory"

### ISSUE THREAD

**Issue by scottishbee** [Miserlou/Zappa#1232]
I'm attempting my first deploy.  I have a simple Flask app that works locally, and I can run `zappa init`. When I try `zappa deploy dev` I get an error that I that seems to come from referencing my local libraries.

Full disclosure: I'm fairly new to python for apps, coming from python for data analysis.

## Context
I've built a flask app that pings a database using sqlalchemy and returns some query results.  I'm trying to get it to deploy via Zappa in order to use it as a framework for some database monitoring.

## Expected Behavior
Successful deploy similar to tutorial.

## Actual Behavior
When running `zappa deploy dev` ...

```

Calling deploy for stage dev..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/scottieb/anaconda/lib/python3.6/site-packages/zappa/cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "/Users/scottieb/anaconda/lib/python3.6/site-packages/zappa/cli.py", line 505, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/scottieb/anaconda/lib/python3.6/site-packages/zappa/cli.py", line 539, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/Users/scottieb/anaconda/lib/python3.6/site-packages/zappa/cli.py", line 709, in deploy
    self.create_package()
  File "/Users/scottieb/anaconda/lib/python3.6/site-packages/zappa/cli.py", line 2171, in create_package
    disable_progress=self.disable_progress
  File "/Users/scottieb/anaconda/lib/python3.6/site-packages/zappa/core.py", line 572, in create_lambda_zip
    copytree(site_packages, temp_package_path, symlinks=False, ignore=shutil.ignore_patterns(*excludes))
  File "/Users/scottieb/anaconda/lib/python3.6/site-packages/zappa/utilities.py", line 32, in copytree
    shutil.copystat(src, dst)
  File "/Users/scottieb/anaconda/lib/python3.6/shutil.py", line 198, in copystat
    st = lookup("stat")(src, follow_symlinks=follow)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/scottieb/Dropbox/0.\\ Re-orged\\ to\\ Stay/Breuds\\ Data/breuds/lib/python3.6/site-packages'

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
```

## Possible Fix
I'm guessing that somehow I am including references to libraries that do not get deployed as well.  Or perhaps I am calling libraries outside my virtualenv (I use flask, pandas, numpy, sqlalchemy and datetime).

## Steps to Reproduce
1. zappa init
2. zappa deploy dev

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: OS 10.13.1, python 3.6.2
* The output of `pip freeze`:
```
alabaster==0.7.10
altair==1.2.0
anaconda-client==1.6.5
anaconda-navigator==1.6.4
anaconda-project==0.8.0
appnope==0.1.0
appscript==1.0.1
argcomplete==1.9.2
asn1crypto==0.22.0
astroid==1.5.3
astropy==2.0.2
Babel==2.4.0
backports.shutil-get-terminal-size==1.0.0
base58==0.2.4
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.0.0
bokeh==0.12.6
boto==2.48.0
boto3==1.4.7
botocore==1.7.41
Bottleneck==1.2.1
branca==0.2.0
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
chest==0.2.3
click==6.7
click-plugins==1.0.3
cligj==0.4.0
cloudpickle==0.4.0
clyent==1.2.2
colorama==0.3.9
conda==4.3.29
configobj==5.0.6
contextlib2==0.5.5
cryptography==2.0.3
cycler==0.10.0
Cython==0.26.1
cytoolz==0.8.2
dask==0.15.2
datashape==0.5.4
decorator==4.1.2
descartes==1.1.0
dill==0.2.6
distributed==1.18.3
docopt==0.4.0
docutils==0.14
durationpy==0.5
entrypoints==0.2.3
et-xmlfile==1.0.1
fastcache==1.0.2
Fiona==1.7.9
Flask==0.12.2
Flask-Cors==3.0.3
folium==0.5.0
future==0.16.0
GDAL==2.1.3
geopandas==0.3.0
geopy==1.11.0
gevent==1.2.2
gmpy2==2.0.8
greenlet==0.4.12
h5py==2.7.0
heapdict==1.0.0
hjson==3.0.1
html5lib==0.999999999
idna==2.5
imageio==2.2.0
imagesize==0.7.1
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
ipywidgets==7.0.0
isort==4.2.15
itsdangerous==0.24
jdcal==1.3
jedi==0.10.2
Jinja2==2.9.6
jmespath==0.9.3
jsonschema==2.6.0
jupyter-client==5.1.0
jupyter-console==5.1.0
jupyter-core==4.3.0
kappa==0.6.0
lambda-packages==0.19.0
lazy-object-proxy==1.3.1
llvmlite==0.20.0
locket==0.2.0
lxml==3.8.0
mandrill==1.0.57
MarkupSafe==1.0
matplotlib==2.0.2
mccabe==0.6.1
mistune==0.7.4
mpmath==0.19
msgpack-python==0.4.8
multipledispatch==0.4.9
munch==2.2.0
nb-conda==2.2.1
nb-conda-kernels==2.1.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==1.11
nltk==3.2.4
nose==1.3.7
notebook==5.0.0
numba==0.35.0
numexpr==2.6.2
numpy==1.12.1
numpydoc==0.7.0
odo==0.5.1
olefile==0.44
openpyxl==2.5.0a3
osmnx==0.5.3
pandas==0.20.3
pandocfilters==1.4.1
partd==0.3.8
path.py==10.3.1
pathlib2==2.3.0
patsy==0.4.1
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.2.1
placebo==0.8.1
ply==3.10
prompt-toolkit==1.0.15
psutil==5.2.2
psycopg2==2.7.3.2
ptyprocess==0.5.2
py==1.4.34
pyasn1==0.3.3
pycodestyle==2.3.1
pycosat==0.6.2
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.7.1
pyOpenSSL==17.2.0
pyparsing==2.2.0
pyproj==1.9.5.1
PySAL==1.13.0
PySocks==1.6.7
pytest==3.2.2
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2017.3
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
redis==2.10.5
requests==2.18.4
rope==0.10.7
Rtree==0.8.3
ruamel-yaml==0.11.14
s3transfer==0.1.11
scikit-image==0.13.0
scikit-learn==0.19.0
scipy==0.19.1
seaborn==0.8.1
Shapely==1.6.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
sortedcontainers==1.5.7
Sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.2.3
SQLAlchemy==1.1.13
sqlalchemy-redshift==0.7.0
statsmodels==0.8.0
sympy==1.1.1
tables==3.4.2
tblib==1.3.2
terminado==0.6
testpath==0.3.1
toml==0.9.3
toolz==0.8.2
tornado==4.5.2
tqdm==4.19.1
traitlets==4.3.2
troposphere==2.0.2
typing==3.6.2
unicodecsv==0.14.1
Unidecode==0.4.21
urllib3==1.22
vega==0.4.4
vincent==0.4.4
virtualenv==15.1.0
wcwidth==0.1.7
webencodings==0.5
Werkzeug==0.12
widgetsnbextension==3.0.2
wrapt==1.10.11
wsgi-request-logger==0.4.6
xlrd==1.1.0
XlsxWriter==0.9.8
xlwings==0.11.4
xlwt==1.2.0
zappa==0.45.1
zict==0.1.2
```

* Your `zappa_settings.json`: 
```
{
    "dev": {
        "app_function": "ping-app.app",
        "aws_region": "us-west-1",
        "profile_name": "Breuds",
        "project_name": "breuds-data",
        "runtime": "python3.6",
        "s3_bucket": "zappa-ping-redshift"
    }
}
```

**Comment by nabaz** [comment]
just remove your virtualenv and create a new one `python -m venv env` and then run pip install -r requirements.txt and should solve the issue for you.

this happens when you have virtualenv running before installing zappa - at least for me that solved it
