### ISSUE TITLE
TraceConfig error when deploying

### ISSUE THREAD

**Issue by kyoto-shift** [Miserlou/Zappa#1241]
I keep getting this exact error when using `zappa deploy`:

> Traceback (most recent call last):
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/zappa/cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/zappa/cli.py", line 505, in handle
    self.dispatch_command(self.command, stage)
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/zappa/cli.py", line 539, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/zappa/cli.py", line 769, in deploy
    self.lambda_arn = self.zappa.create_lambda_function(**kwargs)
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/zappa/core.py", line 1048, in create_lambda_function
    response = self.lambda_client.create_function(**kwargs)
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/botocore/client.py", line 518, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/botocore/client.py", line 573, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Unknown parameter in input: "TracingConfig", must be one of: FunctionName, Runtime, Role, Handler, Code, Description, Timeout, MemorySize, Publish, VpcConfig, DeadLetterConfig, Environment, KMSKeyArn

I also get this error when running 'zappa invoke production --raw`:

> Traceback (most recent call last):
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/zappa/cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/zappa/cli.py", line 505, in handle
    self.dispatch_command(self.command, stage)
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/zappa/cli.py", line 561, in dispatch_command
    no_color=self.vargs['no_color'],
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/zappa/cli.py", line 1223, in invoke
    invocation_type='RequestResponse',
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/zappa/core.py", line 1153, in invoke_lambda_function
    Payload=payload
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/judah/.local/share/virtualenvs/kpfyes2-l82cPnw3/lib/python2.7/site-packages/botocore/client.py", line 544, in _make_api_call
    raise error_class(parsed_response, operation_name)
ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-1:key_for_aws:function:projectname-production

My project is a single app.py file, and my zappa config looks like this: 

>{
    "production": {
        "app_function": "app.app", 
        "aws_region": "us-west-1", 
        "profile_name": "default", 
        "project_name": "projejct_name", 
        "runtime": "python2.7", 
        "s3_bucket": "bucket_name"
    }
}`

**Comment by Miserlou** [comment]
Can  you give a `pip freeze` too?

**Comment by kyoto-shift** [comment]
Sure, this is what `pip freeze` gave me:

> appdirs==1.4.3
argcomplete==1.9.2
base58==0.2.4
boto3==1.4.4
botocore==1.5.38
certifi==2017.11.5
chardet==3.0.4
click==6.7
coverage==4.3.4
docutils==0.13.1
durationpy==0.5
funcsigs==1.0.2
future==0.16.0
futures==3.0.5
hjson==3.0.1
idna==2.6
jmespath==0.9.2
kappa==0.6.0
lambda-packages==0.19.0
nodb==0.3.2
nose==1.3.7
packaging==16.8
pbr==2.0.0
placebo==0.8.1
praw==5.2.0
prawcore==0.12.0
pyparsing==2.2.0
python-dateutil==2.6.0
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.10
six==1.10.0
toml==0.9.3
tqdm==4.19.1
troposphere==2.0.2
Unidecode==0.4.21
update-checker==0.16
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1

**Comment by Miserlou** [comment]
Your botos look way behind

**Comment by kyoto-shift** [comment]
If I run `pipenv update` I get this error:

> Updating all dependencies from Pipfile…
Found 0 installed package(s), purging…

Environment now purged and fresh!
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches boto3==1.4.4,>=1.4.7
Tried: 0.0.1, 0.0.1, 0.0.2, 0.0.2, 0.0.3, 0.0.3, 0.0.4, 0.0.4, 0.0.5, 0.0.5, 0.0.6, 0.0.6, 0.0.7, 0.0.7, 0.0.8, 0.0.8, 0.0.9, 0.0.9, 0.0.10, 0.0.10, 0.0.11, 0.0.11, 0.0.12, 0.0.12, 0.0.13, 0.0.13, 0.0.14, 0.0.14, 0.0.16, 0.0.16, 0.0.17, 0.0.17, 0.0.18, 0.0.18, 0.0.19, 0.0.19, 0.0.20, 0.0.20, 0.0.21, 0.0.21, 0.0.22, 0.0.22, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.1.0, 1.1.0, 1.1.1, 1.1.1, 1.1.2, 1.1.2, 1.1.3, 1.1.3, 1.1.4, 1.1.4, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 1.2.2, 1.2.2, 1.2.3, 1.2.3, 1.2.4, 1.2.4, 1.2.5, 1.2.5, 1.2.6, 1.2.6, 1.3.0, 1.3.0, 1.3.1, 1.3.1, 1.4.0, 1.4.0, 1.4.1, 1.4.1, 1.4.2, 1.4.2, 1.4.3, 1.4.3, 1.4.4, 1.4.4, 1.4.5, 1.4.5, 1.4.6, 1.4.6, 1.4.7, 1.4.7

**Comment by kyoto-shift** [comment]
Oh and running `pipenv install --skip-lock` just deletes all of my dependencies and basically kills the virtualenv

**Comment by kyoto-shift** [comment]
Somehow I got it to work. The only thing I did was `pip install zappa` outside of pipenv and then went back into pipenv and it just worked...

**Comment by Miserlou** [comment]
Yup
