### ISSUE TITLE
No Module Named 'task' with Mezzanine

### ISSUE THREAD

**Issue by jjorissen52** [Miserlou/Zappa#1245]
## Context
When running my application in a local virtual environment, everything works fine. However, when I attempt to deploy the project, I get this traceback in the tail:

```
Traceback (most recent call last):
  File "/var/task/django/core/handlers/base.py", line 131, in get_response
  response = middleware_method(request, response)
  File "/var/task/django/middleware/locale.py", line 36, in process_response
  i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
  File "/var/task/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
  for url_pattern in get_resolver(urlconf).url_patterns:
  File "/var/task/django/utils/functional.py", line 35, in __get__
  res = instance.__dict__[self.name] = self.func(instance)
  File "/var/task/django/urls/resolvers.py", line 313, in url_patterns
  patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/var/task/django/utils/functional.py", line 35, in __get__
  res = instance.__dict__[self.name] = self.func(instance)
  File "/var/task/django/urls/resolvers.py", line 306, in urlconf_module
  return import_module(self.urlconf_name)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'task'
```
I'm sure this has something to do with Mezzanine's Middleware, but I don't know what's wrong.

I am using python 3.6.

## Expected Behavior
I should be able to visit my homepage.

## Actual Behavior
Debug page.

## Steps to Reproduce
1. checkout my project https://github.com/jjorissen52/golf-site/ (make sure project root is golf_site)
2. fill in secrets.conf and possibly modify database settings to fit your setup
3. create virtual environment, run pip install -r requirements.txt, zappa init, deploy
4. attempt to visit homepage

## My Environment (golf_site_z)
* Zappa version used: zappa==0.45.1
* Operating System and Python version: Ubunutu 17.04, Python 3.6
* The output of `pip freeze`:
```
argcomplete==1.9.2
base58==0.2.4
beautifulsoup4==4.6.0
bleach==2.1.1
boto==2.48.0
boto3==1.4.7
botocore==1.7.46
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
Django==1.10.8
django-appconf==1.0.2
django-compressor==2.2
django-contrib-comments==1.8.0
django-storages-redux==1.3.3
djangorestframework==3.7.3
docutils==0.14
durationpy==0.5
filebrowser-safe==0.4.7
future==0.16.0
grappelli-safe==0.4.7
gunicorn==19.7.1
hjson==3.0.1
html5lib==1.0b10
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
Mezzanine==4.2.3
oauthlib==2.0.6
olefile==0.44
Pillow==4.3.0
placebo==0.8.1
psycopg2==2.7.3.2
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2017.3
PyYAML==3.12
rcssmin==1.0.6
requests==2.18.4
requests-oauthlib==0.8.0
rjsmin==1.0.12
s3transfer==0.1.11
six==1.11.0
toml==0.9.3
tqdm==4.19.1
troposphere==2.0.2
tzlocal==1.4
Unidecode==0.4.21
urllib3==1.22
webencodings==0.5.1
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1
```
* Link to project: https://github.com/jjorissen52/golf-site/ 
* `zappa_settings.json`
```
{
    "dev": {
        "aws_region": "us-east-1",
        "django_settings": "golf_site.settings",
        "profile_name": "default",
        "project_name": "golf_site",
        "runtime": "python3.6",
        "s3_bucket": "zappa-0sjf0bvd6",
        "exclude": ["__py_cache__", "__pycache__", "*.pyc", "uploads"]
    }
}
```
* `settings.py`: 
```
from __future__ import absolute_import, unicode_literals
import os, configparser, socket

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIRNAME = PROJECT_ROOT.split(os.sep)[-1]

config = configparser.ConfigParser()
config.read(os.path.join(PROJECT_ROOT, 'secrets.conf'))
USE_SOUTH = True
SECRET_KEY = config.get('django', 'secret_key')

########################
# MAIN DJANGO SETTINGS #
########################

# People who get code error notifications.
# In the format (('Full Name', 'email@example.com'),
#                ('Full Name', 'anotheremail@example.com'))
ADMINS = (
    (config.get('golf_site', 'admin_name'), config.get('golf_site', 'admin_email')),
)
MANAGERS = ADMINS
ALLOWED_HOSTS = ["*"]
USE_TZ = True

LANGUAGE_CODE = "en"

# Supported languages
_ = lambda s: s
LANGUAGES = (
    ('en', _('English')),
)

DEBUG = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SITE_ID = 1
USE_I18N = False
INTERNAL_IPS = ("127.0.0.1",)

AUTHENTICATION_BACKENDS = ("mezzanine.core.auth_backends.MezzanineBackend",)
FILE_UPLOAD_PERMISSIONS = 0o644


CACHE_MIDDLEWARE_KEY_PREFIX = PROJECT_DIRNAME
ROOT_URLCONF = "%s.urls" % PROJECT_DIRNAME
TEMPLATES = [
     {
         'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [
             # insert your TEMPLATE_DIRS here
             os.path.join(PROJECT_ROOT, "templates"),
             os.path.join(PROJECT_ROOT, "events/../events/templates"),
         ],
         'OPTIONS': {
             'context_processors': [
                 # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                 # list if you haven't customized them:
                 'django.contrib.auth.context_processors.auth',
                 'django.template.context_processors.debug',
                 # 'django.template.context_processors.i18n',
                 'django.template.context_processors.media',
                 'django.template.context_processors.request',
                 'django.template.context_processors.static',
                 'django.template.context_processors.tz',
                 'django.contrib.messages.context_processors.messages',
                 'mezzanine.pages.context_processors.page',
                 "mezzanine.conf.context_processors.settings",
                 "mezzanine.pages.context_processors.page",
             ],
             'loaders': [
                 # insert your TEMPLATE_LOADERS here
                 "django.template.loaders.filesystem.Loader",
                 "django.template.loaders.app_directories.Loader",
             ],
             'builtins': [
                 'mezzanine.template.loader_tags',
             ]
         },
     },
 ]


################
# APPLICATIONS #
################

INSTALLED_APPS = (
    # "flat",
    # "moderna",
    # "nova",
    "solid",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.redirects",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django.contrib.staticfiles",
    "mezzanine.boot",
    "mezzanine.conf",
    "mezzanine.core",
    "mezzanine.generic",
    "mezzanine.blog",
    "mezzanine.forms",
    "mezzanine.pages",
    "mezzanine.galleries",
    'events',
    'rest_framework',
    'storages',
    "compressor",
    # "mezzanine.twitter",
    #"mezzanine.accounts",
    #"mezzanine.mobile",
)

# List of middleware classes to use. Order is important; in the request phase,
# these middleware classes will be applied in the order given, and in the
# response phase the middleware will be applied in reverse order.
MIDDLEWARE_CLASSES = (
    "mezzanine.core.middleware.UpdateCacheMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "mezzanine.core.request.CurrentRequestMiddleware",
    "mezzanine.core.middleware.RedirectFallbackMiddleware",
    "mezzanine.core.middleware.TemplateForDeviceMiddleware",
    "mezzanine.core.middleware.TemplateForHostMiddleware",
    "mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware",
    "mezzanine.core.middleware.SitePermissionMiddleware",
    # Uncomment the following if using any of the SSL settings:
    # "mezzanine.core.middleware.SSLRedirectMiddleware",
    "mezzanine.pages.middleware.PageMiddleware",
    "mezzanine.core.middleware.FetchFromCacheMiddleware",
)

# Store these package names here as they may change in the future since
# at the moment we are using custom forks of them.
PACKAGE_NAME_FILEBROWSER = "filebrowser_safe"
PACKAGE_NAME_GRAPPELLI = "grappelli_safe"

#########################
# OPTIONAL APPLICATIONS #
#########################

# These will be added to ``INSTALLED_APPS``, only if available.
OPTIONAL_APPS = (
    "debug_toolbar",
    "django_extensions",
    "compressor",
    PACKAGE_NAME_FILEBROWSER,
    PACKAGE_NAME_GRAPPELLI,
)


try:
    HOSTNAME = socket.gethostname()
except:
    HOSTNAME = 'localhost'

print(os.path.join(PROJECT_ROOT, "golf.db"))

if config.get('local', 'host_name') in HOSTNAME:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(PROJECT_ROOT, "golf.db"),
        }
    }
    STATIC_URL = '/static/'

else:
    ############# DATABASE DEFINITIONS ################
    SCHEMA = config.get('golf_site', 'db_schema')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'OPTIONS': {
                'options': f'-c search_path={SCHEMA}'
            },
            'NAME': config.get('lambda', 'db_name'),
            'USER': config.get('lambda', 'db_user'),
            'PASSWORD': config.get('lambda', 'db_password'),
            'HOST': config.get('lambda', 'db_host'),
            'PORT': '5432',
        }
    }

############### FILE STORAGE CONFIG ###################
STATICFILES_DIRS = [os.path.join(PROJECT_ROOT, '../static/'), os.path.join(PROJECT_ROOT, 'solid/../solid/static/')]
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static_root/')
COMPRESS_ROOT = STATIC_ROOT
AWS_LOCATION = 'content'
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_S3_HOST = "s3.us-east-1.amazonaws.com"
AWS_STORAGE_BUCKET_NAME = config.get('golf_site', 'storage_bucket_name')
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
STATICFILES_LOCATION = 'static'
STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, STATICFILES_LOCATION)
ADMIN_MEDIA_PREFIX = STATIC_URL + 'grappelli/'
MEDIAFILES_LOCATION = 'media'
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
STATICFILES_STORAGE = 'custom_storages.StaticStorage'
DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'
#####################################################



####################
# DYNAMIC SETTINGS #
####################

# set_dynamic_settings() will rewrite globals based on what has been
# defined so far, in order to provide some better defaults where
# applicable. We also allow this settings module to be imported
# without Mezzanine installed, as the case may be when using the
# fabfile, where setting the dynamic settings below isn't strictly
# required.
try:
    from mezzanine.utils.conf import set_dynamic_settings
except ImportError:
    pass
else:
    set_dynamic_settings(globals())
```

**Comment by jjorissen52** [comment]
It seems that the project structure when uploaded to Zappa is a bit different from what Mezzanine assumes, so anything referring to `PROJECT_ROOT` or `PROJECT_DIRNAME` to inject the site name into a string was using `task` instead of `golf_site`. From my own settings:

```
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIRNAME = PROJECT_ROOT.split(os.sep)[-1]

. . .

# Zappa deployment was using task.urls
ROOT_URLCONF = "%s.urls" % PROJECT_DIRNAME
```

As  a consequence, `ROOT_URLCONF` was being set to `task.urls`, which it indeed could not find. The fix is simple; set `ROOT_URLCONF` and other settings based on the project name explicitly, or find another way to gather your project name.
