### ISSUE TITLE
How do you start a project from scratch?

### ISSUE THREAD

**Issue by carlhunterroach** [Miserlou/Zappa#1261]
Are there docs for using `zappa init` without an existing python project?

**Comment by niels581** [comment]
error 
i am in virtualenv 

zappa init
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "c:\users\toshiba\.virtualenvs\lambda-hello-world-wti7vn7p\lib\site-packages\zappa\cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "c:\users\toshiba\.virtualenvs\lambda-hello-world-wti7vn7p\lib\site-packages\zappa\cli.py", line 476, in handle
    self.init()
  File "c:\users\toshiba\.virtualenvs\lambda-hello-world-wti7vn7p\lib\site-packages\zappa\cli.py", line 1504, in init
    \u255a\u2550\u2550\u2550\u2550\u2550\u2550\u255d\u255a\u2550\u255d  \u255a\u2550\u255d\u255a\u2550\u255d     \u255a\u2550\u255d     \u255a\u2550\u255d  \u255a\u2550\u255d\n""", fg='green', bold=True))
  File "c:\users\toshiba\.virtualenvs\lambda-hello-world-wti7vn7p\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)
  File "c:\users\toshiba\.virtualenvs\lambda-hello-world-wti7vn7p\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "c:\users\toshiba\.virtualenvs\lambda-hello-world-wti7vn7p\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "c:\users\toshiba\.virtualenvs\lambda-hello-world-wti7vn7p\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\toshiba\.virtualenvs\lambda-hello-world-wti7vn7p\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\toshiba\.virtualenvs\lambda-hello-world-wti7vn7p\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-9: character maps to <undefined>

**Comment by jwkvam** [comment]
Maybe the cookie cutter examples from this [repo](https://github.com/narfman0/zappa-examples) would be helpful?

**Comment by mlda065** [comment]
I just heard about zappa and tried running a hello world app. `init` did not do what I expected. I expected  `zappa init` to create a template `.py` or `.app` file if one does not exist. 

# Steps to reproduce

* Create a blank directory
* Following the instructions on the readme

```
pip install zappa
zappa init
zappa deploy
```

When `init` asks for the app name, enter `myfunction.app`

```
{
    "dev": {
        "app_function": "myfunction.app",
        "aws_region": "ap-southeast-2",
        "profile_name": "default",
        "project_name": "myproject",
        "runtime": "python3.6",
        "s3_bucket": "myproject-zappa"
    }
```

# Expected behaviour

Since the directory is blank, zappa will create a blank `.py` file (or `.app` file) with all the imports, decorators and functions needed.

# Actual behaviour

* zappa only creates `zappa_settings.json`
* zappa does not create a `.py` or `.app` file
* zappa someone 'deploys' **nothing**, and claims the deployment is sucessful, even though clicking on the API endpoint will return a zappa-generated error

# Context

I'm new to zappa, and I've never used flask or django before. I still don't know whether I *need* django or flask decorators and libraries. I don't know whether I should create a script at `myfunction.app` or `myfunction.py`. (What is a `.app` file? I have no idea) 

I also still have no idea how to tell zappa which libraries I need installed in my virtual env.

The easiest way for me to figure those things and and get started is to have `init` generate a working template if the starting directory is blank.

**Comment by mlda065** [comment]
I don't understand why you wouldn't want zappa to work out of the box. It's not like it requires any effort. I've **already written a pull request**.

What would be the downside to making it easier to create a hello world app? Why arbitrarily restrict the functionality of Zappa, and reject working code that has already been written?

**Comment by scoates** [comment]
Hi. I don't consider it an arbitrary decision. We try to be careful about limiting the scope of Zappa, as every line of code adds cost (in this case, cost is time to maintain), and I think this kind of addition is out of scope.

Additionally, the [pull request](https://github.com/Miserlou/Zappa/pull/1375/files) is not usable as-is:

  * there's an empty execution branch for django
  * the flask branch has a stray `print`
  * the other notification `print` line should probably be a `click.echo` to follow with the rest of how this code works
  * [installing flask into the user's virtualenv](https://github.com/Miserlou/Zappa/pull/1375/files#diff-5e6a43a7125a90e37a105fa7924098c8R1741) is even further out of scope for Zappa
  * and there are a bunch of comments that should be discussion, not code

…so there *is* work required, even if we did want to include this, which I don't believe we do.

To me, this is no different from installing a django-related package and being surprised that it didn't run `django-admin startproject …` for you. This shouldn't be expected.

There *is*, however, some discussion around detecting that the `app_function` is incorrect, and [better handling of broken deployments](﻿https://github.com/Miserlou/Zappa/issues/1414), so failing all else, this will at least report that your deployment failed.

**Comment by Miserlou** [comment]
Reopening for more discussion.

There is a use case for this that hasn't been considered: building a purely event driven application. More than once I've had the need to have functions execute in response to AWS events, and it is weird to write the event handler before the `init`. 

I would like `init` to be able to handle this use case. However, handling this use case naturally opens the door to bootstrapping a web application as well.. :[

**Comment by jwkvam** [comment]
Could we point users to example cookie cutter projects as a solution here? It seems like zappa init is sort of providing the same functionality?
