### ISSUE TITLE
How to invoke task in another task?

### ISSUE THREAD

**Issue by mesuutt** [Miserlou/Zappa#1269]
## Context

I have a async task which take more than 5 minutes same as below:

 `zappa_settings.json`:
```json
{
    "function": "tasks.main_task",
    "expression": "rate(10 minute)"
}
```

```python
# tasks.py
def main_task(*args, *kwargs):
    for i in range(10):
       # time consuming code
       # take 1 minute to execute in each loop.
````

I tried to split this function to small parts and move time consoming part to another function.  I changed this function shown as below:

```python
# tasks.py
from zappa.async import run

def main_task(*args, *kwargs):
    for i in range(10):
       run(child_task)

def child_task(*args, *kwargs):
    print('Child task called')

```

I haven't achieved this. I am getting this error. 

```
[1511964048051] An error occurred (UnrecognizedClientException) when calling the Invoke operation: The security token included in the request is invalid: ClientError
Traceback (most recent call last):
  File "/var/task/handler.py", line 509, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
  return handler.handler(event, context)
  File "/var/task/handler.py", line 336, in handler
  return self.run_function(app_function, event, context)
  File "/var/task/handler.py", line 270, in run_function
  result = app_function(event, context) if varargs else app_function()
  File "/var/task/lambda_tasks.py", line 12, in main_task
  run(child_task)
  File "/var/task/zappa/async.py", line 353, in run
  **task_kwargs).send(task_path, args, kwargs)
  File "/var/task/zappa/async.py", line 170, in send
  self._send(message)
  File "/var/task/zappa/async.py", line 184, in _send
  Payload=payload
  File "/var/runtime/botocore/client.py", line 312, in _api_call
  return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 605, in _make_api_call
  raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException)
 when calling the Invoke operation: The security token included in the request is invalid
```
**Can I achive this? Is this possible?**

## Your Environment
```
zappa==0.45.1
boto3==1.4.8
botocore==1.8.1
```

**Comment by mcrowson** [comment]
That is doable and it looks like you're going about it the right way. Sounds like a permission issue. Does the role zappa is using have sufficient permissions?

**Comment by mesuutt** [comment]
This is auto generated zappa role policy named as `zappa-permissions`. I didn't specify any permission in `zappa_settings.json`. I also added `AWSLambdaFullAccess` permission to the role but not changed anything:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:*"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "lambda:InvokeFunction"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "xray:PutTraceSegments",
                "xray:PutTelemetryRecords"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachNetworkInterface",
                "ec2:CreateNetworkInterface",
                "ec2:DeleteNetworkInterface",
                "ec2:DescribeInstances",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DetachNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:ResetNetworkInterfaceAttribute"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "kinesis:*"
            ],
            "Resource": "arn:aws:kinesis:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "sns:*"
            ],
            "Resource": "arn:aws:sns:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "sqs:*"
            ],
            "Resource": "arn:aws:sqs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "dynamodb:*"
            ],
            "Resource": "arn:aws:dynamodb:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "route53:*"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by mesuutt** [comment]
**Problem solved**

Problem related to adding `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in `zappa_settings.json`. Lambda has another `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` but adding these keys in settings file overwrites env vars of lambda.
I renamed the env vars in the `zappa_settings.json` and solved.
