### ISSUE TITLE
async task feature: access event and context for integration with raven-python-lambda

### ISSUE THREAD

**Issue by jwkvam** [Miserlou/Zappa#1270]
I'm experimenting with this [library](https://github.com/Netflix-Skunkworks/raven-python-lambda) to get additional information into sentry. It works fine with "normal" functions since they take the event and context arguments and this library expects that.

The problem I'm having is that for async zappa tasks, they don't take the event and context arguments. This means I can't get the additional reporting this package provides from my async tasks.

## Context
I setup my async task which I first decorate to get sentry reporting goodies.
```
@task
@RavenLambdaWrapper()
def bar(event, context):
    logging.info(f'{event}, {context}')
```
Then trying to call `bar` yields:
```
decorated() missing 1 required positional argument: 'context': TypeError
Traceback (most recent call last):
File "/var/task/handler.py", line 511, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 242, in lambda_handler
return handler.handler(event, context)
File "/var/task/handler.py", line 347, in handler
result = self.run_function(app_function, event, context)
File "/var/task/handler.py", line 276, in run_function
result = app_function(event, context)
File "/var/task/zappa/async.py", line 253, in route_lambda_task
return run_message(message)
File "/var/task/zappa/async.py", line 289, in run_message
**message['kwargs']
TypeError: decorated() missing 1 required positional argument: 'context'
```

## Expected Behavior
It's a little more work for the end user to extract the payload. But I think it's easier than using the boto api.

## Actual Behavior
Zappa and this library don't work together for async tasks.

## Possible Fix
Add an additional argument to `task` such as `deserialize` which could default to `True` and maintain current behavior. If `deserialize` is `False` then `event` and `context` would get passed on to the user's function.

For now I think I'm going to workaround this by using the boto api to invoke the function.

## Steps to Reproduce
Here's a self contained example.
```
from raven_python_lambda import RavenLambdaWrapper
from zappa.async import task

@task
@RavenLambdaWrapper()
def bar(event, context):
    logging.info(f'bar called {arg}')
    raise Exception(f'bar {event} {context}')

@RavenLambdaWrapper()
def foo(event, context):
    bar(5)
```

## Your Environment
* Zappa version used: 0.44.3

**Comment by zaraken** [comment]
I worked around it by updating async.py with the following
`
@@ -214,7 +214,7 @@ def route_lambda_task(event, context):
     imports the function, calls the function with args
     """
     message = event
-    return run_message(message)
+    return run_message(event, context, message)
 
 
 def route_sns_task(event, context):
@@ -226,16 +226,24 @@ def route_sns_task(event, context):
     message = json.loads(
             record['Sns']['Message']
         )
-    return run_message(message)
+    return run_message(event, context, message)
 
 
-def run_message(message):
+def run_message(event, context, message):
     """
     Runs a function defined by a message object with keys:
     'task_path', 'args', and 'kwargs' used by lambda routing
     and a 'command' in handler.py
     """
     func = import_and_get_task(message['task_path'])
+
+    from inspect import signature
+    params = list(signature(func).parameters)
+    if "event" in params:
+        message['kwargs']['event'] = event
+    if "context" in params:
+        message['kwargs']['context'] = context
+
`
Then using it with 
`def recursive_lambda(event=None, context=None, ttl=0):
    from zappa.async import run
    print(ttl)
    if ttl:
        run(recursive_lambda, kwargs={"ttl": ttl-1})`
I'm using it to call a lambda recursively when about to timetout to continue working on a queue until either the time-to-live parameter is zero or a work-queue is empty.
I've not published this because I thought that with this change I I've broken the local invokation, obviously because there was no event or context available in a non-AWS environment, but it seems that it might've been broken from the beginning. The documentation says that when you run code that uses @task or async.run() it will just make a regular function call but instead it complains about a function being None and breaks. I haven't made the time to fix that one yet.
Needless to say, I am using a custom copy of Zappa, that lags behind the official release, so the lines in the diff above might be a bit off.

**Comment by zaraken** [comment]
I'm not sure if it would work with the task decorator, but by conditionally including `event` and `context` based on function signature it also remains compatible with existing code and there's no need for the additional `deserialize` flag that you are introducing.

**Comment by jwkvam** [comment]
Nice approach, I hadn't thought of that.

One concern I have with this is it implicitly places special meaning on `event` and `context` names. It may lead to subtle bugs for unsuspecting users if they try to use `event` or `context` as an argument without wanting the lambda definitions of `event` or `context`.

I designed my PR to also be compatible with existing code, which is why `deserialize` defaults to `True`. Maybe I should have chosen an option which would be `False` by default like just using `serialize`.

**Comment by zaraken** [comment]
Well, with the exceptions that you might get some unexpected behavior, in case you're already using `event` and/or `context` for other purposes, as you mentioned ... yes, i do think it is compatible. But so is yours, isn't that right. I haven't given it that much thought, really. And that is why I haven't published the changes. The reason I went this way is because, in order to have robust application, you'de need to check the remaining time and try to shut down gracefully otheriwse you'll start running into problems such as performing tasks twice, failing to close database connections and thus blocking them, etc.

**Comment by zaraken** [comment]
Frankly, I am a bit surprised that beside you no one has requested that feature.

**Comment by ranihorev** [comment]
I just decided to pass on Sentry for the mean time, until a stable solution is available :(

**Comment by staticfox** [comment]
Sorry for chiming in, but we're currently facing this issue as well. We're heavily using Zappa's async system and this has been a huge blocker for quiet some time. It's not specific to Sentry (we made our own workaround), but having the context available to tasks would open many doors for third party libraries and applications themselves that require insight to lambda contexts.

Currently, there is no way to determine the remaining time of a Lambda function executed through Zappa's async system without doing some guess work and config parsing. We're unable to implement a proper watchdog, as it would currently involve manually reading Zappa's config, parsing the timeout, determining when the function started, and hoping everything aligns up. We also need to know some additional information such as the request id to do some internal book keeping between task executions. This would also allow libraries such as Sentry to have drop-in support, rather than having to re-create modules to work around not having contexts available on lambda.

Is there anyway I could assist in getting this issue resolved? Our only other option is to fork the library, as this has become a critical issue as of late.

**Comment by kolanos** [comment]
I'm not sure if this would work for tasks, but for regular requests the thread local way is how you would do it:

```python
from flask import request

context = request.environ.get('lambda.context', None)
```

Does this not work in a task context?

**Comment by staticfox** [comment]
No, because there is no request.

```
RuntimeError
Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

The async system is just an ad-hoc way to run arbitrary lamba functions, so things like request contexts don't actually make it to the other end. Coincidentally, this circles back around to the original issue where there is no task context available, since tasks are routed through Zappa internally, which filters out the lambda context before it calls the requested function.

**Comment by synap5e** [comment]
If anyone is running in `Working outside of request context.` when running asynchronous tasks, here is a monkey patch that works for me to fix it. 
Specifically my use case is that I need access to `lambda.context` in some of my code, which is not otherwise possible in async tasks. This patch allows access to the context/event within async tasks in the standard way (i.e. through `request.environ['lambda.context']`).

```python
_original_route_lambda_task = asynchronous.route_lambda_task
def route_lambda_task(event, context):
    environ = {
        'lambda.context': context,
        'lambda.event': event,
        'HTTPS': 'on',
        'wsgi.url_scheme': 'https',
        'SERVER_NAME': '127.0.0.1',
        'SERVER_PORT': '443',
        'REQUEST_METHOD': 'GET',
    }
    with app.request_context(environ):
        _original_route_lambda_task(event, context)
asynchronous.route_lambda_task = route_lambda_task
```
