### ISSUE TITLE
Pillow (4.3.0) is not packaged, instead zappa packages PIL for Windows 64-bit

### ISSUE THREAD

**Issue by ceefour** [Miserlou/Zappa#1286]
This is almost related to #841 , but instead no Pillow is packaged at all.

## Context

Python 3.6 on Windows (Anaconda)

## Expected Behavior

Pillow 4.3.0 is packaged. It seems that lambda-packages doesn't have pillow 4.3.0 yet (https://github.com/Miserlou/lambda-packages/tree/master/lambda_packages/Pillow), however there is a [manylinux wheel](https://pypi.python.org/pypi/Pillow/4.3.0): Pillow-4.3.0-cp36-cp36m-manylinux1_x86_64.whl which should be usable, right ?

## Actual Behavior

Pillow 4.3.0 is not packaged, and instead zappa uses PIL for Windows 64bit:

![image](https://user-images.githubusercontent.com/24123/33804149-77f8130c-ddd1-11e7-918c-e409d1a77171.png)

## Possible Fix

Patch the zip and use the manylinux wheel manually?

## Steps to Reproduce

On Windows 64-bit:

```
pip install Pillow
```

## Your Environment

* Zappa version used: zappa==0.45.1
* Operating System and Python version: Windows 10 64-bit, Python 3.6
* The output of `pip freeze`: 

```
argcomplete==1.9.2
Babel==2.5.1
base58==0.2.4
boto==2.48.0
boto3==1.4.8
botocore==1.8.11
cachetools==2.0.1
certifi==2017.11.5
cfn-flip==0.2.5
chardet==3.0.4
click==6.7
decorator==4.1.2
Django==2.0
django-appconf==1.0.2
django-imagekit==4.0.2
django-ipware==1.1.6
django-nine==0.1.13
django-phonenumber-field==1.3.0
django-qartez==0.7.1
django-s3-storage==0.12.1
docutils==0.14
durationpy==0.5
future==0.16.0
google-auth==1.2.1
hjson==3.0.1
httplib2==0.10.3
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
oauth2client==4.1.2
olefile==0.44
phonenumberslite==8.8.5
pilkit==2.0
Pillow==4.3.0
placebo==0.8.1
psycopg2==2.7.3.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2017.3
PyYAML==3.12
ratelim==0.1.6
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.12
six==1.11.0
toml==0.9.3
tqdm==4.19.1
troposphere==2.1.2
Unidecode==0.4.21
uritemplate==3.0.0
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1
```

* Your `zappa_settings.py`: (Note: this should be `zappa_settings.json`, perhaps you want to change the template?)

```
{
    "prd": {
        "aws_region": "us-east-1",
        "django_settings": "samaraweb.settings",
        "profile_name": "default",
        "project_name": "samaraweb",
        "runtime": "python3.6",
        "s3_bucket": "samaraedu-code",
        "domain": "keluargasamara.com",
        "certificate_arn": "arn:aws:acm:us-east-1:703881650703:certificate/a5683018-90ee-4e47-b59b-bc0d147ed174",
        "route53_enabled": false,
        "exclude": ["snapshot"]
    }
}
```

**Comment by ceefour** [comment]
I tried downgrading to Pillow 3.4.2, but Pillow 3.4.2 seems broken on Windows:

```
...
  writing manifest file 'Pillow.egg-info\SOURCES.txt'
  copying PIL\OleFileIO-README.md -> build\lib.win-amd64-3.6\PIL
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ceefour\AppData\Local\Temp\pip-build-d00s30_s\Pillow\setup.py", line 753, in <module>
      zip_safe=not debug_build(), )
    File "c:\programdata\anaconda3\Lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\programdata\anaconda3\Lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\programdata\anaconda3\Lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\ceefour\git\samara\venv\lib\site-packages\wheel\bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "c:\programdata\anaconda3\Lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\programdata\anaconda3\Lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\programdata\anaconda3\Lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\programdata\anaconda3\Lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\programdata\anaconda3\Lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\programdata\anaconda3\Lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\ceefour\AppData\Local\Temp\pip-build-d00s30_s\Pillow\setup.py", line 521, in build_extensions
      ' using --disable-%s, aborting' % (f, f))
  ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

  ----------------------------------------
  Failed building wheel for Pillow
```

**Comment by ceefour** [comment]
I tried downgrading to Pillow 4.2.0 but still same issue.

BTW other packages are working, for example `psycopg2-2.7.3.2.dist-info/WHEEL` says:

```
Wheel-Version: 1.0
Generator: bdist_wheel (0.29.0)
Root-Is-Purelib: false
Tag: cp36-cp36m-manylinux1_x86_64
```

**Comment by ceefour** [comment]
I think this is the issue (in zappa.py, 0.45.1):

```python
# Then try to use manylinux packages from PyPi..
# Related: https://github.com/Miserlou/Zappa/issues/398
try:
    for installed_package_name in installed_packages_name_set:
        if installed_package_name not in lambda_packages:
            wheel_url = self.get_manylinux_wheel(installed_package_name)
            if wheel_url:
                resp = requests.get(wheel_url, timeout=2, stream=True)
                resp.raw.decode_content = True
                zipresp = resp.raw
                with zipfile.ZipFile(BytesIO(zipresp.read())) as zfile:
                    zfile.extractall(temp_project_path)
        progress.update()
except Exception:
    pass # XXX - What should we do here?
progress.close()
```

because it always skips if package (`Pillow`) is in lambda_packages.

I thought #843 would have fixed it but seems like it hasn't. :(

**Comment by ceefour** [comment]
It seems that `zappa.py` is no longer used and `core.py` is the current logic.

I tried adding this:

```python
            print("Downloading and installing dependencies..")
            installed_packages = self.get_installed_packages(site_packages, site_packages_64)
            print(' '.join([x[0] for x in installed_packages.items()]))
```

but I got:

```
(venv) C:\Users\ceefour\git\samara\samaraweb>zappa package prd
Calling package for stage prd..
Downloading and installing dependencies..
zappa wheel werkzeug urllib3 uritemplate unidecode troposphere tqdm setuptools s3transfer rsa requests ratelim pytz pyasn1 psycopg2 placebo pip pilkit olefile oauth2client kappa jmespath idna httplib2 hjson future durationpy docutils django click chardet certifi cachetools botocore boto3 boto babel argcomplete
```

which means that Pillow isn't even in `get_installed_packages()` ! why??

**Comment by ceefour** [comment]
Workaround: This fixed it for me: in `core.py` > `get_installed_packages()`

```
        installed_packages = {package.project_name.lower(): package.version for package in
                              pip.get_installed_distributions()
                              if package.project_name.lower() in package_to_keep
                              or package.location.lower() in [site_packages.lower(), site_packages_64.lower()]}
```

I'm not sure if this is desirable for non-Windows systems, so probably it can be generalized to do it conditionally based on OS.

**Comment by mirhec** [comment]
This is a big problem for me as well. It seems to work on Mac OS, but not on Windows. I'm using the latest zappa version 0.45.1 and trying to include pillow 5.0.0. Is there any solution out there?

**Comment by stan-sack** [comment]
this is also a massive issue for me. Its bundling the mac and linux builds of openCV and adding over 100mb to my package size which is now over the 500mb limit
