### ISSUE TITLE
Running zappa with no parameters causes exception

### ISSUE THREAD

**Issue by OverlordQ** [Miserlou/Zappa#1350]
Running `zappa` command with no other arguments causes exception

## Context
Running inside venv with zappa installed

## Expected Behavior
Help message appears

## Actual Behavior
```
$ zappa
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/ovrlrdq/.pyenv/versions/3.6.4/envs/venv364zappa/lib/python3.6/site-packages/zappa/cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "/home/ovrlrdq/.pyenv/versions/3.6.4/envs/venv364zappa/lib/python3.6/site-packages/zappa/cli.py", line 505, in handle
    self.dispatch_command(self.command, stage)
  File "/home/ovrlrdq/.pyenv/versions/3.6.4/envs/venv364zappa/lib/python3.6/site-packages/zappa/cli.py", line 520, in dispatch_command
    if not self.vargs['json']:
KeyError: 'json'

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
```

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: Debian, Python 3.6.4
* The output of `pip freeze`: https://hastebin.com/igepoveked.makefile

**Comment by dfurtado** [comment]
Added a PR for this https://github.com/Miserlou/Zappa/pull/1368

**Comment by scoates** [comment]
Python 2 vs 3 problem (doesn't happen in 2.7). @dfurtado's PR fixes it.

**Comment by Miserlou** [comment]
Fixed via PR.
