### ISSUE TITLE
zappa init not working with python 3.6.4 - ModuleNotFoundError: No module named 'lib2to3'

### ISSUE THREAD

**Issue by pmd500** [Miserlou/Zappa#1379]
I'm using python 3.6.4 and virtualenv & ubuntu 17. When I run zappa init, i get the following message:

Traceback (most recent call last):
  File "/home/phild/.virtualenvs/fm/bin/zappa", line 11, in <module>
    load_entry_point('zappa==0.45.1', 'console_scripts', 'zappa')()
  File "/home/phild/.virtualenvs/fm/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/phild/.virtualenvs/fm/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/phild/.virtualenvs/fm/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/home/phild/.virtualenvs/fm/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/phild/.virtualenvs/fm/lib/python3.6/site-packages/zappa-0.45.1-py3.6.egg/zappa/cli.py", line 13, in <module>
    from past.builtins import basestring
  File "/home/phild/.virtualenvs/fm/lib/python3.6/site-packages/past/__init__.py", line 88, in <module>
    from past.translation import install_hooks as autotranslate
  File "/home/phild/.virtualenvs/fm/lib/python3.6/site-packages/past/translation/__init__.py", line 41, in <module>
    from lib2to3.pgen2.parse import ParseError
ModuleNotFoundError: No module named 'lib2to3'

My pip freeze is as follows:
argcomplete==1.9.2
base58==0.2.4
boto3==1.5.22
botocore==1.8.36
certifi==2018.1.18
cfn-flip==1.0.0
chardet==3.0.4
click==6.7
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
placebo==0.8.1
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.12
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.2.0
Unidecode==1.0.22
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1

**Comment by Miserlou** [comment]
Did you try installing 2to3?
