### ISSUE TITLE
Zappa crashes during zappa init

### ISSUE THREAD

**Issue by cameronk** [Miserlou/Zappa#1388]
## Context
Zappa crashes when running `zappa init`.

```
==============

Traceback (most recent call last):
  File "c:\users\camer\desktop\development\ryze\content-engine\api\env\lib\site-packages\zappa\cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "c:\users\camer\desktop\development\ryze\content-engine\api\env\lib\site-packages\zappa\cli.py", line 476, in handle
    self.init()
  File "c:\users\camer\desktop\development\ryze\content-engine\api\env\lib\site-packages\zappa\cli.py", line 1604, in init
    matches = detect_flask_apps()
  File "c:\users\camer\desktop\development\ryze\content-engine\api\env\lib\site-packages\zappa\utilities.py", line 143, in detect_flask_apps
    lines = f.readlines()
  File "c:\users\camer\desktop\development\ryze\content-engine\api\env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 308: character maps to <undefined>

==============
```

## Expected Behavior
zappa should initialize

## Actual Behavior
it crashes

## Steps to Reproduce
1. create a virtual environment, install zappa
2. run `zappa init`
3. it breaks

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: Windows 10, Python 3.6.3
* The output of `pip freeze`: 
```
beautifulsoup4==4.6.0
certifi==2018.1.18
chardet==3.0.4
click==6.7
cssselect==1.0.3
feedfinder2==0.0.4
feedparser==5.2.1
Flask==0.12.2
Flask-MySQLdb==0.2.0
idna==2.6
itsdangerous==0.24
jieba3k==0.35.1
Jinja2==2.10
lxml==4.1.1
MarkupSafe==1.0
mysqlclient==1.3.12
newspaper3k==0.2.6
nltk==3.2.5
Pillow==5.0.0
python-dateutil==2.6.1
PyYAML==3.12
requests==2.18.4
requests-file==1.4.3
scikit-learn==0.19.1
six==1.11.0
tldextract==2.2.0
urllib3==1.22
Werkzeug==0.14.1
```
* Link to your project (optional):
* Your `zappa_settings.py`:  I wish I could get this far

**Comment by rgov** [comment]
Python 3 is expecting that a `.py` file is encoded in Windows-1252, probably the default for Windows 10, but it isn't.

Potential fix: [this line](https://github.com/Miserlou/Zappa/blob/master/zappa/utilities.py#L146) should open the file in binary mode (`rb`)

**Comment by duaneking** [comment]
This is still a thing; currently blocked on my windows devbox from doing ANY zappa dev due to this.
