### ISSUE TITLE
Zappa crashes when running "zappa"

### ISSUE THREAD

**Issue by cameronk** [Miserlou/Zappa#1395]
## Context
After two days and two different OS', I finally got Zappa working. For about 5 minutes, until I had to reset my virtual env (Zappa was packaging my entire virtual env, including /lib/, which resulted in ~100mb deploy zips.)

When I reinstalled, I now get this:

```
camer@DESKTOP-VRG88TF:/mnt/c/Users/camer/Desktop/Development/ryze/content-engine/api$ zappa
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/camer/.local/share/virtualenvs/api-GJXpcMFr/lib/python3.6/site-packages/zappa/cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "/home/camer/.local/share/virtualenvs/api-GJXpcMFr/lib/python3.6/site-packages/zappa/cli.py", line 505, in handle
    self.dispatch_command(self.command, stage)
  File "/home/camer/.local/share/virtualenvs/api-GJXpcMFr/lib/python3.6/site-packages/zappa/cli.py", line 520, in dispatch_command
    if not self.vargs['json']:
KeyError: 'json'

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
```

## Expected Behavior
Zappa should output the usual list of help commands

## Actual Behavior
Zappa breaks

## Steps to Reproduce

1. Create a virtual env with `pipenv` on python 3.6
2. Run `zappa`
3. It breaks

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: Python 3.6.3, Ubuntu 16.04.3
* Your `zappa_settings.py`: 
```
{
    "dev": {
        "app_function": "app.app",
        "aws_region": null,
        "profile_name": "zappa",
        "project_name": "api",
        "runtime": "python3.6",
        "s3_bucket": "zappa-i38d9iob8"
    }
}
```

**Comment by kjenney** [comment]
The same thing is happening to me on OSX with 0.45.1 and Python 3.6.3. I suspect it may be a library issue or something introduced in 3.6.3. Here's my zappa.settings.py:

```
{
    "dev": {
        "aws_region": "us-east-2",
        "django_settings": "mysite.mysite.settings",
        "profile_name": "default",
        "project_name": "mysite",
        "runtime": "python3.6",
        "s3_bucket": "zappa-a8nviyobq"
    }
}
```
