### ISSUE TITLE
Deployed flask endpoint not working:    run_wsgi_app\\n', \"TypeError: 'NoneType' object is not callable\\n\

### ISSUE THREAD

**Issue by ClouddH** [Miserlou/Zappa#1396]
## Context
I am trying to deploy my deep learning model to lambda. The entire deployment package is over 1 GB. I am using slim-handler.   

The app function file looks like this:

```
import logging
from flask import Flask
from flask import request
from flask import json
from model import TacoModel
from utils import image
from keras.preprocessing.image import img_to_array
import numpy as np

app = Flask(__name__)
logging.basicConfig()
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
taco_model = TacoModel()

@app.route('/', methods=['GET'])
def index():
    path = "data/"
    img = image.load_img(path+"test/unknown/hotdog679.JPEG",target_size=(224, 224))
    img = np.array([img_to_array(img)])
    res = taco_model.predict(img)
    return json.dumps(res)



if __name__ == '__main__':
    app.run()
 

```

Everything runs fine locally. When I curl my local server, I am able to get back the expected response. 

The zappa deployment was successful and without error.  But get request produces

```
{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 452, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/private/var/folders/kl/35lz1q3x2gs0y0r_1njxfd0m0000gn/T/pip-build-R7GWCg/Werkzeug/werkzeug/wrappers.py\", line 903, in from_app\\n', '  File \"/private/var/folders/kl/35lz1q3x2gs0y0r_1njxfd0m0000gn/T/pip-build-R7GWCg/Werkzeug/werkzeug/wrappers.py\", line 57, in _run_wsgi_app\\n', '  File \"/private/var/folders/kl/35lz1q3x2gs0y0r_1njxfd0m0000gn/T/pip-build-R7GWCg/Werkzeug/werkzeug/test.py\", line 884, in run_wsgi_app\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}
``` 

## Expected Behavior

Endpoint should work and return a dummy prediction on get request

## Actual Behavior

Get request failed. Produce the above error

## Possible Fix

I have tried clean up my virtualenv  & recreated virtualenv and re-deploy. Error still persists

zappa tail reveals this error

```
[1518497133157] No module named my_app: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 509, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 237, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 129, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
  __import__(name)
ImportError: No module named my_app
```
I tried exporting my lambda zip package. Upon inspection , my flask app function file is missing in the deployment package.  I am new to Zappa, but this looks wrong to me.  So I manually added the app function file and re-zip & upload.  But the get request still broke and zappa tail returns some different error.

Is something wrong during the packaging step ?

## Steps to Reproduce
live link
https://knbxmrhkt0.execute-api.us-west-2.amazonaws.com/dev

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version:  MacOS python 2.7
* The output of `pip freeze`:
```
absl-py==0.1.10
appnope==0.1.0
argcomplete==1.9.2
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0.post1
base58==0.2.4
bcolz==1.1.2
bleach==2.1.2
boto3==1.5.27
botocore==1.8.41
certifi==2018.1.18
cfn-flip==1.0.0
chardet==3.0.4
click==6.7
configparser==3.5.0
cycler==0.10.0
decorator==4.2.1
docutils==0.14
durationpy==0.5
entrypoints==0.2.3
enum34==1.1.6
Flask==0.12.2
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.1.1
h5py==2.7.1
hjson==3.0.1
html5lib==0.9999999
idna==2.6
ipykernel==4.8.1
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.1.1
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
kappa==0.6.0
Keras==1.2.2
lambda-packages==0.19.0
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.1.2
mistune==0.8.3
mock==2.0.0
mpmath==1.0.0
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.4.0
numpy==1.14.0
pandas==0.22.0
pandocfilters==1.4.2
pathlib2==2.3.0
pbr==3.1.1
pexpect==4.4.0
pickleshare==0.7.4
Pillow==5.0.0
placebo==0.8.1
prompt-toolkit==1.0.15
protobuf==3.5.1
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2018.3
PyYAML==3.12
pyzmq==17.0.0
qtconsole==4.3.1
requests==2.18.4
s3transfer==0.1.12
scandir==1.7
scikit-learn==0.19.1
scipy==1.0.0
Send2Trash==1.4.2
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
subprocess32==3.2.7
sympy==1.1.1
tensorflow==1.5.0
tensorflow-tensorboard==1.5.1
terminado==0.8.1
testpath==0.3.1
Theano==1.0.1
toml==0.9.4
tornado==4.5.3
tqdm==4.19.1
traitlets==4.3.2
troposphere==2.2.0
Unidecode==1.0.22
urllib3==1.22
wcwidth==0.1.7
Werkzeug==0.12
widgetsnbextension==3.1.3
wsgi-request-logger==0.4.6
zappa==0.45.1
```

* Link to your project (optional):
* Your `zappa_settings.py`: 
```
{
    "dev": {
        "app_function": "my_app.app",
        "aws_region": "us-west-2",
        "profile_name": "default",
        "project_name": "freshstart3",
        "runtime": "python2.7",
        "s3_bucket": "[redacted]",
        "slim_handler": true
    }
}
```

**Comment by melvinev** [comment]
Try changing:

“app_function": "my_app.app"

To 

“app_function": "app.app"

In the Zappa json settings.

**Comment by ClouddH** [comment]
Just Tried. I only changed app_function's value tp app.app but my_app.py's name remain the same. The same error is returned on HTTP get..
However, zappa tail is now showing a different error

```
.5.dist-info': OSError
Traceback (most recent call last):
  File "/var/task/handler.py", line 509, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 237, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 102, in __init__
  self.load_remote_project_archive(project_archive_path)
  File "/var/task/handler.py", line 166, in load_remote_project_archive
  t.extractall(project_folder)
  File "/usr/lib64/python2.7/tarfile.py", line 2079, in extractall
  self.extract(tarinfo, path)
  File "/usr/lib64/python2.7/tarfile.py", line 2116, in extract
  self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib64/python2.7/tarfile.py", line 2184, in _extract_member
  os.makedirs(upperdirs)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
  mkdir(name, mode)
OSError: [Errno 28] No space left on device: '/tmp/freshstart3/backports.functools_lru_cache-1.5.dist-info'


```

**Comment by tlbjr** [comment]
That requirements.txt is large and some of those big libraries are likely causing your to run out of space when deploying to AWS lambda. There is [a 512 MB limit in /tmp](https://docs.aws.amazon.com/lambda/latest/dg/limits.html). Zappa bundles up the entire application directory when you deploy the application so using ```du -h``` or the Mac equivalent will tell you exactly what you are up against while trying to get the size under control. Remove any large log or data files that aren't required for deploying to lambda.

A suggestion:
Remove your virtual environment directory from the application directory.
Create a new virtual directory a directory up. This will be your new "local" virtual env.
Create a new virtual directory in your application directory. This will be your new "zappa" virtual env.
Have and use a regular requirements.txt for when running locally / where ever.
Have and use a zappa_requirements.txt when deploying to zappa.

Here's my zappa_requirements.txt and regular requirements.txt (with lots more functionality available than what I use on lambda) for reference:
zappa_requirements.txt
```
arrow
aws-xray-sdk
boto3
botocore
flask
flask-restful
google-api-python-client
itsdangerous
jinja2
mandrill
marshmallow
marshmallow-sqlalchemy
oauth2client
passlib
pycrypto
pygsheets
pymysql
python-dateutil
pytz
PyYAML
requests
simplejson
slackclient
sqlalchemy
sqlalchemy-utils
tenacity
urllib3
zappa
```

requirements.txt
```
aniso8601==1.2.0
arrow==0.10.0
astroid==1.4.8
aws-xray-sdk==0.95
blinker==1.4
boto3==1.4.4
botocore==1.5.25
click==6.6
decorator==4.0.10
docopt==0.4.0
docutils==0.13.1
Flask==0.11.1
Flask-Mail==0.9.1
Flask-RESTful==0.3.5
google-api-python-client==1.5.5
hashids==1.2.0
httplib2==0.9.2
ipdb==0.10.1
ipython==5.1.0
ipython-genutils==0.1.0
isort==4.2.5
itsdangerous==0.24
Jinja2==2.8
jmespath==0.9.2
lazy-object-proxy==1.2.2
mandrill==1.0.57
MarkupSafe==0.23
marshmallow==2.10.5
marshmallow-sqlalchemy==0.12.1
mccabe==0.5.2
oauth2client==4.0.0
passlib==1.7.1
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.9
psycopg2==2.6.2
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycodestyle==2.2.0
pycrypto==2.6.1
pyflakes==1.3.0
Pygments==2.1.3
pygsheets==1.0.0
pylint==1.6.4
PyMySQL==0.7.9
pytest==3.0.5
python-dateutil==2.6.0
pytz==2016.7
PyYAML==3.12
requests==2.13.0
rsa==3.4.2
s3transfer==0.1.10
simplegeneric==0.8.1
simplejson==3.10.0
six==1.10.0
slackclient==1.1.0
SQLAlchemy==1.1.4
SQLAlchemy-Utils==0.32.14
tenacity==4.8.0
traitlets==4.3.1
uritemplate==3.0.0
urllib3==1.19
wcwidth==0.1.7
Werkzeug==0.11.11
wrapt==1.10.8
```

**Comment by neelz040** [comment]
I am running to a similar issue. It appears to be keras that causes the problem, any idea why?
