### ISSUE TITLE
Package with c-extension broken when deploying with zappa

### ISSUE THREAD

**Issue by erikcw** [Miserlou/Zappa#1457]
## Context

I'm attempting to deploy an app to zappa that has a dependency on [python-snappy](https://github.com/andrix/python-snappy).  python-snappy contains a c-extension which I've been compiling from the recommended [Docker Image](https://github.com/danielwhatmuff/zappa/tree/feature/python3.6).

The app is running under Python 3.6, so I'm using the `feature/python3.6` branch of the Dockerfile.

## Expected Behavior

Script should be able to `import snappy`.

## Actual Behavior

```py
import snappy

No module named '_snappy_cffi': ModuleNotFoundError
Traceback (most recent call last):
File "/var/task/handler.py", line 509, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 240, in lambda_handler
return handler.handler(event, context)
File "/var/task/handler.py", line 386, in handler
app_function = self.import_module_and_get_function(whole_function)
File "/var/task/handler.py", line 231, in import_module_and_get_function
app_module = importlib.import_module(module)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 978, in _gcd_import
File "<frozen importlib._bootstrap>", line 961, in _find_and_load
File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
File "/tmp/data-to-parq/app.py", line 25, in <module>
from parquet import write_to_parquet
File "/tmp/data-to-parq/parquet.py", line 2, in <module>
import snappy # Just importing to test that it is available in zappa.
File "/tmp/data-to-parq/snappy/__init__.py", line 1, in <module>
from .snappy import (
File "/tmp/data-to-parq/snappy/snappy.py", line 50, in <module>
from .snappy_cffi import UncompressError, compress, decompress, \
File "/tmp/data-to-parq/snappy/snappy_cffi.py", line 1, in <module>
from _snappy_cffi import ffi, lib
ModuleNotFoundError: No module named '_snappy_cffi'
```

Note, that `snappy` tries two locations for the import (I think one is Python, the other is for PyPy)...

https://github.com/andrix/python-snappy/blob/master/snappy/snappy.py#L47

```python
try:
    from ._snappy import UncompressError, compress, decompress, \
                         isValidCompressed, uncompress, _crc32c
except ImportError:
    from .snappy_cffi import UncompressError, compress, decompress, \
isValidCompressed, uncompress, _crc32c
```

Either way, both of those import attempts are failing to find `_snappy`/`snappy_cffi`.

When I examine the contents of my packaged zip file, I see snappy and it's compiled `snappy/_snappy.cpython-36m-x86_64-linux-gnu.so` is present.

```
# ... other dependencies.
snappy/snappy_formats.py
snappy/snappy_cffi_builder.py
snappy/__init__.py
snappy/snappy.py
snappy/hadoop_snappy.py
snappy/snappy_cffi.py
snappy/__main__.py
snappy/_snappy.cpython-36m-x86_64-linux-gnu.so
snappy/__pycache__/snappy_formats.cpython-36.pyc
snappy/__pycache__/__init__.cpython-36.pyc
snappy/__pycache__/snappy_cffi.cpython-36.pyc
snappy/__pycache__/snappy_cffi_builder.cpython-36.pyc
snappy/__pycache__/snappy.cpython-36.pyc
snappy/__pycache__/hadoop_snappy.cpython-36.pyc
snappy/__pycache__/__main__.cpython-36.pyc
snappy/__pycache__/__init__.py
# ... more dependencies...
```

Note that I'm able to `import snappy` without any problems while I'm in the docker container.  This only seems to happen once the app is deployed to Lambda.

## Steps to Reproduce

1. Start shell for `danielwhatmuff`s Python3.6 Docker Image: `docker run -it -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_DEFAULT_REGION=us-east-1 -v $(pwd):/var/task -v ~/.aws:/root/.aws --rm erikcw/zappa bash`
2. Install `snappy-devel` clib using `yum --enablerepo=epel install -y snappy-devel`.
3. `python3 -m venv docker_env && source docker_env/bin/activate && pip install python-snappy && zappa update dev && rm -rf docker_env`

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: Mac OS with Python 3.6 (building under docker as mentioned above).
* The output of `pip freeze`:
```
zappa==0.45.1
numpy==1.14.2
pandas==0.22.0
fastparquet==0.1.4
(docker_env) zappa> pip freeze
argcomplete==1.9.2
base58==0.2.4
boto3==1.6.15
botocore==1.9.15
certifi==2018.1.18
cffi==1.11.5
cfn-flip==1.0.3
chardet==3.0.4
click==6.7
Cython==0.28.1
docutils==0.14
durationpy==0.5
dynamodb-json==1.2
fastparquet==0.1.4
future==0.16.0
hjson==3.0.1
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
llvmlite==0.22.0
numba==0.37.0
numpy==1.14.2
pandas==0.22.0
placebo==0.8.1
ply==3.11
pycparser==2.18
python-dateutil==2.6.1
python-slugify==1.2.4
python-snappy==0.5.2
pytz==2018.3
PyYAML==3.12
requests==2.18.4
s3fs==0.1.4
s3transfer==0.1.13
simplejson==3.13.2
six==1.11.0
thrift==0.11.0
thriftpy==0.3.9
toml==0.9.4
tqdm==4.19.1
troposphere==2.2.1
Unidecode==1.0.22
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1
```
* Your `zappa_settings.py`: 

```js
{
    "dev": {
        "lambda_description": "Convert logs files to Parquet.",
        "memory_size": 1536,
        "timeout_seconds": 300,
        "runtime": "python3.6",
        "slim_handler": true,
        "app_function": "app.run",
        "apigateway_enabled": false,
        "aws_region": "us-east-1",
        "aws_kms_key_arn": "******************",
        "profile_name": "default",
        "project_name": "data-to-parq",
        "s3_bucket": "zappa-*******",
        "keep_warm": false,
        "events": [
           // Some S3 events that listen for new objects and run a function on them.
        ]
    }
}
```

**Comment by worgarside** [comment]
Did you ever manage to sort this @erikcw?
