### ISSUE TITLE
Fails if message is numeric

### ISSUE THREAD

**Issue by qsweber** [Miserlou/Zappa#1466]
https://github.com/Miserlou/Zappa/blob/d1170b49c03d3ddccb6aeec9ead192d6a49b57ac/zappa/handler.py#L298

I sent a message to SNS which consisted simply of the number 1:

```
sns = boto3.resource('sns')
topic = sns.Topic('arn:aws:sns:us-west-2:foo:bar')
topic.publish(Message='1')
```

This caused the following failure:

```
[1522557727786] 'int' object has no attribute 'get': AttributeError
Traceback (most recent call last):
  File "/var/task/handler.py", line 509, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
  return handler.handler(event, context)
  File "/var/task/handler.py", line 384, in handler
  whole_function = self.get_function_for_aws_event(records[0])
  File "/var/task/handler.py", line 293, in get_function_for_aws_event
  if message.get('command'):
AttributeError: 'int' object has no attribute 'get'
```

**Comment by qsweber** [comment]
Addressing this is not urgent, since it's very easy to avoid this by making my SNS messages contain non-integers.
