### ISSUE TITLE
An error occurred (404) when calling the HeadBucket operation: Not Found

### ISSUE THREAD

**Issue by Benjamin-Lee** [Miserlou/Zappa#1472]
## Context

Python 3.6
## Expected Behavior

Zappa should deploy my app
## Actual Behavior

```
(env) Benjamins-MacBook-Pro:mechwolf.org BenjaminLee$ zappa deploy
Calling deploy for stage dev..
Downloading and installing dependencies..
 - yarl==1.1.1: Using locally cached manylinux wheel
 - pymongo==3.6.0: Using locally cached manylinux wheel
 - pandas==0.22.0: Using locally cached manylinux wheel
 - numpy==1.13.3: Using locally cached manylinux wheel
 - multidict==4.1.0: Using locally cached manylinux wheel
 - matplotlib==2.1.1: Using locally cached manylinux wheel
 - lazy-object-proxy==1.3.1: Using locally cached manylinux wheel
 - greenlet==0.4.13: Using locally cached manylinux wheel
 - gevent==1.2.2: Using locally cached manylinux wheel
 - cython==0.27.3: Using locally cached manylinux wheel
 - aiohttp==3.0.3: Using locally cached manylinux wheel
 - sqlite==python36: Using precompiled lambda package
Packaging project as zip.


Warning: Application zip package is likely to be too large for AWS Lambda. Try setting "slim_handler" to true in your Zappa settings file.


Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/zappa/core.py", line 884, in upload_to_s3
    self.s3_client.head_bucket(Bucket=bucket_name)
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadBucket operation: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/zappa/cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/zappa/cli.py", line 505, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/zappa/cli.py", line 539, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/zappa/cli.py", line 714, in deploy
    self.zip_path, self.s3_bucket_name, disable_progress=self.disable_progress)
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/zappa/core.py", line 891, in upload_to_s3
    Bucket=bucket_name,
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid.

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
```
## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: OSX 10.13.3 and Python 3.6.0
* The output of `pip freeze`:
```
aiohttp==3.0.3
alabaster==0.7.10
argcomplete==1.9.2
astroid==1.6.2
async-timeout==2.0.0
attrs==17.4.0
Babel==2.5.3
base58==0.2.4
bokeh==0.12.13
boto3==1.7.2
botocore==1.10.2
certifi==2017.11.5
cfn-flip==1.0.3
chardet==3.0.4
CIRpy==1.0.2
click==6.7
colorama==0.3.9
colorclass==2.2.0
cycler==0.10.0
Cython==0.27.3
decorator==4.1.2
docutils==0.14
durationpy==0.5
eventlet==0.22.1
Flask==0.12.2
Flask-SocketIO==2.9.3
future==0.16.0
gevent==1.2.2
graphviz==0.8.1
greenlet==0.4.13
gunicorn==19.7.1
hjson==3.0.1
idna==2.6
idna-ssl==1.0.0
imagesize==1.0.0
ipython-genutils==0.2.0
isort==4.3.4
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter-core==4.4.0
kappa==0.6.0
lambda-packages==0.19.0
lazy-object-proxy==1.3.1
MarkupSafe==1.0
matplotlib==2.1.1
mccabe==0.6.1
measurement==1.8.0
-e git+https://github.com/Benjamin-Lee/flow-chem.git@a67f6851fbce0cd92dbf2f8953d882ddcbd7b02f#egg=mechwolf
more-itertools==4.1.0
multidict==4.1.0
nbformat==4.4.0
netdisco==1.3
netifaces==0.10.6
networkx==2.0
numpy==1.13.3
packaging==17.1
pandas==0.22.0
Pint==0.8.1
pkginfo==1.4.2
placebo==0.8.1
plotly==2.2.3
pluggy==0.6.0
py==1.5.3
Pygments==2.2.0
pylint==1.8.3
pymongo==3.6.0
pynamodb==3.2.1
pyparsing==2.2.0
Pyro4==4.70
pyserial==3.4
pytest==3.5.0
python-dateutil==2.6.1
python-engineio==2.0.2
python-slugify==1.2.4
python-socketio==1.8.4
pytz==2017.3
PyYAML==3.12
remi==0.1
requests==2.18.4
requests-toolbelt==0.8.0
s3transfer==0.1.13
schedule==0.5.0
serpent==1.23
six==1.11.0
snowballstemmer==1.2.1
socketIO-client==0.7.2
Sphinx==1.7.1
sphinx-rtd-theme==0.2.4
sphinxcontrib-fulltoc==1.2.0
sphinxcontrib-websupport==1.0.1
sympy==0.7.6.1
terminaltables==3.1.0
toml==0.9.4
tornado==4.5.3
tqdm==4.19.1
traitlets==4.3.2
troposphere==2.2.1
twine==1.11.0
Unidecode==1.0.22
unqlite==0.6.2
urllib3==1.22
vedis==0.6.0
websocket==0.2.1
websocket-client==0.47.0
Werkzeug==0.12
wireless==0.3.2
wrapt==1.10.11
wsgi-request-logger==0.4.6
yarl==1.1.1
zappa==0.45.1
zeroconf==0.20.0
```
* Link to your project (optional):
* Your `zappa_settings.py`: 
```
{
    "dev": {
        "s3_bucket": "mechwolf_resolver",
        "app_function": "app.app"
    }
}
```

**Comment by h-2-0** [comment]
Did you solve it, @Benjamin-Lee ? I am also getting this no matter the region.

**Comment by Benjamin-Lee** [comment]
@h-2-0 I made a fresh virtualenv and that worked for me

**Comment by h-2-0** [comment]
Thanks, @Benjamin-Lee ! 

I solved it in a different way. I notice that in my `zappa_settings.json` file the 'aws_region' key had a null value. So I added the region manually to match region set in the `aws configure` command and it worked!

**Comment by Ryanb58** [comment]
I have tried both of these methods without success:/

**Comment by Yohaido159** [comment]
hello I face this problem a lot and finaly I understand the problem is that the problem in the key because O use with MFA and when I create new user without MFA it's success.
