### ISSUE TITLE
Pip 10 compatibility issues

### ISSUE THREAD

**Issue by jleclanche** [Miserlou/Zappa#1478]
Pip 10 was just released and I'm now getting this with it:

```pytb

12:15:05 Traceback (most recent call last):
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py", line 2610, in handle
12:15:05     sys.exit(cli.handle())
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py", line 505, in handle
12:15:05     self.dispatch_command(self.command, stage)
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py", line 549, in dispatch_command
12:15:05     self.update(self.vargs['zip'], self.vargs['no_upload'])
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py", line 877, in update
12:15:05     self.create_package()
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py", line 2171, in create_package
12:15:05     disable_progress=self.disable_progress
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/core.py", line 595, in create_lambda_zip
12:15:05     installed_packages = self.get_installed_packages(site_packages, site_packages_64)
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/core.py", line 751, in get_installed_packages
12:15:05     pip.get_installed_distributions()
12:15:05 AttributeError: module 'pip' has no attribute 'get_installed_distributions'
12:15:05 Build step 'Execute shell' marked build as failure
12:15:05 Finished: FAILURE
```

Workaround: force install pip==9.0.3.

**Comment by scoates** [comment]
Thank you for reporting this. There's no easy fix. Zappa uses [unsupported](https://github.com/pypa/pip/issues/5081) functionality in pip <= 9 that it looks like they removed in 10.

**Comment by monkut** [comment]
hit the same thing today.
The following can be used to rollback your version of pip if you've upgraded to 10.0.0:
```
pip install pip==9.0.3
```

**Comment by shreyashag** [comment]
This needs to get fixed asap as it breaks deployment of new zappa projects by default.
Will be very discouraging to new users!

**Comment by duckpunch** [comment]
I have no idea what this package is, but ran into the same issue.

[Related issue](https://github.com/pyupio/safety/issues/90) for an entirely different package.

Recommended solution there is similar to @monkut's - to pin `pip<10` for now.

**Comment by scoates** [comment]
It's [already pinned at 9.0.1](https://github.com/Miserlou/Zappa/blob/a93a24e39ceb6b583886735c0409a0d3d6d74824/requirements.txt#L13). The user needs to manually downgrade to make this work, if I'm not mistaken.

**Comment by Miserlou** [comment]
I'm gonna pin at 9.0.3 - a version that was only ever released due to my incessant nagging - then publish a long, long overdue new version tonight, and then open a ticket for migrating to pip 10.

**Comment by iamjohnnym** [comment]
Hey guys, I have a PR that i'd like to make.  The functionality still exists within pip.  We just need to change how its imported.  This is where the function lives in 10.0.0.


I propose a change like so:

```python
try: # for pip >= 10
    from pip._internal.utils.misc import get_installed_distributions
except ImportError: # for pip <= 9.0.3
    from pip import get_installed_distributions```

**Comment by shivampaw** [comment]
i have my pip version to 9.0.3 but still get the error:
~~~
==============

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zappa/cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zappa/cli.py", line 505, in handle
    self.dispatch_command(self.command, stage)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zappa/cli.py", line 539, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zappa/cli.py", line 709, in deploy
    self.create_package()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zappa/cli.py", line 2171, in create_package
    disable_progress=self.disable_progress
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zappa/core.py", line 595, in create_lambda_zip
    installed_packages = self.get_installed_packages(site_packages, site_packages_64)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zappa/core.py", line 751, in get_installed_packages
    pip.get_installed_distributions()
AttributeError: module 'pip' has no attribute 'get_installed_distributions'

==============
~~~

**Comment by jamessam** [comment]
pip 9.0.3 is failing for me. 9.0.1 is currently working, but I'm still in the deployment process.

**Comment by agronholm** [comment]
Pip has no public API and as such, importing `pip` is a no-no. You're better off copying to code to where you need it.

**Comment by dacut** [comment]
Hm... in the current master branch, requirements.txt now lists: `pip>=9.0.1, <=10.1.0`

I'm not sure why there's an upper-bound restriction (current pip is 18.0), but it looks like this was solved elsewhere.

**Comment by jasonrhaas** [comment]
@dacut I haven't tried it recently, but I've only has success using `pip==9.0.1`, so I've pinned to that.

**Comment by ewhauser** [comment]
This has been fixed in newer versions of safety and should be closed.
