### ISSUE TITLE
No module named 'app': ModuleNotFoundError , slim_handler : true

### ISSUE THREAD

**Issue by houdinisparks** [Miserlou/Zappa#1482]
## Context
I am trying to deploy a >100 mb flask app with slim_handler : true. Below is my file structure:

```
+-- app
|   +-- routes
|   +-- static
|   +-- __init__.py
|   +-- load.py
+-- venv
+-- run.py
+-- setup.py
+-- requirements.txt
```
However, when i try to deploy to zappa, its gives me the following error below:
```
No module named 'app': ModuleNotFoundError
Traceback (most recent call last):
File "/var/task/handler.py", line 566, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 237, in lambda_handler
handler = cls()
File "/var/task/handler.py", line 129, in __init__
self.app_module = importlib.import_module(self.settings.APP_MODULE)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 978, in _gcd_import
File "<frozen importlib._bootstrap>", line 961, in _find_and_load
File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 978, in _gcd_import
File "<frozen importlib._bootstrap>", line 961, in _find_and_load
File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'

```

this is my zappa_settings.json
```
{
    "dev": {
        "app_function": "run.app",
        "profile_name": "work",
        "project_name": "<projectname>",
        "runtime": "python3.6",
        "s3_bucket": "<s3bucketname>",
        "slim_handler": true
    }
}
```

and my run.py
```
from app.load import create_app

app = create_app()

# We only need this for local development.
if __name__ == '__main__':
    print("initiating the web app...")
    app.run(debug=True)
```

and my load.py file:
```
from flask import Flask
from app import routes

def create_app():
    """An application factory, as explained here: http://flask.pocoo.org/docs/patterns/appfactories/.
    :param config_object: The configuration object to use.
    """
    app = Flask(__name__, static_url_path='', template_folder="static/pages")
    register_blueprints(app)
    return app



def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(routes.api.api_bp)
    app.register_blueprint(routes.index.webpage_bp)
    return None

```

## Your Environment

* Zappa version used: latest from pip installed from github <0.45.11>
* Operating System and Python version: Win 10, python 3.6
* The output of `pip freeze`: 
```
aniso8601==3.0.0
argcomplete==1.9.3
asn1crypto==0.24.0
azure-common==1.1.8
azure-nspkg==2.0.0
azure-storage==0.36.0
base58==0.2.4
boto3==1.6.4
botocore==1.9.4
certifi==2018.1.18
cffi==1.11.5
cfn-flip==1.0.0
chardet==3.0.4
click==6.7
-e git+https://wyy95.visualstudio.com/IVAN/_git/ModelDeployment@213574193aa6759d2b7767871714f5c7e3079a11#egg=cognizant
cryptography==2.2.1
docutils==0.14
durationpy==0.5
Flask==0.12.2
Flask-REST==1.3
Flask-RESTful==0.3.6
future==0.16.0
hjson==3.0.1
idna==2.6
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
lightgbm==2.1.0
MarkupSafe==1.0
numpy==1.14.1
pandas==0.22.0
placebo==0.8.1
pycparser==2.18
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2018.3
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.13
scikit-learn==0.19.1
scipy==1.0.0
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.2.0
Unidecode==1.0.22
urllib3==1.22
Werkzeug==0.13
wsgi-request-logger==0.4.6
zappa==0.45.1

```
* Link to your project (optional):

**Comment by houdinisparks** [comment]
Copying and pasting my solution in #1491, I solved this issue by removing all .pyc files generated from my compiler in windows 10, then putting my project folder in an aws lambda docker image, reinstalled my python dependencies into a new virtual environment inside docker, then deployed the flask app from there. I used mligus/zappa docker image, which is based on the os aws lambda is operating on with zappa and a bare new virtual environment aleady installed. So basically the steps was:

**Open up cmd prompt on ur host system and run the command below:**

`cd <to_project_folder>`
`del /S *.pyc`
Deletes any .pyc files generated from my windows machine that might cause an error if they exists in aws lambda.

` docker run -ti -v %USERPROFILE%/.aws:/root/.aws -v <path_to_project_folder_on_host_sys>:/var/task --rm mligus/zappa bash`
you should then see a command prompt appear like this `zappa>`. make sure your project has been mounted over to the docker container by running `zappa> ls` and check all your project stuff is there.
**Note**: If your AWS credentials are stored differently, refer to the references below to see how to configure your aws credentials on docker separately.

**Within the docker machine run the commands below:**

`zappa> source /var/venv/bin/activate`
Activate the preconfigured virtual environment inside docker.

`zappa> pip install -r requirements.txt`
Install your python dependencies into the virtual environment

`zappa> zappa deploy <env>`
Deploy your app from inside docker.

**references below**
docker image: https://hub.docker.com/r/mligus/zappa/
host sys: windows 10

**Comment by modernresearch** [comment]
@houdinisparks Thank you for this. I spent hours trying to work through all the bugs that seem very common to Zappa deployments. Using the docker container worked. Seems like the project should build a working container as a starting point for users.
