### ISSUE TITLE
Zappa init: UnicodeDecodeError

### ISSUE THREAD

**Issue by JoshZastrow** [Miserlou/Zappa#1488]
On `Zappa init`, possible issue with encoding using CP1252 with a flask application?

## Context

On `Zappa init`, when defining the S3 bucket, Zappa errors out with a decode error:

```
AWS Lambda and API Gateway are only available in certain regions. Let's check to make sure you have a profile set up in one that will work.
Okay, using profile default!

Your Zappa deployments will need to be uploaded to a private S3 bucket.
If you don't have a bucket yet, we'll create one for you too.
What do you want call your bucket? (default 'zappa-5u4ed22rq'):

It looks like this is a Flask application.
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "c:\users\joshu\documents\code\machine-learning\boston-housing-price\app\env\venv\lib\site-packages\zappa\cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "c:\users\joshu\documents\code\machine-learning\boston-housing-price\app\env\venv\lib\site-packages\zappa\cli.py", line 476, in handle
    self.init()
  File "c:\users\joshu\documents\code\machine-learning\boston-housing-price\app\env\venv\lib\site-packages\zappa\cli.py", line 1604, in init
    matches = detect_flask_apps()
  File "c:\users\joshu\documents\code\machine-learning\boston-housing-price\app\env\venv\lib\site-packages\zappa\utilities.py", line 143, in detect_flask_apps
    lines = f.readlines()
  File "c:\users\joshu\documents\code\machine-learning\boston-housing-price\app\env\venv\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 301: character maps to <undefined>

```

## Expected Behavior

Zappa init should run through the process and produce a dictionary of values / config.

## Actual Behavior

 A decode error generated

## Possible Fix

Are adding coding statements to the top of an api.py file necessary? 

## Steps to Reproduce

1. Install the newest version of Anaconda
2.  install virtualenv
3. install zappa, flask, awscli
4. create an S3 bucket
5. write api.py code
6. run zappa init

## Your Environment

* Zappa version used:
* Operating System and Python version: Windows 10, python 3.6
* The output of `pip freeze`:
argcomplete==1.9.2
awscli==1.15.7
base58==0.2.4
boto3==1.7.7
botocore==1.10.7
certifi==2018.4.16
cfn-flip==1.0.3
chardet==3.0.4
click==6.7
colorama==0.3.7
docutils==0.14
durationpy==0.5
Flask==0.12.2
future==0.16.0
hjson==3.0.1
idna==2.6
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
MarkupSafe==1.0
placebo==0.8.1
pyasn1==0.4.2
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.13
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.2.1
Unidecode==1.0.22
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1

* Link to your project (optional):
* Your `zappa_settings.py`: Not found??

**Comment by battini90** [comment]
I got the same error too. I am using the virtual environment on windows10, python3.6 and Zappa0.46.1
Also, in utilities.py, 
it was updated to io.open(full, 'r', encoding='utf-8') as f but I got same error.
Traceback (most recent call last):
  File "d:\python-aws-diy\repo_stats\venv\lib\site-packages\zappa\cli.py", line 2693, in handle
    sys.exit(cli.handle())
  File "d:\python-aws-diy\repo_stats\venv\lib\site-packages\zappa\cli.py", line 475, in handle
    self.init()
  File "d:\python-aws-diy\repo_stats\venv\lib\site-packages\zappa\cli.py", line 1546, in init
    \u255a\u2550\u2550\u2550\u2550\u2550\u2550\u255d\u255a\u2550\u255d  \u255a\u2550\u255d\u255a\u2550\u255d     \u255a\u2550\u255d     \u255a\u2550\u255d  \u255a\u2550\u255d\n""", fg='green', bold=True))
  File "d:\python-aws-diy\repo_stats\venv\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)
  File "d:\python-aws-diy\repo_stats\venv\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "d:\python-aws-diy\repo_stats\venv\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "d:\python-aws-diy\repo_stats\venv\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "d:\python-aws-diy\repo_stats\venv\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "d:\python-aws-diy\repo_stats\venv\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-9: character maps to <undefined>


Any help would be highly appreciated
