### ISSUE TITLE
TooManyRequestsException

### ISSUE THREAD

**Issue by fastingsamurai** [Miserlou/Zappa#1510]
Been getting this error today, never seen it before:

Deploying API Gateway..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/will/edcom/venv/lib/python2.7/site-packages/zappa/cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "/Users/will/edcom/venv/lib/python2.7/site-packages/zappa/cli.py", line 505, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/will/edcom/venv/lib/python2.7/site-packages/zappa/cli.py", line 549, in dispatch_command
    self.update(self.vargs['zip'], self.vargs['no_upload'])
  File "/Users/will/edcom/venv/lib/python2.7/site-packages/zappa/cli.py", line 980, in update
    endpoint_url = self.deploy_api_gateway(api_id)
  File "/Users/will/edcom/venv/lib/python2.7/site-packages/zappa/cli.py", line 2547, in deploy_api_gateway
    cache_cluster_encrypted=self.stage_config.get('cache_cluster_encrypted', False)
  File "/Users/will/edcom/venv/lib/python2.7/site-packages/zappa/core.py", line 1465, in deploy_api_gateway
    variables=variables or {}
  File "/Users/will/edcom/venv/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/will/edcom/venv/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
TooManyRequestsException: An error occurred (TooManyRequestsException) when calling the CreateDeployment operation (reached max retries: 4): Too Many Requests

Any ideas how I could go about figuring out what's happening?

**Comment by scoates** [comment]
Any chance your account is doing more than one `zappa update` (or `zappa deploy`) per minute?

The rate limit on API Gateway is ridiculously low.

**Comment by fastingsamurai** [comment]
Pretty much no chance of that I think :/
