### ISSUE TITLE
update/deploy fails deployment check on non-WSGI application

### ISSUE THREAD

**Issue by jwkvam** [Miserlou/Zappa#1563]
## Context

When doing `zappa depoy` or `zappa update` I receive an error like this:
```
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 500 response code.
```
From the server I can get the following traceback:
```
[1531440426124] 'NoneType' object is not callable
[1531440426133] Traceback (most recent call last):
[1531440426133] File "/var/task/handler.py", line 508, in handler
[1531440426133] response = Response.from_app(self.wsgi_app, environ)
[1531440426133] File "/var/task/werkzeug/wrappers.py", line 939, in from_app
[1531440426133] return cls(*_run_wsgi_app(app, environ, buffered))
[1531440426133] File "/var/task/werkzeug/wrappers.py", line 59, in _run_wsgi_app
[1531440426133] return _run_wsgi_app(*args)
[1531440426133] File "/var/task/werkzeug/test.py", line 923, in run_wsgi_app
[1531440426133] app_rv = app(environ, start_response)
[1531440426133] File "/var/task/zappa/middleware.py", line 72, in __call__
[1531440426133] response = self.application(environ, encode_response)
[1531440426133] TypeError: 'NoneType' object is not callable
```

## Expected Behavior
No API Gateway request should be attempted for non-WSGI applications.

## Actual Behavior
Zappa attempt to touch the endpoint_url and fails because no app is setup.

## Possible Fix
Add in logic to `self.use_gateway` to also check for if an `app_function` is defined?

A workaround is to set `apigateway_enabled: false`, but it's hard to debug and figure out.

## Steps to Reproduce
1. Create a zappa application.
2. Don't set an `app_function`.
3. Zappa deploy.

## Your Environment
* Zappa version used:
0.46.1
* Operating System and Python version:
Docker with Python 3.6
* The output of `pip freeze`:
```
argcomplete==1.9.3
base58==1.0.0
boto3==1.7.30
botocore==1.10.56
certifi==2018.4.16
cfn-flip==1.0.3
chardet==3.0.4
click==6.7
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.7
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
placebo==0.8.1
psutil==5.4.6
python-dateutil==2.7.3
python-slugify==1.2.4
pytzdata==2018.5
PyYAML==3.12
requests==2.19.1
s3transfer==0.1.13
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.3.1
Unidecode==1.0.22
urllib3==1.23
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
zappa==0.46.1
```
* Link to your project (optional):
* Your `zappa_settings.py`: 
```
    "staging": {
        "aws_region": "us-west-2",
        "memory_size": 512,
        "timeout_seconds": 300,
        "debug": true,
        "use_precompiled_packages": false,
        "delete_local_zip": false,
        "slim_handler": false,
        "runtime": "python3.6",
        "keep_warm": false,
        "manage_role": false,
      }
```

**Comment by ozuberi** [comment]
I'm having the same problem as well. Tried undeploying and then re-deploying to no avail. However by doing 'zappa tail' I was able to see that the calls to my  app_function were not working correctly. I'm still playing around with what that should be called, but it might help point you in the right direction

**Comment by jwkvam** [comment]
@ozuberi Thanks I purposefully don't have `app_fucntion` defined. I was able to fix my problem by putting:
```
apigateway_enabled: false
```
in `zappa_settings.json`. I don't think this issue would come up if `app_function` were defined.

**Comment by r-wakatsuki** [comment]
手動で作成した[スタック](https://ap-northeast-1.console.aws.amazon.com/cloudformation/designer/home?region=ap-northeast-1&stackId=arn:aws:cloudformation:ap-northeast-1:001761954102:stack/unsubscribe-aws-cloudformation-00/83294380-910e-11e9-9125-06cfba976b48&action=update)で作った[AGW](https://ap-northeast-1.console.aws.amazon.com/apigateway/home?region=ap-northeast-1#/apis/r0t4n47j9j/stages/dev)は、URLエンドポイントにアクセスするとHTMLがBase64で返ってくる。
Binary Media Typeがなぜか`*/*`に設定されていなかった（Zappaでデプロイした方は設定されていた）ので、設定したら動くようになった。

**Comment by jwilges** [comment]
Hi @jwkvam, it is possible that the patches I prepared for issue #2123 will help you out here as well. Just wanted to tag you so you were aware that there is some movement on this.
