### ISSUE TITLE
SnsAsyncResponse send message in binary format do sns

### ISSUE THREAD

**Issue by lincolwn** [Miserlou/Zappa#1592]
## Context
When I try call function decorated with `task_sns`, I have this issue:

```
[1534860745918] [DEBUG] 2018-08-21T14:12:25.918Z 3adcda53-a54c-11e8-917e-d54b5bfa0880 Event before-parameter-build.sns.Publish: calling handler <function generate_idempotent_uuid at 0x7f2bb8593510>
[1534860745920] Parameter validation failed:
Invalid type for parameter Message, value: b'{"task_path": "product.tasks.ping", "capture_response": false, "response_id": null, "args": [1], "kwargs": {}, "command": "zappa.async.route_sns_task"}', type: <class 'bytes'>, valid types: <class 'str'>: ParamValidationError
Traceback (most recent call last):
  File "/var/task/handler.py", line 567, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
  return handler.handler(event, context)
  File "/var/task/handler.py", line 383, in handler
  exec(raw_command)
  File "<string>", line 1, in <module>
  File "/var/task/zappa/async.py", line 424, in _run_async
  capture_response=capture_response).send(task_path, args, kwargs)
  File "/var/task/zappa/async.py", line 170, in send
  self._send(message)
  File "/var/task/zappa/async.py", line 249, in _send
  Message=payload
  File "/var/task/botocore/client.py", line 314, in _api_call
  return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 586, in _make_api_call
  api_params, operation_model, context=request_context)
  File "/var/task/botocore/client.py", line 621, in _convert_to_request_dict
  api_params, operation_model)
  File "/var/task/botocore/validate.py", line 291, in serialize_to_request
  raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
```
Seeing `SnsAsyncResponse`code I saw that in `_send` method:

https://github.com/Miserlou/Zappa/blob/12ac82e71deeffcb03dbb6549be4f6f60d537382/zappa/async.py#L244

How it return message as `bytes`, `botocore` validator raise an error because it expects `str`.
If remove `encode`method call it will return `str`instead `bytes` instance.

I'm right? May I change that and pull request?

### Zappa Version
`zappa==0.46.2`

**Comment by codenamesubho** [comment]
```
[1556184504255] Parameter validation failed:
Invalid type for parameter Message, value: b'{"task_path": "schedules.task.execute_scheduled_job", "capture_response": false, "response_id": null, "args": [4], "kwargs": {}, "command": "zappa.asynchronous.route_sns_task"}', type: <class 'bytes'>, valid types: <class 'str'>: ParamValidationError
Traceback (most recent call last):
  File "/var/task/handler.py", line 602, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 248, in lambda_handler
  return handler.handler(event, context)
  File "/var/task/handler.py", line 382, in handler
  result = self.run_function(app_function, event, context)
  File "/var/task/handler.py", line 283, in run_function
  result = app_function(event, context) if varargs else app_function()
  File "/var/task/schedules/task.py", line 14, in run_scheduler
  execute_scheduled_job(schedule.id)
  File "/var/task/zappa/asynchronous.py", line 427, in _run_async
  capture_response=capture_response).send(task_path, args, kwargs)
  File "/var/task/zappa/asynchronous.py", line 173, in send
  self._send(message)
  File "/var/task/zappa/asynchronous.py", line 252, in _send
  Message=payload
  File "/var/runtime/botocore/client.py", line 314, in _api_call
  return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 586, in _make_api_call
  api_params, operation_model, context=request_context)
  File "/var/runtime/botocore/client.py", line 621, in _convert_to_request_dict
  api_params, operation_model)
  File "/var/runtime/botocore/validate.py", line 291, in serialize_to_request
  raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Message, value: b'{"task_path": "schedules.task.execute_scheduled_job", "capture_response": false, "response_id": null, "args": [4], "kwargs": {}, "command": "zappa.asynchronous.route_sns_task"}', type: <class 'bytes'>, valid types: <class 'str'>
```
when i use task_sns
`zappa==0.48.2`
