### ISSUE TITLE
Zappa not installing all dependencies in virtual environment?

### ISSUE THREAD

**Issue by complangorous** [Miserlou/Zappa#1635]
I'm trying to spin up a lambda that connects to a database in Snowflake, but am getting a ModuleNotFoundError every time I invoke, despite having installed the packages.

**Environment**: Ubuntu 160.04, Py3.6, virtualenv
**Missing Package**: snowflake-sqlalchemy

## Config

	{
	   {
	    "production": {
	        "aws_kms_key_arn": <AWS_KMS_KEY_ARN>,
	        "apigateway_enabled": false,
	        "slim_handler": true,
	        "manage_roles": false,
	        "app_function": "snowflake_test.main",
	        "aws_region": "us-east-1",
	        "profile_name": "default",
	        "project_name": "snowflake-test",
	        "runtime": "python3.6",
	        "s3_bucket": <S3_BUCKET>,
	        "role_name": snowflake-test-production-ZappaLambdaExecutionRole,
	        "role_arn": <ROLE_ARN>
	    }
	}

## pip freeze

	argcomplete==1.9.3
	asn1crypto==0.24.0
	awscli==1.16.26
	azure-common==1.1.16
	azure-nspkg==2.0.0
	azure-storage==0.36.0
	base58==1.0.0
	boto3==1.8.9
	botocore==1.11.9
	certifi==2018.8.24
	cffi==1.11.5
	cfn-flip==1.0.3
	chardet==3.0.4
	Click==7.0
	colorama==0.3.9
	cryptography==2.3.1
	docutils==0.14
	durationpy==0.5
	future==0.16.0
	hjson==3.0.1
	idna==2.7
	ijson==2.3
	jmespath==0.9.3
	kappa==0.6.0
	lambda-packages==0.20.0
	numpy==1.15.2
	pandas==0.23.4
	placebo==0.8.2
	pyasn1==0.4.4
	pyasn1-modules==0.2.2
	pycparser==2.19
	pycryptodomex==3.6.6
	PyJWT==1.6.4
	pyOpenSSL==18.0.0
	python-dateutil==2.6.1
	python-slugify==1.2.4
	pytz==2018.5
	PyYAML==3.12
	requests==2.19.1
	rsa==3.4.2
	s3transfer==0.1.13
	six==1.11.0
	snowflake==0.0.3
	snowflake-connector-python==1.6.10
	snowflake-sqlalchemy==1.1.2
	SQLAlchemy==1.2.12
	toml==0.10.0
	tqdm==4.19.1
	troposphere==2.3.3
	Unidecode==1.0.22
	urllib3==1.23
	Werkzeug==0.14.1
	wsgi-request-logger==0.4.6
	zappa==0.46.2

## Script

	import pandas as pd
	from sqlalchemy import create_engine
	
	def main():
	
		engine = create_engine('snowflake://<user_login_name>:<password>@<account_name>	
							/<database_name>/<schema_name>?warehouse=
							<warehouse_name>?role=<role_name>')
	
		df = pd.read_sql("""SELECT * FROM Data LIMIT 100""", engine)
		print(df)
	
	if __name__ == "__main__":
		main()

## Expected Behavior
 DataFrame prints to screen.

## Actual Behavior

	No module named 'snowflake.sqlalchemy'; 'snowflake' is not a package: ModuleNotFoundError
	Traceback (most recent call last):
	  File "/var/task/handler.py", line 567, in lambda_handler
	    return LambdaHandler.lambda_handler(event, context)
	  File "/var/task/handler.py", line 240, in lambda_handler
	    return handler.handler(event, context)
	  File "/var/task/handler.py", line 372, in handler
	    result = self.run_function(app_function, event, context)
	  File "/var/task/handler.py", line 275, in run_function
	    result = app_function(event, context) if varargs else app_function()
	  File "/tmp/snowflake-test/snowflake_test.py", line 8, in main	
	     create_engine('snowflake://<user_login_name>:<password>@<account_name>	/<database_name>	/<schema_name>?warehouse=<warehouse_name>?role=<role_name>')
	  File "/tmp/snowflake-test/sqlalchemy/engine/__init__.py", line 425, in create_engine
	    return strategy.create(*args, **kwargs)
	  File "/tmp/snowflake-test/sqlalchemy/engine/strategies.py", line 57, in create
	    entrypoint = u._get_entrypoint()
	  File "/tmp/snowflake-test/sqlalchemy/engine/url.py", line 156, in _get_entrypoint
	    cls = registry.load(name)
	  File "/tmp/snowflake-test/sqlalchemy/util/langhelpers.py", line 217, in load
	    return impl.load()
	  File "/tmp/snowflake-test/pkg_resources/__init__.py", line 2332, in load
	    return self.resolve()
	  File "/tmp/snowflake-test/pkg_resources/__init__.py", line 2338, in resolve
	    module = __import__(self.module_name, fromlist=['__name__'], level=0)
	ModuleNotFoundError: No module named 'snowflake.sqlalchemy'; 'snowflake' is not a package

 Has anyone else had this problem, with snowflake or any other package?

**Comment by jneves** [comment]
@complangorous is it possible that either your project dir or your virtual environment are called "snowflake"?

**Comment by wingardtw** [comment]
I am having this problem. It is not even package specific, when zappa is installing dependencies, it seems to ignore everything in my requirements.txt AND whatever is installed with pip.

**Comment by wingardtw** [comment]
My issue was resolved by pip installing psycopg2-binary in addition to psycopg2. I suppose zappa was conflating its own instance with my local install

**Comment by guneetsinghbhatia** [comment]
'snowflake.sqlalchemy': ModuleNotFoundError this is a message when I am trying to deploy code to lambda using Zappa

**Comment by Kevin-Prichard** [comment]
I also needed to install `psycopg2-binary` via `requirements.txt` in order for SQLAlchemy to be able to `import psycopg2`. Thanks to @wingardtw
