### ISSUE TITLE
zappa update --zip local.zip causes boto ConnectionClosedError with lambda

### ISSUE THREAD

**Issue by kylegibson-rldatix** [Miserlou/Zappa#1686]
## Context

`zappa update --zip local.zip` causes a ConnectionClosedError.

```
$ zappa package development --output foo.zip
Calling package for stage development..
Downloading and installing dependencies..
 - sqlite==python36: Using precompiled lambda package
Packaging project as zip.
Package created: foo.zip (21.2MiB)

$ zappa update development --zip foo.zip
Calling update for stage development..
Updating Lambda function code..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/awsrequest.py", line 125, in _send_request
    method, url, body, headers, *args, **kwargs)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/awsrequest.py", line 152, in _send_output
    self.send(msg)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/awsrequest.py", line 236, in send
    return super(AWSConnection, self).send(str)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out
  
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/httpsession.py", line 258, in send
    decode_content=False,
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/awsrequest.py", line 125, in _send_request
    method, url, body, headers, *args, **kwargs)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/awsrequest.py", line 152, in _send_output
    self.send(msg)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/awsrequest.py", line 236, in send
    return super(AWSConnection, self).send(str)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/home/kyle/.pyenv/versions/3.6.5/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))
  
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/zappa/cli.py", line 2710, in handle
    sys.exit(cli.handle())
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/zappa/cli.py", line 508, in handle
    self.dispatch_command(self.command, stage)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/zappa/cli.py", line 555, in dispatch_command
    self.update(self.vargs['zip'], self.vargs['no_upload'])
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/zappa/cli.py", line 933, in update
    num_revisions=self.num_retained_versions
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/zappa/core.py", line 1104, in update_lambda_function
    response = self.lambda_client.update_function_code(**kwargs)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/client.py", line 610, in _make_api_call
    operation_model, request_dict)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/endpoint.py", line 136, in _send_request
    success_response, exception):
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/endpoint.py", line 210, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/endpoint.py", line 179, in _get_response
    http_response = self._send(request)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/endpoint.py", line 223, in _send
    return self.http_session.send(request)
  File "/home/kyle/.local/share/virtualenvs/asin-Dofq7uIK/lib/python3.6/site-packages/botocore/httpsession.py", line 289, in send
    endpoint_url=request.url
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/xxxxxxxx/code".

```

Note that `zappa update development` works as expected:

```
Calling update for stage development..
Downloading and installing dependencies..
 - sqlite==python36: Using precompiled lambda package
Packaging project as zip.
Uploading xxxxxxxx-1540763761.zip (21.2MiB)..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22.2M/22.2M [00:07<00:00, 2.91MB/s]
Updating Lambda function code..
Updating Lambda function configuration..
Uploading xxxxxxx-template-1540763777.json (1.6KiB)..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.63K/1.63K [00:00<00:00, 12.5KB/s]
Deploying API Gateway..
Scheduling..
Unscheduled xxxxxxxx-zappa-keep-warm-handler.keep_warm_callback.
Scheduled xxxxx-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Your updated Zappa deployment is live!: https://xxxxxxxx
```

## Expected Behavior
zappa update --zip should upload the zip to the lambda

## Actual Behavior
zappa update --zip crashes

## Your Environment
* Zappa version used: 0.47
* Operating System and Python version: ubuntu 16.04 python 3.6.5

**Comment by kylegibson** [comment]
Update: I tested `zappa update --zip s3://bucket/foo.zip` and it worked. This only seems busted for local zips

**Comment by jneves** [comment]
Does `zappa update development --zip s3://bucket/foo.zip` work?

**Comment by kylegibson** [comment]
Yes it does.

**Comment by jneves** [comment]
I suspect you are running it on another stage, either an undeployed one or without a region configured, not the `development` one you were assuming. Do you have multi stages on your zappa_settings file? If so, it's safer to always make the stage explicit on the command line.

**Comment by kylegibson** [comment]
Hi Joao - My original post includes the exact commands that I ran, and those commands do include the explicit stage name. Here's a short version:

1. `zappa update development` -- This works as expected
2. `zappa package development --output foo.zip` - Works as expected
3. `zappa update development --zip foo.zip` - This crashes with a ConnectionClosedError. 
4. `zappa update development --zip s3://xxxxxxx/foo.zip` This works as expected

**Comment by LyleScott** [comment]
Yup, this seems like it's broken for local zips for me, too. To repeat, simply:
- zappa package
- zappa update -z path/to/local/file.zip  # breaks with error above, unconditionally
- zappa update -z s3://foo/bar/file.zip  # works fine
