### ISSUE TITLE
Django SAML: saml2.sigver.SigverError: Can't find ['xmlsec1']

### ISSUE THREAD

**Issue by ameenmaali** [Miserlou/Zappa#1726]
## Context
Python 3.6, zappa 0.47.1: 

I am trying to setup `django_saml2_auth` and running into some issues with `xmlsec1`
`saml2.sigver.SigverError: Can't find ['xmlsec1']`

The setup works locally, but there are some issues with `xmlsec1` running in the AWS Lambda environment. I have tried to build it a number of different ways in docker (using both the Amazonlinux image and lambci python 3.6), but no luck. Steps I've tried:

1) Build and deploy in docker
2) Manually copy library files to `/var/task/myenv/lib/python3.6/site-packages/lib/`
3) Manually update PySAML2 `xmlsec_binary` path 
4) I've also tried to follow: https://github.com/Miserlou/Zappa/issues/1029 and https://github.com/Miserlou/Zappa/issues/1374 with no luck

## Expected Behavior
Redirection to SAML login page

## Actual Behavior
```
Traceback (most recent call last):
  File "/var/task/django/core/handlers/exception.py", line 35, in inner
  response = get_response(request)
  File "/var/task/django/core/handlers/base.py", line 128, in _get_response
  response = self.process_exception_by_middleware(e, request)
  File "/var/task/django/core/handlers/base.py", line 126, in _get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/task/django_saml2_auth/views.py", line 207, in signin
  saml_client = _get_saml_client(get_current_domain(r))
  File "/var/task/django_saml2_auth/views.py", line 99, in _get_saml_client
  spConfig.load(saml_settings)
  File "/var/task/saml2/config.py", line 356, in load
  self.load_complex(cnf, metadata_construction=metadata_construction)
  File "/var/task/saml2/config.py", line 296, in load_complex
  self.load_metadata(cnf["metadata"]))
  File "/var/task/saml2/config.py", line 398, in load_metadata
  disable_ssl_certificate_validation=disable_validation)
  File "/var/task/saml2/mdstore.py", line 850, in __init__
  self.security = security_context(config)
  File "/var/task/saml2/sigver.py", line 1103, in security_context
  xmlsec_binary = get_xmlsec_binary(_path)
  File "/var/task/saml2/sigver.py", line 203, in get_xmlsec_binary
  raise SigverError("Can't find %s" % bin_name)
saml2.sigver.SigverError: Can't find ['xmlsec1']
```

## Steps to Reproduce
1. Install django_saml2_auth
2. Setup required configuration steps to connect to SAML
3. Deploy to Lambda environment
4. Navigate to SAML login page (`django_saml2_auth.views.signin`)
5. Should get the error

## Your Environment

Python 3.6, zappa 0.47.1: 

Dockerfile:

```
FROM lambci/lambda:build-python3.6

RUN yum groupinstall -y 'Development Tools' && \
    yum install -y xmlsec1 libxslt-devel libxml2-devel xmlsec1-devel xmlsec1-openssl-devel libtool-ltdl-devel

ARG environment
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
WORKDIR /var/task

RUN virtualenv dev && source dev/bin/activate && \
    pip install -r requirements.txt

CMD ["bash"]
```

**Comment by weasteam** [comment]
Have you found any solution?

**Comment by ameenmaali** [comment]
Unfortunately I was not able to find a solution for this, so went a different route..but still interested in how to solve this

**Comment by elliotsegler** [comment]
Are you using the slim handler? I am, and noticed that the path to the xmlsec binary was different to what I expected.

I've got `XMLSEC_BINARY=/tmp/myapp/lib/xmlsec1` in `settings.py`.

I also had to set the LD_LIBRARY_PATH environment variable on the lambda to /tmp/myapp/lib in order to get xmlsec1 to find the libraries it's linked against.

**Comment by Sphinxs** [comment]
Some update?

**Comment by weasteam** [comment]
My solution to making it work in Zappa/Django

1. Create an AWS EC2 instance, The image have to be identical to the AMI you are going to use for the Zappa/Django. Install `xmlsec1` and related packages.
2. Copy `xmlsec1`, `libxmlsec1.so.1`, `libxmlsec1.so.1.2.20` to `/site-packages/lib` in your virtualenv
3. Install `libxmlsec1-openssl` and copy `lbixmlsec1-openssl.so`, `lbixmlsec1-openssl.so.1`, `lbixmlsec1-openssl.so.1.20` to `/site-packages/lib`
4. Set `xmlsec_binary` to `"/var/task/lib/xmlsec1"` for saml_settings
```
saml_settings["xmlsec_binary"] = "/var/task/lib/xmlsec1"
```

I hope it helps.

**Comment by MohitBansalOkta** [comment]
@weasteam did you run into any permission issue ? I followed all the above steps and worked fine until I run into Permission issue 
`check_sig: [Errno 13] Permission denied: 'lib/xmlsec1'`

Any idea ?
