### ISSUE TITLE
Zappa won't deploy from Travis with environment variables

### ISSUE THREAD

**Issue by Benjamin-Lee** [Miserlou/Zappa#1736]
## Context

I'm trying to deploy a Zappa app as per [this blog post](https://blog.zappa.io/posts/continuous-zappa-deployments-with-travis) using Python 3.6 and Travis.

## Expected Behavior

The app would deploy. I can deploy from my computer but not Travis.

## Actual Behavior

```
$ export AWS_ACCESS_KEY_ID=[secure]
$ export AWS_SECRET_ACCESS_KEY=[secure]

travis_time:start:0002b71a
[0K$ source ~/virtualenv/python3.6/bin/activate
travis_time:end:0002b71a:start=1545521726858641044,finish=1545521726864754926,duration=6113882
[0K$ python --version
Python 3.6.3
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (python 3.6)
travis_fold:start:install
[0Ktravis_time:start:13e7689c
[0K$ pip install -r requirements.txt
Collecting boto3==1.9.66 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/6b/31/2922911f17940f8616c075415cda13de88577f350c31f9b5ea14ed104e7c/boto3-1.9.66-py2.py3-none-any.whl (128kB)
Collecting pandas==0.22.0 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/da/c6/0936bc5814b429fddb5d6252566fe73a3e40372e6ceaf87de3dec1326f28/pandas-0.22.0-cp36-cp36m-manylinux1_x86_64.whl (26.2MB)
Collecting Werkzeug==0.14.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
Collecting xxhash==1.3.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/df/db/abd8ecd1753b60e5b527365676482bda272d71eaab0ad732a8be5f11d2d8/xxhash-1.3.0-cp36-cp36m-manylinux1_x86_64.whl (46kB)
Collecting Flask==1.0.2 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl (91kB)
Collecting zappa (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/64/e2/2c13f117d2178dd45f25f04c0a3a2afb59f2dc779fec1bdeaf7a8567f776/zappa-0.47.1-py3-none-any.whl (107kB)
Collecting pyarrow (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/36/94/23135312f97b20d6457294606fb70fad43ef93b7bffe567088ebe3623703/pyarrow-0.11.1-cp36-cp36m-manylinux1_x86_64.whl (11.6MB)
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3==1.9.66->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl (59kB)
Collecting botocore<1.13.0,>=1.12.66 (from boto3==1.9.66->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/50/c0/cd4f8bec8a10876f0ce34f0cf264fda04e09df41d1a473a43f890c71fffa/botocore-1.12.71-py2.py3-none-any.whl (5.2MB)
Collecting jmespath<1.0.0,>=0.7.1 (from boto3==1.9.66->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting python-dateutil>=2 (from pandas==0.22.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl (225kB)
Collecting pytz>=2011k (from pandas==0.22.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/f8/0e/2365ddc010afb3d79147f1dd544e5ee24bf4ece58ab99b16fbb465ce6dc0/pytz-2018.7-py2.py3-none-any.whl (506kB)
Requirement already satisfied: numpy>=1.9.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from pandas==0.22.0->-r requirements.txt (line 2))
Collecting click>=5.1 (from Flask==1.0.2->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting itsdangerous>=0.24 (from Flask==1.0.2->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Jinja2>=2.10 (from Flask==1.0.2->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
Collecting PyYAML==3.13 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
Requirement already satisfied: six>=1.11.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: pip>=9.0.1 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Collecting lambda-packages==0.20.0 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/0d/27/e588646a1c8c47b96862aafa66416142db5db857732594aafe19cbbf3fda/lambda_packages-0.20.0.tar.gz (99.7MB)
Collecting tqdm==4.19.1 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/c0/d3/7f930cbfcafae3836be39dd3ed9b77e5bb177bdcf587a80b6cd1c7b85e74/tqdm-4.19.1-py2.py3-none-any.whl (50kB)
Collecting troposphere>=1.9.0 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/c7/d8/ac1aa690cb15d8b5f451ff1c54d106534d305a7dadee25c0052b144d425f/troposphere-2.3.4.tar.gz (128kB)
Collecting requests>=2.20.0 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
Collecting future==0.16.0 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
Collecting docutils>=0.12 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl (543kB)
Collecting toml>=0.9.4 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting wsgi-request-logger==0.4.6 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/04/dd/5e6c52b96a841baec75e5c5647460214aa02e9c4902c7b250375352224c0/wsgi-request-logger-0.4.6.tar.gz
Collecting argcomplete==1.9.3 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/0d/f2/058910b2c732092175875820177dae9d390e71a5f30a9895f92e6a6ca466/argcomplete-1.9.3-py2.py3-none-any.whl
Collecting kappa==0.6.0 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/ee/fa/1b8328d2199520ef5a257f8a2e9315ed0b0194e353a152ca1959490dfbc8/kappa-0.6.0.tar.gz
Collecting durationpy==0.5 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/24/85/70dabb62c3f9705566db0d8a33ebf6c203b5887a1a186f8bcf58a9bf46a6/durationpy-0.5.tar.gz
Collecting python-slugify==1.2.4 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/9f/77/ab7134b731d0e831cf82861c1ab0bb318e80c41155fa9da18958f9d96057/python_slugify-1.2.4-py2.py3-none-any.whl
Requirement already satisfied: wheel>=0.30.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Collecting hjson==3.0.1 (from zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/8a/92/6b6b85064f8a88cb3b31901d839e7b45c33e4ee450bb1b3cf0c226cca8ec/hjson-3.0.1.tar.gz (43kB)
Collecting urllib3<1.25,>=1.20; python_version >= "3.4" (from botocore<1.13.0,>=1.12.66->boto3==1.9.66->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->Flask==1.0.2->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/08/04/f2191b50fb7f0712f03f064b71d8b4605190f2178ba02e975a87f7b89a0d/MarkupSafe-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting cfn_flip>=1.0.2 (from troposphere>=1.9.0->zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/2b/98/c91146bf03087ea35fedeac0e7a751af9cbc29b560f576e6422aaacbe13d/cfn_flip-1.1.0.post1-py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.20.0->zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
Collecting certifi>=2017.4.17 (from requests>=2.20.0->zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.20.0->zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting placebo>=0.8.1 (from kappa==0.6.0->zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/4e/67/cdd143e5cb486b33a0b43c5cdfe96c72f0f5dc0c2a2b5efebd4a47d703c1/placebo-0.8.2.tar.gz
Collecting Unidecode>=0.04.16 (from python-slugify==1.2.4->zappa->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/31/39/53096f9217b057cb049fe872b7fc7ce799a1a89b76cf917d9639e7a558b5/Unidecode-1.0.23-py2.py3-none-any.whl (237kB)
Building wheels for collected packages: PyYAML, lambda-packages, troposphere, future, wsgi-request-logger, kappa, durationpy, hjson, placebo
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/ad/da/0c/74eb680767247273e2cf2723482cb9c924fe70af57c334513f
  Running setup.py bdist_wheel for lambda-packages: started
  Running setup.py bdist_wheel for lambda-packages: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/c3/88/27/fdd463e4ada229ba4874ef3c38bea268d91bddcdf0ea69cb71
  Running setup.py bdist_wheel for troposphere: started
  Running setup.py bdist_wheel for troposphere: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/c2/da/bc/f353d6852cfbb312db95f9dbaf578eaaa3f3863e8d5d2e586f
  Running setup.py bdist_wheel for future: started
  Running setup.py bdist_wheel for future: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/bf/c9/a3/c538d90ef17cf7823fa51fc701a7a7a910a80f6a405bf15b1a
  Running setup.py bdist_wheel for wsgi-request-logger: started
  Running setup.py bdist_wheel for wsgi-request-logger: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/6b/aa/05/d92d33e020a66e347ddd04ec3a57dd5b2c33d14616d675bd43
  Running setup.py bdist_wheel for kappa: started
  Running setup.py bdist_wheel for kappa: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/fe/34/ec/23a576ff864ede8a44f06062b7b6183b11479b860eea67f72b
  Running setup.py bdist_wheel for durationpy: started
  Running setup.py bdist_wheel for durationpy: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/00/cd/8d/5089f745ef355c25c8642b3d8ab6ffb2bb958b91eb13c49c90
  Running setup.py bdist_wheel for hjson: started
  Running setup.py bdist_wheel for hjson: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/34/2a/5b/254bcb7475d861a2bdc1f8f32f9924734b4e045a7c8dd596ae
  Running setup.py bdist_wheel for placebo: started
  Running setup.py bdist_wheel for placebo: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/85/4f/60/7cf98f842649810ac29f0b6b51684621c60e9a6f997aa552e1
Successfully built PyYAML lambda-packages troposphere future wsgi-request-logger kappa durationpy hjson placebo
Installing collected packages: docutils, urllib3, jmespath, python-dateutil, botocore, s3transfer, boto3, pytz, pandas, Werkzeug, xxhash, click, itsdangerous, MarkupSafe, Jinja2, Flask, PyYAML, lambda-packages, tqdm, cfn-flip, troposphere, idna, certifi, chardet, requests, future, toml, wsgi-request-logger, argcomplete, placebo, kappa, durationpy, Unidecode, python-slugify, hjson, zappa, pyarrow
Successfully installed Flask-1.0.2 Jinja2-2.10 MarkupSafe-1.1.0 PyYAML-3.13 Unidecode-1.0.23 Werkzeug-0.14.1 argcomplete-1.9.3 boto3-1.9.66 botocore-1.12.71 certifi-2018.11.29 cfn-flip-1.1.0.post1 chardet-3.0.4 click-7.0 docutils-0.14 durationpy-0.5 future-0.16.0 hjson-3.0.1 idna-2.8 itsdangerous-1.1.0 jmespath-0.9.3 kappa-0.6.0 lambda-packages-0.20.0 pandas-0.22.0 placebo-0.8.2 pyarrow-0.11.1 python-dateutil-2.7.5 python-slugify-1.2.4 pytz-2018.7 requests-2.21.0 s3transfer-0.1.13 toml-0.10.0 tqdm-4.19.1 troposphere-2.3.4 urllib3-1.24.1 wsgi-request-logger-0.4.6 xxhash-1.3.0 zappa-0.47.1
travis_time:end:13e7689c:start=1545521727877395793,finish=1545521779755813937,duration=51878418144
[0Ktravis_fold:end:install
[0Ktravis_time:start:0cbe1cc4
[0K$ echo "all tests passing"
all tests passing
travis_time:end:0cbe1cc4:start=1545521779760698848,finish=1545521779763699315,duration=3000467
[0K[32;1mThe command "echo "all tests passing"" exited with 0.[0m


travis_fold:start:after_success.1
[0Ktravis_time:start:056ad326
[0K$ pip install -r requirements.txt
Requirement already satisfied: boto3==1.9.66 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: pandas==0.22.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: Werkzeug==0.14.1 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: xxhash==1.3.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: Flask==1.0.2 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: zappa in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pyarrow in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from boto3==1.9.66->-r requirements.txt (line 1))
Requirement already satisfied: botocore<1.13.0,>=1.12.66 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from boto3==1.9.66->-r requirements.txt (line 1))
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from boto3==1.9.66->-r requirements.txt (line 1))
Requirement already satisfied: numpy>=1.9.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from pandas==0.22.0->-r requirements.txt (line 2))
Requirement already satisfied: python-dateutil>=2 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from pandas==0.22.0->-r requirements.txt (line 2))
Requirement already satisfied: pytz>=2011k in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from pandas==0.22.0->-r requirements.txt (line 2))
Requirement already satisfied: Jinja2>=2.10 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from Flask==1.0.2->-r requirements.txt (line 5))
Requirement already satisfied: click>=5.1 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from Flask==1.0.2->-r requirements.txt (line 5))
Requirement already satisfied: itsdangerous>=0.24 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from Flask==1.0.2->-r requirements.txt (line 5))
Requirement already satisfied: hjson==3.0.1 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: future==0.16.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: durationpy==0.5 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: toml>=0.9.4 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: docutils>=0.12 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: troposphere>=1.9.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: kappa==0.6.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: six>=1.11.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: argcomplete==1.9.3 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: pip>=9.0.1 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: requests>=2.20.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: tqdm==4.19.1 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: python-slugify==1.2.4 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: wsgi-request-logger==0.4.6 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: lambda-packages==0.20.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: PyYAML==3.13 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: wheel>=0.30.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from zappa->-r requirements.txt (line 6))
Requirement already satisfied: urllib3<1.25,>=1.20; python_version >= "3.4" in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from botocore<1.13.0,>=1.12.66->boto3==1.9.66->-r requirements.txt (line 1))
Requirement already satisfied: MarkupSafe>=0.23 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from Jinja2>=2.10->Flask==1.0.2->-r requirements.txt (line 5))
Requirement already satisfied: cfn-flip>=1.0.2 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from troposphere>=1.9.0->zappa->-r requirements.txt (line 6))
Requirement already satisfied: placebo>=0.8.1 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from kappa==0.6.0->zappa->-r requirements.txt (line 6))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from requests>=2.20.0->zappa->-r requirements.txt (line 6))
Requirement already satisfied: idna<2.9,>=2.5 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from requests>=2.20.0->zappa->-r requirements.txt (line 6))
Requirement already satisfied: certifi>=2017.4.17 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from requests>=2.20.0->zappa->-r requirements.txt (line 6))
Requirement already satisfied: Unidecode>=0.04.16 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from python-slugify==1.2.4->zappa->-r requirements.txt (line 6))
travis_time:end:056ad326:start=1545521779769256550,finish=1545521780629014544,duration=859757994
[0Ktravis_fold:end:after_success.1
[0Ktravis_fold:start:after_success.2
[0Ktravis_time:start:09f93e59
[0K$ zappa update dev
(python-dateutil 2.7.5 (/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages), Requirement.parse('python-dateutil<2.7.0,>=2.6.1'), {'zappa'})
Calling update for stage dev..
Oh no! An error occurred! :(

==============


==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/zappa/cli.py", line 2712, in handle
    sys.exit(cli.handle())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/zappa/cli.py", line 509, in handle
    self.dispatch_command(self.command, stage)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/zappa/cli.py", line 535, in dispatch_command
    self.load_settings(self.vargs.get('settings_file'))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/zappa/cli.py", line 2074, in load_settings
    xray_tracing=self.xray_tracing
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/zappa/core.py", line 293, in __init__
    self.load_credentials(boto_session, profile_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/zappa/core.py", line 2922, in load_credentials
    self.boto_session = boto3.Session(profile_name=profile_name, region_name=self.aws_region)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/session.py", line 679, in get_component
    return self._components.get_component(name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/session.py", line 902, in get_component
    self._components[name] = factory()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/session.py", line 150, in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/session.py", line 233, in get_config_variable
    logical_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/configprovider.py", line 226, in get_config_variable
    return provider.provide()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/configprovider.py", line 323, in provide
    value = provider.provide()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/configprovider.py", line 382, in provide
    config = self._session.get_scoped_config()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/session.py", line 334, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (default) could not be found
```

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: 0.47.1
* Operating System and Python version: Travis Python 3.6
* The output of `pip freeze`:
```
argcomplete==1.9.3
boto3==1.9.66
botocore==1.12.66
brython==3.6.2
certifi==2018.11.29
cfn-flip==1.1.0.post1
chardet==3.0.4
Click==7.0
docutils==0.14
durationpy==0.5
Flask==1.0.2
future==0.16.0
hjson==3.0.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
jiphy==1.2.2
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==1.1.0
numpy==1.15.4
pandas==0.22.0
placebo==0.8.2
pyarrow==0.11.1
python-dateutil==2.7.5
python-slugify==1.2.4
pytz==2018.7
PyYAML==3.13
requests==2.21.0
s3transfer==0.1.13
six==1.12.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.3.4
Unidecode==1.0.23
urllib3==1.24.1
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
xxhash==1.3.0
zappa==0.47.1
```
* Link to your project (optional):
https://github.com/Benjamin-Lee/squiggle-server
https://travis-ci.org/Benjamin-Lee/squiggle-server
* Your `zappa_settings.py`:

**Comment by Benjamin-Lee** [comment]
Had to remove "profile: default" from settings
