### ISSUE TITLE
Zappa Init error 'utf8' codec can't decode byte 0xf6 in position 117: invalid start byte

### ISSUE THREAD

**Issue by thewitty1** [Miserlou/Zappa#1753]
When trying to run zappa init with the default settings, I am getting this error after hitting enter on "What do you want to call your bucket? (default 'zappa-07a8z55ep'):" 

## Expected Behavior
zappa init should continue

## Actual Behavior
Instead I get this error

It looks like this is a Flask application.
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "c:\users\family\desktop\kanzi-master\kanzi-master\venv\lib\site-packages\zappa\cli.py", line 2725, in handle
    sys.exit(cli.handle())
  File "c:\users\family\desktop\kanzi-master\kanzi-master\venv\lib\site-packages\zappa\cli.py", line 480, in handle
    self.init()
  File "c:\users\family\desktop\kanzi-master\kanzi-master\venv\lib\site-packages\zappa\cli.py", line 1672, in init
    matches = detect_flask_apps()
  File "c:\users\family\desktop\kanzi-master\kanzi-master\venv\lib\site-packages\zappa\utilities.py", line 152, in detect_flask_apps
    lines = f.readlines()
  File "c:\users\family\desktop\kanzi-master\kanzi-master\venv\lib\codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 117: invalid start byte

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: 0.47.1
* Operating System and Python version: Windows 10 pro 64bit and Python 2.7.15
* The output of `pip freeze`: 
(venv) C:\Users\family\Desktop\kanzi-master\kanzi-master>pip freeze
aniso8601==1.2.0
argcomplete==1.9.3
asn1crypto==0.24.0
boto3==1.9.78
botocore==1.12.78
certifi==2018.11.29
cffi==1.11.5
cfn-flip==1.1.0.post1
chardet==3.0.4
Click==7.0
configparser==3.5.0
cryptography==2.1.4
docopt==0.6.2
docutils==0.14
durationpy==0.5
enum34==1.1.6
Flask==0.12.1
Flask-Ask==0.9.8
future==0.16.0
futures==3.2.0
fuzzywuzzy==0.17.0
gunicorn==19.9.0
hjson==3.0.1
idna==2.8
ipaddress==1.0.22
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
Kodi-Voice==1.1.3
lambda-packages==0.20.0
MarkupSafe==1.1.0
num2words==0.5.9
packaging==18.0
placebo==0.8.2
pycparser==2.19
pyocclient==0.4
pyOpenSSL==17.0.0
pyparsing==2.3.0
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2018.9
PyYAML==3.13
requests==2.21.0
roman==3.1
s3transfer==0.1.13
six==1.11.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.1
Unidecode==1.0.23
urllib3==1.24.1
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
zappa==0.47.1
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
* Link to your project (optional):
* Your `zappa_settings.py`: don't have yet, assume it gets created by zappa init

**Comment by jash13** [comment]
I got the same problem in Windows 10.
Did you get any solution for this?

**Comment by thewitty1** [comment]
No I haven't.

**Comment by Abhiintheweb** [comment]
> I got the same problem in Windows 10.
> Did you get any solution for this?

Activate your virtualenv 
Move to a separate directory.
Run zappa init.
Worked  in my case.

**Comment by thewitty1** [comment]
So activate the virtual environment in the correct directory. Then do a "cd" command to any random directory, and run Zappa init?

**Comment by jash13** [comment]
Yes either that or I would suggest creating a new folder for it.

**Comment by thewitty1** [comment]
Also, to note, if your following a guide that says to just accept all defaults during Zappa init; you will have a line come up asking where your apps function is. You will need to point it to the path for your kanzi-master directory.

**Comment by thewitty1** [comment]
My apologies to anyone who followed my previous post. If it asks where your apps function is enter "alexa.app"

**Comment by pickfire** [comment]
I found a similar issue too on lambda.
```
'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```
But it works on my machine.
