### ISSUE TITLE
botocore.exceptions.ClientError: InvalidAccessKeyId while uploading an image via Django admin

### ISSUE THREAD

**Issue by thesunlover** [Miserlou/Zappa#1761]
## Context

We use Zappa with Django to deploy our project on the AWS.
We have an API end-point that receives json with base64 images. The image is parsed on the server side and then is saved in an ImageField to Django model (in the DB). All our media images are stored on the AWS S3 service.
At first the issue happened when upgrading the boto3 as soon as a new version is released, upgrading it and then updating the deploy on the AWS Lambda instance.

The last time we had a deploy 28 days back and we got the error from the client in the late evening (17th Jan 2019). Later today our client said that he managed to save his data with the image ( using the same sync procedure from an Android app)
We have development and deploy envirnment with separated dev and deploy requirements. Env is only python36.

When the issue is present in the api requests it is present in the admin as well.

## Expected Behavior
Saving images via Django admin happens normally and the image is visible in the S3 bucket.
Api handles properly saving images on S3 (via Django S3 storage)

## Actual Behavior
boto3 error:
     botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

## Full python traceback from the AWS lambda

```
Traceback (most recent call last):
  File "/var/task/django/core/handlers/exception.py", line 34, in inner
  response = get_response(request)
  File "/var/task/django/core/handlers/base.py", line 126, in _get_response
  response = self.process_exception_by_middleware(e, request)
  File "/var/task/django/core/handlers/base.py", line 124, in _get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/task/django/contrib/admin/options.py", line 604, in wrapper
  return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/var/task/django/utils/decorators.py", line 142, in _wrapped_view
  response = view_func(request, *args, **kwargs)
  File "/var/task/django/views/decorators/cache.py", line 44, in _wrapped_view_func
  response = view_func(request, *args, **kwargs)
  File "/var/task/django/contrib/admin/sites.py", line 223, in inner
  return view(request, *args, **kwargs)
  File "/var/task/django/contrib/admin/options.py", line 1640, in change_view
  return self.changeform_view(request, object_id, form_url, extra_context)
  File "/var/task/django/utils/decorators.py", line 45, in _wrapper
  return bound_method(*args, **kwargs)
  File "/var/task/django/utils/decorators.py", line 142, in _wrapped_view
  response = view_func(request, *args, **kwargs)
  File "/var/task/django/contrib/admin/options.py", line 1525, in changeform_view
  return self._changeform_view(request, object_id, form_url, extra_context)
  File "/var/task/django/contrib/admin/options.py", line 1564, in _changeform_view
  self.save_model(request, new_object, form, not add)
  File "/var/task/django/contrib/admin/options.py", line 1091, in save_model
  obj.save()
  File "/var/task/django/db/models/base.py", line 718, in save
  force_update=force_update, update_fields=update_fields)
  File "/var/task/django/db/models/base.py", line 748, in save_base
  updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/task/django/db/models/base.py", line 809, in _save_table
  for f in non_pks]
  File "/var/task/django/db/models/base.py", line 809, in <listcomp>
  for f in non_pks]
  File "/var/task/django/db/models/fields/files.py", line 288, in pre_save
  file.save(file.name, file.file, save=False)
  File "/var/task/django/db/models/fields/files.py", line 87, in save
  self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/var/task/django/core/files/storage.py", line 49, in save
  return self._save(name, content)
  File "/var/task/storages/backends/s3boto3.py", line 506, in _save
  self._save_content(obj, content, parameters=parameters)
  File "/var/task/storages/backends/s3boto3.py", line 521, in _save_content
  obj.upload_fileobj(content, ExtraArgs=put_parameters)
  File "/var/runtime/boto3/s3/inject.py", line 621, in object_upload_fileobj
  ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/var/runtime/boto3/s3/inject.py", line 539, in upload_fileobj
  return future.result()
  File "/var/runtime/s3transfer/futures.py", line 73, in result
  return self._coordinator.result()
  File "/var/runtime/s3transfer/futures.py", line 233, in result
  raise self._exception
  File "/var/runtime/s3transfer/tasks.py", line 126, in __call__
  return self._execute_main(kwargs)
  File "/var/runtime/s3transfer/tasks.py", line 150, in _execute_main
  return_value = self._main(**kwargs)
  File "/var/runtime/s3transfer/upload.py", line 692, in _main
  client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/var/runtime/botocore/client.py", line 314, in _api_call
  return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 612, in _make_api_call
  raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
```

## Possible Fix
Not sure, but probably... When the session token fails a retry can be triggered with reloading the session token.

## Steps to Reproduce
1. Setup VPC, set all the right, create a zappa role, create S3 bucket with all the policies needed for the `PutObject` action
2. Create Django app with a model that contains an ImageField
3. deploy to AWS, then wait for a new version of boto libs and `zappa update dev` 
4. go to /admin/model_with_image/  and create a new record with an image.
I am not sure I can create a separete working example I can present to the open public.

## Your Environment
* Zappa version used:
0.47.1
* Operating System and Python version:
local: Windows 10 + python3.6
remote: not known + python3.6
* The output of `pip freeze`:
```
argcomplete==1.9.3
beautifulsoup4==4.7.1
boto3==1.9.78
botocore==1.12.79
CacheControl==0.12.5
cchardet==1.1.3
certifi==2018.10.15
cfn-flip==1.1.0.post1
chardet==3.0.4
click==6.7
configparser==3.5.0
datadotworld==1.6.0
datapackage==0.8.9
diff-match-patch==20181111
Django==2.1.5
django-debug-toolbar==1.11
django-extensions==2.1.4
django-import-export==1.2.0
django-rest-auth==0.9.3
django-s3-storage==0.12.4
django-storages==1.7.1
djangorestframework==3.9.0
docutils==0.14
drf-extensions==0.4.0
durationpy==0.5
et-xmlfile==1.0.1
flake8==3.4.0
future==0.16.0
hjson==3.0.1
idna==2.7
ijson==2.3
isodate==0.6.0
jdcal==1.4
jmespath==0.9.3
jsonlines==1.2.0
jsonschema==2.6.0
jsontableschema==0.10.1
kappa==0.6.0
lambda-packages==0.20.0
linear-tsv==1.1.0
mccabe==0.6.1
msgpack==0.5.6
mysqlclient==1.3.14
odfpy==1.3.6
openpyxl==2.5.11
Pillow==5.4.1
placebo==0.8.2
psycopg2==2.7.6.1
pycodestyle==2.3.1
pyflakes==1.5.0
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2018.7
PyYAML==3.13
requests==2.21.0
rfc3986==0.4.1
s3transfer==0.1.13
six==1.11.0
soupsieve==1.7.1
SQLAlchemy==1.2.14
sqlparse==0.2.4
tablib==0.12.1
tabulator==1.4.1
toml==0.10.0
tqdm==4.19.1
troposphere==2.3.4
unicodecsv==0.14.1
Unidecode==1.0.23
urllib3==1.24.1
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
xlrd==1.1.0
xlwt==1.3.0
zappa==0.47.1
zappa-django-utils==0.4.0
```
* Your `zappa_settings.py`: 
```
{
    "dev": {
        "log_level": "ERROR",
        "aws_region": "us-east-1",
        "django_settings": "******hidden******",
        "profile_name": "default",
        "project_name": "******hidden******",
        "runtime": "python3.6",
        "keep_warm":false,
        "timeout_seconds": 30,
        "s3_bucket": "zappa-dev-package",
        "num_retained_versions": 10,
        "environment_variables": {
            "DJANGO_CONF": "aws_lambda",
            "PROJECT_STAGE": "dev"
        },
        "manage_roles": false,
        "role_name": "******hidden******",
        "role_arn": "arn:aws:iam::******hidden******",
        "vpc_config": {
            "SubnetIds": [
                "******hidden******",
                "******hidden******"
            ],
            "SecurityGroupIds": [
                "******hidden******"
            ]
        },
        "events": [
            {
                "function": "******hidden******",
                "expression": "rate(10000 days)"
            },
            {
                "function": "******hidden******",
                "expression": "rate(10000 days)"
            },
            {
                "function": "******hidden******",
                "expression": "rate(10000 days)"
            },
            {
                "function": "******hidden******",
                "expression": "rate(10000 days)"
            },
            {
                "function": "******hidden******",
                "expression": "rate(10000 days)"
            }
        ]
    },
    "production": {
        "extends": "dev",
        "log_level": "ERROR",
        "profile_name": "production",
        "aws_region": "us-west-2",
        "keep_warm":true,
        "s3_bucket": "******hidden******",
        "environment_variables": {
            "DJANGO_CONF": "aws_lambda",
            "PROJECT_STAGE": "production"
        },
        "events": [],
        "role_name": "******hidden******",
        "role_arn": "arn:aws:iam::******hidden******",
        "vpc_config": {
            "SubnetIds": [
                "******hidden******",
                "******hidden******"
            ],
            "SecurityGroupIds": [
                "******hidden******"
            ]
        }
    },
    "production_export": {
        "extends": "production",
        "keep_warm": false,
        "project_name": "******hidden******",
        "timeout_seconds": 900,
        "events": [
            {
                "function": "******hidden******",
                "expression": "rate(6 hours)"
            },
            {
                "function": "******hidden******",
                "expression": "rate(6 hours)"
            },
            {
                "function": "******hidden******",
                "expression": "rate(6 hours)"
            }
        ]
    },
    "production_import": {
        "extends": "production",
        "keep_warm": false,
        "project_name": "******hidden******",
        "timeout_seconds": 900,
        "events": [
            {
                "function": "******hidden******",
                "expression": "rate(16 minutes)"
            },
            {
                "function": "******hidden******",
                "expression": "rate(1 day)"
            }
        ]
    }
}
```

**Comment by badanin-dmitry-playrix** [comment]
Probably, it happens because django-storages retrieving aws security token from lambda environment variables.

workaround would be
create custom storage class
```
class S3Boto3StorageWithoutSecurityToken(S3Boto3Storage):
    def _get_security_token(self):
        return None
```
and use it in settings
DEFAULT_FILE_STORAGE = 'S3Boto3StorageWithoutStorageToken'

**Comment by thesunlover** [comment]
Thanks for the try @badanin-dmitry-playrix, 
I Get the same error:

An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

Probably it would be best if we have somekind of refresh of this token?

Exception Location:  /var/runtime/botocore/client.py in _make_api_call, line 612

Here is the updated `pip freeze` list:

```
argcomplete==1.9.3
beautifulsoup4==4.7.1
boto3==1.9.82
botocore==1.12.82
CacheControl==0.12.5
cchardet==1.1.3
certifi==2018.10.15
cfn-flip==1.1.0.post1
chardet==3.0.4
click==6.7
configparser==3.5.0
datadotworld==1.6.0
datapackage==0.8.9
diff-match-patch==20181111
Django==2.1.5
django-debug-toolbar==1.11
django-extensions==2.1.4
django-import-export==1.2.0
django-rest-auth==0.9.3
django-s3-storage==0.12.4
django-storages==1.7.1
djangorestframework==3.9.1
docutils==0.14
drf-extensions==0.4.0
durationpy==0.5
et-xmlfile==1.0.1
flake8==3.4.0
future==0.16.0
hjson==3.0.1
idna==2.7
ijson==2.3
isodate==0.6.0
jdcal==1.4
jmespath==0.9.3
jsonlines==1.2.0
jsonschema==2.6.0
jsontableschema==0.10.1
kappa==0.6.0
lambda-packages==0.20.0
linear-tsv==1.1.0
mccabe==0.6.1
msgpack==0.5.6
mysqlclient==1.4.1
odfpy==1.3.6
openpyxl==2.5.11
Pillow==5.4.1
placebo==0.8.2
psycopg2==2.7.6.1
pycodestyle==2.3.1
pyflakes==1.5.0
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2018.7
PyYAML==3.13
requests==2.21.0
rfc3986==0.4.1
s3transfer==0.1.13
six==1.11.0
soupsieve==1.7.1
SQLAlchemy==1.2.14
sqlparse==0.2.4
tablib==0.12.1
tabulator==1.4.1
toml==0.10.0
tqdm==4.19.1
troposphere==2.3.4
unicodecsv==0.14.1
Unidecode==1.0.23
urllib3==1.24.1
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
xlrd==1.1.0
xlwt==1.3.0
zappa==0.47.1
zappa-django-utils==0.4.0
```

**Comment by thesunlover** [comment]
here is more deepened discussion on the topic:
https://github.com/jschneier/django-storages/issues/606

**Comment by thesunlover** [comment]
If you still didn't find solution....
My suggestion is to use a custom class that is similar to 
one of the comments:

https://github.com/jschneier/django-storages/issues/606#issuecomment-461762380
https://github.com/jschneier/django-storages/issues/606#issuecomment-461774432
