### ISSUE TITLE
Async function can't find file

### ISSUE THREAD

**Issue by bakaouji** [Miserlou/Zappa#1776]
## Context
When running a zappa asynchronous function, the function can't find my config file on the second call.

I have a flask project with this structure:
app.py
static/
lib/
templates/
utils.py
config.json
zappa_settings.json.

app.py has two functions:

main(): This is the main function that runs, calls generate_pdf(), and returns 200. 
@task generate_pdf(): This function reads the config.json file (code below), generates a PDF and emails it using SES. It needs to be asynchronous as it could take 1-2 minutes to generate, longer than the API gateway timeout.

```
  with open('config.json', 'r', encoding="utf8") as config_file:
    config = json.load(config_file)
```

Above is working fine when the lambda is initially deployed, email is received correctly. However, on the second time the function is run, the generate_pdf() can't find the config file, and the following error is appearing.

```
[Errno 2] No such file or directory: 'config.json': FileNotFoundError
Traceback (most recent call last):
  File "/var/task/handler.py", line 580, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 248, in lambda_handler
  return handler.handler(event, context)
  File "/var/task/handler.py", line 382, in handler
  result = self.run_function(app_function, event, context)
  File "/var/task/handler.py", line 287, in run_function
  result = app_function(event, context)
  File "/var/task/zappa/async.py", line 269, in route_lambda_task
  return run_message(message)
  File "/var/task/zappa/async.py", line 305, in run_message
  **message['kwargs']
  File "/var/task/app.py", line 35, in email_pdf
  config = init()
  File "/var/task/app.py", line 16, in init
  with open('config.json', 'r', encoding="utf8") as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
```

Is the config file somehow being deleted by something? Is it a path issue?

## Your Environment

* Zappa version used: 0.47.1
* Operating System and Python version: Linux, 3.6.7
* The output of `pip freeze`:  
argcomplete==1.9.3
boto3==1.9.86
botocore==1.12.86
cairocffi==0.9.0
CairoSVG==2.2.1
certifi==2018.11.29
cffi==1.11.5
cfn-flip==1.1.0.post1
chardet==3.0.4
Click==7.0
cssselect2==0.2.1
defusedxml==0.5.0
docutils==0.14
durationpy==0.5
Flask==1.0.2
future==0.16.0
hjson==3.0.1
html5lib==1.0.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==1.1.0
Pillow==5.4.1
pkg-resources==0.0.0
placebo==0.8.2
pycparser==2.19
Pyphen==0.9.5
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.13
requests==2.21.0
s3transfer==0.1.13
six==1.12.0
tinycss2==0.6.1
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.1
Unidecode==1.0.23
urllib3==1.24.1
WeasyPrint==44
webencodings==0.5.1
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
zappa==0.47.1
* Link to your project (optional):
* Your `zappa_settings.py`: 
{
    "dev": {
        "app_function": "app.app",
        "aws_region": "us-west-2",
        "profile_name": "default",
        "project_name": "lambda-pdf",
        "runtime": "python3.6",
        "s3_bucket": "lambda-pdf",
        "keep_warm": false,
        "timeout_seconds": 120,
        "extra_permissions": [{ // Attach any extra permissions to this policy.
            "Effect": "Allow",
            "Action": ["ses:*"], // AWS Service ARN
            "Resource": "*"
        }],
        "tags": { // Attach additional tags to AWS Resources
            "project": "lambda_pdf"
        }
    }
}

**Comment by bakaouji** [comment]
Sorry, this had nothing to do with async, but rather the filepath. Was fixed after I changed the file reading code to:
 ```
 config_path = os.environ['LAMBDA_TASK_ROOT'] + "/config.json"
  with open(config_path, 'r', encoding="utf8") as config_file:
    config = json.load(config_file)
```
