### ISSUE TITLE
 - mysqlclient==1.4.2.post1: Warning! Using precompiled lambda package version 1.3.12 instead!

### ISSUE THREAD

**Issue by Vadorequest** [Miserlou/Zappa#1788]
I have the following package in requirements.txt:

    mysqlclient==1.4.2.post1

When I run a `zappa update` it displays the following

```bash
Downloading and installing dependencies..
 - mysqlclient==1.4.2.post1: Warning! Using precompiled lambda package version 1.3.12 instead!
 - sqlite==python36: Using precompiled lambda package
Packaging project as zip.

```

I just wonder why, is it an issue?

**Comment by cl1ent** [comment]
you could set `"use_precompiled_packages"` in your `zappa-settings.json` to `False` which might help you. however I am also wondering why it uses a lower version from zappa-packages even if a higher one was explicitly specified.

**Comment by spinolacastro** [comment]
Hello, i can confirm using local python env 3.6.6 and lambda doesn't let me run the function:

[1554483253817] Instancing..
[1554483255843] /var/task
[1554483256584] mysqlclient 1.3.13 or newer is required; you have 1.3.12.: ImproperlyConfigured
Traceback (most recent call last):
  File "/var/task/handler.py", line 602, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 245, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 151, in __init__
  wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)
  File "/var/task/zappa/ext/django_zappa.py", line 20, in get_django_wsgi
  return get_wsgi_application()
  File "/var/task/django/core/wsgi.py", line 12, in get_wsgi_application
  django.setup(set_prefix=False)
  File "/var/task/django/__init__.py", line 24, in setup
  apps.populate(settings.INSTALLED_APPS)
  File "/var/task/django/apps/registry.py", line 114, in populate
  app_config.import_models()
  File "/var/task/django/apps/config.py", line 211, in import_models
  self.models_module = import_module(models_module_name)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/django/contrib/auth/models.py", line 2, in <module>
  from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/var/task/django/contrib/auth/base_user.py", line 47, in <module>
  class AbstractBaseUser(models.Model):
  File "/var/task/django/db/models/base.py", line 117, in __new__
  new_class.add_to_class('_meta', Options(meta, app_label))
  File "/var/task/django/db/models/base.py", line 321, in add_to_class
  value.contribute_to_class(cls, name)
  File "/var/task/django/db/models/options.py", line 204, in contribute_to_class
  self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/var/task/django/db/__init__.py", line 28, in __getattr__
  return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/var/task/django/db/utils.py", line 201, in __getitem__
  backend = load_backend(db['ENGINE'])
  File "/var/task/django/db/utils.py", line 110, in load_backend
  return import_module('%s.base' % backend_name)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "/var/task/django/db/backends/mysql/base.py", line 36, in <module>
  raise ImproperlyConfigured('mysqlclient 1.3.13 or newer is required; you have %s.' % Database.__version__)
django.core.exceptions.ImproperlyConfigured: mysqlclient 1.3.13 or newer is required; you have 1.3.12.

**Comment by sleepychild** [comment]
> you could set `"use_precompiled_packages"` in your `zappa-settings.json` to `False` which might help you. however I am also wondering why it uses a lower version from zappa-packages even if a higher one was explicitly specified.

If you do that you get "django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?"
For some reason newer versions are not compatible with lambda and older are not compatible with django.
