### ISSUE TITLE
Opening UTF-8 files on Windows machines

### ISSUE THREAD

**Issue by drummonds** [Miserlou/Zappa#1801]
If you try and do local install eg via pip / pipenv on a Windows machine you get a UnicodeDecodeError (see end).
## Context
Using Python3.6.  Although correctly using io.open, encoding is not specified eg like this:
```python
with open('README.md', encoding='utf-8') as readme_file:
    long_description = readme_file.read()```
## Expected Behavior
Should install

## Actual Behavior
UnicodeDecodeError

## Possible Fix
https://github.com/drummonds/Zappa/commit/f24fcc649946d59cfc4e49b57f5c049f12863166
however at the moment a couple of the tests fail:
https://travis-ci.org/drummonds/Zappa/builds/501560955

I am working on this.

## Steps to Reproduce
`pip install C:/Users/HumphreyDrummond/ForkedProjects/zappa`

where version is pre patch

## Your Environment
- Windows 10
- Python 3.6
- Version 0.47.1

# Sample Error Message
Processing c:\users\humphreydrummond\forkedprojects\zappa
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HUMPHR~1\AppData\Local\Temp\pip-req-build-qe6qv2o3\setup.py", line 8, in <module>
        long_description = readme_file.read()
      File "c:\users\humphreydrummond\.virtualenvs\bytestone.co.uk-6mzjitax\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 70907: character maps to <undefined>

**Comment by drummonds** [comment]
Having got it working I am going to suggest a pull request

**Comment by OrangutanGaming** [comment]
All I did was clone and make the change that you made but a few weeks ago and it installed fine, thankfully fairly simple issue, but not too sure how it wasn't reported earlier

**Comment by drummonds** [comment]
Do you have any other changes?  I have just go all the tests to run locally on Windows and now need to fix the issue with zipping paths in slim_handler when going from a Windows developement to lambda.

**Comment by OrangutanGaming** [comment]
I had the bug with Pillow installing properly so I ended up giving up on Windows and only using Zappa for either checking the status or in my ci which uses linux


________________________________

**Comment by OrangutanGaming** [comment]
I had the bug with Pillow installing properly so I ended up giving up on Windows and only using Zappa for either checking the status or in my ci which uses linux

**Comment by drummonds** [comment]
I might investigate looking at a WSL type environment.  I now have all the tests working for Windows see issue 1358
