### ISSUE TITLE
Flask example ModuleNotFoundError 

### ISSUE THREAD

**Issue by ChrisBolman** [Miserlou/Zappa#1809]
Trying to deploy a skeleton Flask app referencing the [example](https://github.com/Miserlou/Zappa/tree/master/example) and keep hitting this err on `zappa deploy`:

```
Deploying API Gateway..
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 500 response code.
```

virtualenv with python: 3.6.5

root folder:

```
- app.py
- requirements.txt
- zappa_settings.json
```

app.py:

```
import logging
from flask import Flask

app = Flask(__name__)
logging.basicConfig()
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

@app.route('/', methods=['GET', 'POST'])
def lambda_handler(event=None, context=None):
	logger.info('Lambda function invoked index()')
	return 'Success'

if __name__ == '__main__':
    app.run()
```

pip freeze:

```
argcomplete==1.9.3
awscli==1.16.121
base58==1.0.0
boto==2.48.0
boto3==1.7.4
botocore==1.10.6
certifi==2019.3.9
cfn-flip==1.1.0.post1
chardet==3.0.4
Click==7.0
colorama==0.3.9
configparser==3.5.0
docutils==0.14
durationpy==0.5
Flask==1.0.2
Flask-Boto3==0.3.2
future==0.16.0
hjson==3.0.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==1.0
placebo==0.9.0
pyasn1==0.4.5
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.13
requests==2.21.0
rsa==3.4.2
s3transfer==0.1.13
six==1.11.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.5
Unidecode==1.0.23
urllib3==1.23
virtualenv==13.1.0
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
zappa==0.47.1
```

zappa_settings.json:

```
{
    "dev": {
        "app_function": "app.app",
        "lambda_handler": "app.lambda_handler",
        "profile_name": "dev-app",
        "manage_roles": false,
        "role_name":"dev-ZappaLambdaExecutionRole",
        "role_arn": "arn:aws:iam::***:role/dev-ZappaLambdaExecutionRole",
        "project_name": "project-dev",
        "runtime": "python3.6",
        "s3_bucket": "zappa-foo",
        "log_level": "DEBUG",
        "http_methods": ["GET"],
        "parameter_depth": 1,
        "timeout_seconds": 300,
        "memory_size": 128,
        "use_precompiled_packages": true
    }
}
```

zappa tail dev:

```
No module named 'app.init'; 'app' is not a package: ModuleNotFoundError
Traceback (most recent call last):
  File "/var/task/handler.py", line 580, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 245, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 139, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app.init'; 'app' is not a package

```

per # [1491](https://github.com/Miserlou/Zappa/issues/1491) I've tried clearing out my .pyc files. same err.

**Comment by ChrisBolman** [comment]
was able to complete deploy by adding `"use_apigateway": false` to zappa_settings.json
