### ISSUE TITLE
Configuration of cognito event's trigger fails

### ISSUE THREAD

**Issue by Yaronn44** [Miserlou/Zappa#1879]
## Context
I wanted to use the cognito event trigger by declaring it in the `zappa_setting.py` with this form :
```        
"cognito": {
            "user_pool": "user-pool-id", 
            "triggers": [{
                "source": "PreAuthentication_Authentication", 
                "function": "my_app.pre_authentication_function"
            }]
        }
```
## Expected Behavior
The zappa update should succeed, and the trigger should be created in the cognito pool.

## Actual Behavior
At the zappa update i have this error that trigger : 
```
Traceback (most recent call last):
  File "c:\***\***\venv\lib\site-packages\zappa\cli.py", line 2712, in handle
    sys.exit(cli.handle())
  File "c:\***\***\venv\lib\site-packages\zappa\cli.py", line 509, in handle
    self.dispatch_command(self.command, stage)
  File "c:\***\***\venv\lib\site-packages\zappa\cli.py", line 556, in dispatch_command
    self.update(self.vargs['zip'], self.vargs['no_upload'])
  File "c:\***\***\venv\lib\site-packages\zappa\cli.py", line 1016, in update
    self.update_cognito_triggers()
  File "c:\***\***\venv\lib\site-packages\zappa\cli.py", line 1138, in update_cognito_triggers
    self.zappa.update_cognito(self.lambda_name, user_pool, lambda_configs, self.lambda_arn)
  File "c:\***\***\venv\lib\site-packages\zappa\core.py", line 1803, in update_cognito
    result = self.cognito_client.update_user_pool(UserPoolId=user_pool, **description_kwargs)
  File "c:\***\***\venv\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\***\***\venv\lib\site-packages\botocore\client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the UpdateUserPool operation: Please use TemporaryPasswordValidityDays instead of UnusedAccountValidityDays
```
An associate of mine did the configuration 2 or 3 weeks ago and everything worked. 

## Possible Fix
In boto3 documentation it is said [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp.html#CognitoIdentityProvider.Client.update_user_pool) that : 
```
Note
If you set a value for TemporaryPasswordValidityDays in PasswordPolicy , that value will be used and UnusedAccountValidityDays will be deprecated for that user pool.
```
But it seems now, that it will not only be deprecated, but also that it shouldn't be in the request body.

About zappa, in the `update_cognito` function in the `core.py` file, the `UnusedAccountValidityDays` attribut and the `TemporaryPasswordValidityDays` are get with the `describe_user_pool` function (line 2044). So both attributs are automatically present in the arguments for the `update_user_pool` function (line 2061).
If the attribut `UnusedAccountValidityDays`  is deleted from `description_kwargs['AdminCreateUserConfig']` (the attributs for the `update_user_pool` function) the update works good. 
It's a bit rude to resolve the problem but I didn't found a better fix for the moment.

## Steps to Reproduce

1. Create a cognito pool
2. Configure the event trigger as said in the zappa readme
3. Make a zappa update

## Your Environment
Test with : 

* Zappa version used: 0.48.2 
* Operating System and Python version: Windows 10 and python 3.7.3 
* The output of `pip freeze`: 
```
argcomplete==1.9.3
boto3==1.9.152
botocore==1.12.152
certifi==2019.3.9
cfn-flip==1.2.0
chardet==3.0.4
Click==7.0
clickclick==1.2.2
connexion==2.2.0
docutils==0.14
durationpy==0.5
Flask==1.0.3
future==0.16.0
hjson==3.0.1
idna==2.8
inflection==0.3.1
itsdangerous==1.1.0
Jinja2==2.10.1
jmespath==0.9.3
jsonschema==2.6.0
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==1.1.1
openapi-spec-validator==0.2.7
placebo==0.9.0
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.13
requests==2.22.0
s3transfer==0.2.0
sentry-sdk==0.8.0
six==1.12.0
SQLAlchemy==1.3.4
swagger-ui-bundle==0.0.3
text-unidecode==1.2
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.7
Unidecode==1.0.23
urllib3==1.24.3
Werkzeug==0.15.4
wsgi-request-logger==0.4.6
zappa==0.48.2
```

* Your `zappa_settings.py`: 
```
"preprod" : {
        "aws_region": "eu-central-1",
        "profile_name": "default",
        "project_name": "***",
        "runtime": "python3.7",
        "s3_bucket": "***",
        "certificate_arn": "***",
        "domain": "***",
        "api_key_required": true,
        "cloudwatch_log_level": "INFO",
        "cors": true,
        "extra_permissions": [{
            "Effect": "Allow",
            "Action": [
                "cognito-idp:*"
            ],
            "Resource": "*"
        }],
        "cognito": { 
            "user_pool": "***", 
            "triggers": [{
                "source": "PreAuthentication_Authentication", 
                "function": "my_app.pre_authentication_function"
            }]
        }
    }
```

And with : 
* Zappa version used: 0.47.1
* Operating System and Python version: Windows 10 and python 3.6
* The output of `pip freeze`: 
```
argcomplete==1.9.3
boto3==1.9.79
botocore==1.12.79
certifi==2019.3.9
cfn-flip==1.2.0
chardet==3.0.4
Click==7.0
clickclick==1.2.2
connexion==2.2.0
docutils==0.14
durationpy==0.5
Flask==1.0.3
future==0.16.0
hjson==3.0.1
idna==2.8
inflection==0.3.1
itsdangerous==1.1.0
Jinja2==2.10.1
jmespath==0.9.3
jsonschema==2.6.0
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==1.1.1
openapi-spec-validator==0.2.7
placebo==0.9.0
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.13
requests==2.22.0
s3transfer==0.1.13
sentry-sdk==0.8.0
six==1.12.0
SQLAlchemy==1.3.4
swagger-ui-bundle==0.0.3
text-unidecode==1.2
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.7
Unidecode==1.0.23
urllib3==1.24.3
Werkzeug==0.15.4
wsgi-request-logger==0.4.6
zappa==0.47.1
```

* Your `zappa_settings.py`: 
```
"preprod" : {
        "aws_region": "eu-central-1",
        "profile_name": "default",
        "project_name": "***",
        "runtime": "python3.6",
        "s3_bucket": "***",
        "certificate_arn": "***",
        "domain": "***",
        "api_key_required": true,
        "cloudwatch_log_level": "INFO",
        "cors": true,
        "extra_permissions": [{
            "Effect": "Allow",
            "Action": [
                "cognito-idp:*"
            ],
            "Resource": "*"
        }],
        "cognito": { 
            "user_pool": "***", 
            "triggers": [{
                "source": "PreAuthentication_Authentication", 
                "function": "my_app.pre_authentication_function"
            }]
        }
    }
```

**Comment by ameycu** [comment]
Thanks for the fix. I had been struggling with it for the last week.
