### ISSUE TITLE
Error when deploying API Gateway: A GET request to '/' yielded a 502 response code.

### ISSUE THREAD

**Issue by michaloslav** [Miserlou/Zappa#1897]
I'm trying to deploy to AWS for the first time using Zappa. I have a Django API running in a virtual environment I created using virtualenvwrapper.

When I ran zappa deploy and now when I run zappa update, it seems to go okay - it downloads and installs dependencies, zips the project, uploads it, uploads the Lambda code and then tries to deploy the API Gateway. That's when it fails and I get the following:
`Unscheduled chatroomserver-dev-zappa-keep-warm-handler.keep_warm_callback.
Scheduled chatroomserver-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.`

It's a super simple chat API, I pushed it here: https://github.com/michaloslav/Chatroom-Backend
(I didn't push ChatroomServer/settings.py because it includes databases access information so if you try to run it, it won't work)

Environment:
Zappa version: 0.48.2
Win 10, Python 3.7
Pip freeze output:
`argcomplete==1.9.3
astroid==2.2.5
base58==0.2.4
boto3==1.9.185
botocore==1.12.185
certifi==2019.6.16
cfn-flip==1.2.1
chardet==3.0.4
Click==7.0
colorama==0.4.1
dataclasses==0.6
Django==2.2.3
django-cors-headers==3.0.2
django-filter==2.1.0
django-mongodb-engine==0.6.0
djangorestframework==3.9.4
djongo==1.2.33
docutils==0.14
durationpy==0.5
future==0.16.0
handler==1.3.0
hjson==3.0.1
idna==2.8
isort==4.3.21
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
lazy-object-proxy==1.4.1
Markdown==3.1.1
mccabe==0.6.1
placebo==0.9.0
pylint==2.3.1
pymongo==3.8.0
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2019.1
PyYAML==5.1.1
requests==2.22.0
s3transfer==0.2.1
six==1.12.0
sqlparse==0.2.4
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.9
typed-ast==1.4.0
Unidecode==1.1.1
urllib3==1.25.3
Werkzeug==0.15.4
wrapt==1.11.2
wsgi-request-logger==0.4.6
zappa==0.48.2`

zappa_settings.json:
`{
    "dev": {
        "aws_region": "us-east-2",
        "django_settings": "ChatroomServer.settings",
        "profile_name": "default",
        "project_name": "chatroomserver",
        "runtime": "python3.7",
        "s3_bucket": "michaloslav-chatroom",
        "extra_permissions": [{
            "Effect": "Allow",
            "Action": ["rekognition:*"],
            "Resource": "*"
        }]
    }
}`

I already saw some people having similar issues and there seem to be 2 potential solutions:
1) Running zappa tail and installing any missing dependencies. I tried that and got the following:
`1562750236050] [ERROR] Runtime.ImportModuleError: Unable to import module 'handler': No module named 'werkzeug
[1562753064340] [ERROR] Runtime.HandlerNotFound: Handler 'lambda_handler' missing on module 'handler'`
(both of these occured multiple times and there was also some other stuff but it doesn't seem relevant)

So I pip installed handler, tried upgrading werkzeug which was already up to date and tried installing lambda_handler which doesn't exist. I tried zappa update again after that and still got the same result
2) Downgrading Zappa to 0.45.1. I tried that but it doesn't support Python 3.7. If necessary, I could downgrade to Python 3.6, the code should still work. I'm not really sure how that would work though and there should be a way to get it to work without downgrading.

**Comment by fbidu** [comment]
I think the problem is related with `TQDM` (https://github.com/tqdm/tqdm/issues/466). I'm not sure _why_ it started happening now, since Zappa's usage of this version of TQDM [goes back two years](https://github.com/Miserlou/Zappa/commit/4903a7dde9ac078cdde93a30cf2eb25313dc68b4).

Either way, if you force TQDM version to be `>= 4.32.2`, it works. Your dependency manager probably will complain but it worked with me. I'm using `pipenv`, by the way.

**Comment by fbidu** [comment]
In my case, Google's Bigquery crashed before Zappa but for the same reason. The full log, for debugging purposes is:

```
[Errno 38] Function not implemented: OSError
Traceback (most recent call last):
File "/var/task/handler.py", line 602, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 245, in lambda_handler
handler = cls()
File "/var/task/handler.py", line 139, in __init__
self.app_module = importlib.import_module(self.settings.APP_MODULE)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/var/task/mobex/zappa.py", line 4, in <module>
from .application import create_app
File "/var/task/mobex/application.py", line 18, in <module>
from .routes import mobex_routes
File "/var/task/mobex/routes.py", line 11, in <module>
from .exporter import AdjustExporter, Exporter, BigQueryExportingError
File "/var/task/mobex/exporter.py", line 7, in <module>
from google.cloud import bigquery
File "/var/task/google/cloud/bigquery/__init__.py", line 35, in <module>
from google.cloud.bigquery.client import Client
File "/var/task/google/cloud/bigquery/client.py", line 53, in <module>
from google.cloud.bigquery.dataset import Dataset
File "/var/task/google/cloud/bigquery/dataset.py", line 26, in <module>
from google.cloud.bigquery.table import TableReference
File "/var/task/google/cloud/bigquery/table.py", line 37, in <module>
import tqdm
File "/var/task/tqdm/__init__.py", line 1, in <module>
from ._tqdm import tqdm
File "/var/task/tqdm/_tqdm.py", line 53, in <module>
mp_lock = mp.Lock() # multiprocessing lock
File "/var/lang/lib/python3.6/multiprocessing/context.py", line 67, in Lock
return Lock(ctx=self.get_context())
File "/var/lang/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
File "/var/lang/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
unlink_now)
OSError: [Errno 38] Function not implemented
```

**Comment by michaloslav** [comment]
@fbidu Thanks for the idea. I tried it and then ran zappa update again but still got the same error message. Anyone got any other ideas? Is there some AWS-side config I missed?

Or maybe I could try to downgrade Python within the virtualenv, if that's even how that works. If anyone knows how to do that, maybe that could be a work around

**Comment by fbidu** [comment]
> @fbidu Thanks for the idea. I tried it and then ran zappa update again but still got the same error message. Anyone got any other ideas? Is there some AWS-side config I missed?
> 
> Or maybe I could try to downgrade Python within the virtualenv, if that's even how that works. If anyone knows how to do that, maybe that could be a work around

Huh, that's weird... Can you see the full log in your AWS CloudWatch?

**Comment by michaloslav** [comment]
Sorry about the late reply. The logs are basically these lines all over again and again.

`START RequestId: 41f30055-88aa-4be2-af60-eaa13b5ef45d Version: $LATEST`

`[ERROR] Runtime.HandlerNotFound: Handler 'lambda_handler' missing on module 'handler'`

`END RequestId: 41f30055-88aa-4be2-af60-eaa13b5ef45d`

`REPORT RequestId: 41f30055-88aa-4be2-af60-eaa13b5ef45d	Duration: 1.47 ms	Billed Duration: 100 ms Memory Size: 512 MB	Max Memory Used: 53 MB	`

(The RequestId changes with every request)

It really looks like the lambda_handler thing might be the problem but I have no idea how to fix that. I already installed handler and it's up to date

**Comment by daleosm** [comment]
I have the same error also

**Comment by daleosm** [comment]
I'm getting the same error in CloudWatch and "zappa tail"

`[ERROR] Runtime.ImportModuleError: Unable to import module 'handler': No module named 'werkzeug'`

**Comment by daleosm** [comment]
Version 0.45.1 will work under Python 3.6.1

**Comment by zkhudson** [comment]
I was getting the same issue, and I was running an older version of Zappa, so I updated Zappa to the latest version. After updating, it's been working. If you are running the latest version you might try downgrading, then upgrading. Sometimes the installation process "fixes" things.

**Comment by pawellesniewski** [comment]
```
[~/env>> virtualenv-3.7 zappa
[~/env>> cd zappa/
[~/env/zappa>> source bin/activate
(zappa) [~/env/zappa>> pip install django zappa
(zappa) [~/env/zappa>> mkdir uploader
(zappa) [~/env/zappa>> cd uploader/
(zappa) [~/env/zappa/uploader>> django-admin startproject uploader .
(zappa) [~/env/zappa/uploader>> zappa init

{
    "dev": {
        "aws_region": "eu-central-1",
        "django_settings": "uploader.settings",
        "profile_name": "xxxx",
        "project_name": "uploader",
        "runtime": "python3.7",
        "s3_bucket": "zappa-xxxx"
    }
}

(zappa) [~/env/zappa/uploader>> zappa deploy
Calling deploy for stage dev..
Downloading and installing dependencies..
 - sqlite==python3: Using precompiled lambda package
'python3.7'
Packaging project as zip.
Uploading uploader-dev-1567076262.zip (14.8MiB)..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15.5M/15.5M [00:08<00:00, 1.90MB/s]
Scheduling..
Scheduled uploader-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Uploading uploader-dev-template-1567076299.json (1.6KiB)..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.62K/1.62K [00:00<00:00, 19.7KB/s]
Waiting for stack uploader-dev to create (this can take a bit)..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:09<00:00,  2.40s/res]
Deploying API Gateway..
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.
```

```
[~>> curl https://xxxx.execute-api.eu-central-1.amazonaws.com/dev
"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 531, in handler\\n    with Response.from_app(self.wsgi_app, environ) as response:\\n', '  File \"/var/task/werkzeug/wrappers/base_response.py\", line 287, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/test.py\", line 1119, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"
```

```
argcomplete==1.9.3
boto3==1.9.218
botocore==1.12.218
certifi==2019.6.16
cfn-flip==1.2.1
chardet==3.0.4
Click==7.0
Django==2.2.4
docutils==0.15.2
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.8
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
placebo==0.9.0
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2019.2
PyYAML==5.1.2
requests==2.22.0
s3transfer==0.2.1
six==1.12.0
sqlparse==0.3.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.5.1
Unidecode==1.1.1
urllib3==1.25.3
Werkzeug==0.15.5
wsgi-request-logger==0.4.6
zappa==0.48.2
```

What is wrong? Thanks in advance for your help :)

**Comment by daleosm** [comment]
The output of zappa tail is needed to help solve the problem.

**Comment by elcolie** [comment]
@michaloslav Your runtime must be `3.6`. `3.7` will works only if you are running GNU/Linux based OS. I guess you are running an OSX as mine.

**Comment by mpeteuil** [comment]
✅ I had a similar issue that using `tqdm` 4.32.2 and Python 3.7 from a [Linux OS](https://romandc.com/zappa-django-guide/setup/#approach-2-docker-with-zappa-recommended) instead of MacOS/OS X solved for me.

**Comment by mantlecurve** [comment]
I had the issue, with tail showing `OSError: [Errno 38] Function not implemented` . Updating `tqdm `to `4.32.2` solved the issue

**Comment by evan-rosa** [comment]
Running into the same issue (i.e. "Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code."). I ran zappa tail and got this error message. Not sure how to proceed.

[1581013830765] [DEBUG] 2020-02-06T18:30:30.765Z 7bfa4009-be95-4208-9194-ac654ef50a80 Event needs-retry.s3.GetObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f82c591ec90>>

**Comment by paulmacie** [comment]
having same problem any fix 
Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd c:\users\paul\desktop\project

c:\Users\paul\Desktop\project>env\scripts\activate.bat

c:\Users\paul\Desktop\project>venv
'venv' is not recognized as an internal or external command,
operable program or batch file.

c:\Users\paul\Desktop\project>zappa deploy dev
Calling deploy for stage dev..
Error: This application is already deployed - did you mean to call update?

c:\Users\paul\Desktop\project>zappa update dev
Calling update for stage dev..
Downloading and installing dependencies..
 - markupsafe==1.1.1: Using locally cached manylinux wheel
 - cryptography==2.1.4: Using locally cached manylinux wheel
 - cffi==1.14.0: Using locally cached manylinux wheel
Packaging project as zip.


Warning: Application zip package is likely to be too large for AWS Lambda. Try setting "slim_handler" to true in your Zappa settings file.


Uploading project-dev-1582597588.zip (80.4MiB)..
100%|█████████████████████████████████████████████████████████████████████████████| 84.3M/84.3M [00:29<00:00, 2.82MB/s]
Updating Lambda function code..
Updating Lambda function configuration..
Uploading project-dev-template-1582597977.json (1.6KiB)..
100%|█████████████████████████████████████████████████████████████████████████████| 1.60k/1.60k [00:00<00:00, 11.4kB/s]
Deploying API Gateway..
Scheduling..
Unscheduled project-dev-zappa-keep-warm-handler.keep_warm_callback.
Scheduled project-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.

c:\Users\paul\Desktop\project>

**Comment by xg1990** [comment]
It seems that the package 
[[handler]](https://pypi.org/project/handler/)
is confusing zappa, 

This error message disappears after running 
```bash 
pip uninstall handler
```

**Comment by sagun786** [comment]
> It seems that the package
> [[handler]](https://pypi.org/project/handler/)
> is confusing zappa,
> 
> This error message disappears after running
> 
> ```shell
> pip uninstall handler
> ```

handler is not event present in the venv, I checked the requirements file, (didn't find it, still ran it out of desperation to deploy). Still no relief

WARNING: Skipping handler as it is not installed.
My Error Breakpoint for reference:
Deploying API Gateway..
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 500 response code.

**Comment by sagun786** [comment]
I also found this interesting comment 

[Comment](https://github.com/Miserlou/Zappa/issues/1985#issuecomment-609642775)
The main issue is that there are indeed precompiled libraries we use - mainly psycopg2.
This one is not working in Lambda - hence you should include instead aws-psycopg2.

**Comment by xg1990** [comment]
> > It seems that the package
> > [[handler]](https://pypi.org/project/handler/)
> > is confusing zappa,
> > This error message disappears after running
> > ```shell
> > pip uninstall handler
> > ```
> 
> handler is not event present in the venv, I checked the requirements file, (didn't find it, still ran it out of desperation to deploy). Still no relief
> 
> ```
> WARNING: Skipping handler as it is not installed.
> ```
> 
> My Error Breakpoint for reference:
> 
> ```
> Calling deploy for stage dev..
> Downloading and installing dependencies..
>  - typed-ast==1.4.1: Downloading
> 100%|████████████████████████████████████████████████████████████████████████████████| 738k/738k [00:00<00:00, 2.43MB/s]
>  - markupsafe==1.1.1: Downloading
> 100%|██████████████████████████████████████████████████████████████████████████████| 27.5k/27.5k [00:00<00:00, 1.83MB/s]
>  - lazy-object-proxy==1.4.3: Downloading
> 100%|██████████████████████████████████████████████████████████████████████████████| 56.5k/56.5k [00:00<00:00, 1.78MB/s]
> Packaging project as zip.
> Uploading capp-dev-1587298017.zip (11.5MiB)..
> 100%|███████████████████████████████████████████████████████████████████████████████| 12.0M/12.0M [00:36<00:00, 329kB/s]
> Scheduling..
> Scheduled capp-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
> Uploading capp-dev-template-1587298074.json (1.6KiB)..
> 100%|██████████████████████████████████████████████████████████████████████████████| 1.59k/1.59k [00:00<00:00, 1.72kB/s]
> Waiting for stack capp-dev to create (this can take a bit)..
>  75%|███████████████████████████████████████████████████████████████                     | 3/4 [00:13<00:04,  4.57s/res]
> Deploying API Gateway..
> Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 500 response code.
> ```

This is a very general error message:
> A GET request to '/' yielded a 500 response code.

You need to run `zappa tail` to check its details. Uninstalling `handler` package can resolve this error:
> Runtime.HandlerNotFound: Handler 'lambda_handler' missing on module 'handler'

**Comment by paulmacie** [comment]
Thank you i will try this

**Comment by Ronster2018** [comment]
Hello everyone,

I am working with a Django application and I wanted to state that I am having a similar issue here. 
```Deploying API Gateway..
Scheduling..
Unscheduled testproject-dev-zappa-keep-warm-handler.keep_warm_callback.
Scheduled testproject-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.
```

 I also checked the tail output and it returns the following error below:
 
```[1587877984524] [DEBUG] 2020-04-26T05:13:04.524Z 7e5760cb-1904-4df8-b9bf-a7a9f3472d4d host found: [lhxnmvwm5b.execute-api.us-east-1.amazonaws.com]
[1587877984524] [DEBUG] 2020-04-26T05:13:04.524Z 7e5760cb-1904-4df8-b9bf-a7a9f3472d4d amazonaws found in host
[1587877984524] 'NoneType' object is not callable
```
My Zappa_settings.json isnt anything too fancy. It is located in the same dir as my manage.py and the django_settings points to the settings file. I did noticed that the project was a bit large so I added the slim_handler option so that the uploaded package would be smaller.
```json
{
    "dev": {
        "aws_region": "us-east-1",
        "django_settings": "testproject.settings",
        "profile_name": "default",
        "project_name": "testproject",
        "runtime": "python3.7",
        "s3_bucket": "zappa-5jlzblfqz",
        "slim_handler": "true"
    }
}
```

I am working within a virtual environment called "env-test" within a docker container so it is as isolated as it gets. I am running it on Ubuntu. My requirements are as follows:
```txt
Package                 Version  
----------------------- ---------
argcomplete             1.11.1   
asgiref                 3.2.7    
astroid                 2.3.3    
boto3                   1.12.46  
botocore                1.15.46  
certifi                 2019.6.16
cfn-flip                1.2.3    
chardet                 3.0.4    
click                   7.1.1    
decorator               4.4.0    
defusedxml              0.6.0    
Django                  3.0.5    
django-allauth          0.41.0   
django-cleanup          4.0.0      
django-cors-headers     3.2.1    
django-js-asset         1.2.2    
django-model-utils      3.2.0    
django-rest-auth        0.9.5    
django-vote             2.1.7    
djangorestframework     3.11.0   
docutils                0.16     
durationpy              0.5      
future                  0.18.2   
gunicorn                20.0.4   
hjson                   3.0.1    
humanize                0.5.1    
idna                    2.8      
importlib-metadata      1.6.0    
isort                   4.3.21   
jmespath                0.9.5    
kappa                   0.6.0    
lazy-object-proxy       1.4.3    
libcnml                 0.9.5    
mccabe                  0.6.1    
oauthlib                3.1.0    
pip                     20.0.2   
pip-tools               5.0.0    
placebo                 0.9.0    
psycopg2-binary         2.8.4    
pylint                  2.4.4    
python-akismet          0.4.1    
python-dateutil         2.8.0    
python-slugify          4.0.0    
python3-openid          3.1.0    
pytz                    2019.1   
PyYAML                  5.3.1    
requests                2.22.0   
requests-oauthlib       1.3.0    
s3transfer              0.3.3    
setuptools              46.1.3   
six                     1.12.0   
sqlparse                0.3.0    
text-unidecode          1.3      
toml                    0.10.0   
tqdm                    4.45.0   
troposphere             2.6.0    
typed-ast               1.4.0    
urllib3                 1.25.3   
Werkzeug                0.16.1   
wheel                   0.34.2   
wrapt                   1.11.2   
wsgi-request-logger     0.4.6    
zappa                   0.51.0   
zipp                    3.1.0 
```

And finally when I navigate to the url provided by zappa status, I receive the following error:
```json
"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 540, in handler\\n    with Response.from_app(self.wsgi_app, environ) as response:\\n', '  File \"/var/task/werkzeug/wrappers/base_response.py\", line 287, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/wrappers/base_response.py\", line 26, in _run_wsgi_app\\n    return _run_wsgi_app(*args)\\n', '  File \"/var/task/werkzeug/test.py\", line 1119, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"
```

While tinkering with the project, I did see a package error when using zappa update:
```bash
ERROR: zappa 0.51.0 has requirement python-dateutil<2.7.0, but you'll have python-dateutil 2.8.0 which is incompatible.
ERROR: botocore 1.15.46 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
```
But after changing even those dependencies, the result was the same. Any help would be appreciated!

**Comment by elcolie** [comment]
@Ronster2018 Try `pip-tools` and use `pip-compile` to make your `requirements.txt`

**Comment by Ronster2018** [comment]
@elcolie Thanks for your recommendation, but that did not work. I had the same outcome. I had the same outcome. I am going to try to just start a very basic Django application and try it from there. Hopefully the deployment works and I will be able to build on top of that.

**Comment by Ronster2018** [comment]
After investigating the tail output, I noticed that an exception was being raised. It was relating to the sqlite version that I had installed. The exception that was thrown was early on and it looks like this is what was causing my issue. After implementing the fix, Zappa began to work for me! The work around can be found [here](https://github.com/Miserlou/Zappa/issues/1880#issuecomment-606710104) under a different issue for this project.

I hope this helps!
