### ISSUE TITLE
Error when Zappa Deploy 

### ISSUE THREAD

**Issue by taegsu** [Miserlou/Zappa#1901]
## Actual Behavior
Traceback (most recent call last):
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/core.py", line 924, in upload_to_s3
    self.s3_client.head_bucket(Bucket=bucket_name)
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/cli.py", line 2779, in handle
    sys.exit(cli.handle())
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/cli.py", line 509, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/cli.py", line 546, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/cli.py", line 723, in deploy
    self.zip_path, self.s3_bucket_name, disable_progress=self.disable_progress)
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/core.py", line 936, in upload_to_s3
    CreateBucketConfiguration={'LocationConstraint': self.aws_region},
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: lasted version
* Operating System and Python version: MAC OS, Python3.7
* Your `zappa_settings.py`: {
    "dev": {
        "django_settings": "myproject.settings",
        "profile_name": "default",
	    "aws_region" : "ap-northeast-1",
	    "manage_roles" : false,
	    "role_name" : "my_arn_role_name",
	    "role_arn" : "my_role_arn_address",
        "project_name": "aws-django-board",
        "runtime": "python3.7",
        "s3_bucket": "lambda"
    }
}

**Comment by mikenotfound** [comment]
It looks like you'll have to choose a unique bucket name as I'm pretty certain `lambda` is already taken.

> Bucket names must be unique across all existing bucket names in Amazon S3
https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
