### ISSUE TITLE
S3 resource does not exist causing module not found

### ISSUE THREAD

**Issue by themmes** [Miserlou/Zappa#1917]
## Context

I do not understand why I am getting the following error. It seems the lambda cannot be loaded from S3 and therefore is not able to find the module to execute the function.

```
[1565266143895] [DEBUG] 2019-08-08T12:09:03.895Z ef9eb08e-f4f9-43a5-9072-c11f15be1b80 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
[1565266143897] The 's3' resource does not exist.
The available resources are:
 -
: ResourceNotExistsError
Traceback (most recent call last):
  File "/var/task/handler.py", line 602, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 245, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 102, in __init__
  self.load_remote_project_archive(project_archive_path)
  File "/var/task/handler.py", line 170, in load_remote_project_archive
  s3 = boto_session.resource('s3')
  File "/var/task/boto3/session.py", line 347, in resource
  has_low_level_client)
boto3.exceptions.ResourceNotExistsError: The 's3' resource does not exist.
The available resources are:
 -
[1565266201109] [DEBUG] 2019-08-08T12:10:01.109Z ef9eb08e-f4f9-43a5-9072-c11f15be1b80 Zappa Event: {'Records': [{'eventVersion': '2.1', 'eventSource': 'aws:s3', 'awsRegion': 'eu-central-1', 'eventTime': '2019-08-08T12:09:00.157Z', 'eventName': 'ObjectCreated:Put', 'userIdentity': {'principalId': 'AWS:AIDAY5TJ3FA44X4WWYBA7'}, 'requestParameters': {'sourceIPAddress': '213.127.67.154'}, 'responseElements': {'x-amz-request-id': 'B35B73FF4F75D59E', 'x-amz-id-2': 'ELkqeB94Gb17TPF12ffhVtASmEhtR7NlQO4DevDruHvA5I5DrFlln/oYPSJkDx9RO/D7MMxERKE='}, 's3': {'s3SchemaVersion': '1.0', 'configurationId': 'function-dev:sample.lambda_handler', 'bucket': {'name': 'test-function', 'ownerIdentity': {'principalId': 'A3V2HVB9FLXO6B'}, 'arn': 'arn:aws:s3:::test-function'}, 'object': {'key': 'test_5.pts.gz', 'size': 7924, 'eTag': '3b39cf26af0e2aa49b917a2771bcc068', 'sequencer': '005D4C10DC203B4EB2'}}}]}
[1565266201111] No module named 'sample': ModuleNotFoundError
Traceback (most recent call last):
  File "/var/task/handler.py", line 602, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 248, in lambda_handler
  return handler.handler(event, context)
  File "/var/task/handler.py", line 423, in handler
  app_function = self.import_module_and_get_function(whole_function)
  File "/var/task/handler.py", line 239, in import_module_and_get_function
  app_module = importlib.import_module(module)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sample'
```

- I verified the tar.gz is in the correct `bucket-zappa` bucket on S3
- The Zappa LambdaRole is correctly created and has access to S3

## Expected Behavior

I expected the application to be found on S3 and the specific module.function to be ran upon the event.

## Actual Behavior

It seems the package cannot be found on S3 and when the S3 event comes in Lambda is not able to find the correct module.function to run

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: 0.48.2
* Operating System and Python version: Xenial 16.04 python3.6
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`: 

```
{
    "dev": {
        "project_name": "test",
        "runtime": "python3.6",
        "exclude": ["env","tests","data","output","notebooks", "launch.sh"],
        "s3_bucket": "bucket-zappa",
        "slim_handler": true,
        "aws_region": "eu-central-1",
        "events": [{
            "function": "sample.lambda_handler",
            "event_source": {
                "arn":  "arn:aws:s3:::test-function",
                "events": ["s3:ObjectCreated:*"]
            }
        }],
        "keep_warm": false,
        "apigateway_enabled": false
    }
}
```

**Comment by themmes** [comment]
Hmm.. I believe my issue might be related to this https://github.com/Miserlou/Zappa/issues/1271#issuecomment-484359007

**Comment by themmes** [comment]
I believe I found the issue which is similar to this https://github.com/Miserlou/Zappa/issues/1579

The items listed in `"exclude": ["env","tests","data","output","notebooks", "launch.sh"],` are not only excluded for my own code, but apparently for everything that should end up in the final zip package.
