### ISSUE TITLE
IsADirectoryError

### ISSUE THREAD

**Issue by elcolie** [Miserlou/Zappa#1922]
## Context

I am unable to deploy my Django 2 with Python 3.7.3. I put all variable into the source code then
with `slim handler` is `false` I got 
```bash
Traceback (most recent call last):
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/cli.py", line 748, in deploy
    function_name=self.lambda_name)
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/core.py", line 1287, in get_lambda_function
    FunctionName=function_name)
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetFunction operation: Function not found: arn:aws:lambda:ap-southeast-1:530403937392:function:futuready-th-li-sarit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/cli.py", line 2779, in handle
    sys.exit(cli.handle())
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/cli.py", line 509, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/cli.py", line 546, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/cli.py", line 779, in deploy
    self.lambda_arn = self.zappa.create_lambda_function(**kwargs)
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/core.py", line 1089, in create_lambda_function
    response = self.lambda_client.create_function(**kwargs)
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Unzipped size must be smaller than 262144000 bytes
```

`slim handler` is `true`. I got
```bash
$ zappa deploy sarit
Calling deploy for stage sarit..
Downloading and installing dependencies..
 - typed-ast==1.4.0: Using locally cached manylinux wheel
 - psycopg2-binary==2.8.3: Using locally cached manylinux wheel
 - pillow==6.1.0: Using locally cached manylinux wheel
 - mypy==0.720: Using locally cached manylinux wheel
 - markupsafe==1.1.1: Using locally cached manylinux wheel
 - lazy-object-proxy==1.4.2: Using locally cached manylinux wheel
 - coverage==4.5.4: Using locally cached manylinux wheel
 - cffi==1.12.3: Using locally cached manylinux wheel
 - sqlite==python3: Using precompiled lambda package
'python3.7'
Packaging project as gzipped tarball.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/durationpy already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/python_dateutil-2.6.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/troposphere-2.5.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/chardet-3.0.4.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/toml already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/chardet already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/placebo-0.9.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/pip-19.2.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/Unidecode-1.1.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/easy_install.py already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/s3transfer already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/cfn_flip-1.2.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/docutils already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/wsgi_request_logger-0.4.6.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/past already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/lambda_packages-0.20.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/unidecode already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/placebo already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/argcomplete already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/Click-7.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/cfn_flip already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/troposphere already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/PyYAML-5.1.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/idna already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/werkzeug already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/wheel already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/click already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/slugify already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/lambda_packages already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/cfn_clean already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/certifi-2019.6.16.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/future-0.16.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/botocore already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/requests already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/pip already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/argcomplete-1.9.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/docutils-0.15.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/certifi already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/zappa already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/wheel-0.33.6.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/idna-2.8.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/boto3-1.9.215.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/tqdm already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/six.py already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/toml-0.10.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/durationpy-0.5.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/kappa already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/urllib3-1.25.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/yaml already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/tqdm-4.19.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/jmespath already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/six-1.12.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/kappa-0.6.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/urllib3 already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/Werkzeug-0.15.5.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/setuptools already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/pkg_resources already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/zappa-0.48.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/hjson already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/requests-2.22.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/python_slugify-1.2.4.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/requestlogger already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/libfuturize already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/s3transfer-0.2.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/future already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/botocore-1.12.215.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/libpasteurize already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/jmespath-0.9.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/dateutil already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/toml.py already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/hjson-3.0.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/setuptools-41.2.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/cfn_tools already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/boto3 already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/man already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/bin already exists. Specify --upgrade to force replacement.
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/cli.py", line 2779, in handle
    sys.exit(cli.handle())
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/cli.py", line 509, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/cli.py", line 546, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/cli.py", line 718, in deploy
    self.create_package()
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/cli.py", line 2230, in create_package
    disable_progress=self.disable_progress
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/core.py", line 627, in create_lambda_zip
    self.copy_editable_packages(egg_links, temp_package_path)
  File "/Users/sarit/.pyenv/versions/3.7.3/envs/life/lib/python3.7/site-packages/zappa/core.py", line 362, in copy_editable_packages
    with open(egg_link, 'rb') as df:
IsADirectoryError: [Errno 21] Is a directory: '/Users/sarit/mein-codes/futuready_th_life_insurance/handler_venv/lib/python3.7/site-packages/zappa.egg-link'

==============
```

## Expected Behavior

`zappa` must replace all the package and be able to deploy the Django Application

## Actual Behavior

It raises an error and stop the deployment

## Possible Fix

No idea

## Steps to Reproduce

1. Django2 Python3.7.3 install through `pyenv`
2. `zappa deploy`
3. Put all configuration into `settings.py` file

## Your Environment

* Zappa version used: `0.48.2`
* Operating System and Python version: `10.14.5`, `Python3.7.3`
* The output of `pip freeze`:
```bash
alabaster==0.7.12
appdirs==1.4.3
appnope==0.1.0
argcomplete==1.9.3
argon2-cffi==19.1.0
asn1crypto==0.24.0
astroid==2.2.5
atomicwrites==1.3.0
attrs==19.1.0
autoflake==1.3.1
Babel==2.7.0
backcall==0.1.0
backports.csv==1.0.7
black==19.3b0
boto3==1.9.215
botocore==1.12.215
certifi==2019.6.16
cffi==1.12.3
cfn-flip==1.2.1
chardet==3.0.4
Click==7.0
Collectfast==1.0.0
coreapi==2.3.3
coreschema==0.0.4
coverage==4.5.4
cryptography==2.7
decorator==4.4.0
defusedxml==0.6.0
diff-match-patch==20181111
Django==2.2.4
django-allauth==0.39.1
django-anymail==6.1.0
django-coverage-plugin==1.6.0
django-crispy-forms==1.7.2
django-debug-toolbar==2.0
django-environ==0.4.5
django-extensions==2.2.1
django-filter==2.2.0
django-import-export==1.2.0
django-model-utils==3.2.0
django-modeltranslation==0.13.3
django-money==0.15
django-redis==4.10.0
django-storages==1.7.1
djangorestframework==3.10.2
djangorestframework-simplejwt==4.3.0
docutils==0.15.2
durationpy==0.5
entrypoints==0.3
et-xmlfile==1.0.1
factory-boy==2.12.0
Faker==2.0.1
flake8==3.7.8
future==0.16.0
gunicorn==19.9.0
hjson==3.0.1
idna==2.8
imagesize==1.1.0
importlib-metadata==0.19
ipdb==0.12.2
ipython==7.7.0
ipython-genutils==0.2.0
isort==4.3.21
itypes==1.1.0
jdcal==1.4.1
jedi==0.15.1
Jinja2==2.10.1
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
lazy-object-proxy==1.4.2
MarkupSafe==1.1.1
mccabe==0.6.1
model-mommy==1.6.0
more-itertools==7.2.0
mypy==0.720
mypy-extensions==0.4.1
oauthlib==3.1.0
odfpy==1.4.0
openpyxl==2.6.3
packaging==19.1
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
pip-tools==4.1.0
placebo==0.9.0
pluggy==0.12.0
prompt-toolkit==2.0.9
psycopg2==2.8.3
psycopg2-binary==2.8.3
ptyprocess==0.6.0
py==1.8.0
py-moneyed==0.8.0
pycodestyle==2.5.0
pycparser==2.19
pyflakes==2.1.1
Pygments==2.4.2
PyJWT==1.7.1
pylint==2.3.1
pylint-django==2.0.11
pylint-plugin-utils==0.5
pyOpenSSL==19.0.0
pyparsing==2.4.2
pytest==5.1.1
pytest-django==3.5.1
pytest-sugar==0.9.2
python-dateutil==2.6.1
python-slugify==1.2.4
python3-openid==3.1.0
pytz==2019.2
PyYAML==5.1.2
redis==3.3.8
requests==2.22.0
requests-oauthlib==1.2.0
s3transfer==0.2.1
sentry-sdk==0.11.1
six==1.12.0
snowballstemmer==1.9.0
Sphinx==2.2.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sqlparse==0.3.0
tablib==0.13.0
termcolor==1.1.0
text-unidecode==1.2
toml==0.10.0
tqdm==4.19.1
traitlets==4.3.2
troposphere==2.5.1
typed-ast==1.4.0
typing==3.7.4.1
typing-extensions==3.7.4
Unidecode==1.1.1
uritemplate==3.0.0
urllib3==1.25.3
wcwidth==0.1.7
Werkzeug==0.15.5
wrapt==1.11.2
wsgi-request-logger==0.4.6
xlrd==1.2.0
xlwt==1.3.0
yapf==0.28.0
zappa==0.48.2
zipp==0.6.0
```
* Link to your project (optional):
* Your `zappa_settings.py`: 
I don't use this
* `zappa_settings.json`
```bash
    "sarit": {
        "profile_name": "xxx-dev",
        "project_name": "yyyy-th-li",
        "runtime": "python3.7",
        "s3_bucket": "futh-life-zappa-dev-sarit",
        "aws_region": "ap-southeast-1",
        "slim_handler": true,
        "django_settings": "dev",
        "memory_size": 3008,
    }
```

**Comment by elcolie** [comment]
* Attempts
1. Remove `.env and .env.dev`
2. Remove `handler_venv`
3. Now I got "TypeError: 'NoneType' object is not callable like this [one](https://medium.com/riow/zappa-file-var-task-handler-py-line-452-d64bd0dafc22)
