### ISSUE TITLE
Zappa deployment does not work if the virtualenv name is the same as the app name

### ISSUE THREAD

**Issue by piraka9011** [Miserlou/Zappa#1938]
## Context

When running Zappa in a virtualenv, I found that if the name of your Django app and the name of your virtualenv are the same, then you will get a 
```
ModuleNotFoundError: No module named '<app-name>'
```
when deploying your app.

## Expected Behavior

Zappa should deploy normally. e.g.
```
Your updated Zappa deployment is live!: https://api.com (https://...api.us-west-2.amazonaws.com/dev)
```

## Actual Behavior

Zappa logs return:
```
[1570156390363] Instancing..
[1570156392032] No module named '<app>': ModuleNotFoundError
Traceback (most recent call last):
  File "/var/task/handler.py", line 580, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 245, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 151, in __init__
  wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)
  File "/var/task/zappa/ext/django_zappa.py", line 20, in get_django_wsgi
  return get_wsgi_application()
  File "/var/task/django/core/wsgi.py", line 12, in get_wsgi_application
  django.setup(set_prefix=False)
  File "/var/task/django/__init__.py", line 19, in setup
  configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/var/task/django/conf/__init__.py", line 79, in __getattr__
  self._setup(name)
  File "/var/task/django/conf/__init__.py", line 66, in _setup
  self._wrapped = Settings(settings_module)
  File "/var/task/django/conf/__init__.py", line 157, in __init__
  mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '<app>'
```
and the 
```
zappa deploy <stage>`
```
command returns
```
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 500 response code.
```

## Possible Fix

I'm unsure, but if someone could point me in the right direction I can take a look.

## Steps to Reproduce

(Assuming you are using virtualenvwrapper)

1. `mkvirtualenv <app> `
2. Name the directory of your main Django app (where the `settings.py` and `urls.py` live) '<app>'.
3. `zappa deploy/update <stage>`

## Your Environment

* Zappa version used: 0.47.0
* Operating System and Python version: Ubuntu 18.04, Python 3.6
* The output of `pip freeze`:
```
awscli==1.16.152
boto3==1.9.152
djangorestframework==3.10.3
django==2.2.5
django-allauth==0.38.0
django-cors-headers==3.1.0
django-extensions==2.1.6
django-filter==2.1.0
django-ranged-fileresponse==0.1.2
django-rest-auth==0.9.5
django-storages==1.7.1
django-environ==0.4.5
future==0.16.0
gunicorn==19.9.0
jmespath==0.9.3
pinax-badges==2.0.0
psycopg2-binary==2.8.2
python-dateutil==2.6.1
sentry-sdk==0.11.2
whoosh==2.7.4
zappa==0.47.0
```
* Link to your project (optional):
* Your `zappa_settings.py`:  Can't display.

**Comment by dpretty** [comment]
@piraka9011 I don't think this is a problem, as this is addressed explicitly at the start of the README file: https://github.com/Miserlou/Zappa/blob/master/README.md#installation-and-configuration

> The virtual environment name should not be the same as the Zappa project name, as this may cause errors.

**Comment by piraka9011** [comment]
Ahh I see, I think I missed that during my pass of the README. I though it was mentioned in an issue somewhere...

Thanks!
