### ISSUE TITLE
Issue while deploying Django project

### ISSUE THREAD

**Issue by CapturedCarbon** [Miserlou/Zappa#1943]
Fails while deploy a django project

## Expected Behavior
Deployment complete!:

## Actual Behavior
Packaging project as gzipped tarball.
ERROR: To modify pip, please run the following command:
C:\Users\Philip\newenv\Scripts\python.exe -m pip install --quiet --target C:\Users\Philip\PycharmProjects\CCL_ADMINISTRATION\handler_venv\Lib\site-packages chardet==3.0.4 wheel==0.33.6 six==1.11.0 Werkzeug==0.16.0 Click==7.0 python-dateutil==2.6.1 toml==0.10.0
certifi==2018.4.16 idna==2.7 kappa==0.6.0 requests==2.20.1 placebo==0.9.0 lambda-packages==0.20.0 jmespath==0.9.3 urllib3==1.24.3 botocore==1.12.215 wsgi-request-logger==0.4.6 cfn-flip==1.2.1 docutils==0.15.2 durationpy==0.5 python-slugify==1.2.4 pip==19.3 s3tr
ansfer==0.2.1 boto3==1.9.215 future==0.16.0 troposphere==2.5.2 hjson==3.0.1 argcomplete==1.9.3 zappa==0.48.2 tqdm==4.19.1 PyYAML==5.1.2 Unidecode==1.1.1 setuptools
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "c:\users\philip\newenv\lib\site-packages\zappa\cli.py", line 2779, in handle
    sys.exit(cli.handle())
  File "c:\users\philip\newenv\lib\site-packages\zappa\cli.py", line 509, in handle
    self.dispatch_command(self.command, stage)
  File "c:\users\philip\newenv\lib\site-packages\zappa\cli.py", line 546, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "c:\users\philip\newenv\lib\site-packages\zappa\cli.py", line 718, in deploy
    self.create_package()
  File "c:\users\philip\newenv\lib\site-packages\zappa\cli.py", line 2225, in create_package
    venv=self.zappa.create_handler_venv(),
  File "c:\users\philip\newenv\lib\site-packages\zappa\core.py", line 435, in create_handler_venv
    raise EnvironmentError("Pypi lookup failed")
OSError: Pypi lookup failed

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used:
* Operating System and Python version: windows : Python 3.6.4
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by prorizontal** [comment]
I have the same issue this happen when I put slim_handler to true on zappa_setting file..

**Comment by mwhug** [comment]
Having the same problem. Has anyone been able to get past this while still using slim_handler?
