### ISSUE TITLE
Can't update due Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by loscil06** [Miserlou/Zappa#1954]
When trying to update a stage (in my case, dev) just after uploading the zip a message appears saying literally the title of this issue.

I made sure I was running zappa from venv and using python 3.7 (been using it with no problems up until now)
## Expected Behavior
The workflow should go on like normal, updating the existing API

## Actual Behavior
Crashes and burns with no further explanation. 

## Steps to Reproduce
1. get into a virtual env
2. run zappa update <branch>
3. wait until it segfaults

## Your Environment

* Zappa version used: 0.48.2
* Operating System and Python version: Ubuntu 19.10 Python 3.7
* The output of `pip freeze`:
```
argcomplete==1.9.3
boto3==1.9.173
botocore==1.12.173
certifi==2019.6.16
cfn-flip==1.2.1
chardet==3.0.4
Click==7.0
docutils==0.14
durationpy==0.5
Flask==1.0.3
future==0.16.0
hjson==3.0.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==1.1.1
marshmallow==3.2.2
placebo==0.9.0
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==5.1.1
requests==2.22.0
s3transfer==0.2.1
six==1.12.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.7
Unidecode==1.1.0
urllib3==1.25.3
Werkzeug==0.15.4
wsgi-request-logger==0.4.6
zappa==0.48.2
```
* Link to your project (optional): https://github.com/loscil06/random_names_api
* Your `zappa_settings.py`: 
```
{
    "dev":
    {
        "s3_bucket": "lmbda2randomnames",
        "app_function": "app.app",
        "aws_region": "us-east-2",
        "parameter_depth": 1,
        "environment_variables":
        {}
    }
}

```

**Comment by loscil06** [comment]
Related to #1193 in which my program has underscores in its title. Such a shame because I had to rename my program without underscores and now have two different versions of deployed APIs. I figure that `zappa update` checks for this particular regex when updating: `[a-zA-Z][-a-zA-Z0-9]*`

**Comment by loscil06** [comment]
Recently I tried to update a program without any kind of underscores in it and the same issue happened.

**Comment by loscil06** [comment]
Upon using a preexisting zip file using the -z argument Zappa (or botocore? python itself?) was less cryptic about what was going on and it appears the problem might have roots in here: [aws-cli/issues/3842](https://github.com/aws/aws-cli/issues/3842)
But also here: [boto3/issues/1062](https://github.com/boto/boto3/issues/1062)

Tweaking  core.py at starting at line 293, changing the values of `long_config_dict` to the following:
```python
long_config_dict = {
            'region_name': aws_region,
            'connect_timeout': 6000,
            'read_timeout': 300
        }
```

will allow the zip to upload... But! Somewhere in the function `upload_to_s3`, while uploading the configs, sometime while uploading the template (in my case "cotizaciones-dev-template-1573633364.json") this happened. 
Upgrading to python3.8, making this change again and "adding support" to python3.8 (in __init__.py) I was finally able to update the function.

Here's my dump
`Traceback (most recent call last):
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/awsrequest.py", line 125, in _send_request
    method, url, body, headers, *args, **kwargs)
  File "/usr/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/awsrequest.py", line 152, in _send_output
    self.send(msg)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/awsrequest.py", line 236, in send
    return super(AWSConnection, self).send(str)
  File "/usr/lib/python3.7/http/client.py", line 987, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/httpsession.py", line 258, in send
    decode_content=False,
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/awsrequest.py", line 125, in _send_request
    method, url, body, headers, *args, **kwargs)
  File "/usr/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/awsrequest.py", line 152, in _send_output
    self.send(msg)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/awsrequest.py", line 236, in send
    return super(AWSConnection, self).send(str)
  File "/usr/lib/python3.7/http/client.py", line 987, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/zappa/cli.py", line 2779, in handle
    sys.exit(cli.handle())
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/zappa/cli.py", line 509, in handle
    self.dispatch_command(self.command, stage)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/zappa/cli.py", line 556, in dispatch_command
    self.update(self.vargs['zip'], self.vargs['no_upload'])
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/zappa/cli.py", line 949, in update
    self.lambda_arn = self.zappa.update_lambda_function(**kwargs)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/zappa/core.py", line 1128, in update_lambda_function
    response = self.lambda_client.update_function_code(**kwargs)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/home/alan/Programming/Python/cotizaciones/env/lib/python3.7/site-packages/botocore/httpsession.py", line 289, in send
    endpoint_url=request.url
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-2.amazonaws.com/2015-03-31/functions/cotizaciones-dev/code"`

**Comment by ikp4success** [comment]
You need to have two separate environments, one for zappa and one for your actual projects. Install only requirements you need in zappa environment.

**Comment by lutrasdebtra** [comment]
Hey folks - I'm having the same issue as @loscil06, but when I try to use Python3.8 I just get a message from zappa saying that Lambda doesn't currently support it. 

@ikp4success could you provide a bit more detail as to what is required for the two seperate environments?

I'm also running Zappa 0.48.2 and Python 3.7.

**Comment by loscil06** [comment]
> Hey folks - I'm having the same issue as @loscil06, but when I try to use Python3.8 I just get a message from zappa saying that Lambda doesn't currently support it.
> 
> @ikp4success could you provide a bit more detail as to what is required for the two seperate environments?
> 
> I'm also running Zappa 0.48.2 and Python 3.7.

Hi, I remember troubleshooting that issue and (i think) happened to be that I had to update a package although I don't remember which one, current successful pip3 freeze output so far is:
`argcomplete==1.9.3
boto3==1.10.9
botocore==1.13.9
certifi==2019.9.11
cfn-flip==1.2.1
chardet==3.0.4
Click==7.0
docutils==0.15.2
durationpy==0.5
Flask==1.1.1
future==0.16.0
hjson==3.0.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.3
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==1.1.1
marshmallow==3.2.2
placebo==0.9.0
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==5.1.2
requests==2.22.0
s3transfer==0.2.1
six==1.12.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.5.2
Unidecode==1.1.1
urllib3==1.25.6
Werkzeug==0.16.0
wsgi-request-logger==0.4.6
zappa==0.48.2
`
Also remember to "update" your zappa installation by "adding support" to python3.8 (in init.py). I don't recommend doing this, I'd say to delete all current packages and reinstall into their latest updates including zappa. If that doesn't work try this one workaround.

**Comment by evojewel** [comment]
Fixed the issue by doing the following:
- Downgraded to python 3.6.10
- Created a new virualenv with python3.6
- installed the dependencies again

**Comment by loscil06** [comment]
> Fixed the issue by doing the following:
> 
>     * Downgraded to python 3.6.10
> 
>     * Created a new virualenv with python3.6
> 
>     * installed the dependencies again

For the moment this is working, this happens when working with old Zappa versions, I've fixed this by either:
> Downgrading python to 3.6 and remaking the virtualenv
>Updating to 3.8 and remaking the virtualenv, while installing Zappa to the newest version while also not updating the dependencies of Zappa
