### ISSUE TITLE
Zappa Installation: UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2347

### ISSUE THREAD

**Issue by qy2205** [Miserlou/Zappa#1986]
## Context

I tried `pip install zappa`, but get the following error

    ERROR: Command errored out with exit status 1:
     command: 'X:\Anaconda3\envs\py36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\quany\\AppData\\Local\\Temp\\pip-install-gxsvadov\\kappa\\setup.py'"'"'; __file__='"'"'C:\\Users\\quany\\AppData\\Local\\Temp\\pip-install-gxsvadov\\kappa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\quany\AppData\Local\Temp\pip-install-gxsvadov\kappa\pip-egg-info'
         cwd: C:\Users\quany\AppData\Local\Temp\pip-install-gxsvadov\kappa\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\quany\AppData\Local\Temp\pip-install-gxsvadov\kappa\setup.py", line 54, in <module>
        run_setup()
      File "C:\Users\quany\AppData\Local\Temp\pip-install-gxsvadov\kappa\setup.py", line 22, in run_setup
        long_description=open_file('README.rst').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2347: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

## Your Environment

* Zappa version used: lastest
* Operating System and Python version: Python3.6 & Python3.7
* The output of `pip freeze`: 
certifi==2019.11.28
wincertstore==0.2

**Comment by jneves** [comment]
@qy2205 just to confirm, this is on Windows?

**Comment by sgpikachu** [comment]
having the same issue, have you solved this yet?

**Comment by heatherwang39** [comment]
facing the same problem

**Comment by qy2205** [comment]
> @qy2205 just to confirm, this is on Windows?


> having the same issue, have you solved this yet?

**Comment by qy2205** [comment]
> having the same issue, have you solved this yet?

I haven't solve that yet.

**Comment by sgpikachu** [comment]
I have looked up online. It says that its because of the chinese system, but I still don't know how to solve it. At last I got the app deployed by installing zappa on amazon ec2.

**Comment by amitfriedman93** [comment]
@sgpikachu Could you please explain how you deployed the app on amazon ec2?

**Comment by sgpikachu** [comment]
@amitfriedman93 Just upload the web application to ec2, install python, install the virtual env, and deploy it on zappa

**Comment by redstoneleo** [comment]
run `chcp 65001` before your commands
https://blog.darkthread.net/blog/command-prompt-codepage/
