### ISSUE TITLE
Incompatible with newly released Werkzeug 1.0.0

### ISSUE THREAD

**Issue by rudyryk** [Miserlou/Zappa#2036]
## Context
After a new today's deployment app didn't work.

## Expected Behavior
Work.

## Actual Behavior
Getting exception after deployment:

```
[ERROR] ImportError: cannot import name 'secure_filename' from 'werkzeug' (/var/task/werkzeug/__init__.py)
Traceback (most recent call last):
  File "/var/task/handler.py", line 602, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 245, in lambda_handler
    handler = cls()
  File "/var/task/handler.py", line 139, in __init__
    self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
```

## Possible Fix
As a workaround here suggested to use older Werkzeug:
https://github.com/puckel/docker-airflow/issues/499

```werkzeug==0.16.1```

## Steps to Reproduce
Try to deploy a new app from a clean environment.

Contents of a `requirements.txt`:

```
zappa
flask
```

## Your Environment

* Zappa version used: ``zappa==0.50.0``
* Operating System and Python version: ``Python 3.7.4`` 
* The output of `pip freeze`:

```
boto3==1.12.4
botocore==1.15.4
certifi==2019.11.28
cfn-flip==1.2.2
chardet==3.0.4
Click==7.0
Flask==1.1.1
Werkzeug==1.0.0
WTForms==2.2.1
zappa==0.50.0
...
```

* Your `zappa_settings.json`: 

```yaml
prod:
  project_name: app-admin
  app_function: app_admin.main.app
  aws_region: eu-central-1
  exclude:
  - .env*
  - boto3*
  - botocore*
  keep_warm: true
  s3_bucket: my-bucket
```

**Comment by taylorgoodallau** [comment]
It looks like the issue with released here - 

https://github.com/Miserlou/Zappa/commit/2500935f99c916dfe969a4fa2a3a31a2dad5e421#diff-b4ef698db8ca845e5845c4618278f29a 

We'd need to double check if there was a good reason it was bumped - in the case it wasn't  we'd need to take the lib back to Werkzeug>=0.14 which should fix it. 

it does look like the package is still in the lib - under libs which could be another possible fix - https://github.com/pallets/werkzeug/blob/9844e0447e63366273c8b9f9f2400e19b45532d1/src/werkzeug/utils.py#L390

**Comment by jneves** [comment]
No, it was part of an unlocking of the dependencies to identify cases like this (where we had version dependencies that were not documented/surfaced because we had them all pinned. Sorry it affected you, please pin it to 0.14 and I'll make that dependency explicit and documented from now on.On 24 Feb 2020 05:11, Taylor Goodall <notifications@github.com> wrote:It looks like the issue with released here -
2500935#diff-b4ef698db8ca845e5845c4618278f29a
We'd need to double check if there was a good reason it was bumped - in the case it wasn't  we'd need to take the lib back to Werkzeug>=0.14 which should fix it.
it does look like the package is still in the lib - under libs which could be another possible fix - https://github.com/pallets/werkzeug/blob/9844e0447e63366273c8b9f9f2400e19b45532d1/src/werkzeug/utils.py#L390

**Comment by jneves** [comment]
This requirement was made explicit with 0.51.0, but I'm keeping this issue open until we update the code to be compatible with werkzeug 1.0.0.

**Comment by snowman2** [comment]
Wekzeug 1.0+ works fine with django.

**Comment by nishalparbhu** [comment]
Hi there, is this still an issue? It seems to work fine with 1.0.1 when I've been testing and I have additional packages that depend on Werkzeug>1.0.0

**Comment by allanlewis** [comment]
What's the status of this issue? It seems that Zappa does work with v1 and maybe also v2. Is it just a matter of configuring the CI to test against the newer versions?

**Comment by phil-airship** [comment]
Updated and confirmed that since the issue was initially reported, the import that caused the issue is no longer present, and the consumed Werkzeug code from old versions is a 1-1 match as far as imports and API
