### ISSUE TITLE
Zappa Deployment to AWS Lamda not working with MSSQL

### ISSUE THREAD

**Issue by ORC-1** [Miserlou/Zappa#2050]
Django apps using MSSQL as Database deployed using Zappa, fails with error: ImproperlyConfigured("Error loading pyodbc module: %s" % e)s_removeddulele named 'pyodbc'
even if installed and works properly on local environment

## Your Environment

* Zappa version used: zappa 0.50.0
* Operating System and Python version: Linux| python 3.7

**Comment by nikbora** [comment]
I get the same for cryptography package when going from 0.49.0 -> 0.50.0. Looking at the logs it never gets included in the deploy - perhaps related to recent abi3/manylinux changes?

zappa=0.50.0
cryptography=2.8

**Comment by millarm** [comment]
I'm deploying those versions with mysql to lambda fine -> one change that is needed is to ensure the lambda has the appropriate mysql libraries.

I'm doing this at present -> running on CodeBuild on AWS and on an Amazon Linux build before I deploy I do

        cp /usr/lib64/mysql/libmysqlclient.* .


Which ensures that the lambda deployment has the same versions of the mysqlclient libraries that I've run the tests on the CodeBuild instance.

**Comment by nikbora** [comment]
Yeah that works, however shouldn't be (and wasn't) necessary as binaries should get downloaded from PyPi.

I suspect the reason this got through is that these unit tests only check that the packaging works (which it does) but not that the binary was included: 

https://github.com/Miserlou/Zappa/blob/379c0bf822eef91faccaa57fcf0111be21430cb1/tests/tests.py#L180

**Comment by nikbora** [comment]
Adding some Lambda logs to have an example (as perhaps the lib IS included but the binding version is wrong):

```
  ...
  File "/var/task/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/var/task/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/var/task/cryptography/hazmat/backends/openssl/backend.py", line 16, in <module>
    from cryptography import utils, x509
  File "/var/task/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/var/task/cryptography/x509/base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/var/task/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/var/task/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: /var/task/cryptography/hazmat/bindings/_constant_time.abi3.so: invalid ELF header
```

**Comment by mjscalexander** [comment]
I am ran into a similiar error. I am running django 1.10.8 and was running zappa 0.50.0 packaged in a lambda function. The way I fixed it was downgrading to a lower version zappa 0.48.2
`Error loading MySQLdb module: No module named 'MySQLdb': ImproperlyConfigured
Traceback (most recent call last):
File "/var/task/process.py", line 169, in main
process(record, context)
File "/var/task/process.py", line 133, in process
django.setup()
File "/var/task/django/__init__.py", line 27, in setup
apps.populate(settings.INSTALLED_APPS)
File "/var/task/django/apps/registry.py", line 108, in populate
app_config.import_models(all_models)
File "/var/task/django/apps/config.py", line 199, in import_models
self.models_module = import_module(models_module_name)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/var/task/django/contrib/auth/models.py", line 4, in <module>
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
File "/var/task/django/contrib/auth/base_user.py", line 52, in <module>
class AbstractBaseUser(models.Model):
File "/var/task/django/db/models/base.py", line 119, in __new__
new_class.add_to_class('_meta', Options(meta, app_label))
File "/var/task/django/db/models/base.py", line 316, in add_to_class
value.contribute_to_class(cls, name)
File "/var/task/django/db/models/options.py", line 214, in contribute_to_class
self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
File "/var/task/django/db/__init__.py", line 33, in __getattr__
return getattr(connections[DEFAULT_DB_ALIAS], item)
File "/var/task/django/db/utils.py", line 211, in __getitem__
backend = load_backend(db['ENGINE'])
File "/var/task/django/db/utils.py", line 115, in load_backend
return import_module('%s.base' % backend_name)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/var/task/django/db/backends/mysql/base.py", line 28, in <module>
raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named 'MySQLdb'`
