### ISSUE TITLE
Error on deploy: botocore.exceptions.ConnectTimeoutError

### ISSUE THREAD

**Issue by kwangsooshin** [Miserlou/Zappa#2061]
## Context

Whne I try to deploy a lambda with zappa, I have the following error:

* zappa tail
```
[1583918839541] [DEBUG] 2020-03-11T09:27:19.541Z 0c3c554a-eb41-4a26-a3a0-193979f79945 Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
[1583918839541] [DEBUG] 2020-03-11T09:27:19.541Z 0c3c554a-eb41-4a26-a3a0-193979f79945 Starting new HTTPS connection (1): {MY_S3_BUCKET}.s3.ap-northeast-2.amazonaws.com:443
                                                                                  ......
[1583918878934] Traceback (most recent call last):
[1583918878934] File "/var/task/urllib3/connection.py", line 160, in _new_conn
[1583918878934] (self._dns_host, self.port), self.timeout, **extra_kw)
[1583918878934] File "/var/task/urllib3/util/connection.py", line 80, in create_connection
[1583918878934] raise err
[1583918878934] File "/var/task/urllib3/util/connection.py", line 70, in create_connection
[1583918878934] sock.connect(sa)
[1583918878934] socket.timeout: timed out
[1583918878934] During handling of the above exception, another exception occurred:
[1583918878934] Traceback (most recent call last):
[1583918878934] File "/var/task/botocore/httpsession.py", line 262, in send
[1583918878934] chunked=self._chunked(request.headers),
[1583918878934] File "/var/task/urllib3/connectionpool.py", line 641, in urlopen
[1583918878934] _stacktrace=sys.exc_info()[2])
[1583918878934] File "/var/task/urllib3/util/retry.py", line 344, in increment
[1583918878934] raise six.reraise(type(error), error, _stacktrace)
[1583918878934] File "/var/task/urllib3/packages/six.py", line 686, in reraise
[1583918878934] raise value
[1583918878934] File "/var/task/urllib3/connectionpool.py", line 603, in urlopen
[1583918878934] chunked=chunked)
[1583918878934] File "/var/task/urllib3/connectionpool.py", line 344, in _make_request
[1583918878934] self._validate_conn(conn)
[1583918878934] File "/var/task/urllib3/connectionpool.py", line 843, in _validate_conn
[1583918878934] conn.connect()
[1583918878934] File "/var/task/urllib3/connection.py", line 316, in connect
[1583918878934] conn = self._new_conn()
[1583918878934] File "/var/task/urllib3/connection.py", line 165, in _new_conn
[1583918878934] (self.host, self.timeout))
[1583918878934] urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPSConnection object at 0x7f31a4048c10>, 'Connection to {MY_ZAPPA_BUCKET}.s3.ap-northeast-2.amazonaws.com timed out. (connect timeout=60)')
[1583918878934] During handling of the above exception, another exception occurred:
[1583918878934] Traceback (most recent call last):
[1583918878934] File "/var/task/botocore/endpoint.py", line 200, in _do_get_response
[1583918878934] http_response = self._send(request)
[1583918878934] File "/var/task/botocore/endpoint.py", line 244, in _send
[1583918878934] return self.http_session.send(request)
[1583918878934] File "/var/task/botocore/httpsession.py", line 286, in send
[1583918878934] raise ConnectTimeoutError(endpoint_url=request.url, error=e)
[1583918878934] botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "https://{MY_S3_BUCKET}.ap-northeast-2.amazonaws.com/dev_{MY_PROJECT_NAME}_current_project.tar.gz"
```

According to the error, it seems that lambda does not have access to the s3 bucket. However, when I checked s3, I found that the `{MY_S3_BUCKET}` bucket was created and the `dev_{MY_PROJECT_NAME}_current_project.tar.gz` file uploaded well inside. (The file size is 120MB.)

What is problem? And What should I do?

## Your Environment

* Zappa version used: 0.51.0
* Operating System and Python version: python3.7
* The output of `pip freeze`:
```
aiohttp==3.5.4
APScheduler==3.6.0
argcomplete==1.11.1
asn1crypto==0.24.0
async-timeout==3.0.1
attrs==19.1.0
bcrypt==3.1.6
boto3==1.9.170
botocore==1.12.170
certifi==2019.6.16
cffi==1.12.3
cfn-flip==1.2.2
chardet==3.0.4
Click==7.0
colorlog==4.0.2
coreapi==2.3.3
coreschema==0.0.4
cryptography==2.7
cycler==0.10.0
Django==2.2.10
django-admin-rangefilter==0.5.2
django-cleanup==3.2.0
django-cors-middleware==1.3.1
django-debug-toolbar==1.11
django-extensions==2.1.9
django-json-widget==0.2.0
django-netfields==1.0.1
django-render-block==0.6
django-sendgrid-v5==0.8.0
django-split-settings==1.0.0
django-storages==1.7.1
django-templated-email==2.3.0
djangorestframework==3.10.2
djangorestframework-jwt==1.11.0
docutils==0.14
drf-writable-nested==0.5.1
drf-yasg==1.16.1
durationpy==0.5
future==0.17.1
gunicorn==19.9.0
hjson==3.0.1
idna==2.8
importlib-metadata==1.5.0
inflection==0.3.1
itypes==1.1.0
Jinja2==2.10.1
jmespath==0.9.4
jsonpointer==2.0
jsonschema==3.0.1
kappa==0.6.0
kiwisolver==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.0
multidict==4.5.2
netaddr==0.7.19
numpy==1.16.4
opencv-python==4.1.0.25
packaging==19.1
paramiko==2.5.0
Pillow==6.2.0
pip-tools==4.5.1
pkg-resources==0.0.0
placebo==0.9.0
psutil==5.6.3
psycopg2-binary==2.8.4
pyasn1==0.4.8
pycparser==2.19
pydicom==1.3.0
PyJWT==1.7.1
PyNaCl==1.3.0
pyparsing==2.4.0
pyrsistent==0.15.2
python-dateutil==2.6.0
python-dotenv==0.10.3
python-http-client==3.1.0
python-slugify==4.0.0
pytz==2019.1
PyYAML==5.1.1
requests==2.22.0
ruamel.yaml==0.15.97
s3transfer==0.2.1
scipy==1.3.0
sendgrid==6.0.5
sentry-sdk==0.14.0
six==1.12.0
slacker==0.13.0
sqlparse==0.3.0
swagger-spec-validator==2.4.3
text-unidecode==1.3
toml==0.10.0
tqdm==4.43.0
troposphere==2.6.0
tzlocal==1.5.1
uritemplate==3.0.1
urllib3==1.25.3
Werkzeug==0.16.1
wsgi-request-logger==0.4.6
yarl==1.3.0
zappa==0.51.0
zipp==3.1.0
```
* Link to your project (optional): Private!
* Your `zappa_settings.json`: 
```
{
    "dev": {
        "aws_region": "ap-northeast-2",
        "django_settings": "core.settings",
        "profile_name": "default",
        "project_name": "{MY_PROJECT_NAME}",
        "runtime": "python3.7",
        "s3_bucket": "{MY_S3_BUCKET}",
        "vpc_config": {
            "SubnetIds": ["subnet-abcd1234", "subnet-efgh5678"],
            "SecurityGroupIds": ["sg-xyz1234567890"]
        },
        "memory_size": 2048,
        "slim_handler": true,
        "timeout_seconds": 300,
        "exclude": ["pytest*", "pytest-*", "__pycache__/*", ".git/*"]
    }
}
```

**Comment by aralmpa** [comment]
Hi,

A shot in the dark to start this going:

Usually timeout errors relate to firewalls obstracting communication between two parts: the requester and the responder - in our case Lambda (function) and S3 (bucket). When a Lambfa function runs in a VPC subnet its communication to the other comonentsis bound by the subnet's network limits. So I would look first there - is there an open connection between them? I mean are the http requests originating from within the function are routed correctly to S3? This is usually accomplished with an interface vpc endpoint (AWS PrivateLink) that points to S3 all the related requests.

Is is the first deploy you made? If not did you manage to succesfully deploy your previous attempt? If yes did you utilize VPC for your functions?

**Comment by kwangsooshin** [comment]
@aralmpa This is first deploy I made. So, I deployed this again except for the VPC configuration. But It is not working too.

**Comment by aralmpa** [comment]
So it is the same error (same traceback log)? Can you share the settings.json?

**Comment by jneves** [comment]
Have you changed the project_name and s3_bucket name? From the logs it looks like you didn't define your own.

**Comment by kwangsooshin** [comment]
I found the cause of the problem.
Even if I changed vpc_config in json, the previous setting remained.
It seems entirely my problem.

**Comment by JacobDel** [comment]
@kwangsooshin  I am experiencing the same issue but I do not understand your answer to how you solved the issue. Can you explain how you solved this issue please?
