### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by serendipity1004** [Miserlou/Zappa#2062]
When I run `zappa deploy stag` I get following error in the cloud watch

```
[ERROR] ModuleNotFoundError: No module named 'user'
Traceback (most recent call last):
  File "/var/task/handler.py", line 609, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
    handler = cls()
  File "/var/task/handler.py", line 146, in __init__
    wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)
  File "/var/task/zappa/ext/django_zappa.py", line 20, in get_django_wsgi
    return get_wsgi_application()
  File "/var/task/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/var/task/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/task/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/var/task/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/var/lang/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
```

I have included the app like below in the django settings.py

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'rest_framework.authtoken',
    'storages',
    'user',
    'core',
    'company',
    'job_post',
    'post',
]
```

It's not able to import the first app that I have created - the user app.

I am currently using pipenv as virtual environment and following is my requirements.txt file

```
argcomplete==1.11.1
asgiref==3.2.4
boto3==1.12.18
botocore==1.15.18
certifi==2019.11.28
cfn-flip==1.2.2
chardet==3.0.4
click==7.1.1
Django==3.0.4
django-filter==2.2.0
django-storages==1.9.1
djangorestframework==3.11.0
djangorestframework-camel-case==1.1.2
docutils==0.15.2
drf-nested-routers==0.91
durationpy==0.5
future==0.18.2
get==2019.4.13
gunicorn==20.0.4
hjson==3.0.1
idna==2.9
jmespath==0.9.5
kappa==0.6.0
Markdown==3.2.1
Pillow==7.0.0
pip-tools==4.5.1
placebo==0.9.0
post==2019.4.13
psycopg2-binary==2.8.4
public==2019.4.13
python-dateutil==2.6.1
python-slugify==4.0.0
pytz==2019.3
PyYAML==5.3
query-string==2019.4.13
request==2019.4.13
requests==2.23.0
s3transfer==0.3.3
six==1.14.0
sqlparse==0.3.1
text-unidecode==1.3
toml==0.10.0
tqdm==4.43.0
troposphere==2.6.0
urllib3==1.25.8
Werkzeug==0.16.1
wsgi-request-logger==0.4.6
zappa==0.51.0
```

What could possibly be the problem? The project runs no problem locally.

**Comment by serendipity1004** [comment]
Also using python 3.7 

Tried deploying in a docker environment. The dockerfile is as follows

```
FROM lambci/lambda:build-python3.7

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src

ENV LIBRARY_PATH=/lib:/usr/lib

RUN pip install -U pip-tools && \
  pip install pipenv

COPY . .

CMD python app/manage.py runserver 0.0.0.0:3000

```

**Comment by serendipity1004** [comment]
My zappa settings file

```
stag:
  django_settings: "app.app.settings"
  profile_name: null
  project_name: ""***********"
  runtime: "python3.7"
  s3_bucket: ""***********"
  aws_region: "ap-northeast-2"
  exclude:
    - "boto3*"
    - "botocore*"
    - "statics"
  vpc_config:
    SubnetIds:
      - "***********"
      - ""***********"
      - ""***********"
    SecurityGroupIds:
      - ""***********"
```

**Comment by seanucd2000** [comment]
Assuming the obvious that a) your app works in the local dev server and b) you commented out the user app and get a similar error in another place and it wasn't just something Django related and c) your project structure is typical of a standard style django app, try changing your django_settings to just app.settings without the second app. (that way the settings file path is relative in depth to the zappa settings file.)

**Comment by serendipity1004** [comment]
@seanucd2000 thank you very much.  I was using docker-compose environment so my zappa_settings.yml was outside of project file so zappa detected the settings to be one directory more nested. after moving the zappa_settings.yml file inside the project and removing the second app it started working!
