### ISSUE TITLE
Cannot import name '_levenshtein' from 'Levenshtein'

### ISSUE THREAD

**Issue by Robinspecteur** [Miserlou/Zappa#2065]
When I try to get my app deployed, I get an ImportError for the levenshtein package
## Context
I am using the `fast-autocomplete` package, which is dependent upon the `levenshtein` package. When I deploy, this is the full traceback of the error:
```
[ERROR] ImportError: cannot import name '_levenshtein' from 'Levenshtein' (/var/task/Levenshtein/__init__.py)
Traceback (most recent call last):
  File "/var/task/handler.py", line 609, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
    handler = cls()
  File "/var/task/handler.py", line 134, in __init__
    self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/app.py", line 5, in <module>
    from fast_autocomplete import AutoComplete
  File "/var/task/fast_autocomplete/__init__.py", line 11, in <module>
    from fast_autocomplete.dwg import AutoComplete
  File "/var/task/fast_autocomplete/dwg.py", line 11, in <module>
    from Levenshtein import distance as levenshtein_distance
  File "/var/task/Levenshtein/__init__.py", line 1, in <module>
    from Levenshtein import _levenshtein
```

This seems to be a quite often used package yet I have only found [one similar issue](https://github.com/Miserlou/Zappa/issues/1132), and I don't understand why it was closed. 

## Expected Behavior
Should be able to import Levenshtein into my lambda function
## Actual Behavior
Levenshtein is not imported

## Steps to Reproduce

1. Add `python-Levenshtein` in my project
2. `zappa deploy/update`
3. Get the importError

## Your Environment

* Zappa version used: 0.51.0
* Operating System and Python version: Mac OS X 10.15.1 Python 3.7
* The output of `pip freeze`:
```aniso8601==8.0.0
argcomplete==1.11.1
boto3==1.12.23
botocore==1.15.23
certifi==2019.11.28
cfn-flip==1.2.2
chardet==3.0.4
click==7.1.1
docutils==0.15.2
durationpy==0.5
fast-autocomplete==0.6.0
Flask==1.1.1
Flask-RESTful==0.3.8
future==0.18.2
hjson==3.0.1
idna==2.9
importlib-metadata==1.5.0
itsdangerous==1.1.0
Jinja2==2.11.1
jmespath==0.9.5
kappa==0.6.0
MarkupSafe==1.1.1
pip-tools==4.5.1
placebo==0.9.0
python-dateutil==2.6.1
python-Levenshtein==0.12.0
python-slugify==4.0.0
pytz==2019.3
PyYAML==5.3
requests==2.23.0
s3transfer==0.3.3
six==1.14.0
text-unidecode==1.3
toml==0.10.0
tqdm==4.43.0
troposphere==2.6.0
urllib3==1.25.8
Werkzeug==0.16.1
wsgi-request-logger==0.4.6
zappa==0.51.0
zipp==3.1.0
```
* Your `zappa_settings.json`: 
```
{
    "dev": {
        "app_function": "app.app",
        "profile_name": "zappa",
        "project_name": "lambda-related-",
        "runtime": "python3.7",
        "s3_bucket": "",
        "slim_handler": false,
        "manage_roles": false,
        "role_name": "ZappaRole",
        "role_arn": "",
    }
}
```
Thank you!

**Comment by Robinspecteur** [comment]
Okay, turns out this was an AWS issue and not a Zappa issue. 

The problem was that Levenshtein uses C code which is compiled by my machine (running Mac OS X) when using `pip install`. 

The solution is, as explained [here](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-python-package-compatible/), to use a linux precompiled wheel package instead of `pip install`. python-Levenshtein does not provide precompiled wheels, but fortunately you can get it [here](https://pypi.org/project/python-Levenshtein-wheels/#files) (`python_Levenshtein_wheels-0.13.1-cp37-cp37m-manylinux2010_x86_64.whl`).
