### ISSUE TITLE
After running zappa deploy, i get these strange errors

### ISSUE THREAD

**Issue by AkshayAwate** [Miserlou/Zappa#2158]
Traceback (most recent call last):
  File "/home/akshay/.local/lib/python3.8/site-packages/zappa/cli.py", line 2778, in handle
    sys.exit(cli.handle())
  File "/home/akshay/.local/lib/python3.8/site-packages/zappa/cli.py", line 512, in handle
    self.dispatch_command(self.command, stage)
  File "/home/akshay/.local/lib/python3.8/site-packages/zappa/cli.py", line 538, in dispatch_command
    self.load_settings(self.vargs.get('settings_file'))
  File "/home/akshay/.local/lib/python3.8/site-packages/zappa/cli.py", line 2116, in load_settings
    self.zappa = Zappa( boto_session=session,
  File "/home/akshay/.local/lib/python3.8/site-packages/zappa/core.py", line 310, in __init__
    self.lambda_client = self.boto_client('lambda', config=long_config)
  File "/home/akshay/.local/lib/python3.8/site-packages/zappa/core.py", line 341, in boto_client
    return self.boto_session.client(service, *args, **self.configure_boto_session_method_kwargs(service, kwargs))
  File "/home/akshay/.local/lib/python3.8/site-packages/boto3/session.py", line 258, in client
    return self._session.create_client(
  File "/home/akshay/.local/lib/python3.8/site-packages/botocore/session.py", line 834, in create_client
    client = client_creator.create_client(
  File "/home/akshay/.local/lib/python3.8/site-packages/botocore/client.py", line 83, in create_client
    client_args = self._get_client_args(
  File "/home/akshay/.local/lib/python3.8/site-packages/botocore/client.py", line 285, in _get_client_args
    return args_creator.get_client_args(
  File "/home/akshay/.local/lib/python3.8/site-packages/botocore/args.py", line 71, in get_client_args
    final_args = self.compute_client_args(
  File "/home/akshay/.local/lib/python3.8/site-packages/botocore/args.py", line 147, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/home/akshay/.local/lib/python3.8/site-packages/botocore/args.py", line 218, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/home/akshay/.local/lib/python3.8/site-packages/botocore/args.py", line 300, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/home/akshay/.local/lib/python3.8/site-packages/botocore/client.py", line 360, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/home/akshay/.local/lib/python3.8/site-packages/botocore/regions.py", line 133, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/home/akshay/.local/lib/python3.8/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

zappa.settings.json
{
    "dev": {
        "django_settings": "backoffice.live_settings",
        "profile_name": "default",
        "project_name": "luna-new",
        "runtime": "python3.8",
        "s3_bucket": "zappa-undo0e9rf"
    },
    "dev_ap_east_1": {
        "aws_region": "ap-east-1",
        "extends": "dev"
    },
    "dev_ap_northeast_1": {
        "aws_region": "ap-northeast-1",
        "extends": "dev"
    },
    "dev_ap_northeast_2": {
        "aws_region": "ap-northeast-2",
        "extends": "dev"
    },
    "dev_ap_northeast_3": {
        "aws_region": "ap-northeast-3",
        "extends": "dev"
    },
    "dev_ap_south_1": {
        "aws_region": "ap-south-1",
        "extends": "dev"
    },
    "dev_ap_southeast_1": {
        "aws_region": "ap-southeast-1",
        "extends": "dev"
    },
    "dev_ap_southeast_2": {
        "aws_region": "ap-southeast-2",
        "extends": "dev"
    },
    "dev_ca_central_1": {
        "aws_region": "ca-central-1",
        "extends": "dev"
    },
    "dev_cn_north_1": {
        "aws_region": "cn-north-1",
        "extends": "dev"
    },
    "dev_cn_northwest_1": {
        "aws_region": "cn-northwest-1",
        "extends": "dev"
    },
    "dev_eu_central_1": {
        "aws_region": "eu-central-1",
        "extends": "dev"
    },
    "dev_eu_north_1": {
        "aws_region": "eu-north-1",
        "extends": "dev"
    },
    "dev_eu_west_1": {
        "aws_region": "eu-west-1",
        "extends": "dev"
    },
    "dev_eu_west_2": {
        "aws_region": "eu-west-2",
        "extends": "dev"
    },
    "dev_eu_west_3": {
        "aws_region": "eu-west-3",
        "extends": "dev"
    },
    "dev_sa_east_1": {
        "aws_region": "sa-east-1",
        "extends": "dev"
    },
    "dev_us_east_1": {
        "aws_region": "us-east-1",
        "extends": "dev"
    },
    "dev_us_east_2": {
        "aws_region": "us-east-2",
        "extends": "dev"
    },
    "dev_us_gov_east_1": {
        "aws_region": "us-gov-east-1",
        "extends": "dev"
    },
    "dev_us_gov_west_1": {
        "aws_region": "us-gov-west-1",
        "extends": "dev"
    },
    "dev_us_west_1": {
        "aws_region": "us-west-1",
        "extends": "dev"
    },
    "dev_us_west_2": {
        "aws_region": "us-west-2",
        "extends": "dev"
    }
}

**Comment by loscil06** [comment]
Are you providing an AWS region in your zappa_settings.json? If you read into your trace back this particular snippet comes up:

raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
