### ISSUE TITLE
Zappa Deploy | Update error on "No such file or directory" Possible duplicate of https://github.com/Miserlou/Zappa/issues/1232

### ISSUE THREAD

**Issue by khixer** [Miserlou/Zappa#2224]
Hey,

I'm having a similar problem mentioned in the duplicate. The only difference is, the solution mentioned is not working. I've put hours to debug it but nothing successful. Kindly help in this regard.

**Error**
```
Traceback (most recent call last):
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/cli.py", line 3422, in handle
    sys.exit(cli.handle())
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/cli.py", line 588, in handle
    self.dispatch_command(self.command, stage)
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/cli.py", line 641, in dispatch_command
    self.update(
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/cli.py", line 1088, in update
    self.create_package()
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/cli.py", line 2743, in create_package
    self.zip_path = self.zappa.create_lambda_zip(
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/core.py", line 632, in create_lambda_zip
    copytree(
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/utilities.py", line 69, in copytree
    copy_file(src, dst, item)
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/utilities.py", line 50, in copy_file
    copytree(s, d, metadata, symlinks, ignore)
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/utilities.py", line 69, in copytree
    copy_file(src, dst, item)
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/utilities.py", line 50, in copy_file
    copytree(s, d, metadata, symlinks, ignore)
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/utilities.py", line 69, in copytree
    copy_file(src, dst, item)
  File "/home/khizar/.local/lib/python3.8/site-packages/zappa/utilities.py", line 52, in copy_file
    shutil.copy2(s, d) if metadata else shutil.copy(s, d)
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/khizar/Repositories/comradly/lambda/.serverless/requirements'
```

**Contents of pip list**
```
Package                          Version  
-------------------------------- ---------
argcomplete                      1.12.3   
boto3                            1.17.110 
botocore                         1.20.110 
CacheControl                     0.12.6   
cachetools                       4.2.2    
certifi                          2021.5.30
cffi                             1.14.6   
cfn-flip                         1.2.3    
chardet                          3.0.4    
click                            8.0.1    
dj-database-url                  0.5.0    
Django                           2.2.5    
django-admin-rangefilter         0.5.4    
django-allow-cidr                0.3.1    
django-cors-headers              3.1.1    
django-extensions                2.2.1    
django-middleware-global-request 0.2.0    
django-sendgrid-v5               0.8.1    
djangorestframework              3.10.3   
docutils                         0.15.2   
durationpy                       0.5      
firebase-admin                   4.4.0    
future                           0.18.2   
google-api-core                  1.31.0   
google-api-python-client         1.12.8   
google-auth                      1.23.0   
google-auth-httplib2             0.0.4    
google-auth-oauthlib             0.4.4    
google-cloud-core                1.7.1    
google-cloud-firestore           2.0.1    
google-cloud-storage             1.40.0   
google-crc32c                    1.1.2    
google-resumable-media           1.3.1    
googleapis-common-protos         1.53.0   
grpcio                           1.38.1   
gspread                          3.1.0    
gunicorn                         19.9.0   
hjson                            3.0.2    
honeycomb-beeline                2.11.2   
httplib2                         0.18.1   
idna                             2.8      
jmespath                         0.10.0   
jsonfield                        2.0.2    
kappa                            0.6.0    
libhoney                         1.10.0   
msgpack                          1.0.2    
netaddr                          0.8.0    
oauth2client                     4.1.3    
oauthlib                         3.1.0    
packaging                        21.0     
pep517                           0.10.0   
Pillow                           7.0.0    
pip                              20.0.2   
pip-tools                        6.2.0    
pkg-resources                    0.0.0    
placebo                          0.9.0    
proto-plus                       1.19.0   
protobuf                         3.17.3   
pyasn1                           0.4.8    
pyasn1-modules                   0.2.8    
pycparser                        2.20     
pyfcm                            1.4.7    
pygsheets                        2.0.2    
pyparsing                        2.4.7    
python-dateutil                  2.4.2    
python-http-client               3.3.2    
python-slugify                   5.0.2    
pytz                             2021.1   
PyYAML                           5.4.1    
reportlab                        3.5.48   
requests                         2.22.0   
requests-oauthlib                1.2.0    
rsa                              4.7.2    
s3transfer                       0.4.2    
sendgrid                         6.4.1    
sentry-sdk                       0.14.4   
setuptools                       44.0.0   
six                              1.16.0   
sqlparse                         0.4.1    
starkbank-ecdsa                  1.1.1    
statsd                           3.3.0    
text-unidecode                   1.3      
toml                             0.10.2   
tqdm                             4.61.2   
troposphere                      3.0.1    
uritemplate                      3.0.1    
urllib3                          1.25.11  
Werkzeug                         0.16.1   
wheel                            0.36.2   
whitenoise                       4.1.4    
wrapt                            1.12.1   
wsgi-request-logger              0.4.6    
zappa                            0.53.0   
```

I've no idea why it's going in the `lambda/.serverless` directory for finding a file

Dup link: https://github.com/Miserlou/Zappa/issues/1232

**Comment by Avin-Techv** [comment]
same issue, did you get any solution or any alternative that worked for you

**Comment by khixer** [comment]
Alternate: https://github.com/serverless/serverless
