### ISSUE TITLE
Force project_name to be smaller than 16 characters

### ISSUE THREAD

**Issue by jayfk** [Miserlou/Zappa#275]
Zappa deploy fails on projects where the project_name has more than 16 characters.

```
Traceback (most recent call last):
  File "/Users/j/dev/.virtualenvs/statuspage-backend/src/zappa/zappa/cli.py", line 1119, in handle
    sys.exit(cli.handle())
  File "/Users/j/dev/.virtualenvs/statuspage-backend/src/zappa/zappa/cli.py", line 174, in handle
    self.deploy()
  File "/Users/j/dev/.virtualenvs/statuspage-backend/src/zappa/zappa/cli.py", line 264, in deploy
    self.schedule()
  File "/Users/j/dev/.virtualenvs/statuspage-backend/src/zappa/zappa/cli.py", line 479, in schedule
    events=events
  File "/Users/j/dev/.virtualenvs/statuspage-backend/src/zappa/zappa/zappa.py", line 1158, in schedule_events
    RoleArn=self.credentials_arn
  File "/Users/j/dev/.virtualenvs/statuspage-backend/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/j/dev/.virtualenvs/statuspage-backend/lib/python2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ValidationException) when calling the PutRule operation: 1 validation error detected: Value 'this-is-a-longer-project-name-prod-zappa-keep-warm-handler.keep_warm_callback' at 'name' failed to satisfy constraint: Member must have length less than or equal to 64
```

**Comment by Miserlou** [comment]
16 or 64? Your traceback posted there gets cut off at "Member must have length less than or equal to 64"

**Comment by jayfk** [comment]
64 total. There are another 48 chars from "{stage}-zappa-keep-warm-handler.keep_warm_callback". With a project name longer than 16 chars that exceeds the 64 chara total.

**Comment by Miserlou** [comment]
Added truncator by default and warning for long custom names.

**Comment by pywebdesign** [comment]
Just to let you know I am getting the same error with version 0.23.0

Value 'backend-specialprotect-backend-zappa-keep-warm-handler.keep_warm_callback' at 'name' failed to satisfy constraint: Member must have length less than or equal to 64

thx
