### ISSUE TITLE
remote exception logging with flask

### ISSUE THREAD

**Issue by jayfk** [Miserlou/Zappa#283]
_Continuing from https://github.com/Miserlou/Zappa/pull/257_..

It looks like flask on zappa is currently unable to log to remote exception loggers/aggregators. I've tried Sentry, Opbeat and Raygun.

It has probably something to do with the following exception that is raised during exception handling.

``` python
[1472050994820] Traceback (most recent call last):
[1472050994820] File "/usr/lib64/python2.7/logging/__init__.py", line 880, in emit
[1472050994821] stream.write(fs % msg)
[1472050994821] File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-9rkaZs/Werkzeug/werkzeug/local.py", line 343, in __getattr__
[1472050994821] AttributeError: 'str' object has no attribute 'write'
[1472050994821] Logged from file app.py, line 1587
```

From what it looks like, flasks `log_exception` function tries to write to _something_ in werkzeug that is a string but should be some kind of stream.

I believe the error get's swallowed somewhere by Zappa, continuing with handling the original exception.
## Workaround

Use logging via mail for now:

``` python
if not app.debug:
    import logging
    from logging.handlers import SMTPHandler
    mail_handler = SMTPHandler(
        mailhost='your.host.com',
        fromaddr='postmaster@your.host.com',
        toaddrs=['you@gmail.com'],
        subject='Error on your app',
        credentials=('username', 'password')
    )
    mail_handler.setLevel(logging.ERROR)
    app.logger.addHandler(mail_handler)
```
# Reproducing the issue
## requirements (sentry)

```
zappa # latest, installed from source
flask==0.11.1
```
## Settings

``` javascript
{
    "dev":{
        "app_function": "app.app", 
        "s3_bucket": "foo",
        "exception_handler": "app.unhandled_exceptions"
    }
}
```
## Minimal flask app (app.py)

``` python
from flask import Flask
from raven import Client

app = Flask(__name__)
SENTRY_DSN = 'https://user:pass@app.getsentry.com/id' # free account at getsentry.com
from raven.contrib.flask import Sentry
sentry = Sentry(app, dsn='YOUR_DSN_HERE')

@app.route('/', methods=['GET'])
def index():
    # this throws an exception that should be sent to sentry
    open("/non-existent.txt")
    return "Hi", 200

# We only need this for local development.
if __name__ == '__main__':
    app.run(debug=True)
```
## Full cloudwatch log

```
[1472050994816] [INFO]  2016-08-24T15:03:14.816Z        e144417b-6a0b-11e6-89cb-931b5b898cc6        Detected environment to be AWS Lambda. Using synchronous HTTP transport.
[1472050994820] Traceback (most recent call last):
[1472050994820] File "/usr/lib64/python2.7/logging/__init__.py", line 880, in emit
[1472050994821] stream.write(fs % msg)
[1472050994821] File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-9rkaZs/Werkzeug/werkzeug/local.py", line 343, in __getattr__
[1472050994821] AttributeError: 'str' object has no attribute 'write'
[1472050994821] Logged from file app.py, line 1587
[1472050994821] [ERROR] 2016-08-24T15:03:14.820Z        e144417b-6a0b-11e6-89cb-931b5b898cc6        Exception on / [GET]
Traceback (most recent call last):
  File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-I1t8YY/flask/flask/app.py", line 1988, in wsgi_app
  File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-I1t8YY/flask/flask/app.py", line 1641, in full_dispatch_request
  File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-I1t8YY/flask/flask/app.py", line 1544, in handle_user_exception
  File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-I1t8YY/flask/flask/app.py", line 1639, in full_dispatch_request
  File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-I1t8YY/flask/flask/app.py", line 1625, in dispatch_request
  File "/var/task/app.py", line 16, in index
    open("/non-existent.txt")
IOError: [Errno 2] No such file or directory: '/non-existent.txt'
[1472050994822] [INFO]  2016-08-24T15:03:14.821Z        e144417b-6a0b-11e6-89cb-931b5b898cc6        93.232.91.154 - - [24/Aug/2016:15:03:14 +0000] "GET / HTTP/1.1" 500 291 "" "HTTPie/0.9.3" 0/234.269
[1472050994822] {"http_status": 500, "content": "PCFET0NUWVBFIEhUTUwgUFVCTElDICItLy9XM0MvL0RURCBIVE1MIDMuMiBGaW5hbC8vRU4iPgo8dGl0bGU+NTAwIEludGVybmFsIFNlcnZlciBFcnJvcjwvdGl0bGU+CjxoMT5JbnRlcm5hbCBTZXJ2ZXIgRXJyb3I8L2gxPgo8cD5UaGUgc2VydmVyIGVuY291bnRlcmVkIGFuIGludGVybmFsIGVycm9yIGFuZCB3YXMgdW5hYmxlIHRvIGNvbXBsZXRlIHlvdXIgcmVxdWVzdC4gIEVpdGhlciB0aGUgc2VydmVyIGlzIG92ZXJsb2FkZWQgb3IgdGhlcmUgaXMgYW4gZXJyb3IgaW4gdGhlIGFwcGxpY2F0aW9uLjwvcD4K"}: LambdaException
Traceback (most recent call last):
  File "/var/task/handler.py", line 396, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 143, in lambda_handler
    raise lex
LambdaException: {"http_status": 500, "content": "PCFET0NUWVBFIEhUTUwgUFVCTElDICItLy9XM0MvL0RURCBIVE1MIDMuMiBGaW5hbC8vRU4iPgo8dGl0bGU+NTAwIEludGVybmFsIFNlcnZlciBFcnJvcjwvdGl0bGU+CjxoMT5JbnRlcm5hbCBTZXJ2ZXIgRXJyb3I8L2gxPgo8cD5UaGUgc2VydmVyIGVuY291bnRlcmVkIGFuIGludGVybmFsIGVycm9yIGFuZCB3YXMgdW5hYmxlIHRvIGNvbXBsZXRlIHlvdXIgcmVxdWVzdC4gIEVpdGhlciB0aGUgc2VydmVyIGlzIG92ZXJsb2FkZWQgb3IgdGhlcmUgaXMgYW4gZXJyb3IgaW4gdGhlIGFwcGxpY2F0aW9uLjwvcD4K"}
[1472051018205] Zappa Event: {u'account': u'747357196988', u'region': u'us-east-1', u'detail': {}, u'detail-type': u'Scheduled Event', u'source': u'aws.events', u'version': u'0', u'time': u'2016-08-24T15:03:10Z', u'id': u'7135a8fb-e8bc-4f80-9a5a-8c5846ba3b7b', u'resources': [u'arn:aws:events:us-east-1:747357196988:rule/test-dev-zappa-keep-warm-handler.keep_warm_callback']}
[1472051018205] Zappa Event: {}
[1472051018205] [DEBUG] 2016-08-24T15:03:38.205Z        efbca15e-6a0b-11e6-af26-2bf427140012        Zappa Event: {}
```

**Comment by Miserlou** [comment]
Oooof, that's a deep cut! Good bug. I'm not sure where in the stack this is happening though.

Do you need to call setLevel somewhere first? Is something somewhere trying to write to a temporary file outside of tmp? Not really sure what's going on here. Keep digging?

**Comment by jayfk** [comment]
> Do you need to call setLevel somewhere first?

Nope, but raven is probably doing something like this.

I'll keep digging over the weekend.

**Comment by aectann** [comment]
@jayfk hmm.. there seem to be an issue with default transport that sentry uses. I managed to make it work by setting requests transport explicitly.

```sentry = Sentry(app,
                client=Client(transport=RequestsHTTPTransport, dsn='https://user:pass@app.getsentry.com/id'))```

**Comment by aectann** [comment]
Got that in logs with default transport.

`Traceback (most recent call last):
  File "/var/task/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/var/task/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/var/task/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/var/task/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1199, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] Operation not permitted>
`

**Comment by jayfk** [comment]
That's interesting @aectann. Did you try to call the sentry client directly with `client.captureMessage()`?

**Comment by aectann** [comment]
I did, same results, works with requests transport. No luck with the
default one.

**Comment by Miserlou** [comment]
Welp, upstream wasn't very helpful: https://github.com/pallets/flask/issues/2008#issuecomment-245087224

**Comment by n3il** [comment]
Anyone have a fix? I just now got this error

**Comment by aectann** [comment]
@n3il have you tried RequestsHTTPTransport?

**Comment by etataurov** [comment]
I believe that issue is not related particularly to Flask, but to lambda function lifetime.
Flask example sends errors with synchronous transports (schemes like `sync+https`, `requests+https`) but fails to send with asynchronous (schemes: `async+https`(default transport), `gevent+https`, `threaded+requests+https`).
I haven't tried with Pyramid or Django, but with Bottle I get the same behavior.

Bottle example for the reference
```python
from bottle import route, run, request
import bottle


@route('/')
def index():
    request.app.sentry.captureMessage("Sentry won't get it with async transport")
    return 'Hello name!'

app = bottle.app()
app.catchall = False

from raven import Client
from raven.contrib.bottle import Sentry
client = Client('threaded+requests+https://<YOURDSN>')
app = Sentry(app, client)

if __name__ == '__main__':
    run(app, host='localhost', port=8080)
```

**Comment by dacut** [comment]
Here's a step closer to what's going on.

`Flask.log_exception()` is doing its normal thing making a call to `self.logger.error`. Doing some instrumentation on this shows the logger has two handlers:
    Start app.log_exception:
    self.logger=<flask.logging.DebugLogger object at 0x7fe7f0854e10>
    self.logger.handlers[0]=<flask.logging.DebugHandler object at 0x7fe7f0854bd0>
    self.logger.handlers[0].stream=<__main__.CustomFile object at 0x7fe801713650>
    self.logger.handlers[1]=<flask.logging.ProductionHandler object at 0x7fe7f0854d50>
    self.logger.handlers[1].stream=''

Wait, what? The ProductionHandler has a string as a stream. Or, rather, a string wrapped in a `werkzeug.local.LocalProxy`, which is what's returning the `getattr()`.

Flask's `flask.logger.create_logger()` function just does this:
    prod_handler = ProductionHandler(_proxy_stream)

`_proxy_stream` is the `werkzeug.local.LocalProxy` initialized by `flask.logger` thusly:
    @LocalProxy
    def _proxy_stream():
        """Finds the most appropriate error stream for the application.  If a
        WSGI request is in flight we log to wsgi.errors, otherwise this resolves
        to sys.stderr.
        """
        ctx = _request_ctx_stack.top
        if ctx is not None:
            return ctx.request.environ['wsgi.errors']
        return sys.stderr

Indeed, `ctx.request.envion['wsgi.errors']` is an empty string. I'm trying to figure out where the hell this is being initialized.

Lambda's runtime environment does have some WSGI handlers, and I know it plays games with the logger to make things go to the Lambda stream handlers (and eventually CloudWatch), but I suspect it's not there.

**Comment by dacut** [comment]
Aha! It's in zappa.wsgi:

       environ = {
            'PATH_INFO': path,
            'QUERY_STRING': query_string,
            'REMOTE_ADDR': remote_addr,
            'REQUEST_METHOD': method,
            'SCRIPT_NAME': str(script_name) if script_name else '',
            'SERVER_NAME': str(server_name),
            'SERVER_PORT': str('80'),
            'SERVER_PROTOCOL': str('HTTP/1.1'),
            'wsgi.version': (1, 0),
            'wsgi.url_scheme': str('http'),
            'wsgi.input': body,
            'wsgi.errors': str(''),
            'wsgi.multiprocess': False,
            'wsgi.multithread': False,
            'wsgi.run_once': False,
        }

Pull request coming your way.

**Comment by geeknam** [comment]
I have the same problem with django. does anyone know how bypass this issue?
My settings:

```python
INSTALLED_APPS += (
    'raven.contrib.django.raven_compat',
)

RAVEN_CONFIG = {
    'dsn': 'requests+https://key1:key2@sentry.io/project_id',
    'transport': 'raven.transport.requests.RequestsHTTPTransport'
}
```

**Comment by rustanacexd** [comment]
so this is fixed now?

**Comment by dacut** [comment]
Should be long fixed. Make sure you're up-to-date.

**Comment by scottwoodall** [comment]
(new to Zappa)

I'm seeing this error when trying to manually triggering a Sentry event (`zappa manage dev "raven test"`) with Zappa 0.45.1

```
[ERROR] 2017-12-27T16:09:49.944Z 3de4e094-eb20-11e7-bd40-7d3e8c21cbab Sentry responded with an error: <urlopen error [Errno 1] Operation not permitted> (url: https://sentry.io/api/264296/store/)
Traceback (most recent call last):
File "/var/lang/lib/python3.6/urllib/request.py", line 1318, in do_open
encode_chunked=req.has_header('Transfer-encoding'))
File "/var/lang/lib/python3.6/http/client.py", line 1239, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/var/lang/lib/python3.6/http/client.py", line 1285, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/var/lang/lib/python3.6/http/client.py", line 1234, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/var/lang/lib/python3.6/http/client.py", line 1026, in _send_output
self.send(msg)
File "/var/lang/lib/python3.6/http/client.py", line 964, in send
self.connect()
File "/var/task/raven/utils/http.py", line 31, in connect
timeout=self.timeout,
File "/var/lang/lib/python3.6/socket.py", line 722, in create_connection
raise err
File "/var/lang/lib/python3.6/socket.py", line 713, in create_connection
sock.connect(sa)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/task/raven/transport/threaded.py", line 165, in send_sync
super(ThreadedHTTPTransport, self).send(url, data, headers)
File "/var/task/raven/transport/http.py", line 43, in send
ca_certs=self.ca_certs,
File "/var/task/raven/utils/http.py", line 66, in urlopen
return opener.open(url, data, timeout)
File "/var/lang/lib/python3.6/urllib/request.py", line 526, in open
response = self._open(req, data)
File "/var/lang/lib/python3.6/urllib/request.py", line 544, in _open
'_open', req)
File "/var/lang/lib/python3.6/urllib/request.py", line 504, in _call_chain
result = func(*args)
File "/var/task/raven/utils/http.py", line 46, in https_open
return self.do_open(ValidHTTPSConnection, req)
File "/var/lang/lib/python3.6/urllib/request.py", line 1320, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 1] Operation not permitted>```

My `wsgi.py`:

```(caselogpro) scott@dev:/media/sf_source/personal/caselogpro$ more backend/wsgi.py
import os

from django.core.wsgi import get_wsgi_application
from raven import Client
from raven.middleware import Sentry
from raven.transport.requests import RequestsHTTPTransport

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings.devl')

application = Sentry(
    get_wsgi_application(),
    Client(
        os.environ.get('SENTRY_DSN'),
        transport=RequestsHTTPTransport
    ),
)
```

Thoughts or suggestions?

**Comment by heimann** [comment]
Are you in a VPC? I got a similar error before in a VPC when I hadn't properly configured a NAT Gateway.

**Comment by scottwoodall** [comment]
I am in a VPC. I setup an internet gateway but might of configured it wrong.

I’ll tinker with that and report back.

**Comment by heimann** [comment]
I've also typically not used Sentry like that in my WSGI config. I've just done 

```application = Sentry(get_wsgi_application())``` 
without passing the Client as the second argument. Been a little while since I used Sentry however so my knowledge might be out of date. 

Another thing you could try is removing the sentry WSGI middleware and running raven test with just the minimal setup to see if that yields a different outcome.

**Comment by dacut** [comment]
An Internet Gateway is not sufficient for IPv4 connectivity. You need to have a NAT instance (either your own or the AWS NAT Gateway) to translate the private IP address of the Lambda ENI to something routable, and the Lambda ENIs need to be in a subnet whose route table includes a default route to the NAT.

This isn't a problem with IPv6 -- everything "just works" there. Someday...

On Dec 27, 2017, at 9:00 AM, David Heimann <notifications@github.com<mailto:notifications@github.com>> wrote:


I've also typically not used Sentry like that in my WSGI config. I've just done

application = Sentry(get_wsgi_application())
without passing the Client as the second argument. Been a little while since I used Sentry however so my knowledge might be out of date.

Another thing you could try is removing the sentry WSGI middleware and running raven test with just the minimal setup to see if that yields a different outcome.

**Comment by anush0247** [comment]
with below config, its working fine for us, we tested a vpc enabled deployment

```python
INSTALLED_APPS += (
    'raven.contrib.django.raven_compat',
)

RAVEN_CONFIG = {
    'dsn': 'https://client_id:secret_key@sentry.io/project_id',
    'transport': 'raven.transport.requests.RequestsHTTPTransport'
}
```

**Comment by charlax** [comment]
Same thing, had to hardcode the transport:

```pythonn
from raven import Client
from raven.transport.http import HTTPTransport
from raven.contrib.flask import Sentry

client = Client(
    dsn=config.SENTRY_DSN,
    processors=(... ),
    release=config.BUILD,
    raise_send_errors=True,
    transport=HTTPTransport,
)
```
