### ISSUE TITLE
How to get a more detailed log?

### ISSUE THREAD

**Issue by michaelluk** [Miserlou/Zappa#301]
This is the full trace of my log. I was wondering how to get a more detailed log about the error? I believe there is something wrong with my setup as all I got is some encoded log, while the logs in  #164 and #283 are much more readable?  Thanks :)

**My json file**

> {
>   "dev": {
>     "project_name": "dev_botbrain",
>     "keep_warm": false,
>     "debug": true,
>     "log_level": "DEBUG",
>     "aws_region": "ap-northeast-1",
>     "django_settings": "config.settings.local",
>     "s3_bucket": "MY_BUCKET_NAME",
>     "timeout_seconds": 300,
>     "memory_size": 512,
>     "use_precompiled_packages": true,
>     "exclude": ["*.env"] // A list of regex patterns to exclude from the archive
>   }
> }

**Log tail**
`[1472804045000] 'NoneType' object has no attribute 'endswith'
[1472804045000] PCFET0NUWVBFIGh0bWw+NTAwLiBGcm9tIFphcHBhOiA8cHJlPidOb25lVHlwZScgb2JqZWN0IGhhcyBubyBhdHRyaWJ1dGUgJ2VuZHN3aXRoJzwvcHJlPjxiciAvPjxwcmU+VHJhY2ViYWNrIChtb3N0IHJlY2VudCBjYWxsIGxhc3QpOjxiciAvPiAgRmlsZSAiL3Zhci90YXNrL2hhbmRsZXIucHkiLCBsaW5lIDMwOCwgaW4gaGFuZGxlcjxiciAvPiAgICBhcHBfZnVuY3Rpb24gPSBnZXRfZGphbmdvX3dzZ2koc2V0dGluZ3MuREpBTkdPX1NFVFRJTkdTKTxiciAvPiAgRmlsZSAiL3Zhci90YXNrL2RqYW5nb196YXBwYV9hcHAucHkiLCBsaW5lIDE0LCBpbiBnZXRfZGphbmdvX3dzZ2k8YnIgLz4gICAgZGphbmdvLnNldHVwKCk8YnIgLz4gIEZpbGUgIi9wcml2YXRlL3Zhci9mb2xkZXJzLzJiL3dzY240bHExMnN2NW1zM2dyZmJoODIxaDAwMDBncC9UL3BpcC1idWlsZC1OY3NsRUIvZGphbmdvL2RqYW5nby9fX2luaXRfXy5weSIsIGxpbmUgMTgsIGluIHNldHVwPGJyIC8+ICBGaWxlICIvcHJpdmF0ZS92YXIvZm9sZGVycy8yYi93c2NuNGxxMTJzdjVtczNncmZiaDgyMWgwMDAwZ3AvVC9waXAtYnVpbGQtTmNzbEVCL2RqYW5nby9kamFuZ28vYXBwcy9yZWdpc3RyeS5weSIsIGxpbmUgMTE1LCBpbiBwb3B1bGF0ZTxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL2FwcHMucHkiLCBsaW5lIDE1LCBpbiByZWFkeTxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL3NldHRpbmdzLnB5IiwgbGluZSAyNDIsIGluIHBhdGNoX2FsbDxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL3NldHRpbmdzLnB5IiwgbGluZSAyMjEsIGluIHBhdGNoX21pZGRsZXdhcmVfY2xhc3NlczxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL3NldHRpbmdzLnB5IiwgbGluZSAyMDEsIGluIGlzX3Rvb2xiYXJfbWlkZGxld2FyZV9pbnN0YWxsZWQ8YnIgLz4gIEZpbGUgIi9wcml2YXRlL3Zhci9mb2xkZXJzLzJiL3dzY240bHExMnN2NW1zM2dyZmJoODIxaDAwMDBncC9UL3BpcC1idWlsZC1OY3NsRUIvZGphbmdvLWRlYnVnLXRvb2xiYXIvZGVidWdfdG9vbGJhci9taWRkbGV3YXJlLnB5IiwgbGluZSAxNiwgaW4gPG1vZHVsZT48YnIgLz4gIEZpbGUgIi9wcml2YXRlL3Zhci9mb2xkZXJzLzJiL3dzY240bHExMnN2NW1zM2dyZmJoODIxaDAwMDBncC9UL3BpcC1idWlsZC1OY3NsRUIvZGphbmdvLWRlYnVnLXRvb2xiYXIvZGVidWdfdG9vbGJhci90b29sYmFyLnB5IiwgbGluZSAxNTEsIGluIDxtb2R1bGU+PGJyIC8+ICBGaWxlICIvcHJpdmF0ZS92YXIvZm9sZGVycy8yYi93c2NuNGxxMTJzdjVtczNncmZiaDgyMWgwMDAwZ3AvVC9waXAtYnVpbGQtTmNzbEVCL2RqYW5nby1kZWJ1Zy10b29sYmFyL2RlYnVnX3Rvb2xiYXIvdG9vbGJhci5weSIsIGxpbmUgMTQ1LCBpbiBnZXRfdXJsczxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL3Rvb2xiYXIucHkiLCBsaW5lIDExOCwgaW4gZ2V0X3BhbmVsX2NsYXNzZXM8YnIgLz4gIEZpbGUgIi91c3IvbGliNjQvcHl0aG9uMi43L2ltcG9ydGxpYi9fX2luaXRfXy5weSIsIGxpbmUgMzcsIGluIGltcG9ydF9tb2R1bGU8YnIgLz4gICAgX19pbXBvcnRfXyhuYW1lKTxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL3BhbmVscy9fX2luaXRfXy5weSIsIGxpbmUgOCwgaW4gPG1vZHVsZT48YnIgLz4gIEZpbGUgIi9wcml2YXRlL3Zhci9mb2xkZXJzLzJiL3dzY240bHExMnN2NW1zM2dyZmJoODIxaDAwMDBncC9UL3BpcC1idWlsZC1OY3NsRUIvZGphbmdvLWRlYnVnLXRvb2xiYXIvZGVidWdfdG9vbGJhci91dGlscy5weSIsIGxpbmUgNDUsIGluIDxtb2R1bGU+PGJyIC8+ICBGaWxlICIvcHJpdmF0ZS92YXIvZm9sZGVycy8yYi93c2NuNGxxMTJzdjVtczNncmZiaDgyMWgwMDAwZ3AvVC9waXAtYnVpbGQtTmNzbEVCL2RqYW5nby1kZWJ1Zy10b29sYmFyL2RlYnVnX3Rvb2xiYXIvdXRpbHMucHkiLCBsaW5lIDM4LCBpbiBnZXRfbW9kdWxlX3BhdGg8YnIgLz5BdHRyaWJ1dGVFcnJvcjogJ05vbmVUeXBlJyBvYmplY3QgaGFzIG5vIGF0dHJpYnV0ZSAnZW5kc3dpdGgnPGJyIC8+PC9wcmU+: Exception
Traceback (most recent call last):
  File "/var/task/handler.py", line 414, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 153, in lambda_handler
    raise ex
Exception: PCFET0NUWVBFIGh0bWw+NTAwLiBGcm9tIFphcHBhOiA8cHJlPidOb25lVHlwZScgb2JqZWN0IGhhcyBubyBhdHRyaWJ1dGUgJ2VuZHN3aXRoJzwvcHJlPjxiciAvPjxwcmU+VHJhY2ViYWNrIChtb3N0IHJlY2VudCBjYWxsIGxhc3QpOjxiciAvPiAgRmlsZSAiL3Zhci90YXNrL2hhbmRsZXIucHkiLCBsaW5lIDMwOCwgaW4gaGFuZGxlcjxiciAvPiAgICBhcHBfZnVuY3Rpb24gPSBnZXRfZGphbmdvX3dzZ2koc2V0dGluZ3MuREpBTkdPX1NFVFRJTkdTKTxiciAvPiAgRmlsZSAiL3Zhci90YXNrL2RqYW5nb196YXBwYV9hcHAucHkiLCBsaW5lIDE0LCBpbiBnZXRfZGphbmdvX3dzZ2k8YnIgLz4gICAgZGphbmdvLnNldHVwKCk8YnIgLz4gIEZpbGUgIi9wcml2YXRlL3Zhci9mb2xkZXJzLzJiL3dzY240bHExMnN2NW1zM2dyZmJoODIxaDAwMDBncC9UL3BpcC1idWlsZC1OY3NsRUIvZGphbmdvL2RqYW5nby9fX2luaXRfXy5weSIsIGxpbmUgMTgsIGluIHNldHVwPGJyIC8+ICBGaWxlICIvcHJpdmF0ZS92YXIvZm9sZGVycy8yYi93c2NuNGxxMTJzdjVtczNncmZiaDgyMWgwMDAwZ3AvVC9waXAtYnVpbGQtTmNzbEVCL2RqYW5nby9kamFuZ28vYXBwcy9yZWdpc3RyeS5weSIsIGxpbmUgMTE1LCBpbiBwb3B1bGF0ZTxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL2FwcHMucHkiLCBsaW5lIDE1LCBpbiByZWFkeTxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL3NldHRpbmdzLnB5IiwgbGluZSAyNDIsIGluIHBhdGNoX2FsbDxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL3NldHRpbmdzLnB5IiwgbGluZSAyMjEsIGluIHBhdGNoX21pZGRsZXdhcmVfY2xhc3NlczxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL3NldHRpbmdzLnB5IiwgbGluZSAyMDEsIGluIGlzX3Rvb2xiYXJfbWlkZGxld2FyZV9pbnN0YWxsZWQ8YnIgLz4gIEZpbGUgIi9wcml2YXRlL3Zhci9mb2xkZXJzLzJiL3dzY240bHExMnN2NW1zM2dyZmJoODIxaDAwMDBncC9UL3BpcC1idWlsZC1OY3NsRUIvZGphbmdvLWRlYnVnLXRvb2xiYXIvZGVidWdfdG9vbGJhci9taWRkbGV3YXJlLnB5IiwgbGluZSAxNiwgaW4gPG1vZHVsZT48YnIgLz4gIEZpbGUgIi9wcml2YXRlL3Zhci9mb2xkZXJzLzJiL3dzY240bHExMnN2NW1zM2dyZmJoODIxaDAwMDBncC9UL3BpcC1idWlsZC1OY3NsRUIvZGphbmdvLWRlYnVnLXRvb2xiYXIvZGVidWdfdG9vbGJhci90b29sYmFyLnB5IiwgbGluZSAxNTEsIGluIDxtb2R1bGU+PGJyIC8+ICBGaWxlICIvcHJpdmF0ZS92YXIvZm9sZGVycy8yYi93c2NuNGxxMTJzdjVtczNncmZiaDgyMWgwMDAwZ3AvVC9waXAtYnVpbGQtTmNzbEVCL2RqYW5nby1kZWJ1Zy10b29sYmFyL2RlYnVnX3Rvb2xiYXIvdG9vbGJhci5weSIsIGxpbmUgMTQ1LCBpbiBnZXRfdXJsczxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL3Rvb2xiYXIucHkiLCBsaW5lIDExOCwgaW4gZ2V0X3BhbmVsX2NsYXNzZXM8YnIgLz4gIEZpbGUgIi91c3IvbGliNjQvcHl0aG9uMi43L2ltcG9ydGxpYi9fX2luaXRfXy5weSIsIGxpbmUgMzcsIGluIGltcG9ydF9tb2R1bGU8YnIgLz4gICAgX19pbXBvcnRfXyhuYW1lKTxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28tZGVidWctdG9vbGJhci9kZWJ1Z190b29sYmFyL3BhbmVscy9fX2luaXRfXy5weSIsIGxpbmUgOCwgaW4gPG1vZHVsZT48YnIgLz4gIEZpbGUgIi9wcml2YXRlL3Zhci9mb2xkZXJzLzJiL3dzY240bHExMnN2NW1zM2dyZmJoODIxaDAwMDBncC9UL3BpcC1idWlsZC1OY3NsRUIvZGphbmdvLWRlYnVnLXRvb2xiYXIvZGVidWdfdG9vbGJhci91dGlscy5weSIsIGxpbmUgNDUsIGluIDxtb2R1bGU+PGJyIC8+ICBGaWxlICIvcHJpdmF0ZS92YXIvZm9sZGVycy8yYi93c2NuNGxxMTJzdjVtczNncmZiaDgyMWgwMDAwZ3AvVC9waXAtYnVpbGQtTmNzbEVCL2RqYW5nby1kZWJ1Zy10b29sYmFyL2RlYnVnX3Rvb2xiYXIvdXRpbHMucHkiLCBsaW5lIDM4LCBpbiBnZXRfbW9kdWxlX3BhdGg8YnIgLz5BdHRyaWJ1dGVFcnJvcjogJ05vbmVUeXBlJyBvYmplY3QgaGFzIG5vIGF0dHJpYnV0ZSAnZW5kc3dpdGgnPGJyIC8+PC9wcmU+
[1472804049811] Zappa Event: {u'body': u'e30=', u'headers': {u'Via': u'1.1 519d155fc93511a6839f1aee56b9fd49.cloudfront.net (CloudFront)', u'Accept-Language': u'en-US,en;q=0.8,zh-CN;q=0.6,zh-TW;q=0.4', u'Accept-Encoding': u'gzip, deflate, sdch, br', u'CloudFront-Is-SmartTV-Viewer': u'false', u'CloudFront-Forwarded-Proto': u'https', u'X-Forwarded-For': u'183.xx.xx.xx, 54.xx.xx.xx', u'CloudFront-Viewer-Country': u'HK', u'Accept': u'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', u'Upgrade-Insecure-Requests': u'1', u'Host': u'avdi94s8fd.execute-api.ap-northeast-1.amazonaws.com', u'X-Forwarded-Proto': u'https', u'X-Amz-Cf-Id': u'gC-_wPE85Jk53p42qe5UVdPwGl2NsgbMO5DCGKeQ8061CQ3l_W-vag==', u'CloudFront-Is-Tablet-Viewer': u'false', u'X-Forwarded-Port': u'443', u'User-Agent': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36', u'CloudFront-Is-Mobile-Viewer': u'false', u'CloudFront-Is-Desktop-Viewer': u'true'}, u'params': {}, u'method': u'GET', u'query': {}}
[1472804049811] [DEBUG] 2016-09-02T08:14:09.811Z    399b9d96-70e5-11e6-a0da-7dad31de2e92    Zappa Event: {u'body': u'e30=', u'headers': {u'Via': u'1.1 519d155fc93511a6839f1aee56b9fd49.cloudfront.net (CloudFront)', u'Accept-Language': u'en-US,en;q=0.8,zh-CN;q=0.6,zh-TW;q=0.4', u'Accept-Encoding': u'gzip, deflate, sdch, br', u'CloudFront-Is-SmartTV-Viewer': u'false', u'CloudFront-Forwarded-Proto': u'https', u'X-Forwarded-For': u'183.xx.xx.xx, 54.xx.xx.xx', u'CloudFront-Viewer-Country': u'HK', u'Accept': u'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', u'Upgrade-Insecure-Requests': u'1', u'Host': u'avdi94s8fd.execute-api.ap-northeast-1.amazonaws.com', u'X-Forwarded-Proto': u'https', u'X-Amz-Cf-Id': u'gC-_wPE85Jk53p42qe5UVdPwGl2NsgbMO5DCGKeQ8061CQ3l_W-vag==', u'CloudFront-Is-Tablet-Viewer': u'false', u'X-Forwarded-Port': u'443', u'User-Agent': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36', u'CloudFront-Is-Mobile-Viewer': u'false', u'CloudFront-Is-Desktop-Viewer': u'true'}, u'params': {}, u'method': u'GET', u'query': {}}
[1472804049812] populate() isn't reentrant
[1472804049812] PCFET0NUWVBFIGh0bWw+NTAwLiBGcm9tIFphcHBhOiA8cHJlPnBvcHVsYXRlKCkgaXNuJ3QgcmVlbnRyYW50PC9wcmU+PGJyIC8+PHByZT5UcmFjZWJhY2sgKG1vc3QgcmVjZW50IGNhbGwgbGFzdCk6PGJyIC8+ICBGaWxlICIvdmFyL3Rhc2svaGFuZGxlci5weSIsIGxpbmUgMzA4LCBpbiBoYW5kbGVyPGJyIC8+ICAgIGFwcF9mdW5jdGlvbiA9IGdldF9kamFuZ29fd3NnaShzZXR0aW5ncy5ESkFOR09fU0VUVElOR1MpPGJyIC8+ICBGaWxlICIvdmFyL3Rhc2svZGphbmdvX3phcHBhX2FwcC5weSIsIGxpbmUgMTQsIGluIGdldF9kamFuZ29fd3NnaTxiciAvPiAgICBkamFuZ28uc2V0dXAoKTxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28vZGphbmdvL19faW5pdF9fLnB5IiwgbGluZSAxOCwgaW4gc2V0dXA8YnIgLz4gIEZpbGUgIi9wcml2YXRlL3Zhci9mb2xkZXJzLzJiL3dzY240bHExMnN2NW1zM2dyZmJoODIxaDAwMDBncC9UL3BpcC1idWlsZC1OY3NsRUIvZGphbmdvL2RqYW5nby9hcHBzL3JlZ2lzdHJ5LnB5IiwgbGluZSA3OCwgaW4gcG9wdWxhdGU8YnIgLz5SdW50aW1lRXJyb3I6IHBvcHVsYXRlKCkgaXNuJ3QgcmVlbnRyYW50PGJyIC8+PC9wcmU+: Exception
Traceback (most recent call last):
  File "/var/task/handler.py", line 414, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 153, in lambda_handler
    raise ex
Exception: PCFET0NUWVBFIGh0bWw+NTAwLiBGcm9tIFphcHBhOiA8cHJlPnBvcHVsYXRlKCkgaXNuJ3QgcmVlbnRyYW50PC9wcmU+PGJyIC8+PHByZT5UcmFjZWJhY2sgKG1vc3QgcmVjZW50IGNhbGwgbGFzdCk6PGJyIC8+ICBGaWxlICIvdmFyL3Rhc2svaGFuZGxlci5weSIsIGxpbmUgMzA4LCBpbiBoYW5kbGVyPGJyIC8+ICAgIGFwcF9mdW5jdGlvbiA9IGdldF9kamFuZ29fd3NnaShzZXR0aW5ncy5ESkFOR09fU0VUVElOR1MpPGJyIC8+ICBGaWxlICIvdmFyL3Rhc2svZGphbmdvX3phcHBhX2FwcC5weSIsIGxpbmUgMTQsIGluIGdldF9kamFuZ29fd3NnaTxiciAvPiAgICBkamFuZ28uc2V0dXAoKTxiciAvPiAgRmlsZSAiL3ByaXZhdGUvdmFyL2ZvbGRlcnMvMmIvd3NjbjRscTEyc3Y1bXMzZ3JmYmg4MjFoMDAwMGdwL1QvcGlwLWJ1aWxkLU5jc2xFQi9kamFuZ28vZGphbmdvL19faW5pdF9fLnB5IiwgbGluZSAxOCwgaW4gc2V0dXA8YnIgLz4gIEZpbGUgIi9wcml2YXRlL3Zhci9mb2xkZXJzLzJiL3dzY240bHExMnN2NW1zM2dyZmJoODIxaDAwMDBncC9UL3BpcC1idWlsZC1OY3NsRUIvZGphbmdvL2RqYW5nby9hcHBzL3JlZ2lzdHJ5LnB5IiwgbGluZSA3OCwgaW4gcG9wdWxhdGU8YnIgLz5SdW50aW1lRXJyb3I6IHBvcHVsYXRlKCkgaXNuJ3QgcmVlbnRyYW50PGJyIC8+PC9wcmU+`

**Comment by Miserlou** [comment]
It looks like those errors are only happening with Django deployments? I'm not completely sure.  Let's see.

**Comment by michaelluk** [comment]
Oh no! Just found out that the encoded string is in base64 format. I can see the error now :)

**Comment by michaelluk** [comment]
@Miserlou Yeah, just trying to deploy a django project created by https://github.com/pydanny/cookiecutter-django to see whether all the packages are supported. The debugging life can be much more easier to have a more detailed log.

**Comment by Miserlou** [comment]
Yeah, absolutely. Really annoying to see that encoded exception in the logs.

**Comment by koriaf** [comment]
btw have you fixed reentrant exception? I had it a week ago, then fixed it, and now I'm having it again and have already forgot what to do.

**Comment by Miserlou** [comment]
No more B64 going on, this is no longer relevant.
