### ISSUE TITLE
Too naive VPC setting getter

### ISSUE THREAD

**Issue by koriaf** [Miserlou/Zappa#326]
When:
```
zappa status
```
And no VPC used, I see
```
Traceback (most recent call last):
  File "/xxx/.venv/lib/python2.7/site-packages/zappa/cli.py", line 1224, in handle
    sys.exit(cli.handle())
  File "/xxx/.venv/lib/python2.7/site-packages/zappa/cli.py", line 223, in handle
    self.status()
  File "/xxx/.venv/lib/python2.7/site-packages/zappa/cli.py", line 641, in status
    tabular_print("Lambda VPC ID", conf['VpcConfig']['VpcId'])
KeyError: u'VpcId'
```

There is probably shall be `conf.get('VpcConfig', {}).get('VpcId', 'Not assigned')`

**Comment by Miserlou** [comment]
👍 👍 👍
