### ISSUE TITLE
DynamoDB streams as event source is broken  

### ISSUE THREAD

**Issue by claudeatsafe** [Miserlou/Zappa#333]
I could identify two issues, first it seems like in https://github.com/Miserlou/Zappa/blob/master/zappa/util.py#L151 the name should be the Lambda ARN and not the function name (`funk.name = lambda_arn`). Otherwise I get the following error:
```
Traceback (most recent call last):
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/zappa/cli.py", line 1251, in handle
    sys.exit(cli.handle())
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/zappa/cli.py", line 219, in handle
    self.schedule()
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/zappa/cli.py", line 563, in schedule
    events=events
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/zappa/zappa.py", line 1212, in schedule_events
    self.unschedule_events(lambda_name=lambda_name, lambda_arn=lambda_arn, events=events)
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/zappa/zappa.py", line 1358, in unschedule_events
    self.boto_session
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/zappa/util.py", line 192, in remove_event_source
    rule_response = event_source_obj.remove(funk)
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/kappa/event_source/kinesis.py", line 96, in remove
    uuid = self._get_uuid(function)
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/kappa/event_source/kinesis.py", line 36, in _get_uuid
    EventSourceArn=self.arn)
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/kappa/awsclient.py", line 83, in call
    data = results.build_full_result()
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/botocore/paginate.py", line 290, in build_full_result
    for response in self:
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/botocore/paginate.py", line 102, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/botocore/paginate.py", line 174, in _make_request
    return self._method(**current_kwargs)
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ValidationException) when calling the ListEventSourceMappings operation: 1 validation error detected: Value 'replication.replicate_records' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws:lambda:)?([a-z]{2}-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?
```

The second issue is related to the `create_event_permission` call in the `schedule_events` function (https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L1263). It seems like this is not necessary for DynamoDB streams events, it started working once I commented that section out.

Anyways, I do not fully understand yet how this exactly works, so before I open a pull request and break a whole bunch of other things, any idea what is wrong and what is the best way to fix it?

**Comment by Miserlou** [comment]
Annoying, I haven't used DDB as an event source myself yet. Thanks for reporting. The create_event_permissions is definitely needed for S3 events, maybe useless for other events, and apparently detrimental for DDB events.

This stuff is full of quirks that need sending through trial and error like this. Hopefully it'll be an easy fix and we can get it in the next release tomorrow.

**Comment by claudeatsafe** [comment]
Would you like to give me a try to fix it, or are you looking into it?

**Comment by Miserlou** [comment]
If you're blocking on this right now and you know what to expect, please by all means, be my guest and try to fix it.

**Comment by claudeatsafe** [comment]
Alright, I have a look.
