### ISSUE TITLE
Flag use_apigateway is ignored on undeploy

### ISSUE THREAD

**Issue by claudeatsafe** [Miserlou/Zappa#342]
With the introduction of CloudFormation, the flag `use_apigateway` is ignored on `undeploy`. If I deploy a Zappa function with the setting `use_apigateway: false` I get the following error message on undeploy:
```
Deleting API Gateway..
ERROR:Could not get API id
Traceback (most recent call last):
  File "/Users/cvessaz/Development/zappa/zappa/zappa.py", line 1109, in get_api_id
    LogicalResourceId='Api')
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the DescribeStackResource operation: Stack 'tokenservice-dev-us-west-2' does not exist
No Zappa stack named tokenservice-dev-us-west-2
```

**Comment by claudeatsafe** [comment]
I should clarify, the script keeps working and jumps to unscheduling, but it could be slightly less verbose.

**Comment by Miserlou** [comment]
Ah, excellent catch.

`use_apitgateway` needs some love generally, IMO. I think we could be better at doing non-web server-less services.

Are there other ways you think we could improve in this regard?

**Comment by Miserlou** [comment]
@mathom :)

**Comment by claudeatsafe** [comment]
Do you mind re-opening this issue? This is also a problem during update:
```
(tokenserviceenv) GLOBI:tokenservice cvessaz$ zappa update
Packaging project as zip...
Uploading tokenservice-dev-us-west-2-1474674378.zip (2.4MiB)...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.48M/2.48M [00:32<00:00, 57.9KB/s]
Updating Lambda function code..
Updating Lambda function configuration..
Uploading tokenservice-dev-us-west-2-template-1474674419.json (338.6KiB)...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 347K/347K [00:02<00:00, 143KB/s]
CloudFormation stack missing, re-deploy to enable updates
ERROR:Could not get API id
Traceback (most recent call last):
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/zappa/zappa.py", line 1109, in get_api_id
    LogicalResourceId='Api')
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the DescribeStackResource operation: Stack 'tokenservice-dev-us-west-2' does not exist
```

**Comment by Miserlou** [comment]
👍
