### ISSUE TITLE
Function for event_source SNS does not fire.

### ISSUE THREAD

**Issue by mguidone** [Miserlou/Zappa#370]
When providing the following configuration. The function <my_file.my_function> does not fire when and sms Publish event occurs. However, the "lambda_handler": "my_file.lambda_handler" DOES fire.

> 		"events": [
> 			{
> 			"function": "my_file.my_function",
> 			"event_source": {
> 				"arn":  "arn:aww:sns:usda-prime-2:112122552617:my-sns-queue",
> 				"events": [
> 					"sms:Publish"
> 					]
> 				}
> 			}
> 		],
>

**Comment by Miserlou** [comment]
sns:Publish, not sms:Publish?

**Comment by mguidone** [comment]
Darn MAC spell checker.  I edited out some of my settings and the Mac/Safari auto-correct preferred 'sms'


> 				"events": [
> 					"sns:Publish"
> 					]
> 				}
>

**Comment by mguidone** [comment]
I do get the sns events, in the lambda_handler, just not in the function specified there.

**Comment by Miserlou** [comment]
Do you see anything in the logs if you do `zappa tail`?

Ideally, there should be an event dictionary with a Records: item in it.

**Comment by mguidone** [comment]
Learned something new... zappa tail 

The only lines I get in tail are the following..   

[1475264415474] [INFO]	2016-09-30T19:40:15.474Z	b5c79e14-8745-11e6-8e34-ab94c3735340	Starting new HTTPS connection (1): hooks.slack.com
[1475264470433] [INFO]	2016-09-30T19:41:10.433Z	d68dd085-8745-11e6-a723-1923db42bf9f	Starting new HTTPS connection (1): hooks.slack.com

**Comment by mguidone** [comment]
zappa status however assume I have 'use_apigateway: true' and crashes as such...

ERROR:Could not get API ID.
Traceback (most recent call last):
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/zappa/zappa.py", line 1117, in get_api_id
    LogicalResourceId='Api')
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the DescribeStackResource operation: Stack 'gateway-events-staging' does not exist
	API Gateway URL:      None
ERROR:Could not get API ID.
Traceback (most recent call last):
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/zappa/zappa.py", line 1117, in get_api_id
    LogicalResourceId='Api')
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the DescribeStackResource operation: Stack 'gateway-events-staging' does not exist
	Domain URL:           None Supplied

**Comment by mguidone** [comment]
Seems very odd to me. Its almost as if the __init__ on the LambdaHandler class isn't getting called. I don't get any of the logging from there showing up at all.

**Comment by parroyo** [comment]
I've just tested it with the latest package in pip (zappa==0.26.0) and it works fine for me.

@mguidone The function to process the SNS message must have two parameters: event and context, something like that:
```
def read_topic(event, context):
    print("SNS message received!")
```
Otherwise, the function won't be invoked.
Once your project is deployed, you can check the SNS subscription in the AWS UI in the lambda panel or in the SNS Topic panel. 

I don't think the zappa status issue is related to the SNS event processing.

I hope it helps.

**Comment by mguidone** [comment]
Apologies...  This thread strayed a bit.
