### ISSUE TITLE
zappa status raises exception on NON-wsgi projects. 

### ISSUE THREAD

**Issue by mguidone** [Miserlou/Zappa#377]
On status reporting for **API Gateway UR**L and **Domain URL** status raises an exception if your Zappa project is non-wsgi and using use_apigateway: false.

```
	Error Rate (24h):     0.00%
ERROR:Could not get API ID.
Traceback (most recent call last):
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/zappa/zappa.py", line 1117, in get_api_id
    LogicalResourceId='Api')
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the DescribeStackResource operation: Stack 'gateway-events-staging' does not exist
	API Gateway URL:      None
ERROR:Could not get API ID.
Traceback (most recent call last):
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/zappa/zappa.py", line 1117, in get_api_id
    LogicalResourceId='Api')
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mguidone/Envs/lambda-work/lib/python2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the DescribeStackResource operation: Stack 'gateway-events-staging' does not exist
	Domain URL:           None Supplied
```

**Comment by Miserlou** [comment]
This is actually already fixed in master, thanks for reporting!

**Comment by pavlo-p** [comment]
it is still reproduced on 0.28.2
