### ISSUE TITLE
NameError: global name 'yellow' is not defined

### ISSUE THREAD

**Issue by claudeatsafe** [Miserlou/Zappa#393]
```
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/zappa/cli.py", line 1370, in handle
    sys.exit(cli.handle())
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/zappa/cli.py", line 196, in handle
    self.deploy()
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/zappa/cli.py", line 302, in deploy
    self.schedule()
  File "/Users/cvessaz/.virtualenvs/tokenserviceenv/lib/python2.7/site-packages/zappa/cli.py", line 598, in schedule
    click.echo(click.style("Function does not exist", fg=yellow) + ", please " + click.style("deploy", bold=True) + "first. Ex:" + click.style("zappa deploy {}.".format(self.api_stage), bold=True))
NameError: global name 'yellow' is not defined

==============
```

**Comment by claudeatsafe** [comment]
I am using Zappa 0.27.0.

**Comment by Miserlou** [comment]
Good catch. Really dumb bug.
