### ISSUE TITLE
Bad creation of event name

### ISSUE THREAD

**Issue by kwellman** [Miserlou/Zappa#450]
Zappa is creating event names incorrectly. When I deploy, this is what gets scheduled:
                                                                                                   
    Scheduled myprojectname12-production-zappa-keep-warm-ha.keep_warm_callback!                                        
    Scheduled myprojectname12-production-zappa-le-certify-han.certify_callback!

The output of my logs shows that this results in an error:

    [1478189485992] [DEBUG] 2016-11-03T16:11:25.992Z        2baf8cde-a1e0-11e6-9b47-4dcbbd87d28d    Zappa Event: {u'acc
    ount': u'123456789', u'region': u'us-east-1', u'detail': {}, u'detail-type': u'Scheduled Event', u'source': u'aw
    s.events', u'version': u'0', u'time': u'2016-11-03T16:10:58Z', u'id': u'2d815cc7-02f8-4ff1-bb07-702892a067a2', u'resource
    s': [u'arn:aws:events:us-east-1:123456789:rule/myprojectname12-production-zappa-keep-warm-ha.keep_warm_callback']}                                                                                                           
    [1478189485992] No module named ha: ImportError                                                                    
    Traceback (most recent call last):                                                                                 
      File "/var/task/handler.py", line 477, in lambda_handler                                                         
        return LambdaHandler.lambda_handler(event, context)                                                            
      File "/var/task/handler.py", line 208, in lambda_handler                                                         
        raise ex                                                                                                       
    ImportError: No module named ha

Seems like zappa is not shortening long names correctly.

**Comment by kwellman** [comment]
Duplicate of  #403
