### ISSUE TITLE
Windows os.path.join bug 

### ISSUE THREAD

**Issue by Benoss** [Miserlou/Zappa#453]
Line 1432 of cli.py
django_py = ''.join(os.path.join([base, os.sep, 'ext', os.sep, 'django_zappa.py']))

os.path.join signature is join(path, *paths) not join(*paths) i am not sure why it is not crashing on Linux

Removing the list remove the initial traceback but return the wrong path
```
 >>> os.path.join('c:\\users\\benoit\\envs\\zappa_test_env\\lib\\site-packages\\zappa', '\\', u'ext', '\\', u'django_zappa.py')
u'c:\\django_zappa.py'
```

Fix is as simple as changing the line to 
django_py = ''.join(os.path.join(base, 'ext',  'django_zappa.py'))

Here is the simple stacktrace
```
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> os.path.join(['c:\\users\\benoit\\envs\\zappa_test_env\\lib\\site-packages\\zappa', 'ext', 'django_zappa.py'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'os' is not defined
>>> import os
>>> os.path.join(['c:\\users\\benoit\\envs\\zappa_test_env\\lib\\site-packages\\zappa', 'ext', 'django_zappa.py'])
['c:\\users\\benoit\\envs\\zappa_test_env\\lib\\site-packages\\zappa', 'ext', 'django_zappa.py']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Benoit\Envs\zappa_test_env\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Users\Benoit\Envs\wolcen_server_env\lib\ntpath.py", line 117, in splitdrive
    normp = p.replace(altsep, sep)
AttributeError: 'list' object has no attribute 'replace'
>>>
```

**Comment by Miserlou** [comment]
Good catch, also confused about why it's working on nix and not Windows. Want to submit a PR?

**Comment by Benoss** [comment]
Done

**Comment by Miserlou** [comment]
👍
