### ISSUE TITLE
ImportError: No module named migrations.exceptions

### ISSUE THREAD

**Issue by codalprashant** [Miserlou/Zappa#464]
[1478786097289] No module named migrations.exceptions: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 477, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 186, in lambda_handler
    handler = cls()
  File "/var/task/handler.py", line 126, in __init__
    wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)
  File "/var/task/django_zappa_app.py", line 20, in get_django_wsgi
    return get_wsgi_application()
  File "/var/task/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/tmp/pip-build-fFPMfx/django/django/__init__.py", line 20, in setup
  File "/tmp/pip-build-fFPMfx/django/django/utils/log.py", line 10, in <module>
  File "/var/task/django/core/management/__init__.py", line 13, in <module>
    from django.core.management.base import (
  File "/var/task/django/core/management/base.py", line 17, in <module>
    from django.db.migrations.exceptions import MigrationSchemaMissing
ImportError: No module named migrations.exceptions

with django 1.10 and zappa 0.28.4

[URL] = https://959103f814.execute-api.us-east-1.amazonaws.com/develop

**Comment by Miserlou** [comment]
You'll need to post more information, when does this occur, what are your settings, etc..

**Comment by codalprashant** [comment]
zappa deploy develop works fine. My zappa_settings.json
{ "develop": { "aws_region": "us-east-1", "django_settings": "newpro.settings", "s3_bucket": "newprobucket" } }


watching using tail gives that error

**Comment by khaliullov** [comment]
@codalprashant got the same problems with the latest Django==1.10.3
just use Djanog==1.9.11

@Miserlou  if you want to reproduce use this commit: https://github.com/khaliullov/MoonshineBot/commit/9bd6a0b36953665006917a2a7f9bf133ba49d334

problem occurs because zip does not containt django.db.migrations.exceptions.pyc and some other precompiled files in this folder.

**Comment by bjinwright** [comment]
This is what I was talking about the other day. I can confirm as well.

**Comment by bjinwright** [comment]
It happens with zappa==0.28.3 only. If you downgrade to 0.28.2 it works fine.

**Comment by Miserlou** [comment]
Was it caused by this?: https://github.com/Miserlou/Zappa/issues/436
