### ISSUE TITLE
Packaging project as zip.. Oh no! An error occurred! :(

### ISSUE THREAD

**Issue by bl4ckmesa** [Miserlou/Zappa#485]
```(env) aperture:fs_aws aaronr$ zappa deploy dev
Calling deploy for environment dev..
Downloading and installing dependencies..
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 90/90 [00:33<00:00,  2.65pkg/s]
Packaging project as zip..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/zappa/cli.py", line 1577, in handle
    sys.exit(cli.handle())
  File "/Library/Python/2.7/site-packages/zappa/cli.py", line 245, in handle
    self.dispatch_command(self.command, environment)
  File "/Library/Python/2.7/site-packages/zappa/cli.py", line 277, in dispatch_command
    self.deploy()
  File "/Library/Python/2.7/site-packages/zappa/cli.py", line 359, in deploy
    self.create_package()
  File "/Library/Python/2.7/site-packages/zappa/cli.py", line 1374, in create_package
    app_module, app_function = self.app_function.rsplit('.', 1)
ValueError: need more than 1 value to unpack

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
(env) aperture:fs_aws aaronr$

### I'm just starting from scratch, building a basic flask app like in your demo.  Here's 
### some more context, since it's all short enough to include:

```(env) aperture:fs_aws aaronr$ ls
env                 my_app.py           zappa_settings.json
(env) aperture:fs_aws aaronr$ cat my_app.py 
from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello():
    return "Hello, from Zappa!\n"

if __name__ == '__main__':
    app.run()
(env) aperture:fs_aws aaronr$ cat zappa_settings.json 
{
    "dev": {
        "app_function": "demo", 
        "s3_bucket": "zappa-pke0w6cg3"
    }
}(env) aperture:fs_aws aaronr$
Running on a Mac, OS 10.12.1

**Comment by Miserlou** [comment]
Your app_function is a modular path, not just a string. Ex, `my_app.app`, not `demo`. This should be automatically detected by `zappa init`.

**Comment by Miserlou** [comment]
Added a check to explain this.
