### ISSUE TITLE
ImportError - unable to import Zappa

### ISSUE THREAD

**Issue by mcowger** [Miserlou/Zappa#489]
Created a brand new venv, and have it activated, with zappa installed:

```
(alexa) PS C:\Users\cowgem\PycharmProjects\AlexaFordSkill> pip check zappa
No broken requirements found.
```
can 
But yet no zappa commands can run:

```
(alexa) PS C:\Users\cowgem\PycharmProjects\AlexaFordSkill> zappa init
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cowgem\venv\alexa\Scripts\zappa.exe\__main__.py", line 5, in <module>
  File "c:\users\cowgem\venv\alexa\lib\site-packages\zappa\cli.py", line 38, in <module>
    from zappa import Zappa, logger, API_GATEWAY_REGIONS
ImportError: cannot import name 'Zappa'
```

**Comment by Miserlou** [comment]
You're using Python3. See: https://github.com/Miserlou/Zappa/issues/6#issuecomment-262605572
