### ISSUE TITLE
ImportError using Zappa to connect to Cassandra

### ISSUE THREAD

**Issue by haonans** [Miserlou/Zappa#526]
I just started using Zappa and thank you so much for this great project.

I am trying to use Zappa to connect to Cassandra cluster but I encountered this problem. 

```
[1481141556190] [DEBUG] 2016-12-07T20:12:36.174Z 7ea1bfb0-bcb9-11e6-8a1f-4b5e8a83f51d Zappa Event: {}
[1481141588746] /var/task/cassandra/cluster.so: invalid ELF header: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 479, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 189, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 116, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
  __import__(name)
  File "/var/task/app.py", line 16, in <module>
  import models
  File "/Users/haonans/Development/SOA-Backend-System/app_recommender/models.py", line 3, in <module>
  File "/var/task/cassandra/cqlengine/connection.py", line 20, in <module>
  from cassandra.cluster import Cluster, _NOT_SET, NoHostAvailable, UserTypeDoesNotExist
ImportError: /var/task/cassandra/cluster.so: invalid ELF header
```

I tested locally, it works well.

Thank you!

**Comment by Miserlou** [comment]
> ImportError: /var/task/cassandra/cluster.so: invalid ELF header

I assume you're using OSX locally? You will need to use a version of Cassandra compiled for X64 linux. More here: https://github.com/Miserlou/lambda-packages

**Comment by haonans** [comment]
@Miserlou Hi Rich, yeah, I am using OSX locally. I checked out the link, but cassandra-driver is not currently supported. I will try to rebuild my app on Linux to see if the problem is solved or not.

**Comment by Miserlou** [comment]
Lambda Packages will give you instructions on how to build and scoop what you need on an EC2 box. If you do that, please submit cassandra to lambda-packages so all other Zappa users get the benefit please!

**Comment by haonans** [comment]
I will try it out and if it works, I'll definitely share it!

**Comment by Miserlou** [comment]
Woot!

**Comment by haonans** [comment]
@Miserlou Ubuntu doesn't work for me but Amazon Linux does! I will create a PR asap. Thank you Rich!
