### ISSUE TITLE
An uncaught exception happened while servicing this request

### ISSUE THREAD

**Issue by sarlindo** [Miserlou/Zappa#537]
**python** version - 2.7.12
**Ubuntu:** 16.04
**zappa:** 0.31.0

I am trying to simply deploy an existing django app using zappa and I have got to finally work in terms of actually deploying to aws/lambda, but when I go to the end point url I am getting this error:

```{
    "message": "An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.", 
    "traceback": [
        "Traceback (most recent call last):\n", 
        "  File \"/var/task/handler.py\", line 406, in handler\n    response = Response.from_app(self.wsgi_app, environ)\n", 
        "  File \"/tmp/pip-build-7SmY5d/Werkzeug/werkzeug/wrappers.py\", line 865, in from_app\n", 
        "  File \"/tmp/pip-build-7SmY5d/Werkzeug/werkzeug/wrappers.py\", line 57, in _run_wsgi_app\n", 
        "  File \"/tmp/pip-build-7SmY5d/Werkzeug/werkzeug/test.py\", line 871, in run_wsgi_app\n", 
        "TypeError: 'NoneType' object is not callable\n"
    ]
}
```

## tail with zappa shows this:

```[1481681849422] Import by filename is not supported.: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 479, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 189, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 129, in __init__
  wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)
  File "/var/task/django_zappa_app.py", line 20, in get_django_wsgi
  return get_wsgi_application()
  File "/tmp/pip-build-H2vIYI/Django/django/core/wsgi.py", line 13, in get_wsgi_application
  File "/tmp/pip-build-H2vIYI/Django/django/__init__.py", line 22, in setup
  File "/tmp/pip-build-H2vIYI/Django/django/conf/__init__.py", line 53, in __getattr__
  File "/tmp/pip-build-H2vIYI/Django/django/conf/__init__.py", line 41, in _setup
  File "/tmp/pip-build-H2vIYI/Django/django/conf/__init__.py", line 97, in __init__
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
  __import__(name)
```
## my zappa_settings.json file looks like this:
```
{
    "production": {
       "s3_bucket": "sptdbt123",
       "django_settings": "/home/arlindo/projects/poker/poker/settings.py"
    }
}
```

**Comment by Miserlou** [comment]
> File "/var/task/django_zappa_app.py", line 20, in get_django_wsgi

What's that?

**Comment by sarlindo** [comment]
Not sure where that came from? its not in my django project.

**Comment by Miserlou** [comment]
Oh, you're right! My bad.

**Comment by Miserlou** [comment]
What's the Django version?

Does your Django settings do something like importing from another file?

**Comment by sarlindo** [comment]
Django==1.10.4

**Comment by sarlindo** [comment]
settings file is as such:

```
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SECRET_KEY = '{{ django_secretkey }}'

DEBUG = True

TEMPLATE_DEBUG = True

ALLOWED_HOSTS = ['*']

import django.conf.global_settings as DEFAULT_SETTINGS

STATIC_URL = '/static/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.spt',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'poker.middleware.LastSiteUrl',
)

ROOT_URLCONF = 'poker.urls'

WSGI_APPLICATION = 'poker.wsgi.application'

DATABASES = {
    'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': '{{ rdsi_dbname }}',
            'USER': '{{ rds_dbuser }}',
            'PASSWORD': '{{ rds_dbpassword }}',
            'HOST': '{{ rds_endpointhost }}',
            'PORT': '{{ rds_dbport }}',
    }
}
```

**Comment by sarlindo** [comment]
project directory tree looks like this:

```
.
├── apps
│   ├── __init__.py
│   └── spt
│       ├── admin.py
│       ├── dbutil.py
│       ├── __init__.py
│       ├── models.py
│       ├── static
│       │   ├── admin
│       │   │   ├── base.css
│       │   │   ├── css
│       │   │   │   ├── base.css
│       │   │   │   ├── rtl.css
│       │   │   │   └── widgets.css
│       │   │   ├── img
│       │   │   │   ├── changelist-bg.gif
│       │   │   │   ├── default-bg-reverse.gif
│       │   │   │   ├── deleted-overlay.gif
│       │   │   │   ├── gis
│       │   │   │   │   ├── move_vertex_off.png
│       │   │   │   │   └── move_vertex_on.png
│       │   │   │   ├── icon_addlink.gif
│       │   │   │   ├── icon_alert.gif
│       │   │   │   └── tooltag-arrowright.png
│       │   │   └── js
│       │   │       ├── actions.js
│       │   │       ├── actions.min.js
│       │   │       ├── admin
│       │   │       │   ├── DateTimeShortcuts.js
│       │   │       │   └── RelatedObjectLookups.js
│       │   │       ├── calendar.js
│       │   │       ├── collapse.js
│       │   │       ├── collapse.min.js
│       │   │       ├── core.js
│       │   │       ├── inlines.js
│       │   │       ├── inlines.min.js
│       │   │       ├── jquery.init.js
│       │   │       ├── jquery.js
│       │   │       ├── jquery.min.js
│       │   │       ├── LICENSE-JQUERY.txt
│       │   │       ├── prepopulate.js
│       │   │       ├── prepopulate.min.js
│       │   │       ├── related-widget-wrapper.js
│       │   │       ├── SelectBox.js
│       │   │       ├── SelectFilter2.js
│       │   │       ├── timeparse.js
│       │   │       └── urlify.js
│       │   ├── favicon.ico
│       │   ├── image
│       │   │   ├── aces1.jpg
│       │   │   ├── wrap_bg.cpt
│       │   │   └── wrap_bg.jpg
│       │   ├── spt.css
│       │   └── sptstats.js
│       ├── templates
│       │   ├── admin
│       │   │   └── base_site.html
│       │   ├── base.html
│       │   ├── index.html
│       ├── templatetags
│       │   ├── __init__.py
│       │   ├── sptcharts.py
│       │   └── utility.py
│       ├── tests.py
│       ├── urls.py
│       └── views.py
├── last_url.txt
├── manage.py
├── poker
│   ├── __init__.py
│   ├── middleware.py
│   ├── settings.py
│   ├── settings.py.template
│   ├── urls.py
│   └── wsgi.py
├── Procfile
├── requirements
│   ├── common.txt
│   ├── dev.txt
│   ├── prod.txt
├── requirements.txt
└── zappa_settings.json

```

**Comment by sarlindo** [comment]
ok it seems i got past this issue by changing the zappa settings file to point to the same settings config as I had in my original wsgi file.

```os.environ.setdefault("DJANGO_SETTINGS_MODULE", "poker.settings")```

changed zappa json file to this:

```
{
    "production": { 
       "s3_bucket": "sptdbt123",
       "django_settings": "poker.settings"
    }
}

```

**Comment by sarlindo** [comment]
now running into new issue

```

[1481687600892] [ERROR] 2016-12-14T03:53:20.891Z daae00be-c1b0-11e6-b8da-f9188720193a Internal Server Error: /production/
Traceback (most recent call last):
  File "/tmp/pip-build-H2vIYI/Django/django/core/handlers/exception.py", line 39, in inner
  File "/tmp/pip-build-H2vIYI/Django/django/core/handlers/base.py", line 249, in _legacy_get_response
  File "/tmp/pip-build-H2vIYI/Django/django/core/handlers/base.py", line 172, in _get_response
  File "/tmp/pip-build-H2vIYI/Django/django/urls/resolvers.py", line 270, in resolve
  File "/tmp/pip-build-H2vIYI/Django/django/utils/functional.py", line 35, in __get__
  File "/tmp/pip-build-H2vIYI/Django/django/urls/resolvers.py", line 313, in url_patterns
  File "/tmp/pip-build-H2vIYI/Django/django/utils/functional.py", line 35, in __get__
  File "/tmp/pip-build-H2vIYI/Django/django/urls/resolvers.py", line 306, in urlconf_module
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
  __import__(name)
  File "/var/task/poker/urls.py", line 1, in <module>
  from django.conf.urls import patterns, include, url
ImportError: cannot import name patterns

```

**Comment by sarlindo** [comment]
ok the last issue was related to django 1.10 vs 1.8. Now just have to play around with VPC to have lamba inside a vpc.

**Comment by Miserlou** [comment]
Hooray! :D
