### ISSUE TITLE
zappa invoke

### ISSUE THREAD

**Issue by bashu** [Miserlou/Zappa#564]
```shell
zappa invoke staging "print 1 + 2 + 3" --raw                   (feature/lambda✱)
Calling invoke for environment staging..
START RequestId: abababf4-c81d-11e6-a731-612b3622cb56 Version: $LATEST
need more than 1 value to unpack: ValueError
Traceback (most recent call last):
  File "/var/task/handler.py", line 479, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 192, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 309, in handler
    app_function = self.import_module_and_get_function(whole_function)
  File "/var/task/handler.py", line 182, in import_module_and_get_function
    module, function = whole_function.rsplit('.', 1)
ValueError: need more than 1 value to unpack

END RequestId: abababf4-c81d-11e6-a731-612b3622cb56
REPORT RequestId: abababf4-c81d-11e6-a731-612b3622cb56	Duration: 0.46 ms	Billed Duration: 100 ms 	Memory Size: 512 MB	Max Memory Used: 54 MB
```

**Comment by bashu** [comment]
💩

**Comment by Miserlou** [comment]
Ugh, I assume this is the result of that PR I didn't test thoroughly enough.

**Comment by Miserlou** [comment]
Yeah, that's the case. The new ArgumentParser is apparently conditional to ordering. Goddammit, gotta revert all this.

**Comment by bjinwright** [comment]
This is still happening for me

**Comment by vigilantzealot** [comment]
Still happening to me as well! When will the fix be pushed upstream?

**Comment by dangayle** [comment]
Ditto

**Comment by parroyo** [comment]
It's working fine on the latest version (0.34.0)

**Comment by Miserlou** [comment]
Sweet

**Comment by TammoHeeren** [comment]
This showed up for me again today. I am on 0.35.2. 

Log output:
```
need more than 1 value to unpack: ValueError
Traceback (most recent call last):
File "/var/task/handler.py", line 520, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 233, in lambda_handler
return handler.handler(event, context)
File "/var/task/handler.py", line 392, in handler
app_function = self.import_module_and_get_function(whole_function)
File "/var/task/handler.py", line 223, in import_module_and_get_function
module, function = whole_function.rsplit('.', 1)
ValueError: need more than 1 value to unpack
```

Init-file:
```
{
  "dev": {
    "lambda_description": "Stats",
    "s3_bucket": "ems30",
    "app_function": "app.app",
    "apigateway_enabled": false,
    "keep_warm": false,
    "log_level": "INFO",
    "memory_size": 512,
    "timeout_seconds": 300,
    "events": [
      {
        "function": "app.lambda_handler",
        "event_source": {
          "arn": "arn:aws:s3:::ems30test",
          "events": [
            "s3:ObjectCreated:*",
            "s3:ObjectRemoved:DeleteMarkerCreated"
          ]
        }
      }
    ]
  }
}
```

**Comment by Miserlou** [comment]
And it wasn't happening in the previous version?

**Comment by TammoHeeren** [comment]
Some other code I am running with a previous version does not have this problem. This code I only tested with 0.35.2. I am happy to downgrade and test.

**Comment by TammoHeeren** [comment]
This is interesting. When I add/remove an object from the bucket that I specified in the init file it works without the error message. 
When I add a file to a bucket that I manually specify in the admin console, it throws the error.
I am specifying the other bucket manually because I need prefix support and I don't think that zappa supports that currently.

**Comment by TammoHeeren** [comment]
Apparently when I create a trigger via the lambda console, it does not name it properly. In this case it is necessary to edit the trigger from the s3 console. Is there any why that zappa can support prefixes in the s3 triggers or is there and option to add it?

**Comment by TammoHeeren** [comment]
Looks like this is already supported by kappa using the following:

```
{
  "function": "app.lambda_handler",
  "event_source": {
    "arn": "arn:aws:s3:::...",
    "events": [
      "s3:ObjectCreated:*",
      "s3:ObjectRemoved:DeleteMarkerCreated"
    ],
    "key_filters": [
      {
        "type": "prefix",
        "value": "..."
      }
    ]
  }
}
```
