### ISSUE TITLE
S3 bucket creation fails with error, ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation

### ISSUE THREAD

**Issue by chaithuam** [Miserlou/Zappa#569]
I am following the example listed on https://github.com/Miserlou/Zappa/tree/master/example but I am getting the below error - somehow the LocationConstraint keyword in the create_bucket is not specified.
ERROR- ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

stack trace(venv) Chaithanyas-MacBook-Pro:zappa_dev chaithanya$ zappa deploy dev
Calling deploy for environment dev..
Downloading and installing dependencies..
100%|██████████████████████████████████████████| 36/36 [00:06<00:00,  5.59pkg/s]
Packaging project as zip..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/chaithanya/zappa_dev/venv/lib/python2.7/site-packages/zappa/cli.py", line 1847, in handle
    sys.exit(cli.handle())
  File "/Users/chaithanya/zappa_dev/venv/lib/python2.7/site-packages/zappa/cli.py", line 345, in handle
    self.dispatch_command(self.command, environment)
  File "/Users/chaithanya/zappa_dev/venv/lib/python2.7/site-packages/zappa/cli.py", line 377, in dispatch_command
    self.deploy()
  File "/Users/chaithanya/zappa_dev/venv/lib/python2.7/site-packages/zappa/cli.py", line 461, in deploy
    self.zip_path, self.s3_bucket_name)
  File "/Users/chaithanya/zappa_dev/venv/lib/python2.7/site-packages/zappa/zappa.py", line 562, in upload_to_s3
    Bucket=bucket_name,
  File "/Users/chaithanya/zappa_dev/venv/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/chaithanya/zappa_dev/venv/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

**Comment by chaithuam** [comment]
the bucket name was not unique. resolved the error by giving a unique bucket name :-)

**Comment by mdeselincourt** [comment]
Was not unique within what domain? I am getting this error and I do not already have a bucket with the intended name.

**Comment by ashleykleynhans** [comment]
Thanks for pointing out the actual error (bucket name needs to be unique), the error from AWS could just say that the bucket name is not unique instead of the useless error that it returns which makes you think that the issue is something completely different.
