### ISSUE TITLE
z_cli.certify() error

### ISSUE THREAD

**Issue by seanpaley** [Miserlou/Zappa#588]
When redeploying a site with recertify set, I see these errors in the cloudwatch logs:

This application [31misn't deployed yet[0m - did you mean to call [1mdeploy[0m?: ClickException
Traceback (most recent call last):
File "/var/task/handler.py", line 479, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 192, in lambda_handler
return handler.handler(event, context)
File "/var/task/handler.py", line 301, in handler
return self.run_function(app_function, event, context)
File "/var/task/handler.py", line 237, in run_function
result = app_function(event, context)
File "/var/task/handler.py", line 493, in certify_callback
return lh.update_certificate()
File "/var/task/handler.py", line 253, in update_certificate
z_cli.certify()
File "/private/var/folders/26/dklxrj8130l1rxw1r5qnb7nw0000gn/T/pip-build-4CS1fJ/zappa/zappa/cli.py", line 1206, in certify
ClickException: This application [31misn't deployed yet[0m - did you mean to call [1mdeploy[0m?

**Comment by michi88** [comment]
we might be swallowing an exception here:

```python
    def get_lambda_function_versions(self, function_name):
        """
        Simply returns the versions available for a Lambda function, given a function name.

        """
        try:
            response = self.lambda_client.list_versions_by_function(FunctionName=function_name)
            return response.get('Versions', [])
        except Exception:
            return []
```

When that returns `[]` you get the error above. I've also seen this.
