### ISSUE TITLE
Unable to import module 'handler': No module named werkzeug.wrappers

### ISSUE THREAD

**Issue by wobeng** [Miserlou/Zappa#593]
When I try to access my endpoint I get:

`Unable to import module 'handler': No module named werkzeug.wrappers`

**Answers to Prospect Questions:**

1. Is it in virtualenv : YES

2. Requirements.txt
```
Flask
marshmallow
zappa
```
3. pip list

```
argcomplete (1.7.0)
base58 (0.2.4)
boto3 (1.4.3)
botocore (1.4.93)
click (6.7)
docutils (0.13.1)
Flask (0.12)
futures (3.0.5)
hjson (2.0.2)
itsdangerous (0.24)
Jinja2 (2.9.4)
jmespath (0.9.0)
kappa (0.6.0)
lambda-packages (0.11.0)
MarkupSafe (0.23)
marshmallow (2.11.1)
pip (9.0.1)
placebo (0.8.1)
python-dateutil (2.6.0)
python-slugify (1.2.1)
PyYAML (3.12)
requests (2.12.4)
s3transfer (0.1.10)
setuptools (32.3.1)
six (1.10.0)
toml (0.9.2)
tqdm (4.10.0)
troposphere (1.9.1)
Unidecode (0.4.20)
Werkzeug (0.11.15)
wheel (0.29.0)
wsgi-request-logger (0.4.6)
zappa (0.32.1)
```

4.  zappa deploy dev, First attempt

```(app-example-env2) [testuser@ip-app-example]$ zappa deploy dev
(boto3 1.4.3 (/home/testuser/py/app-example-env2/lib/python2.7/dist-packages), Requirement.parse('boto3==1.4.2'), set([u'zappa']))
Calling deploy for environment dev..
Creating ZappaLambdaExecution IAM Role..
Creating zappa-permissions policy on ZappaLambdaExecution IAM Role.
Downloading and installing dependencies..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:01<00:00, 30.52pkg/s]
Packaging project as zip..
Uploading app-example-dev-1484158898.zip (11.7KiB)..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12.0K/12.0K [00:00<00:00, 59.2KB/s]
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/testuser/py/app-example-env2/local/lib/python2.7/dist-packages/zappa/cli.py", line 1847, in handle
    sys.exit(cli.handle())
  File "/home/testuser/py/app-example-env2/local/lib/python2.7/dist-packages/zappa/cli.py", line 345, in handle
    self.dispatch_command(self.command, environment)
  File "/home/testuser/py/app-example-env2/local/lib/python2.7/dist-packages/zappa/cli.py", line 377, in dispatch_command
    self.deploy()
  File "/home/testuser/py/app-example-env2/local/lib/python2.7/dist-packages/zappa/cli.py", line 474, in deploy
    memory_size=self.memory_size)
  File "/home/testuser/py/app-example-env2/local/lib/python2.7/dist-packages/zappa/zappa.py", line 651, in create_lambda_function
    VpcConfig=vpc_config
  File "/home/testuser/py/app-example-env2/local/lib/python2.7/dist-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/testuser/py/app-example-env2/local/lib/python2.7/dist-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
```

5.  zappa deploy dev, Second attempt

```
(app-example-env2) [testuser@ip-172-31-48-13 app-example]$ zappa deploy dev
(boto3 1.4.3 (/home/testuser/py/app-example-env2/lib/python2.7/dist-packages), Requirement.parse('boto3==1.4.2'), set([u'zappa']))
Calling deploy for environment dev..
Downloading and installing dependencies..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:00<00:00, 34.34pkg/s]
Packaging project as zip..
Uploading app-example-dev-1484158909.zip (11.7KiB)..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12.0K/12.0K [00:00<00:00, 61.9KB/s]
Scheduling..
Scheduled app-example-dev-zappa-keep-warm-handler.keep_warm_callback!
Uploading app-example-dev-template-1484158911.json (1.5KiB)..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.57K/1.57K [00:00<00:00, 23.2KB/s]
Waiting for stack app-example-dev to create (this can take a bit)..
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:18<00:00,  6.08s/res]
Deploying API Gateway..
Deployment complete!: https://...........execute-api.us-east-1.amazonaws.com/dev

```

**Comment by Miserlou** [comment]
Remake your venv and try again.

**Comment by wobeng** [comment]
@Miserlou I tried multiple times and I get the same thing. Does using blueprint have to do with it?

**Comment by Miserlou** [comment]
Oh, it's a permissions thing. If you don't have the raw power, you'll need to define your own policy. You're on a corporate account?

**Comment by wobeng** [comment]
@Miserlou  Unable to import module 'handler': No module named werkzeug.wrappers is a permission thing?

The account I'm using have this policy

IAMFullAccess - AWS Managed policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "iam:*",
            "Resource": "*"
        }
    ]
}
```
PowerUserAccess - AWS Managed policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "NotAction": [
                "iam:*",
                "organizations:*"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "organizations:DescribeOrganization",
            "Resource": "*"
        }
    ]
}
```

**Comment by wobeng** [comment]
Also, @Miserlou , Is the virtualenv libraries suppose to be copied in the package zipped lambda file? When I download my lambda function zip file, I see that the zip file is very small. Is there a change libraries are not being copied over?

**Comment by wobeng** [comment]
I had to rebuilt my linux environment, worked after that
