### ISSUE TITLE
Stack Creation failed after successful undeploy on hello world app

### ISSUE THREAD

**Issue by richiverse** [Miserlou/Zappa#615]
## Context
```
Got the following error:
 File "/home/rich/Projects/test/venv/lib/python2.7/site-packages/zappa/zappa.py", line 1279, in update_stack
    raise EnvironmentError("Stack creation failed. "
EnvironmentError: Stack creation failed. Please check your CloudFormation console. You may also need to `undeploy`.
```

```
(venv) rich@rich-vbox:~/Projects/test$ zappa undeploy dev                                                                                                                                         
Calling undeploy for environment dev..
Are you sure you want to undeploy? [y/n] y
Deleting API Gateway..
Waiting for stack test-dev to be deleted..
Unscheduling..
Unscheduled test-dev-zappa-keep-warm-handler.keep_warm_callback.
Deleting Lambda function..
Done!
(venv) rich@rich-vbox:~/Projects/test$ zappa deploy dev                                                                                                                                           
Calling deploy for environment dev..
Downloading and installing dependencies..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:02<00:00, 12.43pkg/s]
Packaging project as zip..
Uploading test-dev-1484946080.zip (6.2MiB)..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.46M/6.46M [00:01<00:00, 4.65MB/s]
Scheduling..
Scheduled test-dev-zappa-keep-warm-handler.keep_warm_callback!
Uploading test-dev-template-1484946090.json (1.5KiB)..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.56K/1.56K [00:00<00:00, 22.0KB/s]
Waiting for stack test-dev to create (this can take a bit)..
  0%|                                                                                                                                                                      | 0/4 [00:00<?, ?res/s]Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/rich/Projects/test/venv/lib/python2.7/site-packages/zappa/cli.py", line 1847, in handle
    sys.exit(cli.handle())
  File "/home/rich/Projects/test/venv/lib/python2.7/site-packages/zappa/cli.py", line 345, in handle
    self.dispatch_command(self.command, environment)
  File "/home/rich/Projects/test/venv/lib/python2.7/site-packages/zappa/cli.py", line 377, in dispatch_command
    self.deploy()
  File "/home/rich/Projects/test/venv/lib/python2.7/site-packages/zappa/cli.py", line 493, in deploy
    self.zappa.update_stack(self.lambda_name, self.s3_bucket_name, wait=True)
  File "/home/rich/Projects/test/venv/lib/python2.7/site-packages/zappa/zappa.py", line 1279, in update_stack
    raise EnvironmentError("Stack creation failed. "
EnvironmentError: Stack creation failed. Please check your CloudFormation console. You may also need to `undeploy`.

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
```
 

## Expected Behavior

app should deploy
## Actual Behavior

got error
## Possible Fix

not sure
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Zappa version used: latest from pip
* Operating System and Python version: ubuntu 64 | 2.7.12
* Link to your project (optional):
* Your `zappa_settings.py`: 
```
{
    "dev": {
        "app_function": "app.app", 
        "s3_bucket": "zappa-xxx",
	"profile_name": "zappa-deploy",
	"manage_roles": false
    }
}
```

policy used
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1484866929000",
            "Effect": "Allow",
            "Action": [
                "s3:CreateBucket",
                "s3:PutObject",
                "s3:GetObject"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "Stmt1484866929001",
            "Effect": "Allow",
            "Action": [
                "iam:GetRole",
                "iam:PassRole"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "Stmt1484866929002",
            "Effect": "Allow",
            "Action": [
                "lambda:CreateFunction",
                "lambda:GetFunction",
                "lambda:AddPermission",
                "lambda:GetPolicy",
                "lambda:RemovePermission",
                "lambda:DeleteFunction"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "Stmt1484866929003",
            "Effect": "Allow",
            "Action": [
                "events:ListRules",
                "events:PutRule",
                "events:ListTargetsByRule",
                "events:DeleteRule",
                "events:PutTargets",
                "events:RemoveTargets"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "Stmt1484866929004",
            "Effect": "Allow",
            "Action": [
                "cloudformation:CreateStack",
                "cloudformation:DescribeStacks",
                "cloudformation:UpdateStack",
                "cloudformation:ListStackResources",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStackResource"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "Stmt1484866929005",
            "Effect": "Allow",
            "Action": [
                "apigateway:GET"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

**Comment by richiverse** [comment]
Here's my cloudformation dump... looks like you need to check for apigateway POST capabilities prior to cryptic error message:

 	16:26:53 UTC-0500 	ROLLBACK_COMPLETE 	AWS::CloudFormation::Stack 	test-dev 	
	16:26:51 UTC-0500 	DELETE_COMPLETE 	AWS::ApiGateway::RestApi 	Api 	
	16:26:48 UTC-0500 	ROLLBACK_IN_PROGRESS 	AWS::CloudFormation::Stack 	test-dev 	The following resource(s) failed to create: [Api]. . Rollback requested by user.
	16:26:47 UTC-0500 	CREATE_FAILED 	AWS::ApiGateway::RestApi 	Api 	User: arn:aws:iam::xxxxxx:user/zappa-deploy is not authorized to perform: apigateway:POST on resource: arn:aws:apigateway:us-east-1::/restapis

**Comment by richiverse** [comment]
apigateway:PUT also fails cryptically but the following PATCH showed up correctly in the error message.

**Comment by richiverse** [comment]
apigateway:DELETE also fails cryptically

**Comment by bobcolner** [comment]
I'm also seeing this error when using the `undeploy` command.

**Comment by peter-ki** [comment]
any hints how to deal with this?

**Comment by darylyu** [comment]
You need to give write access to the user. A quick way to do this is to add the IAM user to an IAM group that has the `AmazonAPIGatewayAdministrator` policy.

This is a bit dangerous, because it gives the user access to *all* API gateways so they will be able to add/delete API gateways that are used by other teams in your organization.

**Comment by vpontis** [comment]
Hmm, I know that my user has full privileges and I am also getting this error...

I've been deploying for over a month now so I'm not sure what changed...

Here is what I see in CloudFront

![image](https://user-images.githubusercontent.com/1319079/49139485-c34e9480-f2a6-11e8-9cd0-ee848b2f741b.png)

It's weird because I don't have logs in CloudFront other than recently. I think something is going on where Zappa thinks that it's supposed to create something in CloudFront but it doesn't need to...

---

Edit even before posting, it looks like this was because I modified the `cors` setting in zappa... I kept the `cors` setting as `false` and I am no longer getting this issue. 

But now I don't know what I would do if I wanted to enable CORS on CloudFront.
