### ISSUE TITLE
Setting "slim_handler" to true doesn't change packaging

### ISSUE THREAD

**Issue by alexlokhov** [Miserlou/Zappa#638]
Setting slim_handler to true doesn't seem to change packaging.

## Expected Behavior
As per the docs, setting slim_handler to true should trigger creation of a small handler file and the rest of the project should be loaded from S3 at run time.

## Actual Behavior
I still see one large package being pushed to lambda. Exactly the same behaviour is observed with and without slim_handler being set to true:
```
Downloading and installing dependencies..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 47/47 [00:07<00:00, 14.60pkg/s]
Packaging project as zip..


Warning: Application zip package is likely to be too large for AWS Lambda.


Uploading credit-score-ap-dev-1485818785.zip (88.2MiB)..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 92.5M/92.5M [00:01<00:00, 52.2MB/s]
Updating Lambda function code..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 1981, in handle
    sys.exit(cli.handle())
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 398, in handle
    self.dispatch_command(self.command, environment)
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 434, in dispatch_command
    self.update()
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 660, in update
    self.s3_bucket_name, self.zip_path, self.lambda_name)
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/zappa.py", line 669, in update_lambda_function
    Publish=publish
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the UpdateFunctionCode operation: Unzipped size must be smaller than 262144000 bytes

```

## Steps to Reproduce
```
virtualenv env
source env/bin/activate
pip install zappa flask scipy sklearn pandas mysql-connector-python-rf smart_open
zappa deploy dev
```
## Context
Some machine learning libraries like scipy, sklearn and pandas take up a lot of space and do not fit into Lambda with default settings.

## Your Environment
* Zappa version used:
```
zappa -v
0.34.0
```
* Operating System and Python version:
```
4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:48:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.12 (default, Jul  1 2016, 15:12:24)
```
* `zappa_settings.json`: 
```
{
    "dev": {
        "app_function": "my_app.app",
        "s3_bucket": "zappa-xxxxxxxxx",
        "aws_region": "eu-west-1",
        "slim_handler": true
    }
}
```

**Comment by Miserlou** [comment]
Ah yes! Sorry about this - `slim_handler` has been merged into `master`, but hasn't been published to `pip` yet as it needs a bit more testing (like this.) It will land in the next version, which will also include #636 .

**Comment by alexlokhov** [comment]
Thanks

**Comment by alexlokhov** [comment]
FYI, tested with the latest master pulled from the repo. I see that the key makes a difference and that Zappa creates two packages now, but the handler package is still big.
```
(env) root@noddleScraper:~/credit_score_api# zappa update dev
Calling update for environment dev..
Downloading and installing dependencies..
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 47/47 [00:08<00:00,  5.85pkg/s]
Packaging project as zip..
Downloading and installing dependencies..
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 47/47 [00:06<00:00,  7.61pkg/s]
Packaging project as zip..
Uploading credit-score-ap-dev-1485823171.zip (91.5MiB)..
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 95.9M/95.9M [00:02<00:00, 46.2MB/s]
Uploading handler_credit-score-ap-dev-1485823223.zip (81.0MiB)..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 84.7M/84.9M [00:01<00:00, 53.0MB/s]
Updating Lambda function code..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 2057, in handle
    sys.exit(cli.handle())
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 399, in handle
    self.dispatch_command(self.command, environment)
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 435, in dispatch_command
    self.update()
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 695, in update
    self.s3_bucket_name, handler_file, self.lambda_name)
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/zappa.py", line 755, in update_lambda_function
    Publish=publish
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the UpdateFunctionCode operation: Unzipped size must be smaller than 262144000 bytes

==============
```
