### ISSUE TITLE
Requests SSLError

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#640]
This ticket is pretty much just for SEO purposes.

Are you getting this error?

```
/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Oh no! An error occurred! :(
==============

Traceback (most recent call last):
  File "/home/ubuntu/OpenMail/tools/decode_web/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 1981, in handle
    sys.exit(cli.handle())
  File "/home/ubuntu/OpenMail/tools/decode_web/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 398, in handle
    self.dispatch_command(self.command, environment)
  File "/home/ubuntu/OpenMail/tools/decode_web/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 430, in dispatch_command
    self.deploy()
  File "/home/ubuntu/OpenMail/tools/decode_web/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 594, in deploy
    requests.get(endpoint_url)
  File "/home/ubuntu/OpenMail/tools/decode_web/venv/local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ubuntu/OpenMail/tools/decode_web/venv/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/OpenMail/tools/decode_web/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/OpenMail/tools/decode_web/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/OpenMail/tools/decode_web/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

==============
```

Try `apt-get install libffi-dev libssl-dev`, then `pip install requests[security]` and re-deploy.

**Comment by neotheicebird** [comment]
Installing these libraries doesn't work for me. Still getting:

```
==============

Traceback (most recent call last):
  File "/vol/home/ubuntu/NLU-NLC-TF/site/flaskenv/local/lib/python2.7/site-packa
ges/zappa/cli.py", line 2068, in handle
    sys.exit(cli.handle())
  File "/vol/home/ubuntu/NLU-NLC-TF/site/flaskenv/local/lib/python2.7/site-packa
ges/zappa/cli.py", line 403, in handle
    self.dispatch_command(self.command, environment)
  File "/vol/home/ubuntu/NLU-NLC-TF/site/flaskenv/local/lib/python2.7/site-packa
ges/zappa/cli.py", line 435, in dispatch_command
    self.deploy()
  File "/vol/home/ubuntu/NLU-NLC-TF/site/flaskenv/local/lib/python2.7/site-packa
ges/zappa/cli.py", line 618, in deploy
    requests.get(endpoint_url)
  File "/vol/home/ubuntu/NLU-NLC-TF/site/flaskenv/local/lib/python2.7/site-packa
ges/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/vol/home/ubuntu/NLU-NLC-TF/site/flaskenv/local/lib/python2.7/site-packa
ges/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/vol/home/ubuntu/NLU-NLC-TF/site/flaskenv/local/lib/python2.7/site-packa
ges/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/vol/home/ubuntu/NLU-NLC-TF/site/flaskenv/local/lib/python2.7/site-packa
ges/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/vol/home/ubuntu/NLU-NLC-TF/site/flaskenv/local/lib/python2.7/site-packa
ges/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

==============
```

**Comment by neotheicebird** [comment]
I was using Python version==2.7.6 on Ubuntu 14.04, updating to python 2.7.13 and then doing `pip install requests[security]` seemed to fix this.

A good article on upgrading python: http://mbless.de/blog/2016/01/09/upgrade-to-python-2711-on-ubuntu-1404-lts.html

**Comment by the-esculator** [comment]
@neotheicebird Thank you, your proposed solution of updating python for Ubuntu 14.04 fixed this issue

**Comment by gene1wood** [comment]
I encountered this problem on my Ubuntu 14.04 / Python 2.7.6 environment and solved it by running

`pip install pyOpenSSL ndg-httpsclient pyasn1`

in my zappa virtualenv

As suggested on [stackoverflow](http://stackoverflow.com/a/29099439/168874)

@Miserlou since it's apparent the AWS API Gateway won't talk with old openssl (well not that old, a current Ubuntu LTS release), would it make sense to include these modules in the zappa [`requirements.txt`](https://github.com/Miserlou/Zappa/blob/master/requirements.txt) to prevent this problem?

**Comment by johnyoonh** [comment]
For anyone facing this problem in 2019, the problem is likely to be with older version of  `cryptography` being used in lambda-packages. Use the master version which includes v2.3.1 instead of v1.9 as suggested by jakul. https://github.com/Miserlou/Zappa/issues/1455#issuecomment-380420973

    pip install -U git+https://github.com/Miserlou/lambda-packages
