### ISSUE TITLE
Still issues with the slim_hanlder key

### ISSUE THREAD

**Issue by alexlokhov** [Miserlou/Zappa#641]
I tested the latest Zappa 0.35. With the slim_hanlder key enabled I now get two zip file. The handler zip file contains most of the packages from the main zip file (but not all). Because of this, the handler package is still too big.

I believe the handler file was supposed to have a minimal set of packages so that it is small enough to fit on Lambda. I have also tried running Zappa to create local zip files (`zappa package dev`) and check what's inside. The hanlder zip file contains 75% of all packages, including all the heavy ones: scipy, sklearn, pandas, numpy, etc.

## Actual Behavior
```
 zappa update dev
Calling update for environment dev..
Downloading and installing dependencies..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 47/47 [00:06<00:00,  6.74pkg/s]
Packaging project as zip..
Downloading and installing dependencies..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 47/47 [00:06<00:00,  7.44pkg/s]
Packaging project as zip..
Uploading credit-score-ap-dev-1485982804.zip (91.7MiB)..
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 96.2M/96.2M [00:02<00:00, 33.4MB/s]
Uploading handler_credit-score-ap-dev-1485982858.zip (81.0MiB)..
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 84.9M/84.9M [00:01<00:00, 55.4MB/s]
Updating Lambda function code..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 2057, in handle
    sys.exit(cli.handle())
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 399, in handle
    self.dispatch_command(self.command, environment)
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 435, in dispatch_command
    self.update()
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/cli.py", line 695, in update
    self.s3_bucket_name, handler_file, self.lambda_name)
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/zappa/zappa.py", line 755, in update_lambda_function
    Publish=publish
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/credit_score_api/env/local/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the UpdateFunctionCode operation: Unzipped size must be smaller than 262144000 bytes

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
```

## Your Environment
* Zappa version used:
0.35
* Operating System and Python version:
```
4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:48:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.12 (default, Jul  1 2016, 15:12:24)
[GCC 5.4.0 20160609] on linux2
```

* Your `zappa_settings.py`: 
```
{
    "dev": {
        "app_function": "my_app.app",
        "s3_bucket": "zappa-xxxxxxxxxx",
        "aws_region": "eu-west-1",
        "slim_handler": true
    }
}
```

**Comment by Miserlou** [comment]
@mcrowson

**Comment by Miserlou** [comment]
Thank you for your bug report!
