### ISSUE TITLE
zappa package fails with multiple local virtualenvs 

### ISSUE THREAD

**Issue by monkeypants** [Miserlou/Zappa#679]
If I have multiple virtual environments, one that is activated and another that is not, I do not seem to be able to run `zappa package`. If I delete the deactivated on, it works.

For example, I did this:
```
me$ virtualenv .venv
me$ . .venv/bin/activate
me$ pip install -r requirements.txt
me$ deactivate
me$ virtualenv .venv-another
me$ . .venv-another/bin/activate
me$ pip install -r requirements.txt
```
And then I did this:
```
(.venv-zappa-build) me$ zappa package
Calling package for environment dev..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/me/my-working-dir/.venv-another/lib/python2.7/site-packages/zappa/cli.py", line 2086, in handle
    sys.exit(cli.handle())
  File "/Users/me/my-working-dir/.venv-another//lib/python2.7/site-packages/zappa/cli.py", line 404, in handle
    self.dispatch_command(self.command, environment)
  File "/Users/me/my-working-dir/.venv-another/lib/python2.7/site-packages/zappa/cli.py", line 438, in dispatch_command
    self.package()
  File "/Users/me/my-working-dir/.venv-another/lib/python2.7/site-packages/zappa/cli.py", line 505, in package
    self.create_package()
  File "/Users/me/my-working-dir/.venv-another/lib/python2.7/site-packages/zappa/cli.py", line 1707, in create_package
    ["boto3", "dateutil", "botocore", "s3transfer", "six.py", "jmespath", "concurrent"])
  File "/Users/me/my-working-dir/.venv-another/lib/python2.7/site-packages/zappa/zappa.py", line 392, in create_lambda_zip
    copytree(cwd, temp_project_path, symlinks=False, ignore=shutil.ignore_patterns(*excludes))
  File "/Users/me/my-working-dir/.venv-another/lib/python2.7/site-packages/zappa/util.py", line 48, in copytree
    copytree(s, d, symlinks, ignore)
  File "/Users/me/my-working-dir/.venv-another/lib/python2.7/site-packages/zappa/util.py", line 48, in copytree
    copytree(s, d, symlinks, ignore)
  File "/Users/me/my-working-dir/.venv-another/lib/python2.7/site-packages/zappa/util.py", line 48, in copytree
    copytree(s, d, symlinks, ignore)
  File "/Users/me/my-working-dir/.venv-another/lib/python2.7/site-packages/zappa/util.py", line 26, in copytree
    shutil.copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/fv/0yfx9pws7dbdc84wymph4hc40000gp/T/1487561855/.venv/include/python2.7'

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
```
That was the bad news. But this fixed it
```
(.venv-zappa-build) me$ rm -rf .venv
(.venv-zappa-build) me$ zappa package
Calling package for environment dev..
Downloading and installing dependencies..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 42/42 [00:14<00:00,  4.01pkg/s]
Packaging project as zip..
Package created: appointments-mo-dev-1487561882.zip (7.8MiB)
(.venv-zappa-build) me$ 
```

I think what should happen is that parallel, unused virtualenvs should be silently ignored

* Zappa version used: 0.36.0
* Operating System and Python version: OSX / newish (I don't know, I hate it. Nice metal box though)
* Your `zappa_settings.py`: 
```
{
  "dev": {
    "app_function": "app.app",
    "s3_bucket": "some-bucket-name-blahblahblah"
  }
}
```

**Comment by Miserlou** [comment]
If you add the other venv to your excludes does it work?

**Comment by monkeypants** [comment]
If I add the other venv to excludes it does work, thanks. 

But I still think zappa should not barf here.

**Comment by Miserlou** [comment]
If you want to send a PR, it should be a simple fix to check if a dir being packaged is a venv root or not.
