### ISSUE TITLE
'Executable may have wrong permissions' error

### ISSUE THREAD

**Issue by TammoHeeren** [Miserlou/Zappa#682]
I am running phantomjs from lambda. Until recently that worked without any problems.
I am getting the following error with 0.36.1 & 0.36.0. This does not occur with 0.35.2.

Tammo

```
Message: 'phantomjs' executable may have wrong permissions. 
: WebDriverException
Traceback (most recent call last):
  File "/var/task/handler.py", line 497, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 232, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 350, in handler
    result = self.run_function(app_function, event, context)
  File "/var/task/handler.py", line 277, in run_function
    result = app_function(event, context)
  File "/var/task/app.py", line 16, in app
    main(event, context)
  File "/var/task/app.py", line 32, in main
    scraping(event=event, context=context)
  File "/var/task/app.py", line 28, in scraping
    scraper(event=event, context=context)
  File "/var/task/support/scraping/scraper.py", line 85, in __call__
    with browser() as driver:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/theeren/PyCharmProjects/project/support/scraping/browserdriver.py", line 30, in browser
  File "/home/theeren/PyCharmProjects/project/support/scraping/browserdriver.py", line 23, in acquire
  File "/var/task/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/var/task/selenium/webdriver/common/service.py", line 86, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'phantomjs' executable may have wrong permissions. 
```

**Comment by Miserlou** [comment]
Phew, lots of errors in the latest version for you. Sorry about that.

What permissions does PhantomJS expect?

**Comment by TammoHeeren** [comment]
I really don't know what permissions it expects. I just know that when I downgrade zappa to 0.35.2 everything works fine. I can generate a minimal example if that helps. 
Love the tool. Thank you for providing and supporting it.

**Comment by Miserlou** [comment]
What is the chmod of that file in your local venv?

**Comment by TammoHeeren** [comment]
`-rwxrwxr-x 1 theeren theeren  65M Feb 20 13:24 phantomjs`

**Comment by Miserlou** [comment]
Do you have any test code I can repro with?

**Comment by TammoHeeren** [comment]
I will create one.

**Comment by TammoHeeren** [comment]
Here is a minimal example. Works with 35.2 does not work with latest (36.1).

https://github.com/TammoHeeren/ems30_test001

**Comment by Miserlou** [comment]
Can you add a bit of documentation on how to test that? I don't know what I'm supposed to be doing to get that to work, I just get selenium errors.

**Comment by Miserlou** [comment]
Ah, okay, I think I can repro.

**Comment by Miserlou** [comment]
Fixed, thanks for the report and repro.

**Comment by TammoHeeren** [comment]
Awesome. Thank you for the quick fix.
