### ISSUE TITLE
Copytree Issue When Computer Has Been Online a While

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#720]
## Context

 
When my computer has been on for a while, calling zappa update results in a permission error when doing the copytree command within zappa. Rebooting my computer allows me to call update again.

## Expected Behavior

It should successfully update.

## Actual Behavior

It raises an OSError

## Possible Fix

Not sure. :(

## Steps to Reproduce

This only happens intermittently. Here is the trace I get when it occurs

```python
Traceback (most recent call last):
  File "/Users/my_user/Documents/project/env/lib/python2.7/site-packages/zappa/cli.py", line 2142, in handle
    sys.exit(cli.handle())
  File "/Users/my_user/Documents/project/env/lib/python2.7/site-packages/zappa/cli.py", line 414, in handle
    self.dispatch_command(self.command, environment)
  File "/Users/my_user/Documents/project/env/lib/python2.7/site-packages/zappa/cli.py", line 450, in dispatch_command
    self.update()
  File "/Users/my_user/Documents/project/env/lib/python2.7/site-packages/zappa/cli.py", line 692, in update
    self.create_package()
  File "/Users/my_user/Documents/project/env/lib/python2.7/site-packages/zappa/cli.py", line 1763, in create_package
    ["boto3", "dateutil", "botocore", "s3transfer", "six.py", "jmespath", "concurrent"])
  File "/Users/my_user/Documents/project/env/lib/python2.7/site-packages/zappa/zappa.py", line 395, in create_lambda_zip
    copytree(cwd, temp_project_path, symlinks=False, ignore=shutil.ignore_patterns(*excludes))
  File "/Users/my_user/Documents/project/env/lib/python2.7/site-packages/zappa/util.py", line 48, in copytree
    copytree(s, d, symlinks, ignore)
  File "/Users/my_user/Documents/project/env/lib/python2.7/site-packages/zappa/util.py", line 48, in copytree
    copytree(s, d, symlinks, ignore)
  File "/Users/my_user/Documents/project/env/lib/python2.7/site-packages/zappa/util.py", line 48, in copytree
    copytree(s, d, symlinks, ignore)
  File "/Users/my_user/Documents/project/env/lib/python2.7/site-packages/zappa/util.py", line 26, in copytree
    shutil.copystat(src, dst)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/76/x28nq9jd5d52vjsr1xsmz9640000gq/T/1489582652/docenv/include/python2.7'
```
## Your Environment

* Zappa version used: 0.38 through 0.39
* Operating System and Python version: OSX

**Comment by Miserlou** [comment]
Now that's an interesting one. 

Is your computer full? Is something else playing with the permissions on your temp folders?

**Comment by mcrowson** [comment]
loads of room on the hard drive and in memory.

**Comment by Miserlou** [comment]
Ah. Are you guys both using the latest OSX? This may have to do with https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html

**Comment by dtenenba** [comment]
Getting this as well with zappa 0.38.1 and 0.39.1, OS X 10.12.1 and Python 2.7.10.
I have System Integrity Protection on. I'll try turning it off.

**Comment by Miserlou** [comment]
Please note that I am not encouraging enable to disable their System Integrity Protection, I'm just trying to isolate and identify the problem.

**Comment by Miserlou** [comment]
Related discussion: https://github.com/pypa/pip/issues/3165

**Comment by mcrowson** [comment]
yes, on OSX

**Comment by dtenenba** [comment]
I was able to work around this issue with the following. I realize this is a hack and not a suitable fix for everyone, but I was dead in the water without it.

```diff
diff --git a/zappa/util.py b/zappa/util.py
index b9b6956..95989ea 100644
--- a/zappa/util.py
+++ b/zappa/util.py
@@ -9,11 +9,30 @@ import requests
 import shutil
 import stat
 import urlparse
+import errno
 
 ##
 # Settings / Packaging
 ##
 
+def copystat2(src, dst):
+    """Copy all stat info (mode bits, atime, mtime, flags) from src to dst"""
+    st = os.stat(src)
+    mode = stat.S_IMODE(st.st_mode)
+    if hasattr(os, 'utime'):
+        os.utime(dst, (st.st_atime, st.st_mtime))
+    if hasattr(os, 'chmod'):
+        os.chmod(dst, mode)
+    if hasattr(os, 'chflags') and hasattr(st, 'st_flags'):
+        try:
+            os.chflags(dst, st.st_flags)
+        except OSError, why:
+            for err in 'EOPNOTSUPP', 'ENOTSUP', 'EPERM':
+                if hasattr(errno, err) and why.errno == getattr(errno, err):
+                    break
+            else:
+                raise
+
 def copytree(src, dst, symlinks=False, ignore=None):
     """
     This is a contributed re-implementation of 'copytree' that
@@ -23,7 +42,7 @@ def copytree(src, dst, symlinks=False, ignore=None):
 
     if not os.path.exists(dst):
         os.makedirs(dst)
-        shutil.copystat(src, dst)
+        copystat2(src, dst)
     lst = os.listdir(src)
 
     if ignore:
@@ -47,7 +66,8 @@ def copytree(src, dst, symlinks=False, ignore=None):
         elif os.path.isdir(s):
             copytree(s, d, symlinks, ignore)
         else:
-            shutil.copy2(s, d)
+            shutil.copy(s, d)
+            copystat2(s, d)
 
 def parse_s3_url(url):
     """

```

**Comment by stevezau** [comment]
Also getting this on the latest version

**Comment by MihaZelnik** [comment]
same here

**Comment by bcongdon** [comment]
For others getting this error, I noticed that if I had 2 virtualenvs in my Zappa directory, I'd also get this error.

Deleting/moving the inactive virtualenv fixed this for me.

**Comment by mcrowson** [comment]
Oh that could be it! I have done that quite a few times before testing Python 2 and 3.

**Comment by mcrowson** [comment]
This is likely a duplicate of #679
