### ISSUE TITLE
Add a pre-deployment sanity check

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#78]
Just display warnings if the app_module doesn't exist to avoid the

     UnboundLocalError: local variable 'app_module' referenced before assignment 

that happens from putting the wrong values in zappa_settings.

**Comment by tipu** [comment]
on it.

**Comment by tipu** [comment]
I'm going to put the addition for this in `zappa/cli.py:create_package()`. Does this seem like a suitable place?

**Comment by Miserlou** [comment]
This would probably be better to but in zappa.py so that it could be used by other clients. We should expect that this function may grow over time.

**Comment by tipu** [comment]
@Miserlou `zappa/zappa.py` appears to be unaware of the `zappa_settings` reference that `zappa/cli` holds onto. Should I inject the `zappa_settings` into `zappa/zappa.py` or should I implement it in the `update` method within ZappaCLI?

**Comment by collingreen** [comment]
It would be helpful to check types on config values -- for example, memory_size, parameter_depth, timout_seconds, etc all need to be numbers, not strings. If they are strings, zappa will zip your project, upload it, then fail with an error:
> Parameter validation failed:
Invalid type for parameter MemorySize, value: 128, type: <type 'unicode'>, valid types: <type 'int'>, <type 'long'>

**Comment by Miserlou** [comment]
This recently happened to somebody in IRC:

```
[1471899440322] No module named your_module
[1471899440322] No module named your_module: ImportError
Traceback (most recent call last):
 File "/var/task/handler.py", line 345, in lambda_handler
   return LambdaHandler.lambda_handler(event, context)
 File "/var/task/handler.py", line 122, in lambda_handler
   return cls().handler(event, context)
 File "/var/task/handler.py", line 317, in handler
   raise e
ImportError: No module named your_module
```

Could we check if the specified module exists before uploading?
