### ISSUE TITLE
NoRegionError from boto on init when no default profile in aws credentials file

### ISSUE THREAD

**Issue by pdpol** [Miserlou/Zappa#780]
Running `zappa init` from a Django project gave me the following traceback. Easy workaround was to change the AWS profile I intended to deploy the project to to `default`, but I personally try not to keep a `default` profile in my credentials file to be explicit about which AWS env I'm working in.

```
Traceback (most recent call last):
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/zappa/cli.py", line 2187, in handle
    sys.exit(cli.handle())
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/zappa/cli.py", line 385, in handle
    self.init()
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/zappa/cli.py", line 1192, in init
    self.check_venv()
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/zappa/cli.py", line 2154, in check_venv
    temp_zappa = Zappa()
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/zappa/zappa.py", line 232, in __init__
    self.lambda_client = self.boto_session.client('lambda', config=long_config)
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/botocore/client.py", line 70, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/botocore/client.py", line 224, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/botocore/args.py", line 103, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/botocore/client.py", line 297, in resolve
    service_name, region_name)
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/Users/pdpol/.virtualenvs/weather/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
NoRegionError: You must specify a region.
```
Relevant lines [here](https://github.com/Miserlou/Zappa/blob/master/zappa/cli.py#L2154) and [here](https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L207). 

Would love to get a prompt before initializing the Zappa instance to optionally pass in a profile name, or output that Zappa needs a default profile for init to work.

* Zappa version used: 0.40.0
* Operating System and Python version: OS X El Crapitan 10.11.6, Python 2.7.11

**Comment by Miserlou** [comment]
Yeah, I think there are two bugs here, one is to stop creating that temporary Zappa and just a static venv checker, that's a hack currently, and then the other would be to add a 'region' picker to `init` based on the profiles available in the credentials file. Up for it?

**Comment by pdpol** [comment]
Yep, I can take a crack at it this weekend.

**Comment by Miserlou** [comment]
Merged!
