### ISSUE TITLE
slim_handler=true Fails with Python 3.6

### ISSUE THREAD

**Issue by olirice** [Miserlou/Zappa#831]
## Context
When python version is 3.6 slimhandler fails to download the project zip from s3

 

## Sample project
```python
# my_app.py
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello():
    return 'Hello, Zappa' 

if __name__ == '__main__':
    app.run()
```

```js
# zappa_settings.json
{
    "dev": {
        "app_function": "my_app.app", 
        "s3_bucket": "zappa-test-dev-uid-008854",
        "slim_handler": true, # This is relevant
        "debug" : true
    }
}
```

## Steps to Reproduce

1. Create the 2 files listed above
2. Make sure you're using python3.6
3. `zappa deploy dev`

After the application deploys it will respond to all requests with internal sever errors.

4. Taking a look at what's going on `zappa tail dev`

```
[1494278519589] [DEBUG] 2017-05-08T21:21:59.589Z 5dfaca12-3434-11e7-b87e-2786428b2841 Registering retry handlers for service: s3
[1494278519608] [DEBUG] 2017-05-08T21:21:59.608Z 5dfaca12-3434-11e7-b87e-2786428b2841 Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f70406b9f28>
[1494278519608] [DEBUG] 2017-05-08T21:21:59.608Z 5dfaca12-3434-11e7-b87e-2786428b2841 Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f7040264c80>
[1494278519648] invalid syntax (_base.py, line 381): SyntaxError
Traceback (most recent call last):
  File "/var/task/handler.py", line 514, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 259, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 121, in __init__
  self.load_remote_project_zip(project_zip_path)
  File "/var/task/handler.py", line 181, in load_remote_project_zip
  s3 = boto_session.resource('s3')
  File "/var/task/boto3/session.py", line 389, in resource
  aws_session_token=aws_session_token, config=config)
  File "/var/task/boto3/session.py", line 263, in client
  aws_session_token=aws_session_token, config=config)
  File "/var/task/botocore/session.py", line 836, in create_client
  client_config=config, api_version=api_version)
  File "/var/task/botocore/client.py", line 64, in create_client
  cls = self._create_client_class(service_name, service_model)
  File "/var/task/botocore/client.py", line 86, in _create_client_class
  base_classes=bases)
  File "/var/task/botocore/hooks.py", line 227, in emit
  return self._emit(event_name, kwargs)
  File "/var/task/botocore/hooks.py", line 210, in _emit
  response = handler(**kwargs)
  File "/var/task/boto3/utils.py", line 61, in _handler
  module = import_module(module)
  File "/var/task/boto3/utils.py", line 52, in import_module
  __import__(name)
  File "/var/task/boto3/s3/inject.py", line 15, in <module>
  from boto3.s3.transfer import create_transfer_manager
  File "/var/task/boto3/s3/transfer.py", line 127, in <module>
  from s3transfer.exceptions import RetriesExceededError as \
  File "/var/task/s3transfer/__init__.py", line 134, in <module>
  import concurrent.futures
  File "/var/task/concurrent/futures/__init__.py", line 8, in <module>
  from concurrent.futures._base import (FIRST_COMPLETED,
  File "/var/task/concurrent/futures/_base.py", line 381
  raise exception_type, self._exception, self._traceback
        ^
SyntaxError: invalid syntax
[1494278519648] Traceback (most recent call last):
[1494278519648] File "/var/runtime/awslambda/bootstrap.py", line 234, in handle_event_request
[1494278519648] result = request_handler(json_input, context)
[1494278519648] File "/var/runtime/awslambda/bootstrap.py", line 54, in request_handler
[1494278519649] return request_handler(*arg)
[1494278519649] File "/var/task/handler.py", line 514, in lambda_handler
[1494278519649] return LambdaHandler.lambda_handler(event, context)
[1494278519649] File "/var/task/handler.py", line 259, in lambda_handler
[1494278519649] handler = cls()
[1494278519649] File "/var/task/handler.py", line 121, in __init__
[1494278519649] self.load_remote_project_zip(project_zip_path)
[1494278519649] File "/var/task/handler.py", line 181, in load_remote_project_zip
[1494278519649] s3 = boto_session.resource('s3')
[1494278519649] File "/var/task/boto3/session.py", line 389, in resource
[1494278519650] aws_session_token=aws_session_token, config=config)
[1494278519650] File "/var/task/boto3/session.py", line 263, in client
```

## Your Environment

* Zappa version used: 41.2
* Operating System and Python version: ubuntu 14.04, python 3.6.1

**Comment by Miserlou** [comment]
Does anything about this jump out at you, @mcrowson ?

**Comment by mcrowson** [comment]
Looks like 3.6 wasn't set in the config so it defaults to 2.7 for the handlers runtime. The packages were likely shipped up based on 3.6 though. Try setting the runtime setting in the zappa_settings.json

**Comment by olirice** [comment]
after updating `zappa_settings.json` to 
```js
{
    "dev": {
        "app_function": "my_app.app", 
        "s3_bucket": "zappa-test-dev-uid-0000122",
        "runtime": "python3.6",
        "slim_handler": true,
        "debug" : true
    }
}
```
and updating the deployment, the internal server error is still thrown.

Here are the logs

```
[1494284518990] [INFO] 2017-05-08T23:01:58.990Z 55feb0cf-3442-11e7-9437-457b9a71c71a Found credentials in environment variables.
[1494284518990] [DEBUG] 2017-05-08T23:01:58.990Z 55feb0cf-3442-11e7-9437-457b9a71c71a Loading JSON file: /var/task/botocore/data/endpoints.json
[1494284519007] [DEBUG] 2017-05-08T23:01:58.995Z 55feb0cf-3442-11e7-9437-457b9a71c71a Loading JSON file: /var/task/botocore/data/s3/2006-03-01/service-2.json
[1494284519029] [DEBUG] 2017-05-08T23:01:59.29Z 55feb0cf-3442-11e7-9437-457b9a71c71a Loading JSON file: /var/task/botocore/data/_retry.json
[1494284519029] [DEBUG] 2017-05-08T23:01:59.29Z 55feb0cf-3442-11e7-9437-457b9a71c71a Registering retry handlers for service: s3
[1494284519048] [DEBUG] 2017-05-08T23:01:59.48Z 55feb0cf-3442-11e7-9437-457b9a71c71a Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f7aa86e0f28>
[1494284519048] [DEBUG] 2017-05-08T23:01:59.48Z 55feb0cf-3442-11e7-9437-457b9a71c71a Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f7aa828ac80>
[1494284519070] invalid syntax (_base.py, line 381): SyntaxError
Traceback (most recent call last):
  File "/var/task/handler.py", line 514, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 259, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 121, in __init__
  self.load_remote_project_zip(project_zip_path)
  File "/var/task/handler.py", line 181, in load_remote_project_zip
  s3 = boto_session.resource('s3')
  File "/var/task/boto3/session.py", line 389, in resource
  aws_session_token=aws_session_token, config=config)
  File "/var/task/boto3/session.py", line 263, in client
  aws_session_token=aws_session_token, config=config)
  File "/var/task/botocore/session.py", line 836, in create_client
  client_config=config, api_version=api_version)
  File "/var/task/botocore/client.py", line 64, in create_client
  cls = self._create_client_class(service_name, service_model)
  File "/var/task/botocore/client.py", line 86, in _create_client_class
  base_classes=bases)
  File "/var/task/botocore/hooks.py", line 227, in emit
  return self._emit(event_name, kwargs)
  File "/var/task/botocore/hooks.py", line 210, in _emit
  response = handler(**kwargs)
  File "/var/task/boto3/utils.py", line 61, in _handler
  module = import_module(module)
  File "/var/task/boto3/utils.py", line 52, in import_module
  __import__(name)
  File "/var/task/boto3/s3/inject.py", line 15, in <module>
  from boto3.s3.transfer import create_transfer_manager
  File "/var/task/boto3/s3/transfer.py", line 127, in <module>
  from s3transfer.exceptions import RetriesExceededError as \
  File "/var/task/s3transfer/__init__.py", line 134, in <module>
  import concurrent.futures
  File "/var/task/concurrent/futures/__init__.py", line 8, in <module>
  from concurrent.futures._base import (FIRST_COMPLETED,
  File "/var/task/concurrent/futures/_base.py", line 381
  raise exception_type, self._exception, self._traceback
        ^
SyntaxError: invalid syntax
[1494284519070] Traceback (most recent call last):
[1494284519070] File "/var/runtime/awslambda/bootstrap.py", line 234, in handle_event_request
[1494284519070] result = request_handler(json_input, context)
[1494284519070] File "/var/runtime/awslambda/bootstrap.py", line 54, in request_handler
[1494284519071] return request_handler(*arg)
[1494284519071] File "/var/task/handler.py", line 514, in lambda_handler
[1494284519071] return LambdaHandler.lambda_handler(event, context)
[1494284519087] File "/var/task/handler.py", line 259, in lambda_handler
[1494284519087] handler = cls()
[1494284519087] File "/var/task/handler.py", line 121, in __init__
[1494284519087] self.load_remote_project_zip(project_zip_path)
[1494284519087] File "/var/task/handler.py", line 181, in load_remote_project_zip
[1494284519087] s3 = boto_session.resource('s3')
[1494284519087] File "/var/task/boto3/session.py", line 389, in resource
[1494284519088] aws_session_token=aws_session_token, config=config)
[1494284519088] File "/var/task/boto3/session.py", line 263, in client
[1494284519088] aws_session_token=aws_session_token, config=config)
[1494284519088] File "/var/task/botocore/session.py", line 836, in create_client
[1494284519088] client_config=config, api_version=api_version)
[1494284519088] File "/var/task/botocore/client.py", line 64, in create_client
[1494284519088] cls = self._create_client_class(service_name, service_model)
[1494284519088] File "/var/task/botocore/client.py", line 86, in _create_client_class
[1494284519088] base_classes=bases)
[1494284519088] File "/var/task/botocore/hooks.py", line 227, in emit
[1494284519089] return self._emit(event_name, kwargs)
[1494284519089] File "/var/task/botocore/hooks.py", line 210, in _emit
[1494284519089] response = handler(**kwargs)
[1494284519089] File "/var/task/boto3/utils.py", line 61, in _handler
[1494284519089] module = import_module(module)
[1494284519089] File "/var/task/boto3/utils.py", line 52, in import_module
[1494284519089] __import__(name)
[1494284519089] File "/var/task/boto3/s3/inject.py", line 15, in <module>
[1494284519089] from boto3.s3.transfer import create_transfer_manager
[1494284519089] File "/var/task/boto3/s3/transfer.py", line 127, in <module>
[1494284519089] from s3transfer.exceptions import RetriesExceededError as \
[1494284519089] File "/var/task/s3transfer/__init__.py", line 134, in <module>
[1494284519089] import concurrent.futures
[1494284519089] File "/var/task/concurrent/futures/__init__.py", line 8, in <module>
[1494284519089] from concurrent.futures._base import (FIRST_COMPLETED,
[1494284519089] File "/var/task/concurrent/futures/_base.py", line 381
[1494284519089] raise exception_type, self._exception, self._traceback
[1494284519090] ^
[1494284519090] SyntaxError: invalid syntax
[1494284519090] During handling of the above exception, another exception occurred:
[1494284519090] Traceback (most recent call last):
[1494284519090] File "/var/runtime/awslambda/bootstrap.py", line 466, in <module>
[1494284519090] main()
[1494284519090] File "/var/runtime/awslambda/bootstrap.py", line 462, in main
[1494284519090] handle_event_request(request_handler, invokeid, event_body, context_objs, invoked_function_arn)
[1494284519090] File "/var/runtime/awslambda/bootstrap.py", line 248, in handle_event_request
[1494284519090] result = to_json(result)
[1494284519090] File "/var/runtime/awslambda/bootstrap.py", line 224, in to_json
[1494284519090] return json.dumps(obj, default=decimal_serializer)
[1494284519090] File "/var/lang/lib/python3.6/json/__init__.py", line 238, in dumps
[1494284519090] **kw).encode(obj)
[1494284519090] File "/var/lang/lib/python3.6/json/encoder.py", line 199, in encode
[1494284519091] chunks = self.iterencode(o, _one_shot=True)
[1494284519091] File "/var/lang/lib/python3.6/json/encoder.py", line 257, in iterencode
[1494284519107] return _iterencode(o, 0)
[1494284519107] File "/var/runtime/awslambda/bootstrap.py", line 42, in decimal_serializer
[1494284519107] raise TypeError(repr(o) + " is not JSON serializable")
[1494284519107] TypeError: <FrameSummary file /var/task/handler.py, line 514 in lambda_handler> is not JSON serializable
[1494284519232] invalid syntax (_base.py, line 381)
SyntaxError
```

**Comment by mcrowson** [comment]
Hrm, I can reproduce it but that's about as far as I can get tonight. My next guess would be to look at the boto stuff we're sending up. Lambda should already have its needed botocore/boto3 for the 3.6 runtime, so we don't really need to ship it up like we currently do. I'll keep digging late tonight or tomorrow if I get some time.

**Comment by Miserlou** [comment]
Possibly related: https://github.com/Miserlou/Zappa/issues/827

**Comment by olirice** [comment]
Thank you both for the suggestions and fast response!

I can confirm blurrcat's comment in #827 that manually adding "concurrent" to "exclude" in zappa_settings.json solves the problem.

i.e.
```js
{
    "dev": {
        "app_function": "my_app.app", 
        "s3_bucket": "zappa-test-dev-uid-0000122",
        "runtime": "python3.6",
        "exclude": ["concurrent"],
        "slim_handler": true,
        "debug" : true
    }
}
```

**Comment by mcrowson** [comment]
Duplicate of #827 then?

**Comment by vlcinsky** [comment]
Can someone fix the issue title? I had quite some difficulties to find what  `slimandler` means :-).

Something like: "`slim_handler=true` fails with Python 3.6"

**Comment by olirice** [comment]
@mcrowson Its the same underlying problem but the patch @Miserlou suggested in #827 (partially shown below) would need to be updated to something like:

```python
# Create the zip file(s)
if self.stage_config.get('slim_handler', False):
    self.zip_path = self.zappa.create_lambda_zip(
        prefix=self.lambda_name,
        use_precompiled_packages=self.stage_config.get('use_precompiled_packages', True),
        # exclude=self.stage_config.get('exclude', [])  # Remove this
        exclude = self.stage_config.get('exclude', []) if sys.version_info[0] < 3 else self.stage_config.get('exclude', ['concurrent']) # Add this
        )
```
Since blurrcat is not using slim_handler it probably wouldn't hurt to keep it separate.

I'm happy either way. Feel free to close this out if you think the fix for #827 will also catch the slim_handler changes.

**Comment by mcrowson** [comment]
They both use the same underlying function, so if we moved that exclude logic to the create_lambda_zip function or above the if slim_handler condition, it should fix both issues.

**Comment by Miserlou** [comment]
Did this get fixed in 42.0 or master?

**Comment by olirice** [comment]
Yes, fixed in 42.0

Thanks all

**Comment by JoshZastrow** [comment]
Hi, I had Zappa fail on me after deployment, and after a lot of testing and digging I came across this issue. I think it's related to the troubles I'm having; something about using slim-handler is causing my deployment to fail (on the Github Example).

**Comment by scoates** [comment]
Link: #1491
