### ISSUE TITLE
Race condition between role creation and lambda function creation

### ISSUE THREAD

**Issue by gene1wood** [Miserlou/Zappa#901]
## Context

This bug occurs in zappa 0.42.0. Issue #249 reports this race condition. A mitigation was added at fa1b224fc43c7c8739dd179f9a038d31e13911e9 but it looks like the problem persists.

## Expected Behavior

For zappa to either loop and query for the existence of the IAM role before creating the lambda function or to change the sleep to something longer to allow for role creation to complete before creating the lambda function

## Actual Behavior

The stacktrace is below. Looks like it happens [here](https://github.com/Miserlou/Zappa/blob/39f05172213fc4ca9dbddb09c908e31d43cc1c36/zappa/zappa.py#L716-L731) which isn't addressed in fa1b224. 

The workaround is to wait a few seconds and re-run deploy.

```
$ venv/bin/zappa deploy dev
...snip...

==============

Traceback (most recent call last):
  File "/path/to/zappa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 2187, in handle
    sys.exit(cli.handle())
  File "/path/to/zappa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 414, in handle
    self.dispatch_command(self.command, environment)
  File "/path/to/zappa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 446, in dispatch_command
    self.deploy()
  File "/path/to/zappa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 607, in deploy
    memory_size=self.memory_size
  File "/path/to/zappa/venv/local/lib/python2.7/site-packages/zappa/zappa.py", line 730, in create_lambda_function
    DeadLetterConfig=dead_letter_config
  File "/path/to/zappa/venv/local/lib/python2.7/site-packages/botocore-1.5.16-py2.7.egg/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/path/to/zappa/venv/local/lib/python2.7/site-packages/botocore-1.5.16-py2.7.egg/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.

==============

Need help? Found a bug? Let us know! :D
```

## Possible Fix

Check for the existence of the IAM role before creating the function and if it's not present but should be loop and keep checking until it shows up (give up after some long threshold e.g. a couple minutes).

## Steps to Reproduce

Deploy a new zappa project for which the IAM role has not yet been created.

## Your Environment

* Zappa version used: 0.42.0
* Operating System and Python version: Ubuntu 14.04 Python 2.7
* The output of `pip freeze`:
```
appdirs==1.4.3
argcomplete==1.8.2
base58==0.2.4
boto3==1.4.4
botocore==1.5.40
certifi==2017.4.17
chardet==3.0.3
click==6.7
docutils==0.13.1
durationpy==0.4
future==0.16.0
futures==3.1.1
hjson==2.0.2
idna==2.5
jmespath==0.9.2
kappa==0.6.0
lambda-packages==0.15.0
packaging==16.8
placebo==0.8.1
pyparsing==2.2.0
python-dateutil==2.6.0
python-slugify==1.2.4
PyYAML==3.12
requests==2.16.5
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.11.2
troposphere==1.9.3
Unidecode==0.4.20
urllib3==1.21.1
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.42.0
```
* Your `zappa_settings.py`: Happens with any settings

**Comment by youcandanch** [comment]
I keep running into this reliably with new deployments in CI. Gonna take a stab at it for 0.49.
