### ISSUE TITLE
Package command should not require aws cli config/credentials

### ISSUE THREAD

**Issue by brianrower** [Miserlou/Zappa#909]
I've been integrating zappa into an AWS Codebuild/Codepipeline. When running on a codebuild instance, zappa fails with the stack trace shown below. Clearly it's failing initializing boto due to the lack of aws config and credentials files. But when doing a package command, I do not believe any AWS resources are utilized, hence this command should work without the credentials.

### Steps to reproduce locally (without codebuild):
1. cd into a directory with a working zappa build
2. activate the virtual env
3. Run "mv ~/.aws ~/.aws.bak" (so that boto cannot find config and credentials)
3. run "zappa package <env> -o lam.zip"

### Environment:
Ubuntu 16.04 and 14.04
Python 3.5.2
zappa 0.42.0

### Workaround:
Create a  config and credential files in a valid format, but invalid crentials like this:
config:
```
[default]
output = json
region = us-west-2
```

credentials:
```
[default]
aws_access_key_id = XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
(note: those are ACTUALLY X's in the file, I'm not trying to hide valid credentials)
and point the environment variables AWS_CONFIG_FILE and AWS_SHARED_CREDENTIALS_FILE to these files. Since it's just an issue with initializing boto and no aws resources are accessed, the zappa package command then succeeds

Stack Trace:
```
Traceback (most recent call last):
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/zappa/cli.py", line 2353, in handle
sys.exit(cli.handle())
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/zappa/cli.py", line 456, in handle
self.dispatch_command(self.command, stage)
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/zappa/cli.py", line 482, in dispatch_command
self.load_settings(self.vargs.get('settings_file'))
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/zappa/cli.py", line 1801, in load_settings
runtime=self.runtime
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/zappa/core.py", line 248, in __init__
self.load_credentials(boto_session, profile_name)
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/zappa/core.py", line 2354, in load_credentials
self.boto_session = boto3.Session(profile_name=profile_name, region_name=self.aws_region)
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/boto3/session.py", line 80, in __init__
self._setup_loader()
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/boto3/session.py", line 120, in _setup_loader
self._loader = self._session.get_component('data_loader')
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/botocore/session.py", line 701, in get_component
return self._components.get_component(name)
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/botocore/session.py", line 897, in get_component
self._components[name] = factory()
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/botocore/session.py", line 181, in <lambda>
lambda: create_loader(self.get_config_variable('data_path')))
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/botocore/session.py", line 265, in get_config_variable
elif self._found_in_config_file(methods, var_config):
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/botocore/session.py", line 286, in _found_in_config_file
return var_config[0] in self.get_scoped_config()
File "/codebuild/output/src623405482/src/.python/lib/python3.5/site-packages/botocore/session.py", line 358, in get_scoped_config
raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (default) could not be found
```

**Comment by Miserlou** [comment]
Confirming this as a bug. Please note that you should only use Python 2.7 or 3.6, not 3.5.

**Comment by devyhia** [comment]
@brianrower This is irrelevant to the bug. How is your CodePipeline working? I assume you don't have a CodeDeploy part, right? You just run: `zappa update {env}` in your CodeDeploy?

**Comment by brianrower** [comment]
@devyhia We do not use zappa deploy/update to do our deployments and we instead package and then do a cloud formation step to deploy. We do this for two reasons: 
1. the zappa deploy/update commands issue CLI commands to create some things, we prefer instead that everything is created in a single cloud formation stack. 
2. We deploy to multiple environments, so we prefer to be able to build the lambda zip package once and then deploy the same package to multiple environments instead of re-building the package for each environment we deploy to.
