### ISSUE TITLE
Kodi Alexa setup - Config missing

### ISSUE THREAD

**Issue by ForgerM** [Miserlou/Zappa#920]
Hello All,

I was following this guide to get Alexa to connect with my Kodi on my Android TV: https://www.howtogeek.com/249336/how-to-control-your-kodi-media-center-with-an-amazon-echo/

I'm stuck at the part of the zappa deploy dev part.
I keep getting the next error:

 

(venv) root@nas-36-15-E0:/data/Kodi-Alexa# zappa deploy dev
Calling deploy for stage dev..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/data/Kodi-Alexa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 2353, in handle
    sys.exit(cli.handle())
  File "/data/Kodi-Alexa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 456, in handle
    self.dispatch_command(self.command, stage)
  File "/data/Kodi-Alexa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 490, in dispatch_command
    self.deploy()
  File "/data/Kodi-Alexa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 650, in deploy
    self.create_package()
  File "/data/Kodi-Alexa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 1945, in create_package
    output=output
  File "/data/Kodi-Alexa/venv/local/lib/python2.7/site-packages/zappa/core.py", line 441, in create_lambda_zip
    copytree(cwd, temp_project_path, symlinks=False, ignore=shutil.ignore_patterns(*excludes))
  File "/data/Kodi-Alexa/venv/local/lib/python2.7/site-packages/zappa/utilities.py", line 54, in copytree
    copytree(s, d, symlinks, ignore)
  File "/data/Kodi-Alexa/venv/local/lib/python2.7/site-packages/zappa/utilities.py", line 54, in copytree
    copytree(s, d, symlinks, ignore)
  File "/data/Kodi-Alexa/venv/local/lib/python2.7/site-packages/zappa/utilities.py", line 54, in copytree
    copytree(s, d, symlinks, ignore)
  File "/data/Kodi-Alexa/venv/local/lib/python2.7/site-packages/zappa/utilities.py", line 56, in copytree
    shutil.copy2(s, d)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/data/Kodi-Alexa/ativate/lib/python2.7/config'

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!

Normally the code should deploy, but the config file doesn't appear or anything. Zappa init went fine.

Does anyone know how to resolve this?

Thanks in advance.

With kind regards,

Matthias

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: zappa-0.42.0
* Operating System and Python version: Readynas 104 Python 2.7
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by Miserlou** [comment]
Hm, annoying! Unfortunately, we didn't write this tutorial so we can't really provide support on it. Did you have any luck?
