### ISSUE TITLE
Zappa Init will not set up deployment configuration settings

### ISSUE THREAD

**Issue by jschwarzwalder** [Miserlou/Zappa#927]
## Context

 
Using Python 3.6 with flask-ask on Windows 10 machine using [this tutorial.](https://developer.amazon.com/blogs/post/8e8ad73a-99e9-4c0f-a7b3-60f92287b0bf/new-alexa-tutorial-deploy-flask-ask-skills-to-aws-lambda-with-zappa)

I followed the instructions on the blog and on the Readme.md, but zappa init is encountering errors. 

## Expected Behavior

I created a virtual enviroment, installed zappa, and typed in zappa init.
I expected for zappa to run intial set up and create a json file

## Actual Behavior

I got the following message
```
zappa init
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\zappa\cli.py", line 2348, in handle
    sys.exit(cli.handle())
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\zappa\cli.py", line 427, in handle
    self.init()
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\zappa\cli.py", line 1279, in init
    click.echo(click.style(u"""\nzappa\u255d\n""", fg='green', bold=True))
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u255d' in position 7: character maps to <undefined>

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
```

## Possible Fix
 
When I removed this part of the cli.py file it seemed to let me get farther.
`
        # Explain system.
        click.echo(click.style(u"""\n███████╗ █████╗ ██████╗ ██████╗  █████╗
╚══███╔╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗
  ███╔╝ ███████║██████╔╝██████╔╝███████║
 ███╔╝  ██╔══██║██╔═══╝ ██╔═══╝ ██╔══██║
███████╗██║  ██║██║     ██║     ██║  ██║
╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝     ╚═╝  ╚═╝\n""", fg='green', bold=True))`

Now the error reads
``` ==============
==============


Traceback (most recent call last):
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\zappa\cli.py", line 2348, in handle
    sys.exit(cli.handle())
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\zappa\cli.py", line 427, in handle
    self.init()
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\zappa\cli.py", line 1379, in init
    matches = detect_flask_apps()
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\site-packages\zappa\utilities.py", line 143, in detect_flask_apps
    lines = f.readlines()
  File "c:\users\v-jamisc\.virtualenvs\alexa-color\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 301: character maps to <undefined>

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!

```
## Steps to Reproduce

1. Open gitbash on Windows 10 Machine
2. Create Virtual Environment with virtualenvwrapper
3. Go to directory of  project files
4. Type in workon [virtual enviroment]
5. Type in pip install zappa
6. Type in zappa init

## Your Environment

* Zappa version used:
0.42.0
* Operating System and Python version:
Windows 10
Python 3.6
* The output of `pip freeze`:
pip freeze
aniso8601==1.2.0
appdirs==1.4.3
argcomplete==1.8.2
asn1crypto==0.22.0
awscli==1.11.99
base58==0.2.4
boto3==1.4.4
botocore==1.5.40
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.3
click==6.7
colorama==0.3.7
cryptography==1.9
docutils==0.13.1
durationpy==0.4
Flask==0.12.1
Flask-Ask==0.9.3
future==0.16.0
futures==3.1.1
hjson==2.0.2
idna==2.5
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.2
kappa==0.6.0
lambda-packages==0.15.0
MarkupSafe==1.0
packaging==16.8
placebo==0.8.1
pyasn1==0.2.3
pycparser==2.17
pyOpenSSL==17.0.0
pyparsing==2.2.0
python-dateutil==2.6.0
python-slugify==1.2.4
PyYAML==3.12
requests==2.17.3
rsa==3.4.2
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.11.2
troposphere==1.9.3
Unidecode==0.4.20
urllib3==1.21.1
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.42.0

**Comment by jonatasbaldin** [comment]
Hi!

I think this could a problem on  your operating system default encoding. It looks like it's failing to open a file inside your directory when detecting a Flask app.

We could try something:
1. Could you see in your text editor the file encoding? Try enforcing the `repo_stats.py` in UTF-8.
2. Inside your virtual env, could you execute this and give us the output?
```
python
import localte
locale.getpreferredencoding(False)
```

**Comment by jonatasbaldin** [comment]
@Miserlou hey mate! I guess this is a encoding problem, do you think forcing `encoding='utf-8'` on the `open()` at `statement at utilities.py:143` could prevent this kind of issue?

**Comment by Miserlou** [comment]
@jonatasbaldin - could be, this is likely a Windows-specific bug. It'd be great if we could get a Windows-using maintainer to help out things like this..

**Comment by jonatasbaldin** [comment]
@Miserlou will try to get a Windows VM to test this. Meanwhile, if another contributor could test, I'd appreciate!

**Comment by hmc-cs-abaugus** [comment]
Hi, I've been following the same tutorial and I'm getting the same exact error on a Windows machine. When I executed the commands that @jonatasbaldin listed, my output was 'cp1252'. I'm not sure how to see the file encoding or how to force/enforce it. Any help would be greatly appreciated!

**Comment by hmc-cs-abaugus** [comment]
I'm able to avoid these errors by moving the virtual environment's directory outside of the directory where my python file is located, but then I have to move that directory back into the python code's directory in order for "zappa deploy dev" to work. I then wind up with a slew of errors when I try to do "zappa update dev"; it seems like it shouldn't be necessary to move the virtual environment directory around so much, which is why I assumed that "zappa init" and "zappa deploy dev" were the sources of my problems. Thanks for any help!

**Comment by awasylew** [comment]
Same here:
$ zappa init
[...]
It looks like this is a Flask application.
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "d:\develo\ping-store\ve-zappa\lib\site-packages\zappa\cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "d:\develo\ping-store\ve-zappa\lib\site-packages\zappa\cli.py", line 476, in handle
    self.init()
  File "d:\develo\ping-store\ve-zappa\lib\site-packages\zappa\cli.py", line 1604, in init
    matches = detect_flask_apps()
  File "d:\develo\ping-store\ve-zappa\lib\site-packages\zappa\utilities.py", line 143, in detect_flask_apps
    lines = f.readlines()
  File "D:\Program Files\Python-362\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6142: character maps to <undefined>

I changed utilities.py as per jonatasbaldin commented on 12 Jun.
And it worked.

**Comment by pnadolny13** [comment]
I was able to get this fixed this by updating line 142 of /venv/Lib/site-packages/zappa/utilities.py to force encoding with this... 

open(full, 'r', encoding='utf-8') as f:
