### ISSUE TITLE
Import Error on zappa deploy

### ISSUE THREAD

**Issue by lormayna** [Miserlou/Zappa#928]
Good morning, I'm trying to make some tests with Zappa and Flask.
I'm working with Debian 8 and python2.7 inside a virtualenv.

This is the error that I got:

(packt)lorenzo@wolf:~/projects/packt/app$ zappa deploy dev
(botocore 1.5.65 (/home/lorenzo/projects/packt/lib/python2.7/site-packages), Requirement.parse('botocore==1.5.40'))
Calling deploy for stage dev..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/lorenzo/projects/packt/local/lib/python2.7/site-packages/zappa/cli.py", line 2353, in handle
    sys.exit(cli.handle())
  File "/home/lorenzo/projects/packt/local/lib/python2.7/site-packages/zappa/cli.py", line 456, in handle
    self.dispatch_command(self.command, stage)
  File "/home/lorenzo/projects/packt/local/lib/python2.7/site-packages/zappa/cli.py", line 490, in dispatch_command
    self.deploy()
  File "/home/lorenzo/projects/packt/local/lib/python2.7/site-packages/zappa/cli.py", line 650, in deploy
    self.create_package()
  File "/home/lorenzo/projects/packt/local/lib/python2.7/site-packages/zappa/cli.py", line 1945, in create_package
    output=output
  File "/home/lorenzo/projects/packt/local/lib/python2.7/site-packages/zappa/core.py", line 388, in create_lambda_zip
    import pip
  File "/home/lorenzo/projects/packt/local/lib/python2.7/site-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/lorenzo/projects/packt/local/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/lorenzo/projects/packt/local/lib/python2.7/site-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!

**Comment by jonatasbaldin** [comment]
Hi!

This is probably related to your `pip`version, which old versions relied on the `IncompleteRead` from `requests`.

Which version of `pip` are you using? Which operating system?

Maybe try to update `pip` with `pip install --upgrade pip`.

Thanks!

**Comment by lormayna** [comment]
Yes, upgrading pip solve the problem :)
Thank you for your help

Il 12/giu/2017 14:02, "Jonatas Baldin" <notifications@github.com> ha
scritto:

**Comment by jonatasbaldin** [comment]
Yay, thanks for using Zappa 😄
