### ISSUE TITLE
Can't deploy any Zappa apps using Mac

### ISSUE THREAD

**Issue by BenjaminWatts** [Miserlou/Zappa#948]
## Context
I seem to be unable to deploy an zappa apps from my Mac - though I have been able to do so successfully from an old ubuntu machine I have. As I seem to have the same python/zappa version on both, the same internet connection etc - I really can't find a reason why it shouldn't work!

I have tried a couple of django projects - all with the same issue! Any help much appreciated!

## Expected Behavior
I would expect it to deploy - just as it does from my ubuntu machine

## Actual Behavior
I get this error message when trying to deploy initially or update 
(env) Benjamins-MacBook-Pro:Spheres benjaminwatts$ zappa update dev
Calling update for stage dev..
Downloading and installing dependencies..
 - mysql-python==1.2.5: Using precompiled lambda package 
Packaging project as zip..
Uploading spheres-dev-1498143411.zip (12.8MiB)..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13.4M/13.4M [00:16<00:00, 694KB/s]
Updating Lambda function code..
Updating Lambda function configuration..
Uploading spheres-dev-template-1498143442.json (1.6KiB)..
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.60K/1.60K [00:00<00:00, 5.61KB/s]
Deploying API Gateway..
Scheduling..
Unscheduled spheres-dev-zappa-keep-warm-handler.keep_warm_callback.
Scheduled spheres-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/benjaminwatts/Spheres/env/lib/python2.7/site-packages/zappa/cli.py", line 2351, in handle
    sys.exit(cli.handle())
  File "/Users/benjaminwatts/Spheres/env/lib/python2.7/site-packages/zappa/cli.py", line 456, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/benjaminwatts/Spheres/env/lib/python2.7/site-packages/zappa/cli.py", line 500, in dispatch_command
    self.update()
  File "/Users/benjaminwatts/Spheres/env/lib/python2.7/site-packages/zappa/cli.py", line 903, in update
    requests.get(endpoint_url)
  File "/Users/benjaminwatts/Spheres/env/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/benjaminwatts/Spheres/env/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/benjaminwatts/Spheres/env/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/benjaminwatts/Spheres/env/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Users/benjaminwatts/Spheres/env/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='lt421rpwnd.execute-api.eu-west-1.amazonaws.com', port=443): Max retries exceeded with url: /dev (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x113244bd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

## Steps to Reproduce
Following the instructions here https://www.youtube.com/watch?v=plUrbPN0xc8

## Your Environment

* Zappa version used:
0.42.1
* Operating System and Python version:
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
* The output of `pip freeze`:
argcomplete==1.8.2
base58==0.2.4
boto3==1.4.4
botocore==1.5.40
certifi==2017.4.17
chardet==3.0.4
click==6.7
Django==1.8
docutils==0.13.1
durationpy==0.4
future==0.16.0
futures==3.1.1
hjson==2.0.7
idna==2.5
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.15.1
MySQL-python==1.2.5
nose==1.3.7
placebo==0.8.1
python-dateutil==2.6.0
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.1
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.14.0
troposphere==1.9.4
Unidecode==0.4.20
urllib3==1.21.1
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.42.1
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by Miserlou** [comment]
Zappa is developed on OSX, so that's not the problem. I think this is
specific to your own system.

**Comment by BenjaminWatts** [comment]
Thanks - oh dear - any ideas what I could try and do to fix - reinstall python/check firewalls ?

**Comment by GeorgianaPetria** [comment]
Hi, I'm having the exact same issue. Did you find any solution?

**Comment by mcrowson** [comment]
Might be a permissions issue with aws creds

**Comment by BenjaminWatts** [comment]
hey - sorry for delay. yes _ I discovered it was a problem with my internet connection / firewall setup- and that running the deploy over either a VPN or 4G instead got around the issue. good luck!

**Comment by jasonrhaas** [comment]
should this issue be closed?

**Comment by BenjaminWatts** [comment]
Yes
