### ISSUE TITLE
trouble running with python 3.6 in docker container

### ISSUE THREAD

**Issue by stratospark** [Miserlou/Zappa#954]
I'm trying to follow the directions here: https://blog.zappa.io/posts/docker-zappa-and-python3

After having done so, I'm getting many error messages that I hadn't seen with my previous experience with zappa and python 2.

## Context
Attempting to use zappa 0.42.1 in a Python 3.6 docker container running in docker-machine on macOS 10.12.4.

## Expected Behavior
Allow me to move forward with basic Zappa development, as I had been doing with python 2.

## Actual Behavior
```
(myenv) zappashell> zappa
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/var/task/myenv/lib/python3.6/site-packages/zappa/cli.py", line 2351, in handle
    sys.exit(cli.handle())
  File "/var/task/myenv/lib/python3.6/site-packages/zappa/cli.py", line 435, in handle
    self.load_settings_file(self.vargs.get('settings_file'))
  File "/var/task/myenv/lib/python3.6/site-packages/zappa/cli.py", line 1850, in load_settings_file
    settings_file = self.get_json_or_yaml_settings()
  File "/var/task/myenv/lib/python3.6/site-packages/zappa/cli.py", line 1832, in get_json_or_yaml_settings
    raise ClickException("Please configure a zappa_settings file or call `zappa init`.")
click.exceptions.ClickException: Please configure a zappa_settings file or call `zappa init`.

==============
```

also:

```
(myenv) zappashell> zappa deploy dev
Calling deploy for stage dev..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/var/task/myenv/lib/python3.6/site-packages/zappa/cli.py", line 2351, in handle
    sys.exit(cli.handle())
  File "/var/task/myenv/lib/python3.6/site-packages/zappa/cli.py", line 456, in handle
    self.dispatch_command(self.command, stage)
  File "/var/task/myenv/lib/python3.6/site-packages/zappa/cli.py", line 482, in dispatch_command
    self.load_settings(self.vargs.get('settings_file'))
  File "/var/task/myenv/lib/python3.6/site-packages/zappa/cli.py", line 1799, in load_settings
    runtime=self.runtime
  File "/var/task/myenv/lib/python3.6/site-packages/zappa/core.py", line 253, in __init__
    self.s3_client = self.boto_session.client('s3')
  File "/var/runtime/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/var/task/myenv/lib/python3.6/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/var/task/myenv/lib/python3.6/site-packages/botocore/client.py", line 64, in create_client
    cls = self._create_client_class(service_name, service_model)
  File "/var/task/myenv/lib/python3.6/site-packages/botocore/client.py", line 86, in _create_client_class
    base_classes=bases)
  File "/var/task/myenv/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/var/task/myenv/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/var/runtime/boto3/utils.py", line 61, in _handler
    module = import_module(module)
  File "/var/runtime/boto3/utils.py", line 52, in import_module
    __import__(name)
  File "/var/runtime/boto3/s3/inject.py", line 15, in <module>
    from boto3.s3.transfer import create_transfer_manager
  File "/var/runtime/boto3/s3/transfer.py", line 127, in <module>
    from s3transfer.exceptions import RetriesExceededError as \
  File "/var/runtime/s3transfer/__init__.py", line 134, in <module>
    import concurrent.futures
  File "/var/task/myenv/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/var/task/myenv/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax

==============
```

## Steps to Reproduce

1. Follow tutorial to create python 3.6 docker container
2. pip install zappa
3. run `zappa` and see error
4. run `zappa init` then `zappa deploy dev` to see error

## Your Environment
```
(myenv) zappashell> pip freeze
argcomplete==1.8.2
base58==0.2.4
boto3==1.4.4
botocore==1.5.40
certifi==2017.4.17
chardet==3.0.4
click==6.7
docutils==0.13.1
durationpy==0.4
future==0.16.0
futures==3.1.1
hjson==2.0.7
idna==2.5
jmespath==0.9.1
kappa==0.6.0
lambda-packages==0.15.1
placebo==0.8.1
python-dateutil==2.6.0
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.1
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.14.0
troposphere==1.9.4
Unidecode==0.4.20
urllib3==1.21.1
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.42.1
```

**Comment by CKrawczyk** [comment]
I have been able to get zappa working inside a docker container, I used the following `Dockerfile`:
```
FROM python:3.6.1

# name this folder what you want
WORKDIR /usr/src/aggregation

COPY requirements.txt ./

# create the zappa environment 
RUN python3 -m venv --system-site-packages /usr/src/env/zappa
# add the environment to the .bashrc so when you log in it switches for you
RUN echo '. /usr/src/env/zappa/bin/activate' >> /root/.bashrc
# activate the env and pip install requirements
RUN . /usr/src/env/zappa/bin/activate \
          && pip install -r requirements.txt

# move the app to the container
COPY . ./

# I have a flask app so start it up
CMD . /usr/src/env/zappa/bin/activate \
            && python routs.py
```

I use `docker-compose` to handle my docker settings and can use `docker-compose run NAME_OF_CONTAINER /bin/bash -l` to start up a bash terminal that zappa can be run from.  The `--system-site-packages` switch when making the env was the bit that tripped me up for a while, zappa will not work without it.

If you just want a bash terminal on start up you can replace the final `CMD` with:
```
CMD /bin/bash -l
```

**Comment by stratospark** [comment]
@CKrawczyk thank you. However, I'm interested in creating a Docker image that is based on a similar Linux environment that will be running on Amazon. I have some 3rd party dependencies like Tensorflow that aren't working for me with zappa on python2, that I hope may work with python 3.

**Comment by stratospark** [comment]
Thanks to a conversation with Edgar, the original author of the blog post, we narrowed it down to an outdated package `jmespath==0.9.1` that is part of the docker image. My solution was to `pip uninstall jmespath` before activating the zappa virtual environment.
