### ISSUE TITLE
Using Zappa with MFA

### ISSUE THREAD

**Issue by scretu** [Miserlou/Zappa#978]
We force MFA in our organisation, for the Web Console, but not for API calls.
## Context
We do this with this rule:

```
{
    "Condition": {
        "Bool": {
            "aws:MultiFactorAuthPresent": "false"
        }
    },
    "Effect": "Deny",
    "NotAction": "iam:*",
    "Resource": "*",
    "Sid": "BlockConsoleButNotAPIAccessOtherThanAboveUnlessSignedInWithMFA"
},
```
(for more details, see https://stackoverflow.com/questions/28177505/enforce-mfa-for-aws-console-login-but-not-for-api-calls)

## Expected Behavior
Zappa should have S3 permissions. awscli works just fine:

```
$ aws s3 cp zappa_settings.json s3://s3-bucket-in-zappa_settings-json/
upload: ./zappa_settings.json to s3://s3-bucket-in-zappa_settings-json/zappa_settings.json

$ aws s3 cp s3://s3-bucket-in-zappa_settings-json/zappa_settings.json zappa_settings2.json
download: s3://s3-bucket-in-zappa_settings-json/zappa_settings.json to ./zappa_settings2.json
```

## Actual Behavior
Once that rule is in place, zappa fails:

```
$ zappa update dev
(botocore 1.5.76 (/home/path/to/zappa-venv/lib/python2.7/site-packages), Requirement.parse('botocore==1.5.40'), set([u'zappa']))
Calling update for stage dev..
Downloading and installing dependencies..
 - lazy-object-proxy==1.2.2: Using locally cached manylinux wheel
 - psycopg2==2.7.1: Using locally cached manylinux wheel
Packaging project as zip..
Uploading zappatest-dev-1498824631.zip (13.8MiB)..
100%|█████████████████████████████████| 14.5M/14.5M [00:03<00:00, 3.83MB/s]
Updating Lambda function code..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/path/to/zappa-venv/local/lib/python2.7/site-packages/zappa/cli.py", line 2358, in handle
    sys.exit(cli.handle())
  File "/home/path/to/zappa-venv/local/lib/python2.7/site-packages/zappa/cli.py", line 459, in handle
    self.dispatch_command(self.command, stage)
  File "/home/path/to/zappa-venv/local/lib/python2.7/site-packages/zappa/cli.py", line 503, in dispatch_command
    self.update()
  File "/home/path/to/zappa-venv/local/lib/python2.7/site-packages/zappa/cli.py", line 828, in update
    self.lambda_name
  File "/home/path/to/zappa-venv/local/lib/python2.7/site-packages/zappa/core.py", line 886, in update_lambda_function
    Publish=publish
  File "/home/path/to/zappa-venv/local/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/path/to/zappa-venv/local/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AccessDeniedException) when calling the UpdateFunctionCode operation: Your access has been denied by S3, please make sure your request credentials have permission to GetObject for s3-bucket-in-zappa_settings-json/zappatest-dev-1498824631.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied
```
## Your Environment
* Zappa version used: zappa==0.42.2
* Operating System and Python version: Ubuntu 16.04.2, Python 2.7.12
* The output of `pip freeze`: 
argcomplete==1.8.2
base58==0.2.4
boto3==1.4.4
botocore==1.5.76
certifi==2017.4.17
chardet==3.0.4
click==6.7
Django==1.11.2
docutils==0.13.1
durationpy==0.4
flowy==0.3.3
future==0.16.0
futures==3.1.1
hjson==2.0.7
idna==2.5
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.15.1
lazy-object-proxy==1.2.2
pkg-resources==0.0.0
placebo==0.8.1
psycopg2==2.7.1
python-dateutil==2.6.0
python-slugify==1.2.4
pytz==2017.2
PyYAML==3.12
requests==2.18.1
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.14.0
troposphere==1.9.4
Unidecode==0.4.20
urllib3==1.21.1
venusian==1.1.0
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.42.2
* Your `zappa_settings.py`: 
```
{
  "dev": {
    "django_settings": "zappatest.settings",
    "aws_region": "us-east-1",
    "s3_bucket": "s3-bucket-in-zappa_settings-json",
    "vpc_config": {
      "SubnetIds": ["subnet-78cc0b0e"],
      "SecurityGroupIds": ["sg-a380e5d9"]
    },
    "manage_roles": false,
    "role_name": "zappatest-dev-ZappaLambdaExecutionRole"
  }
}
```

**Comment by Miserlou** [comment]
You're managing your own rules, not sure what you expect Zappa to do about this.

**Comment by scretu** [comment]
I don't understand your reply. You mean "roles", not "rules", I assume. The role exists, already, and looks like this:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:*"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "lambda:InvokeFunction",
                "lambda:UpdateFunctionCode"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachNetworkInterface",
                "ec2:CreateNetworkInterface",
                "ec2:DeleteNetworkInterface",
                "ec2:DescribeInstances",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DetachNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:ResetNetworkInterfaceAttribute"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "kinesis:*"
            ],
            "Resource": "arn:aws:kinesis:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "sns:*"
            ],
            "Resource": "arn:aws:sns:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "sqs:*"
            ],
            "Resource": "arn:aws:sqs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "dynamodb:*"
            ],
            "Resource": "arn:aws:dynamodb:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "route53:*"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "cloudformation:*"
            ],
            "Resource": "*"
        }
    ]
}
```
But the error is the same, as long as this policy is in place:
```
{
    "Condition": {
        "Bool": {
            "aws:MultiFactorAuthPresent": "false"
        }
    },
    "Effect": "Deny",
    "NotAction": "iam:*",
    "Resource": "*",
    "Sid": "BlockConsoleButNotAPIAccessOtherThanAboveUnlessSignedInWithMFA"
},
```
If I remove it, zappa works. But it should work with it as well. awscli works with the above mentioned policy, as that policy only enforces MFA for the web console, not for API calls.

**Comment by Miserlou** [comment]
PR welcome

**Comment by scretu** [comment]
Using a tool like https://github.com/lonelyplanet/aws-mfa fixes the above issues, so I'll close it
